module DASHI.Mathematics.Complexity.PNotEqualsNPTransitionGeneratedRestrictionQuotientExact where

------------------------------------------------------------------------
-- THE CLASSIFIER FIELD IS REDUNDANT
--
-- Once the root quotient state and Boolean transition table are known, every
-- reachable restriction-node class is generated by replaying its derivation.
--
-- Therefore Q1 does not need to construct/store an arbitrary classify
-- function.  It only needs:
--
--   stateCount
--   rootState
--   step
--   semantic congruence for the generated selector.
--
-- This owner compiles that smaller object to the repository's existing
-- RestrictionSemanticQuotient and proves every existing quotient reduces back
-- to this transition-generated form.
------------------------------------------------------------------------

open import Agda.Builtin.Bool using (Bool; false; true)
open import Agda.Builtin.Equality using (_≡_; refl)
open import Agda.Builtin.Nat using (Nat)
open import Data.Fin.Base using (Fin)
open import Relation.Binary.PropositionalEquality using (sym; trans)

import DASHI.Mathematics.Complexity.BooleanFormulaSATSelfReductionExact as SAT
import DASHI.Mathematics.Complexity.PNotEqualsNPSelfDiagonalRestrictionFamilyExact as Family
import DASHI.Mathematics.Complexity.PNotEqualsNPResourceClosingRestrictionQuotientExact as Quotient
import DASHI.Mathematics.Complexity.PNotEqualsNPRestrictionQuotientClassSelectionAlgorithmExact as Selector

------------------------------------------------------------------------
-- Transition-generated selector independent of the old classify field.
------------------------------------------------------------------------

generatedSelect :
  ∀ {rootVariables currentVariables stateCount : Nat}
    {root : SAT.BooleanFormula rootVariables}
    (rootState : Fin stateCount)
    (step : Fin stateCount → Bool → Fin stateCount)
    {current : SAT.BooleanFormula currentVariables} →
  Family.RestrictionDerivation root current →
  Fin stateCount
generatedSelect rootState step Family.restrictionRoot =
  rootState
generatedSelect rootState step
    (Family.restrictionFalse derivation) =
  step
    (generatedSelect rootState step derivation)
    false
generatedSelect rootState step
    (Family.restrictionTrue derivation) =
  step
    (generatedSelect rootState step derivation)
    true

------------------------------------------------------------------------
-- Smaller quotient surface.
------------------------------------------------------------------------

record TransitionGeneratedRestrictionQuotient
    {rootVariables : Nat}
    (root : SAT.BooleanFormula rootVariables) : Set₁ where
  constructor transition-generated-restriction-quotient
  field
    stateCount :
      Nat

    rootState :
      Fin stateCount

    step :
      Fin stateCount →
      Bool →
      Fin stateCount

    sameGeneratedStateImpliesSatisfiabilityEquivalent :
      ∀ {leftVariables rightVariables : Nat}
        {left : SAT.BooleanFormula leftVariables}
        {right : SAT.BooleanFormula rightVariables}
        (leftDerivation :
          Family.RestrictionDerivation root left)
        (rightDerivation :
          Family.RestrictionDerivation root right) →
      generatedSelect rootState step leftDerivation
      ≡
      generatedSelect rootState step rightDerivation →
      Quotient.SatisfiabilityEquivalent left right

open TransitionGeneratedRestrictionQuotient public

------------------------------------------------------------------------
-- Compile the smaller object to the legacy quotient expected downstream.
------------------------------------------------------------------------

toRestrictionSemanticQuotient :
  ∀ {rootVariables : Nat}
    {root : SAT.BooleanFormula rootVariables} →
  TransitionGeneratedRestrictionQuotient root →
  Quotient.RestrictionSemanticQuotient root
toRestrictionSemanticQuotient generated =
  Quotient.restriction-semantic-quotient
    (stateCount generated)
    (generatedSelect
      (rootState generated)
      (step generated))
    (step generated)
    (λ derivation → refl)
    (λ derivation → refl)
    (sameGeneratedStateImpliesSatisfiabilityEquivalent
      generated)

------------------------------------------------------------------------
-- Every existing quotient has exactly this generated form.
------------------------------------------------------------------------

existingRootState :
  ∀ {rootVariables : Nat}
    {root : SAT.BooleanFormula rootVariables}
    (quotient : Quotient.RestrictionSemanticQuotient root) →
  Fin (Quotient.stateCount quotient)
existingRootState quotient =
  Quotient.classify quotient
    Family.restrictionRoot

generatedSelectMatchesExistingClassify :
  ∀ {rootVariables currentVariables : Nat}
    {root : SAT.BooleanFormula rootVariables}
    (quotient : Quotient.RestrictionSemanticQuotient root)
    {current : SAT.BooleanFormula currentVariables}
    (derivation : Family.RestrictionDerivation root current) →
  generatedSelect
      (existingRootState quotient)
      (Quotient.step quotient)
      derivation
  ≡
  Quotient.classify quotient derivation
generatedSelectMatchesExistingClassify quotient derivation =
  Selector.selectClassExact quotient derivation

fromRestrictionSemanticQuotient :
  ∀ {rootVariables : Nat}
    {root : SAT.BooleanFormula rootVariables} →
  Quotient.RestrictionSemanticQuotient root →
  TransitionGeneratedRestrictionQuotient root
fromRestrictionSemanticQuotient quotient =
  transition-generated-restriction-quotient
    (Quotient.stateCount quotient)
    (existingRootState quotient)
    (Quotient.step quotient)
    semanticCongruence
  where
    semanticCongruence :
      ∀ {leftVariables rightVariables : Nat}
        {left : SAT.BooleanFormula leftVariables}
        {right : SAT.BooleanFormula rightVariables}
        (leftDerivation :
          Family.RestrictionDerivation root left)
        (rightDerivation :
          Family.RestrictionDerivation root right) →
      generatedSelect
          (existingRootState quotient)
          (Quotient.step quotient)
          leftDerivation
      ≡
      generatedSelect
          (existingRootState quotient)
          (Quotient.step quotient)
          rightDerivation →
      Quotient.SatisfiabilityEquivalent left right
    semanticCongruence
        leftDerivation
        rightDerivation
        sameGenerated =
      Quotient.sameStateImpliesSatisfiabilityEquivalent
        quotient
        leftDerivation
        rightDerivation
        sameExisting
      where
        sameExisting :
          Quotient.classify quotient leftDerivation
          ≡
          Quotient.classify quotient rightDerivation
        sameExisting =
          trans
            (sym
              (generatedSelectMatchesExistingClassify
                quotient
                leftDerivation))
            (trans
              sameGenerated
              (generatedSelectMatchesExistingClassify
                quotient
                rightDerivation))

------------------------------------------------------------------------
-- Round-trip classifier equality pointwise.
------------------------------------------------------------------------

generatedRoundTripClassify :
  ∀ {rootVariables currentVariables : Nat}
    {root : SAT.BooleanFormula rootVariables}
    (quotient : Quotient.RestrictionSemanticQuotient root)
    {current : SAT.BooleanFormula currentVariables}
    (derivation : Family.RestrictionDerivation root current) →
  Quotient.classify
      (toRestrictionSemanticQuotient
        (fromRestrictionSemanticQuotient quotient))
      derivation
  ≡
  Quotient.classify quotient derivation
generatedRoundTripClassify =
  generatedSelectMatchesExistingClassify

------------------------------------------------------------------------
-- FRONTIER CONSEQUENCE
--
-- The arbitrary classifier is no longer part of the constructive frontier.
--
-- Q1 need only discover:
--
--   rootState
--   finite Boolean transition table
--   closed representatives / structural chains proving semantic congruence.
--
-- Class labels for every descendant are then executable replay output with the
-- exact restriction-depth runtime proved in the selector owner.
------------------------------------------------------------------------
