module DASHI.Mathematics.Complexity.PNotEqualsNPGeneratedClosedQ1DiscoveryExact where

------------------------------------------------------------------------
-- MINIMAL Q1 DISCOVERY PAYLOAD
--
-- Existing theorem:
--   PNotEqualsNPTransitionGeneratedRestrictionQuotientExact
--
-- proves that the arbitrary classify field is redundant.  Once rootState and
-- the Boolean step table are known, every reachable class is generated by
-- replaying the literal Shannon restriction derivation.
--
-- Therefore the Q1 constructor should not be asked to discover/store a
-- classifier.  The minimal closed discovery payload is:
--
--   rootState
--   step table
--   semantic congruence of generated states
--   strict representatives
--   structural representative chains.
--
-- This owner compiles that smaller payload back to the legacy
-- ClosedStrictRepresentativeQuotient consumed by all existing authority and
-- Q2 machinery.
------------------------------------------------------------------------

open import Agda.Builtin.Nat using (Nat)
open import Data.Fin.Base using (Fin)
open import Data.Maybe.Base using (Maybe; just; nothing)
open import Data.Product using (Σ; _,_)
open import Relation.Binary.PropositionalEquality using (cong)

import DASHI.Mathematics.Complexity.BooleanFormulaSATSelfReductionExact as SAT
import DASHI.Mathematics.Complexity.CookLevinCircuitGCTBoundary as Cook
import DASHI.Mathematics.Complexity.PNotEqualsNPCookIndexedFormulaBridgeExact as Bridge
import DASHI.Mathematics.Complexity.PNotEqualsNPProgramDescriptionFormulaEmbeddingExact as Size
import DASHI.Mathematics.Complexity.PNotEqualsNPSelfDiagonalRestrictionFamilyExact as Family
import DASHI.Mathematics.Complexity.PNotEqualsNPTransitionGeneratedRestrictionQuotientExact as Generated
import DASHI.Mathematics.Complexity.PNotEqualsNPResourceClosingRestrictionQuotientExact as Quotient
import DASHI.Mathematics.Complexity.PNotEqualsNPStrictSemanticRepresentativeQuotientExact as Strict
import DASHI.Mathematics.Complexity.PNotEqualsNPClosedStrictRepresentativeQuotientExact as Closed
import DASHI.Mathematics.Complexity.PNotEqualsNPSelfReferenceAllOverheadBudgetExact as Q1
import DASHI.Mathematics.Complexity.PNotEqualsNPBoundedSelfReferenceWellFoundedExact as Q2
import DASHI.Mathematics.Complexity.PNotEqualsNPQ1ReachableStateRecurrenceExact as Recurrence
import DASHI.Mathematics.Complexity.PNotEqualsNPQ1ExecutedConstructionMachineExact as Executed
import DASHI.Mathematics.Complexity.PNotEqualsNPQ1OperationalConstructionCostExact as Operational
import DASHI.Mathematics.Complexity.PNotEqualsNPQ1ConstructionChargedRecurrenceExact as Charged

------------------------------------------------------------------------
-- Generated closed representative surface.
------------------------------------------------------------------------

record GeneratedClosedRepresentativeQuotient
    {rootVariables : Nat}
    (root : SAT.BooleanFormula rootVariables) : Set₁ where
  constructor generated-closed-representative-quotient
  field
    generatedQuotient :
      Generated.TransitionGeneratedRestrictionQuotient root

    representative :
      Fin (Generated.stateCount generatedQuotient) →
      Cook.BooleanFormula

    representativeEquivalent :
      ∀ {currentVariables : Nat}
        {current : SAT.BooleanFormula currentVariables}
        (derivation :
          Family.RestrictionDerivation root current) →
      Strict.CookSatisfiabilityEquivalent
        (Bridge.indexedToCook current)
        (representative
          (Generated.generatedSelect
            (Generated.rootState generatedQuotient)
            (Generated.step generatedQuotient)
            derivation))

    representativeStrictlySmallerThanRoot :
      (state : Fin (Generated.stateCount generatedQuotient)) →
      Size.formulaNodeCount
        (representative state)
      <
      Size.formulaNodeCount
        (Bridge.indexedToCook root)

    representativeChain :
      (state : Fin (Generated.stateCount generatedQuotient)) →
      Closed.StructuralRepresentativeChain
        (representative state)

open GeneratedClosedRepresentativeQuotient public

------------------------------------------------------------------------
-- Compile to the legacy strict quotient.
------------------------------------------------------------------------

toStrictSemanticRepresentativeQuotient :
  ∀ {rootVariables : Nat}
    {root : SAT.BooleanFormula rootVariables} →
  GeneratedClosedRepresentativeQuotient root →
  Strict.StrictSemanticRepresentativeQuotient root
toStrictSemanticRepresentativeQuotient generatedClosed =
  Strict.strict-semantic-representative-quotient
    legacyQuotient
    (representative generatedClosed)
    (representativeEquivalent generatedClosed)
    (representativeStrictlySmallerThanRoot generatedClosed)
  where
    legacyQuotient :
      Quotient.RestrictionSemanticQuotient _
    legacyQuotient =
      Generated.toRestrictionSemanticQuotient
        (generatedQuotient generatedClosed)

toClosedStrictRepresentativeQuotient :
  ∀ {rootVariables : Nat}
    {root : SAT.BooleanFormula rootVariables} →
  GeneratedClosedRepresentativeQuotient root →
  Closed.ClosedStrictRepresentativeQuotient root
toClosedStrictRepresentativeQuotient generatedClosed =
  Closed.closed-strict-representative-quotient
    (toStrictSemanticRepresentativeQuotient generatedClosed)
    (representativeChain generatedClosed)

------------------------------------------------------------------------
-- The generated selector is literally the classifier after compilation.
------------------------------------------------------------------------

compiledClassifierIsGenerated :
  ∀ {rootVariables currentVariables : Nat}
    {root : SAT.BooleanFormula rootVariables}
    (generatedClosed :
      GeneratedClosedRepresentativeQuotient root)
    {current : SAT.BooleanFormula currentVariables}
    (derivation :
      Family.RestrictionDerivation root current) →
  Quotient.classify
    (Strict.quotient
      (Closed.strictQuotient
        (toClosedStrictRepresentativeQuotient generatedClosed)))
    derivation
  ≡
  Generated.generatedSelect
    (Generated.rootState (generatedQuotient generatedClosed))
    (Generated.step (generatedQuotient generatedClosed))
    derivation
compiledClassifierIsGenerated generatedClosed derivation =
  refl

------------------------------------------------------------------------
-- State-specific Q1 discovery payload, including the existing all-overhead
-- strict-fit certificate after compilation.
------------------------------------------------------------------------

GeneratedQ1StateWitness :
  (state : Q2.BoundedSelfReferenceState) →
  Set₁
GeneratedQ1StateWitness state =
  Σ
    (GeneratedClosedRepresentativeQuotient
      (Bridge.cookToIndexed
        (Q2.currentFormula state)))
    (λ generatedClosed →
      Q1.ClosedQuotientAllOverheadFits
        (toClosedStrictRepresentativeQuotient generatedClosed)
        (Recurrence.stateOverhead state))

generatedWitnessToLegacyQ1 :
  ∀ {state : Q2.BoundedSelfReferenceState} →
  GeneratedQ1StateWitness state →
  Recurrence.Q1StateWitness state
generatedWitnessToLegacyQ1
    (generatedClosed , fits) =
  toClosedStrictRepresentativeQuotient generatedClosed
  ,
  fits

------------------------------------------------------------------------
-- Preferred machine receipt: decode the SMALL generated payload, not the
-- legacy quotient with an arbitrary classifier field.
------------------------------------------------------------------------

record GeneratedExecutedQ1ConstructionRun
    (state : Q2.BoundedSelfReferenceState) : Set₁ where
  constructor generated-executed-q1-construction-run
  field
    MachineState : Set
    machineStep : MachineState → MachineState

    decodeGeneratedWitness :
      MachineState →
      Maybe (GeneratedQ1StateWitness state)

    machineStart machineFinal : MachineState
    machineStepCount : Nat

    machineExecution :
      Executed.Iterates
        machineStep
        machineStepCount
        machineStart
        machineFinal

    generatedWitness :
      GeneratedQ1StateWitness state

    machineFinalDecodesGeneratedWitness :
      decodeGeneratedWitness machineFinal
      ≡
      just generatedWitness

    machineConstructionAndNextStrict :
      (Operational.q1WitnessGraphCellCount
        (generatedWitnessToLegacyQ1 generatedWitness)
        + machineStepCount)
      +
      Q2.recursiveMeasure
        (Charged.q1WitnessNextState
          state
          (generatedWitnessToLegacyQ1 generatedWitness))
      <
      Q2.recursiveMeasure state

open GeneratedExecutedQ1ConstructionRun public

mapGeneratedWitness :
  ∀ {state : Q2.BoundedSelfReferenceState} →
  Maybe (GeneratedQ1StateWitness state) →
  Maybe (Recurrence.Q1StateWitness state)
mapGeneratedWitness nothing =
  nothing
mapGeneratedWitness (just witness) =
  just (generatedWitnessToLegacyQ1 witness)

generatedExecutedRunToExecutedRun :
  ∀ {state : Q2.BoundedSelfReferenceState} →
  GeneratedExecutedQ1ConstructionRun state →
  Executed.ExecutedQ1ConstructionRun state
generatedExecutedRunToExecutedRun {state} run =
  Executed.executed-q1-construction-run
    (MachineState run)
    (machineStep run)
    (λ machineState →
      mapGeneratedWitness
        (decodeGeneratedWitness run machineState))
    (machineStart run)
    (machineFinal run)
    (machineStepCount run)
    (machineExecution run)
    (generatedWitnessToLegacyQ1
      (generatedWitness run))
    finalDecodesLegacy
    (machineConstructionAndNextStrict run)
  where
    finalDecodesLegacy :
      mapGeneratedWitness
        (decodeGeneratedWitness run (machineFinal run))
      ≡
      just
        (generatedWitnessToLegacyQ1
          (generatedWitness run))
    finalDecodesLegacy =
      cong
        mapGeneratedWitness
        (machineFinalDecodesGeneratedWitness run)

GeneratedExecutedQ1StateConstructor : Set₁
GeneratedExecutedQ1StateConstructor =
  (state : Q2.BoundedSelfReferenceState) →
  Maybe (GeneratedExecutedQ1ConstructionRun state)

generatedConstructorToExecuted :
  GeneratedExecutedQ1StateConstructor →
  Executed.ExecutedQ1StateConstructor
generatedConstructorToExecuted constructor state
    with constructor state
... | nothing =
  nothing
... | just run =
  just (generatedExecutedRunToExecutedRun run)

generatedConstructorToQ2StepSystem :
  GeneratedExecutedQ1StateConstructor →
  Q2.BoundedSelfReferenceStepSystem
generatedConstructorToQ2StepSystem constructor =
  Executed.executedConstructorToQ2StepSystem
    (generatedConstructorToExecuted constructor)

------------------------------------------------------------------------
-- FRONTIER CONSEQUENCE
--
-- The live constructor no longer owes an arbitrary classifier.
--
-- It owes only:
--
--   generated transition quotient:
--     stateCount + rootState + step + generated-state semantic congruence
--
--   plus:
--     strict representative for each generated state
--     structural chain for each representative
--     all-overhead fit.
--
-- Class selection for every reachable descendant is then executable replay,
-- already proved exact with transition cost equal to restriction depth.
------------------------------------------------------------------------
