module DASHI.Mathematics.Complexity.PNotEqualsNPGeneratedClosedQ1DiscoveryExact where

------------------------------------------------------------------------
-- MINIMAL Q1 DISCOVERY PAYLOAD
--
-- Existing theorem:
--   PNotEqualsNPTransitionGeneratedRestrictionQuotientExact
--
-- proves that the arbitrary classify field is redundant.  Once rootState and
-- the Boolean step table are known, every reachable class is generated by
-- replaying the literal Shannon restriction derivation.
--
-- Therefore the Q1 constructor should not be asked to discover/store a
-- classifier.  The minimal closed discovery payload is:
--
--   rootState
--   step table
--   semantic congruence of generated states
--   strict representatives
--   structural representative chains.
--
-- This owner compiles that smaller payload back to the legacy
-- ClosedStrictRepresentativeQuotient consumed by all existing authority and
-- Q2 machinery.
------------------------------------------------------------------------

open import Agda.Builtin.Nat using (Nat)
open import Data.Fin.Base using (Fin)
open import Data.Product using (Σ; _,_)

import DASHI.Mathematics.Complexity.BooleanFormulaSATSelfReductionExact as SAT
import DASHI.Mathematics.Complexity.CookLevinCircuitGCTBoundary as Cook
import DASHI.Mathematics.Complexity.PNotEqualsNPCookIndexedFormulaBridgeExact as Bridge
import DASHI.Mathematics.Complexity.PNotEqualsNPProgramDescriptionFormulaEmbeddingExact as Size
import DASHI.Mathematics.Complexity.PNotEqualsNPSelfDiagonalRestrictionFamilyExact as Family
import DASHI.Mathematics.Complexity.PNotEqualsNPTransitionGeneratedRestrictionQuotientExact as Generated
import DASHI.Mathematics.Complexity.PNotEqualsNPResourceClosingRestrictionQuotientExact as Quotient
import DASHI.Mathematics.Complexity.PNotEqualsNPStrictSemanticRepresentativeQuotientExact as Strict
import DASHI.Mathematics.Complexity.PNotEqualsNPClosedStrictRepresentativeQuotientExact as Closed
import DASHI.Mathematics.Complexity.PNotEqualsNPSelfReferenceAllOverheadBudgetExact as Q1
import DASHI.Mathematics.Complexity.PNotEqualsNPBoundedSelfReferenceWellFoundedExact as Q2
import DASHI.Mathematics.Complexity.PNotEqualsNPQ1ReachableStateRecurrenceExact as Recurrence

------------------------------------------------------------------------
-- Generated closed representative surface.
------------------------------------------------------------------------

record GeneratedClosedRepresentativeQuotient
    {rootVariables : Nat}
    (root : SAT.BooleanFormula rootVariables) : Set₁ where
  constructor generated-closed-representative-quotient
  field
    generatedQuotient :
      Generated.TransitionGeneratedRestrictionQuotient root

    representative :
      Fin (Generated.stateCount generatedQuotient) →
      Cook.BooleanFormula

    representativeEquivalent :
      ∀ {currentVariables : Nat}
        {current : SAT.BooleanFormula currentVariables}
        (derivation :
          Family.RestrictionDerivation root current) →
      Strict.CookSatisfiabilityEquivalent
        (Bridge.indexedToCook current)
        (representative
          (Generated.generatedSelect
            (Generated.rootState generatedQuotient)
            (Generated.step generatedQuotient)
            derivation))

    representativeStrictlySmallerThanRoot :
      (state : Fin (Generated.stateCount generatedQuotient)) →
      Size.formulaNodeCount
        (representative state)
      <
      Size.formulaNodeCount
        (Bridge.indexedToCook root)

    representativeChain :
      (state : Fin (Generated.stateCount generatedQuotient)) →
      Closed.StructuralRepresentativeChain
        (representative state)

open GeneratedClosedRepresentativeQuotient public

------------------------------------------------------------------------
-- Compile to the legacy strict quotient.
------------------------------------------------------------------------

toStrictSemanticRepresentativeQuotient :
  ∀ {rootVariables : Nat}
    {root : SAT.BooleanFormula rootVariables} →
  GeneratedClosedRepresentativeQuotient root →
  Strict.StrictSemanticRepresentativeQuotient root
toStrictSemanticRepresentativeQuotient generatedClosed =
  Strict.strict-semantic-representative-quotient
    legacyQuotient
    (representative generatedClosed)
    (representativeEquivalent generatedClosed)
    (representativeStrictlySmallerThanRoot generatedClosed)
  where
    legacyQuotient :
      Quotient.RestrictionSemanticQuotient _
    legacyQuotient =
      Generated.toRestrictionSemanticQuotient
        (generatedQuotient generatedClosed)

toClosedStrictRepresentativeQuotient :
  ∀ {rootVariables : Nat}
    {root : SAT.BooleanFormula rootVariables} →
  GeneratedClosedRepresentativeQuotient root →
  Closed.ClosedStrictRepresentativeQuotient root
toClosedStrictRepresentativeQuotient generatedClosed =
  Closed.closed-strict-representative-quotient
    (toStrictSemanticRepresentativeQuotient generatedClosed)
    (representativeChain generatedClosed)

------------------------------------------------------------------------
-- The generated selector is literally the classifier after compilation.
------------------------------------------------------------------------

compiledClassifierIsGenerated :
  ∀ {rootVariables currentVariables : Nat}
    {root : SAT.BooleanFormula rootVariables}
    (generatedClosed :
      GeneratedClosedRepresentativeQuotient root)
    {current : SAT.BooleanFormula currentVariables}
    (derivation :
      Family.RestrictionDerivation root current) →
  Quotient.classify
    (Strict.quotient
      (Closed.strictQuotient
        (toClosedStrictRepresentativeQuotient generatedClosed)))
    derivation
  ≡
  Generated.generatedSelect
    (Generated.rootState (generatedQuotient generatedClosed))
    (Generated.step (generatedQuotient generatedClosed))
    derivation
compiledClassifierIsGenerated generatedClosed derivation =
  refl

------------------------------------------------------------------------
-- State-specific Q1 discovery payload, including the existing all-overhead
-- strict-fit certificate after compilation.
------------------------------------------------------------------------

GeneratedQ1StateWitness :
  (state : Q2.BoundedSelfReferenceState) →
  Set₁
GeneratedQ1StateWitness state =
  Σ
    (GeneratedClosedRepresentativeQuotient
      (Bridge.cookToIndexed
        (Q2.currentFormula state)))
    (λ generatedClosed →
      Q1.ClosedQuotientAllOverheadFits
        (toClosedStrictRepresentativeQuotient generatedClosed)
        (Recurrence.stateOverhead state))

generatedWitnessToLegacyQ1 :
  ∀ {state : Q2.BoundedSelfReferenceState} →
  GeneratedQ1StateWitness state →
  Recurrence.Q1StateWitness state
generatedWitnessToLegacyQ1
    (generatedClosed , fits) =
  toClosedStrictRepresentativeQuotient generatedClosed
  ,
  fits

------------------------------------------------------------------------
-- FRONTIER CONSEQUENCE
--
-- The live constructor no longer owes an arbitrary classifier.
--
-- It owes only:
--
--   generated transition quotient:
--     stateCount + rootState + step + generated-state semantic congruence
--
--   plus:
--     strict representative for each generated state
--     structural chain for each representative
--     all-overhead fit.
--
-- Class selection for every reachable descendant is then executable replay,
-- already proved exact with transition cost equal to restriction depth.
------------------------------------------------------------------------
