module DASHI.Mathematics.Complexity.PNotEqualsNPQ1Q2AllOverheadBridgeExact where

------------------------------------------------------------------------
-- Q1 -> Q2: THE SAME RESOURCE CURRENCY ON THE ACTUAL RECURSIVE STATE
--
-- Q1 produces a strict inequality
--
--   |closedAuthority| + (quotation + rebinding) < |root|.
--
-- Q2 measures a recursive state by
--
--   |currentFormula| + (programCodeSize + rebindingOverhead).
--
-- This owner identifies those currencies exactly by building the canonical
-- current/next recursive states with
--
--   programCodeSize    = quotationOverhead
--   rebindingOverhead  = rebindingOverhead.
--
-- Therefore a Q1 all-overhead certificate is already a strict decrease of the
-- WHOLE Q2 recursive state.  There is no hidden equal-or-larger rebuild between
-- these two layers.
--
-- What remains open is constructing Q1 for every nonterminal state generated by
-- the special self-instantiation process.  This bridge does not assume that.
------------------------------------------------------------------------

open import Agda.Builtin.Equality using (_≡_; refl)
open import Agda.Builtin.Nat using (Nat; _+_)
open import Data.Nat using (_<_)
import Data.Nat.Properties as NatP

import DASHI.Mathematics.Complexity.BooleanFormulaSATSelfReductionExact as SAT
import DASHI.Mathematics.Complexity.PNotEqualsNPCookIndexedFormulaBridgeExact as Bridge
import DASHI.Mathematics.Complexity.PNotEqualsNPProgramDescriptionFormulaEmbeddingExact as Size
import DASHI.Mathematics.Complexity.PNotEqualsNPClosedStrictRepresentativeQuotientExact as Closed
import DASHI.Mathematics.Complexity.PNotEqualsNPClosedRestrictionQuotientSATAuthorityExact as Authority
import DASHI.Mathematics.Complexity.PNotEqualsNPSelfReferenceAllOverheadBudgetExact as Q1
import DASHI.Mathematics.Complexity.PNotEqualsNPBoundedSelfReferenceWellFoundedExact as Q2

------------------------------------------------------------------------
-- Canonical Q2 states for one Q1 descent.
------------------------------------------------------------------------

rootRecursiveState :
  ∀ {rootVariables : Nat}
    (root : SAT.BooleanFormula rootVariables)
    (overhead : Q1.SelfReferenceOverhead) →
  Q2.BoundedSelfReferenceState
rootRecursiveState root overhead =
  Q2.bounded-self-reference-state
    (Bridge.indexedToCook root)
    (Q1.quotationOverhead overhead)
    (Q1.rebindingOverhead overhead)
    (Size.formulaNodeCount (Bridge.indexedToCook root)
      + Q1.totalOverhead overhead)
    NatP.≤-refl

authorityRecursiveState :
  ∀ {rootVariables : Nat}
    {root : SAT.BooleanFormula rootVariables}
    (closed : Closed.ClosedStrictRepresentativeQuotient root)
    (overhead : Q1.SelfReferenceOverhead) →
  Q2.BoundedSelfReferenceState
authorityRecursiveState closed overhead =
  Q2.bounded-self-reference-state
    (Authority.closedQuotientSATAuthority closed)
    (Q1.quotationOverhead overhead)
    (Q1.rebindingOverhead overhead)
    (Size.formulaNodeCount
      (Authority.closedQuotientSATAuthority closed)
      + Q1.totalOverhead overhead)
    NatP.≤-refl

------------------------------------------------------------------------
-- Definitional measure identities.
------------------------------------------------------------------------

rootRecursiveMeasure :
  ∀ {rootVariables : Nat}
    (root : SAT.BooleanFormula rootVariables)
    (overhead : Q1.SelfReferenceOverhead) →
  Q2.recursiveMeasure
    (rootRecursiveState root overhead)
  ≡
  Size.formulaNodeCount (Bridge.indexedToCook root)
    + Q1.totalOverhead overhead
rootRecursiveMeasure root overhead =
  refl

authorityRecursiveMeasure :
  ∀ {rootVariables : Nat}
    {root : SAT.BooleanFormula rootVariables}
    (closed : Closed.ClosedStrictRepresentativeQuotient root)
    (overhead : Q1.SelfReferenceOverhead) →
  Q2.recursiveMeasure
    (authorityRecursiveState closed overhead)
  ≡
  Size.formulaNodeCount
      (Authority.closedQuotientSATAuthority closed)
    + Q1.totalOverhead overhead
authorityRecursiveMeasure closed overhead =
  refl

------------------------------------------------------------------------
-- Main bridge: Q1 is literally a Q2 whole-state decrease.
------------------------------------------------------------------------

q1AllOverheadGivesQ2MeasureDecrease :
  ∀ {rootVariables : Nat}
    {root : SAT.BooleanFormula rootVariables}
    (closed : Closed.ClosedStrictRepresentativeQuotient root)
    (overhead : Q1.SelfReferenceOverhead) →
  Q1.ClosedQuotientAllOverheadFits closed overhead →
  Q2.recursiveMeasure
    (authorityRecursiveState closed overhead)
  <
  Q2.recursiveMeasure
    (rootRecursiveState root overhead)
q1AllOverheadGivesQ2MeasureDecrease
    closed
    overhead
    fits =
  Q1.closedAuthorityPlusAllOverheadStrictlySmaller
    closed
    overhead
    fits

------------------------------------------------------------------------
-- Pack the one-step recursive transition as explicit proof data.
------------------------------------------------------------------------

record Q1Q2StrictStep
    {rootVariables : Nat}
    {root : SAT.BooleanFormula rootVariables}
    (closed : Closed.ClosedStrictRepresentativeQuotient root)
    (overhead : Q1.SelfReferenceOverhead) : Set where
  constructor q1-q2-strict-step
  field
    current :
      Q2.BoundedSelfReferenceState

    next :
      Q2.BoundedSelfReferenceState

    currentIsRoot :
      current ≡ rootRecursiveState root overhead

    nextIsAuthority :
      next ≡ authorityRecursiveState closed overhead

    decreases :
      Q2.recursiveMeasure next
      <
      Q2.recursiveMeasure current

open Q1Q2StrictStep public

q1BuildsQ2StrictStep :
  ∀ {rootVariables : Nat}
    {root : SAT.BooleanFormula rootVariables}
    (closed : Closed.ClosedStrictRepresentativeQuotient root)
    (overhead : Q1.SelfReferenceOverhead) →
  Q1.ClosedQuotientAllOverheadFits closed overhead →
  Q1Q2StrictStep closed overhead
q1BuildsQ2StrictStep {root = root} closed overhead fits =
  q1-q2-strict-step
    (rootRecursiveState root overhead)
    (authorityRecursiveState closed overhead)
    refl
    refl
    (q1AllOverheadGivesQ2MeasureDecrease
      closed overhead fits)

------------------------------------------------------------------------
-- Research boundary.
--
-- This removes the bookkeeping ambiguity identified in the roadmap:
-- quotation/rebinding overhead is charged in Q1 and the exact same quantity is
-- present in the Q2 recursive measure.
--
-- The remaining hard theorem must now construct, at each live self-instantiation
-- state, the closed quotient and all-overhead fit certificate used above.
------------------------------------------------------------------------
