module DASHI.Mathematics.Complexity.PNotEqualsNPQ1RootedExhaustiveMergeExact where

------------------------------------------------------------------------
-- ROOT-ORIGINATED FINITE SHANNON ENUMERATION
--
-- Each graded layer is generated from the literal root by repeated execution
-- of both restriction transitions. There is no externally supplied list of
-- "reachable states".
--
-- The construction deliberately allows duplicates, and merges semantic keys
-- only after enumerating each layer. It is a concrete exhaustive reference
-- algorithm, not a polynomial bound or an admitted direct-DP/Q1 constructor.
------------------------------------------------------------------------

open import Agda.Builtin.Equality using (_≡_; refl)
open import Agda.Builtin.List using (List; []; _∷_)
open import Agda.Builtin.Nat using (Nat; zero; suc; _+_)
open import Data.List.Base using (length)

import DASHI.Mathematics.Complexity.BooleanFormulaSATSelfReductionExact as SAT
import DASHI.Mathematics.Complexity.PNotEqualsNPSelfDiagonalRestrictionFamilyExact as Family
import DASHI.Mathematics.Complexity.PNotEqualsNPSelfDiagonalResidualWidthExact as Width
import DASHI.Mathematics.Complexity.PNotEqualsNPQ1CanonicalTruthTableMergeExact as Merge
import DASHI.Mathematics.Complexity.PNotEqualsNPQ1EnumeratedMergedLayerExact as Step

------------------------------------------------------------------------
-- A path is typed at its actual remaining arity.
------------------------------------------------------------------------

data DescentPath
    {rootVariables : Nat}
    (root : SAT.BooleanFormula rootVariables) :
    Nat → Set where
  atRoot :
    DescentPath root rootVariables
  descend :
    ∀ {remaining} →
    DescentPath root (suc remaining) →
    DescentPath root remaining

rootLayerNode :
  ∀ {rootVariables : Nat}
    (root : SAT.BooleanFormula rootVariables) →
  Width.LayerNode {root = root} rootVariables
rootLayerNode root =
  Width.layer-node
    (Family.restriction-node
      rootVariables
      root
      Family.restrictionRoot)
    refl
  where
    rootVariables : Nat
    rootVariables = _

------------------------------------------------------------------------
-- Entire layer is generated by actual transitions from the preceding layer.
------------------------------------------------------------------------

rootedLayer :
  ∀ {rootVariables remaining : Nat}
    {root : SAT.BooleanFormula rootVariables} →
  DescentPath root remaining →
  List (Width.LayerNode {root = root} remaining)
rootedLayer {root = root} atRoot =
  rootLayerNode root ∷ []
rootedLayer (descend previous) =
  Step.enumerateShannonChildren
    (rootedLayer previous)

rootedMergedSemanticKeys :
  ∀ {rootVariables remaining : Nat}
    {root : SAT.BooleanFormula rootVariables} →
  DescentPath root remaining →
  List (Merge.SemanticKey remaining)
rootedMergedSemanticKeys path =
  Merge.canonicalMergedLayer
    (rootedLayer path)

------------------------------------------------------------------------
-- Exact structural count before semantic deduplication.
------------------------------------------------------------------------

rootedLayerEnumerationCount :
  ∀ {rootVariables remaining : Nat}
    {root : SAT.BooleanFormula rootVariables} →
  DescentPath root remaining →
  Nat
rootedLayerEnumerationCount path =
  length (rootedLayer path)

rootedLayerCountAtRoot :
  ∀ {rootVariables : Nat}
    {root : SAT.BooleanFormula rootVariables} →
  rootedLayerEnumerationCount (atRoot {root = root})
  ≡
  suc zero
rootedLayerCountAtRoot =
  refl

rootedLayerCountAfterDescent :
  ∀ {rootVariables remaining : Nat}
    {root : SAT.BooleanFormula rootVariables}
    (previous : DescentPath root (suc remaining)) →
  rootedLayerEnumerationCount (descend previous)
  ≡
  Step.twice (rootedLayerEnumerationCount previous)
rootedLayerCountAfterDescent previous =
  Step.enumeratedChildCount (rootedLayer previous)

------------------------------------------------------------------------
-- Declared operation counts across all layers of the explicit traversal.
------------------------------------------------------------------------

rootedDeclaredWork :
  ∀ {rootVariables remaining : Nat}
    {root : SAT.BooleanFormula rootVariables} →
  DescentPath root remaining →
  Nat
rootedDeclaredWork {root = root} atRoot =
  Merge.layerTotalAccounting (rootLayerNode root ∷ [])
rootedDeclaredWork (descend previous) =
  rootedDeclaredWork previous
  + Step.oneLayerDeclaredWork (rootedLayer previous)

------------------------------------------------------------------------
-- Importantly, this structural traversal is intentionally exponential in the
-- number of descent levels before deduplication. It is a concrete regression
-- donor and an upper-bound work baseline, not the still-missing globally
-- charged, canonically indexed, strict-fit Q1 construction.
------------------------------------------------------------------------
