module DASHI.Biology.Agriculture.Everything where

import DASHI.Biology.Agriculture.HungriaBiologicalNitrogenFixationSourceAtlas
import DASHI.Biology.Agriculture.HungriaSourceAttributionPromotionBoundaryExact
import DASHI.Biology.Agriculture.HungriaSoybeanBNFExact
import DASHI.Biology.Agriculture.HungriaEconomicEmissionModel2023Exact
import DASHI.Biology.Agriculture.NitrogenaseChemistryCrossPollinationExact
import DASHI.Biology.Agriculture.BNFMechanismToFieldPromotionBidiExact
import DASHI.Biology.Agriculture.BNFEconomicValidationCrossPollinationExact
import DASHI.Biology.Agriculture.BNFClimateCountryLESCrossPollinationExact
import DASHI.Biology.Agriculture.BNFQualifiedInterventionModelExact
import DASHI.Biology.Agriculture.BNFSevenGenerationPlanningExact
import DASHI.Biology.Agriculture.BNFSevenGenerationRobustnessExact
import DASHI.Biology.Agriculture.Hungria2024EconomicReplayInputAuditExact
import DASHI.Biology.Agriculture.Hungria2024HeadlineLineageWeldExact

-- Acacia/Senegalia dryland BNF <-> situated-protein <-> LES tranche.
import DASHI.Biology.Agriculture.AcaciaSenegalRhizobialBNFSourceAtlasExact
import DASHI.Biology.Agriculture.AcaciaSenegalRhizobialBNFSourceAtlasRegression
import DASHI.Biology.Agriculture.LegumeNodulationSituatedProteinBridgeExact
import DASHI.Biology.Agriculture.LegumeNodulationSituatedProteinBridgeRegression
import DASHI.Biology.Agriculture.AcaciaSenegalBNFLESCrossPollinationExact
import DASHI.Biology.Agriculture.AcaciaSenegalBNFLESCrossPollinationRegression
