module DASHI.Biology.Agriculture.Everything where

import DASHI.Biology.Agriculture.HungriaBiologicalNitrogenFixationSourceAtlas
import DASHI.Biology.Agriculture.HungriaSourceAttributionPromotionBoundaryExact
import DASHI.Biology.Agriculture.HungriaSoybeanBNFExact
import DASHI.Biology.Agriculture.HungriaEconomicEmissionModel2023Exact
import DASHI.Biology.Agriculture.NitrogenaseChemistryCrossPollinationExact
import DASHI.Biology.Agriculture.BNFMechanismToFieldPromotionBidiExact
import DASHI.Biology.Agriculture.BNFEconomicValidationCrossPollinationExact
import DASHI.Biology.Agriculture.BNFClimateCountryLESCrossPollinationExact
import DASHI.Biology.Agriculture.BNFQualifiedInterventionModelExact
import DASHI.Biology.Agriculture.BNFSevenGenerationPlanningExact
import DASHI.Biology.Agriculture.BNFSevenGenerationRobustnessExact
import DASHI.Biology.Agriculture.Hungria2024EconomicReplayInputAuditExact
import DASHI.Biology.Agriculture.Hungria2024HeadlineLineageWeldExact

-- Acacia/Senegalia dryland BNF <-> situated-protein <-> LES tranche.
import DASHI.Biology.Agriculture.AcaciaSenegalRhizobialBNFSourceAtlasExact
import DASHI.Biology.Agriculture.AcaciaSenegalRhizobialBNFSourceAtlasRegression
import DASHI.Biology.Agriculture.AcaciaRhizobialCompetitiveOccupancyExact
import DASHI.Biology.Agriculture.AcaciaRhizobialCompetitiveOccupancyRegression
import DASHI.Biology.Agriculture.LegumeNodulationSituatedProteinBridgeExact
import DASHI.Biology.Agriculture.LegumeNodulationSituatedProteinBridgeRegression
import DASHI.Biology.Agriculture.AcaciaSenegalBNFLESCrossPollinationExact
import DASHI.Biology.Agriculture.AcaciaSenegalBNFLESCrossPollinationRegression
import DASHI.Biology.Agriculture.AcaciaSenegalBNFEdaphicLESExact
import DASHI.Biology.Agriculture.AcaciaSenegalBNFEdaphicLESRegression
import DASHI.Biology.Agriculture.AcaciaSenegalSymbiosisEnvironmentalEnablementExact
import DASHI.Biology.Agriculture.AcaciaSenegalSymbiosisEnvironmentalEnablementRegression
import DASHI.Biology.Agriculture.AcaciaSenegalDualSymbiosisPContextExact
import DASHI.Biology.Agriculture.AcaciaSenegalDualSymbiosisPContextRegression
import DASHI.Biology.Agriculture.AcaciaSenegalPlantNitrogenAssimilationEvidenceExact
import DASHI.Biology.Agriculture.AcaciaSenegalPlantNitrogenAssimilationEvidenceRegression
import DASHI.Biology.Agriculture.AcaciaSenegalBNFMeasurementHierarchyExact
import DASHI.Biology.Agriculture.AcaciaSenegalBNFMeasurementHierarchyRegression
import DASHI.Biology.Agriculture.AcaciaSenegalFixedNTransferNutrientBudgetExact
import DASHI.Biology.Agriculture.AcaciaSenegalFixedNTransferNutrientBudgetRegression
import DASHI.Biology.Agriculture.AcaciaSenegalWaterCropManagementCrossPollinationExact
import DASHI.Biology.Agriculture.AcaciaSenegalWaterCropManagementCrossPollinationRegression
