module DASHI.Environment.BiocontrolFirstImplementationRegression where

import DASHI.Core.FirstImplementationTimestampExact as Chronology
import DASHI.Environment.BiocontrolFirstImplementationExact as First

externalityFirstImplementation : Chronology.FirstImplementationReceipt
externalityFirstImplementation = First.biocontrolExternalityFirstImplementation

costedChoiceFirstImplementation : Chronology.FirstImplementationReceipt
costedChoiceFirstImplementation = First.biocontrolCostedChoiceFirstImplementation

siQuantityFirstImplementation : Chronology.FirstImplementationReceipt
siQuantityFirstImplementation = First.biocontrolSIQuantityFirstImplementation

chemistry369FirstImplementation : Chronology.FirstImplementationReceipt
chemistry369FirstImplementation = First.biocontrolChemistry369FirstImplementation

springfieldMechanicalRemovalFirstImplementation : Chronology.FirstImplementationReceipt
springfieldMechanicalRemovalFirstImplementation = First.springfieldMechanicalRemovalFirstImplementation
