module DASHI.Environment.BiocontrolChemistryAcquisitionPromotionExact where

open import DASHI.Core.Prelude
open import Agda.Builtin.String using (String)

import DASHI.Core.EvidenceAcquisitionSelectiveReopeningExact as Acquisition
import DASHI.Core.AffectedDependencyClosureExact as Dependency
import DASHI.Core.GovernedObservationProvenanceExact as Governed
import DASHI.Environment.BiocontrolCalibratedEcologicalClassificationExact as Calibration
import DASHI.Environment.BiocontrolChemistryParetoExperimentSchedulerExact as Scheduler

------------------------------------------------------------------------
-- PARETO-SCHEDULED EXPERIMENT -> ACQUISITION -> QUALIFIED OBSERVATION
-- -> CALIBRATED CLASSIFICATION -> SELECTIVE REOPENING
--
-- The scheduler chooses what would separate the current finite collision.  It
-- does not thereby acquire a field observation.  This owner inserts the missing
-- evidence/payment boundary explicitly.
--
-- Attribution rule carried forward from earlier rounds:
--   * external sources own only source-bounded premises actually acquired;
--   * BIPM remains metrology-only;
--   * Ipswich remains salvinia operational context only;
--   * DASHI owns the synthetic finite worlds, scheduler, obligations,
--     dependency graph and selective-reopening theorems;
--   * a numeric/site observation requires its own source/sample/protocol/time/
--     uncertainty provenance before it can be promoted as empirical evidence.
------------------------------------------------------------------------

------------------------------------------------------------------------
-- Targeted acquisition obligations generated by the already-selected bundles.
------------------------------------------------------------------------

speciesAssayAcquisitionTarget : Acquisition.AcquisitionTarget
speciesAssayAcquisitionTarget = Acquisition.acquisition-target
  "biocontrol species/fraction assay observation"
  "acquire the analyte/species/fraction observation required by the Pareto-selected speciesSensitive experiment bundle"
  "site-qualified assay/sensor record with sample identity, method, time window, uncertainty and provenance"
  "operator or laboratory source package carrying equivalent provenance coordinates"
  "acquisition remains subject to the actual site/operator/laboratory access and authority rules"

speciesAssayAcquisitionObligation :
  Acquisition.AcquisitionObligation speciesAssayAcquisitionTarget
speciesAssayAcquisitionObligation =
  Acquisition.obligationFromNotLocated speciesAssayAcquisitionTarget

contextAcquisitionTarget : Acquisition.AcquisitionTarget
contextAcquisitionTarget = Acquisition.acquisition-target
  "biocontrol contextual-classification observation"
  "acquire the site/season/window/protocol/uncertainty context required by the Pareto-selected contextualChemistry experiment bundle"
  "site-qualified contextual record linked to the same observation identity"
  "operator, monitoring, laboratory or management record preserving the same-object context lineage"
  "acquisition remains subject to source-specific access, governance and authority"

contextAcquisitionObligation :
  Acquisition.AcquisitionObligation contextAcquisitionTarget
contextAcquisitionObligation =
  Acquisition.obligationFromNotLocated contextAcquisitionTarget

speciesSchedulerReceipt : Scheduler.SpeciesParetoScheduledExperiment
speciesSchedulerReceipt = Scheduler.canonicalSpeciesParetoScheduledExperiment

contextSchedulerReceipt : Scheduler.ContextParetoScheduledExperiment
contextSchedulerReceipt = Scheduler.canonicalContextParetoScheduledExperiment

------------------------------------------------------------------------
-- A scheduled/synthetic fibre witness is not an acquired observation.
--
-- No canonical value of `QualifiedObservation` is constructed here.  The type
-- is a promotion gate that downstream runtime/source acquisition must pay.
------------------------------------------------------------------------

record SourceProtocolQualifiedObservation : Set where
  constructor source-protocol-qualified-observation
  field
    selectedBundleReference : String
    observationValueReference : String
    sourceIdentityReference : String
    siteIdentityReference : String
    sampleIdentityReference : String
    samplingWindowReference : String
    assayOrSensorProtocolReference : String
    analyteOrContextReference : String
    uncertaintyReference : String
    custodyTransformationReference : String
    provenanceLineage : Governed.CoordinateLineage
    sourceLocated : Bool
    protocolPaid : Bool
    observationValuePaid : Bool
    sameObjectIdentityPaid : Bool
    syntheticFixture : Bool

open SourceProtocolQualifiedObservation public

record QualifiedObservation (observation : SourceProtocolQualifiedObservation) : Set where
  constructor qualified-observation
  field
    sourceLocatedIsTrue : sourceLocated observation ≡ true
    protocolPaidIsTrue : protocolPaid observation ≡ true
    observationValuePaidIsTrue : observationValuePaid observation ≡ true
    sameObjectIdentityPaidIsTrue : sameObjectIdentityPaid observation ≡ true
    syntheticFixtureIsFalse : syntheticFixture observation ≡ false

open QualifiedObservation public

record QualifiedClassificationPromotion
    (observation : SourceProtocolQualifiedObservation)
    (classification : Calibration.CalibratedClassificationReceipt) : Set where
  constructor qualified-classification-promotion
  field
    observationIsQualified : QualifiedObservation observation
    empiricalObservationPaidIsTrue :
      Calibration.empiricalObservationPaid classification ≡ true
    thresholdCalibrationPaidIsTrue :
      Calibration.thresholdCalibrationPaid classification ≡ true
    uncertaintyHandlingPaidIsTrue :
      Calibration.uncertaintyHandlingPaid classification ≡ true
    localValidationPaidIsTrue :
      Calibration.localValidationPaid (Calibration.context classification) ≡ true
    createsInterventionAuthorityIsFalse :
      Calibration.createsInterventionAuthority classification ≡ false
    promotionReference : String

open QualifiedClassificationPromotion public

------------------------------------------------------------------------
-- Selective downstream reopening.
--
-- The graph is repository-local DASHI structure.  A changed acquired
-- observation can reopen the classification and its explicitly dependent
-- rebound consumer.  No edge is declared to the Springfield equipment lane.
------------------------------------------------------------------------

data BiocontrolAcquisitionArtifact : Set where
  acquiredObservationArtifact : BiocontrolAcquisitionArtifact
  calibratedClassificationArtifact : BiocontrolAcquisitionArtifact
  reboundConsumerArtifact : BiocontrolAcquisitionArtifact
  springfieldEquipmentArtifact : BiocontrolAcquisitionArtifact

data BiocontrolAcquisitionDepends :
  BiocontrolAcquisitionArtifact → BiocontrolAcquisitionArtifact → Set where
  observationToClassification :
    BiocontrolAcquisitionDepends
      acquiredObservationArtifact calibratedClassificationArtifact
  classificationToRebound :
    BiocontrolAcquisitionDepends
      calibratedClassificationArtifact reboundConsumerArtifact

biocontrolAcquisitionDependencyGraph :
  Acquisition.AcquisitionDependencyGraph BiocontrolAcquisitionArtifact
biocontrolAcquisitionDependencyGraph = Acquisition.acquisition-dependency-graph
  BiocontrolAcquisitionDepends
  "qualified observation -> calibrated classification -> rebound consumer; no declared path to Springfield equipment selection"

observationReopensClassification :
  Acquisition.SelectiveAcquisitionReopening
    biocontrolAcquisitionDependencyGraph
    acquiredObservationArtifact
    calibratedClassificationArtifact
observationReopensClassification =
  Acquisition.oneEdgeAcquisitionReopening observationToClassification

classificationReopensReboundConsumer :
  Acquisition.SelectiveAcquisitionReopening
    biocontrolAcquisitionDependencyGraph
    calibratedClassificationArtifact
    reboundConsumerArtifact
classificationReopensReboundConsumer =
  Acquisition.oneEdgeAcquisitionReopening classificationToRebound

observationReopensReboundConsumer :
  Acquisition.SelectiveAcquisitionReopening
    biocontrolAcquisitionDependencyGraph
    acquiredObservationArtifact
    reboundConsumerArtifact
observationReopensReboundConsumer =
  Acquisition.selective-acquisition-reopening
    (Dependency.obligationsCompose
      (Acquisition.obligation observationReopensClassification)
      (Acquisition.obligation classificationReopensReboundConsumer))
    "newly qualified observation reopens the dependency-reachable rebound consumer through the calibrated-classification edge"

------------------------------------------------------------------------
-- Attribution / promotion firewall.
------------------------------------------------------------------------

record BiocontrolChemistryAcquisitionPromotionBoundary : Set where
  constructor biocontrolChemistryAcquisitionPromotionBoundary
  field
    scheduledBundleIsAcquiredObservation : Bool
    scheduledBundleIsAcquiredObservationIsFalse :
      scheduledBundleIsAcquiredObservation ≡ false

    syntheticRefinedFibreIsFieldMeasurement : Bool
    syntheticRefinedFibreIsFieldMeasurementIsFalse :
      syntheticRefinedFibreIsFieldMeasurement ≡ false

    sourceProtocolQualificationRequiredBeforePromotion : Bool
    sourceProtocolQualificationRequiredBeforePromotionIsTrue :
      sourceProtocolQualificationRequiredBeforePromotion ≡ true

    calibrationPaymentRequiredAfterObservation : Bool
    calibrationPaymentRequiredAfterObservationIsTrue :
      calibrationPaymentRequiredAfterObservation ≡ true

    acquiredObservationReopensOnlyDependencyReachableConsumers : Bool
    acquiredObservationReopensOnlyDependencyReachableConsumersIsTrue :
      acquiredObservationReopensOnlyDependencyReachableConsumers ≡ true

    schedulerCreatesDeploymentAuthority : Bool
    schedulerCreatesDeploymentAuthorityIsFalse :
      schedulerCreatesDeploymentAuthority ≡ false

    acquisitionObligationInventsUnavailableRecord : Bool
    acquisitionObligationInventsUnavailableRecordIsFalse :
      acquisitionObligationInventsUnavailableRecord ≡ false

    crossPollinationTransfersSourceAuthorship : Bool
    crossPollinationTransfersSourceAuthorshipIsFalse :
      crossPollinationTransfersSourceAuthorship ≡ false

    ipswichSalviniaRecordPaysChemistryMeasurement : Bool
    ipswichSalviniaRecordPaysChemistryMeasurementIsFalse :
      ipswichSalviniaRecordPaysChemistryMeasurement ≡ false

    bipmMetrologyPaysEcologicalClassification : Bool
    bipmMetrologyPaysEcologicalClassificationIsFalse :
      bipmMetrologyPaysEcologicalClassification ≡ false

canonicalBiocontrolChemistryAcquisitionPromotionBoundary :
  BiocontrolChemistryAcquisitionPromotionBoundary
canonicalBiocontrolChemistryAcquisitionPromotionBoundary =
  biocontrolChemistryAcquisitionPromotionBoundary
    false refl
    false refl
    true refl
    true refl
    true refl
    false refl
    false refl
    false refl
    false refl
    false refl

attributionReading : String
attributionReading =
  "The scheduler and synthetic fibres are DASHI mathematics, not observations. External sources retain only their acquired source-bounded premises. An empirical promotion requires a separately acquired same-object observation with source/site/sample/time/protocol/uncertainty provenance, followed by separately paid calibration. BIPM remains metrology-only; Ipswich remains salvinia operational context only; citation and cross-pollination import neither proof nor authority."
