module DASHI.Environment.KNFPermacultureFruitValidationExact where

import DASHI.Environment.PermacultureEmbodiedEnergyLandscapeBridgeExact
import DASHI.Environment.KoreanNaturalFarmingExact
import DASHI.Environment.KNFPermacultureEmbodiedEnergyBridgeExact
import DASHI.Biology.FruitBoundaryResourcePaidRepairExact
