module DASHI.Moonshine.JInvariant369ModularLevelCuspObserversExact where

------------------------------------------------------------------------
-- MODULAR LEVEL STRUCTURE FOR THE 3/6/9/27 J-PHASE OBSERVERS
--
-- Mathematical correction / target:
--
-- The full principal-level covering X(N) -> X(1) does NOT in general have
-- cyclic deck group C_N.  Its full finite modular symmetry is much larger.
--
-- What is canonically cyclic is the cusp-translation orbit generated by
--
--   T : tau |-> tau + 1.
--
-- Modulo the principal congruence subgroup Gamma(N), T^N is trivial:
--
--   T^N = [ 1 N ]
--         [ 0 1 ]  == I (mod N).
--
-- Hence the cyclic cusp fibre generated by T has the canonical presentation
--
--   <T> / <T^N> ~= Z/NZ.
--
-- This module connects the existing 3/6/9/27 observer carriers to exactly that
-- structure.  It does NOT identify the full level-N modular cover with C_N.
------------------------------------------------------------------------

open import DASHI.Core.Prelude
open import Agda.Builtin.Bool using (Bool; true; false)
open import Agda.Builtin.Nat using (Nat; zero; suc)
open import Agda.Builtin.String using (String)
open import Data.Integer using (ℤ; 0ℤ; 1ℤ; +_)
open import Relation.Binary.PropositionalEquality using (cong; sym; trans)

open import DASHI.Physics.Closure.BalancedTernaryContinuousEnvelope
  using (Trit; neg; zer; pos; []; _∷_)

import Base369 as Base
import DASHI.Physics.Closure.TriadicEisensteinTransformationTheorem as Eisenstein
import DASHI.Foundations.TriadicFiniteQuotient as Q
import DASHI.Algebra.TriadicFiniteArithmetic as Arithmetic
import DASHI.Biology.TriadicKernelLiftQuotientExact as Kernel
import DASHI.Foundations.SSPTritCarrier as SSP
import DASHI.Foundations.Base369Ternary27HypervoxelFabricGeometryExact as Fabric
import DASHI.Moonshine.JInvariantFormulaic369RendererExact as Render

------------------------------------------------------------------------
-- 1. Literal translation matrices.
------------------------------------------------------------------------

translationMatrix : ℤ → Eisenstein.SL2Z
translationMatrix n =
  Eisenstein.sl2z 1ℤ n 0ℤ 1ℤ refl

T : Eisenstein.SL2Z
T = translationMatrix 1ℤ

translationPower : Nat → Eisenstein.SL2Z
translationPower n = translationMatrix (+ n)

record TranslationPowerPrincipalLevelWitness
    (level : Nat) : Set where
  constructor translation-power-principal-level-witness
  field
    aIsOne :
      Eisenstein.a (translationPower level) ≡ 1ℤ
    bIsLevel :
      Eisenstein.b (translationPower level) ≡ + level
    cIsZero :
      Eisenstein.c (translationPower level) ≡ 0ℤ
    dIsOne :
      Eisenstein.d (translationPower level) ≡ 1ℤ

open TranslationPowerPrincipalLevelWitness public

translationPowerPrincipalWitness :
  (level : Nat) →
  TranslationPowerPrincipalLevelWitness level
translationPowerPrincipalWitness level =
  translation-power-principal-level-witness refl refl refl refl

level3PrincipalWitness : TranslationPowerPrincipalLevelWitness 3
level3PrincipalWitness = translationPowerPrincipalWitness 3

level6PrincipalWitness : TranslationPowerPrincipalLevelWitness 6
level6PrincipalWitness = translationPowerPrincipalWitness 6

level9PrincipalWitness : TranslationPowerPrincipalLevelWitness 9
level9PrincipalWitness = translationPowerPrincipalWitness 9

level27PrincipalWitness : TranslationPowerPrincipalLevelWitness 27
level27PrincipalWitness = translationPowerPrincipalWitness 27

------------------------------------------------------------------------
-- 2. Canonical triadic cusp fibres Z/3^d Z.
--
-- The repository already represents Z/3^d Z by balanced-ternary residues.
-- Translation by T is therefore addition of the residue 1.
------------------------------------------------------------------------

oneResidue : (depth : Nat) → Q.Residue3Pow depth
oneResidue zero = []
oneResidue (suc depth) = pos ∷ Arithmetic.zeroResidue depth

translateTriadic :
  (depth : Nat) →
  Q.Residue3Pow depth →
  Q.Residue3Pow depth
translateTriadic depth x =
  Arithmetic.addResidue (oneResidue depth) x

reduceOne :
  (depth : Nat) →
  Q.reduce (oneResidue (suc depth)) ≡ oneResidue depth
reduceOne zero = refl
reduceOne (suc depth) = refl

reduceTranslate :
  (depth : Nat) →
  (x : Q.Residue3Pow (suc depth)) →
  Q.reduce (translateTriadic (suc depth) x)
  ≡
  translateTriadic depth (Q.reduce x)
reduceTranslate depth x =
  trans
    (Arithmetic.reduce-addResidue
      (oneResidue (suc depth)) x)
    (cong
      (λ one → Arithmetic.addResidue one (Q.reduce x))
      (reduceOne depth))

level3CuspFibre : Set
level3CuspFibre = Q.Residue3Pow Q.one

level9CuspFibre : Set
level9CuspFibre = Q.Residue3Pow Q.two

level27CuspFibre : Set
level27CuspFibre = Q.Residue3Pow Q.three

level9To3CoveringProjection :
  level9CuspFibre → level3CuspFibre
level9To3CoveringProjection = Q.reduce

level27To9CoveringProjection :
  level27CuspFibre → level9CuspFibre
level27To9CoveringProjection = Q.reduce

level9To3TranslationEquivariant :
  (x : level9CuspFibre) →
  level9To3CoveringProjection (translateTriadic Q.two x)
  ≡
  translateTriadic Q.one (level9To3CoveringProjection x)
level9To3TranslationEquivariant =
  reduceTranslate Q.one

level27To9TranslationEquivariant :
  (x : level27CuspFibre) →
  level27To9CoveringProjection (translateTriadic Q.three x)
  ≡
  translateTriadic Q.two (level27To9CoveringProjection x)
level27To9TranslationEquivariant =
  reduceTranslate Q.two

------------------------------------------------------------------------
-- 3. Existing C3 observer == level-3 cusp fibre as a finite carrier.
------------------------------------------------------------------------

kernelTritToTrit : Kernel.KernelTrit → Trit
kernelTritToTrit Kernel.negativeTrit = neg
kernelTritToTrit Kernel.zeroTrit = zer
kernelTritToTrit Kernel.positiveTrit = pos

tritToKernelTrit : Trit → Kernel.KernelTrit
tritToKernelTrit neg = Kernel.negativeTrit
tritToKernelTrit zer = Kernel.zeroTrit
tritToKernelTrit pos = Kernel.positiveTrit

kernelRoundTrip :
  (x : Kernel.KernelTrit) →
  tritToKernelTrit (kernelTritToTrit x) ≡ x
kernelRoundTrip Kernel.negativeTrit = refl
kernelRoundTrip Kernel.zeroTrit = refl
kernelRoundTrip Kernel.positiveTrit = refl

tritRoundTrip :
  (x : Trit) →
  kernelTritToTrit (tritToKernelTrit x) ≡ x
tritRoundTrip neg = refl
tritRoundTrip zer = refl
tritRoundTrip pos = refl

observer3ToLevel3 :
  Kernel.KernelTrit → level3CuspFibre
observer3ToLevel3 x = kernelTritToTrit x ∷ []

level3ToObserver3 :
  level3CuspFibre → Kernel.KernelTrit
level3ToObserver3 (x ∷ []) = tritToKernelTrit x

observer3LevelRoundTrip :
  (x : Kernel.KernelTrit) →
  level3ToObserver3 (observer3ToLevel3 x) ≡ x
observer3LevelRoundTrip = kernelRoundTrip

level3ObserverRoundTrip :
  (x : level3CuspFibre) →
  observer3ToLevel3 (level3ToObserver3 x) ≡ x
level3ObserverRoundTrip (neg ∷ []) = refl
level3ObserverRoundTrip (zer ∷ []) = refl
level3ObserverRoundTrip (pos ∷ []) = refl

------------------------------------------------------------------------
-- 4. Existing NineSheet == level-9 cusp fibre as a finite carrier.
--
-- Important: NineSheet was originally a product carrier.  The bijection below
-- does not assert that its old coordinatewise semantics was already cyclic.
-- Instead it transports the canonical Z/9Z cusp action onto that same set.
------------------------------------------------------------------------

observer9ToLevel9 :
  Kernel.NineSheet → level9CuspFibre
observer9ToLevel9 (a , b) =
  kernelTritToTrit a ∷ kernelTritToTrit b ∷ []

level9ToObserver9 :
  level9CuspFibre → Kernel.NineSheet
level9ToObserver9 (a ∷ b ∷ []) =
  tritToKernelTrit a , tritToKernelTrit b

observer9LevelRoundTrip :
  (x : Kernel.NineSheet) →
  level9ToObserver9 (observer9ToLevel9 x) ≡ x
observer9LevelRoundTrip (Kernel.negativeTrit , Kernel.negativeTrit) = refl
observer9LevelRoundTrip (Kernel.negativeTrit , Kernel.zeroTrit) = refl
observer9LevelRoundTrip (Kernel.negativeTrit , Kernel.positiveTrit) = refl
observer9LevelRoundTrip (Kernel.zeroTrit , Kernel.negativeTrit) = refl
observer9LevelRoundTrip (Kernel.zeroTrit , Kernel.zeroTrit) = refl
observer9LevelRoundTrip (Kernel.zeroTrit , Kernel.positiveTrit) = refl
observer9LevelRoundTrip (Kernel.positiveTrit , Kernel.negativeTrit) = refl
observer9LevelRoundTrip (Kernel.positiveTrit , Kernel.zeroTrit) = refl
observer9LevelRoundTrip (Kernel.positiveTrit , Kernel.positiveTrit) = refl

level9ObserverRoundTrip :
  (x : level9CuspFibre) →
  observer9ToLevel9 (level9ToObserver9 x) ≡ x
level9ObserverRoundTrip (neg ∷ neg ∷ []) = refl
level9ObserverRoundTrip (neg ∷ zer ∷ []) = refl
level9ObserverRoundTrip (neg ∷ pos ∷ []) = refl
level9ObserverRoundTrip (zer ∷ neg ∷ []) = refl
level9ObserverRoundTrip (zer ∷ zer ∷ []) = refl
level9ObserverRoundTrip (zer ∷ pos ∷ []) = refl
level9ObserverRoundTrip (pos ∷ neg ∷ []) = refl
level9ObserverRoundTrip (pos ∷ zer ∷ []) = refl
level9ObserverRoundTrip (pos ∷ pos ∷ []) = refl

translateObserver9 :
  Kernel.NineSheet → Kernel.NineSheet
translateObserver9 x =
  level9ToObserver9
    (translateTriadic Q.two (observer9ToLevel9 x))

------------------------------------------------------------------------
-- 5. Existing ternary hypervoxel == level-27 cusp fibre as a finite carrier.
--
-- Again this is a carrier bijection plus an INDUCED cyclic cusp action.
-- It does not identify the hypervoxel's coordinatewise C3^3 group with C27.
------------------------------------------------------------------------

sspToTrit : SSP.SSPTrit → Trit
sspToTrit SSP.sspNegOne = neg
sspToTrit SSP.sspZero = zer
sspToTrit SSP.sspPosOne = pos

tritToSSP : Trit → SSP.SSPTrit
tritToSSP neg = SSP.sspNegOne
tritToSSP zer = SSP.sspZero
tritToSSP pos = SSP.sspPosOne

sspRoundTrip :
  (x : SSP.SSPTrit) →
  tritToSSP (sspToTrit x) ≡ x
sspRoundTrip SSP.sspNegOne = refl
sspRoundTrip SSP.sspZero = refl
sspRoundTrip SSP.sspPosOne = refl

observer27ToLevel27 :
  Fabric.Ternary27Point → level27CuspFibre
observer27ToLevel27 p =
  sspToTrit (Fabric.x p)
    ∷ sspToTrit (Fabric.y p)
    ∷ sspToTrit (Fabric.z p)
    ∷ []

level27ToObserver27 :
  level27CuspFibre → Fabric.Ternary27Point
level27ToObserver27 (x ∷ y ∷ z ∷ []) =
  Fabric.ternary27Point
    (tritToSSP x)
    (tritToSSP y)
    (tritToSSP z)

observer27LevelRoundTrip :
  (p : Fabric.Ternary27Point) →
  level27ToObserver27 (observer27ToLevel27 p) ≡ p
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspNegOne SSP.sspNegOne SSP.sspNegOne) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspNegOne SSP.sspNegOne SSP.sspZero) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspNegOne SSP.sspNegOne SSP.sspPosOne) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspNegOne SSP.sspZero SSP.sspNegOne) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspNegOne SSP.sspZero SSP.sspZero) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspNegOne SSP.sspZero SSP.sspPosOne) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspNegOne SSP.sspPosOne SSP.sspNegOne) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspNegOne SSP.sspPosOne SSP.sspZero) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspNegOne SSP.sspPosOne SSP.sspPosOne) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspZero SSP.sspNegOne SSP.sspNegOne) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspZero SSP.sspNegOne SSP.sspZero) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspZero SSP.sspNegOne SSP.sspPosOne) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspZero SSP.sspZero SSP.sspNegOne) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspZero SSP.sspZero SSP.sspZero) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspZero SSP.sspZero SSP.sspPosOne) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspZero SSP.sspPosOne SSP.sspNegOne) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspZero SSP.sspPosOne SSP.sspZero) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspZero SSP.sspPosOne SSP.sspPosOne) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspPosOne SSP.sspNegOne SSP.sspNegOne) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspPosOne SSP.sspNegOne SSP.sspZero) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspPosOne SSP.sspNegOne SSP.sspPosOne) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspPosOne SSP.sspZero SSP.sspNegOne) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspPosOne SSP.sspZero SSP.sspZero) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspPosOne SSP.sspZero SSP.sspPosOne) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspPosOne SSP.sspPosOne SSP.sspNegOne) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspPosOne SSP.sspPosOne SSP.sspZero) = refl
observer27LevelRoundTrip (Fabric.ternary27Point SSP.sspPosOne SSP.sspPosOne SSP.sspPosOne) = refl

level27ObserverRoundTrip :
  (x : level27CuspFibre) →
  observer27ToLevel27 (level27ToObserver27 x) ≡ x
level27ObserverRoundTrip (neg ∷ neg ∷ neg ∷ []) = refl
level27ObserverRoundTrip (neg ∷ neg ∷ zer ∷ []) = refl
level27ObserverRoundTrip (neg ∷ neg ∷ pos ∷ []) = refl
level27ObserverRoundTrip (neg ∷ zer ∷ neg ∷ []) = refl
level27ObserverRoundTrip (neg ∷ zer ∷ zer ∷ []) = refl
level27ObserverRoundTrip (neg ∷ zer ∷ pos ∷ []) = refl
level27ObserverRoundTrip (neg ∷ pos ∷ neg ∷ []) = refl
level27ObserverRoundTrip (neg ∷ pos ∷ zer ∷ []) = refl
level27ObserverRoundTrip (neg ∷ pos ∷ pos ∷ []) = refl
level27ObserverRoundTrip (zer ∷ neg ∷ neg ∷ []) = refl
level27ObserverRoundTrip (zer ∷ neg ∷ zer ∷ []) = refl
level27ObserverRoundTrip (zer ∷ neg ∷ pos ∷ []) = refl
level27ObserverRoundTrip (zer ∷ zer ∷ neg ∷ []) = refl
level27ObserverRoundTrip (zer ∷ zer ∷ zer ∷ []) = refl
level27ObserverRoundTrip (zer ∷ zer ∷ pos ∷ []) = refl
level27ObserverRoundTrip (zer ∷ pos ∷ neg ∷ []) = refl
level27ObserverRoundTrip (zer ∷ pos ∷ zer ∷ []) = refl
level27ObserverRoundTrip (zer ∷ pos ∷ pos ∷ []) = refl
level27ObserverRoundTrip (pos ∷ neg ∷ neg ∷ []) = refl
level27ObserverRoundTrip (pos ∷ neg ∷ zer ∷ []) = refl
level27ObserverRoundTrip (pos ∷ neg ∷ pos ∷ []) = refl
level27ObserverRoundTrip (pos ∷ zer ∷ neg ∷ []) = refl
level27ObserverRoundTrip (pos ∷ zer ∷ zer ∷ []) = refl
level27ObserverRoundTrip (pos ∷ zer ∷ pos ∷ []) = refl
level27ObserverRoundTrip (pos ∷ pos ∷ neg ∷ []) = refl
level27ObserverRoundTrip (pos ∷ pos ∷ zer ∷ []) = refl
level27ObserverRoundTrip (pos ∷ pos ∷ pos ∷ []) = refl

translateObserver27 :
  Fabric.Ternary27Point → Fabric.Ternary27Point
translateObserver27 p =
  level27ToObserver27
    (translateTriadic Q.three (observer27ToLevel27 p))

------------------------------------------------------------------------
-- 6. Level 6 cusp fibre on the existing HexTruth carrier.
------------------------------------------------------------------------

translate6 : Base.HexTruth → Base.HexTruth
translate6 Base.hex-0 = Base.hex-1
translate6 Base.hex-1 = Base.hex-2
translate6 Base.hex-2 = Base.hex-3
translate6 Base.hex-3 = Base.hex-4
translate6 Base.hex-4 = Base.hex-5
translate6 Base.hex-5 = Base.hex-0

reflect6 : Base.HexTruth → Base.HexTruth
reflect6 Base.hex-0 = Base.hex-0
reflect6 Base.hex-1 = Base.hex-5
reflect6 Base.hex-2 = Base.hex-4
reflect6 Base.hex-3 = Base.hex-3
reflect6 Base.hex-4 = Base.hex-2
reflect6 Base.hex-5 = Base.hex-1

translate6SixTimes :
  (x : Base.HexTruth) →
  translate6
    (translate6
      (translate6
        (translate6
          (translate6
            (translate6 x)))))
  ≡ x
translate6SixTimes Base.hex-0 = refl
translate6SixTimes Base.hex-1 = refl
translate6SixTimes Base.hex-2 = refl
translate6SixTimes Base.hex-3 = refl
translate6SixTimes Base.hex-4 = refl
translate6SixTimes Base.hex-5 = refl

reflect6Involutive :
  (x : Base.HexTruth) →
  reflect6 (reflect6 x) ≡ x
reflect6Involutive Base.hex-0 = refl
reflect6Involutive Base.hex-1 = refl
reflect6Involutive Base.hex-2 = refl
reflect6Involutive Base.hex-3 = refl
reflect6Involutive Base.hex-4 = refl
reflect6Involutive Base.hex-5 = refl

------------------------------------------------------------------------
-- 7. What it means for the actual j-phase quantisers to be modular-level
--    observers rather than merely equal-sector partitions.
------------------------------------------------------------------------

record J369ModularCuspObserverStructure
    (R : Render.JPhaseRenderingAlgebra) : Set₁ where
  constructor j369-modular-cusp-observer-structure
  field
    translatePhase3 : Render.Phase R → Render.Phase R
    translatePhase6 : Render.Phase R → Render.Phase R
    translatePhase9 : Render.Phase R → Render.Phase R
    translatePhase27 : Render.Phase R → Render.Phase R

    phase3IntertwinesCuspTranslation :
      (phase : Render.Phase R) →
      observer3ToLevel3
        (Render.phase3 R (translatePhase3 phase))
      ≡
      translateTriadic Q.one
        (observer3ToLevel3 (Render.phase3 R phase))

    phase6IntertwinesCuspTranslation :
      (phase : Render.Phase R) →
      Render.phase6 R (translatePhase6 phase)
      ≡
      translate6 (Render.phase6 R phase)

    phase9IntertwinesCuspTranslation :
      (phase : Render.Phase R) →
      observer9ToLevel9
        (Render.phase9 R (translatePhase9 phase))
      ≡
      translateTriadic Q.two
        (observer9ToLevel9 (Render.phase9 R phase))

    phase27IntertwinesCuspTranslation :
      (phase : Render.Phase R) →
      observer27ToLevel27
        (Render.phase27 R (translatePhase27 phase))
      ≡
      translateTriadic Q.three
        (observer27ToLevel27 (Render.phase27 R phase))

open J369ModularCuspObserverStructure public

------------------------------------------------------------------------
-- 8. Covering compatibility of the observer tower.
--
-- These equations are the finite shadow of the level-covering maps
--
--   X(27) -> X(9) -> X(3)
--
-- restricted to the canonical cusp-translation fibres.
------------------------------------------------------------------------

observer27ToObserver9ViaLevel :
  Fabric.Ternary27Point → Kernel.NineSheet
observer27ToObserver9ViaLevel p =
  level9ToObserver9
    (level27To9CoveringProjection (observer27ToLevel27 p))

observer9ToObserver3ViaLevel :
  Kernel.NineSheet → Kernel.KernelTrit
observer9ToObserver3ViaLevel p =
  level3ToObserver3
    (level9To3CoveringProjection (observer9ToLevel9 p))

observer27To9TranslationCommutes :
  (p : Fabric.Ternary27Point) →
  observer27ToObserver9ViaLevel (translateObserver27 p)
  ≡
  translateObserver9 (observer27ToObserver9ViaLevel p)
observer27To9TranslationCommutes p =
  trans
    (cong level9ToObserver9
      (cong level27To9CoveringProjection
        (level27ObserverRoundTrip
          (translateTriadic Q.three (observer27ToLevel27 p)))))
    (trans
      (cong level9ToObserver9
        (level27To9TranslationEquivariant (observer27ToLevel27 p)))
      (cong level9ToObserver9
        (cong (translateTriadic Q.two)
          (sym
            (level9ObserverRoundTrip
              (level27To9CoveringProjection
                (observer27ToLevel27 p)))))))

------------------------------------------------------------------------
-- 9. Boundary.
------------------------------------------------------------------------

record J369ModularLevelBoundary : Set where
  constructor j369-modular-level-boundary
  field
    literalTMatrixOwned : Bool
    tPower3PrincipalWitnessOwned : Bool
    tPower6PrincipalWitnessOwned : Bool
    tPower9PrincipalWitnessOwned : Bool
    tPower27PrincipalWitnessOwned : Bool

    c3ObserverCarrierBijectionToLevel3CuspFibre : Bool
    c9ObserverCarrierBijectionToLevel9CuspFibre : Bool
    c27ObserverCarrierBijectionToLevel27CuspFibre : Bool
    c6CyclicCuspActionOwned : Bool

    level27To9To3CoveringMapsTranslationEquivariant : Bool
    fullLevelNDeckGroupClaimedCyclic : Bool
    hypervoxelC3CubedClaimedEqualToCyclicC27AsGroup : Bool
    rendererCuspTranslationIntertwinerInstantiated : Bool
    analyticModularCurveCoverConstructed : Bool

    nextResidual : String

open J369ModularLevelBoundary public

canonicalJ369ModularLevelBoundary : J369ModularLevelBoundary
canonicalJ369ModularLevelBoundary =
  j369-modular-level-boundary
    true true true true true
    true true true true
    true false false false false
    "instantiate continuous phase translation by 1/N turn from the concrete argument carrier and prove phase3/6/9/27 intertwine it with the canonical cusp-translation actions; separately construct the analytic quotient H/Gamma(N) only if a consumer needs the full modular curve rather than its cyclic cusp fibre"
