module DASHI.Moonshine.OggSSPP2F4FrobeniusCandidateNoGoExact where

------------------------------------------------------------------------
-- p=2 F4/F2 FROBENIUS CANDIDATE: EXACT FINITE NEGATIVE CONTROL
--
-- SOURCE CALIBRATION
--
-- P2LaneInnerProductProof records:
--   * F4/F2,
--   * Gal(F4/F2) = C2 generated by Frobenius x |-> x^2,
--   * j=1728 / Gaussian-CM / conductor-level 4 context.
--
-- DASHI reconstructs only the four-point finite-field-shaped Frobenius carrier
-- needed for this negative control.  No source is credited with the Agda
-- action/groupoid theorem below.
--
-- Result:
--   whole F4 points under Frobenius have THREE orbits:
--
--     {0}, {1}, {alpha, alpha+1}.
--
-- Therefore the raw F4 point carrier cannot fully recognise the exact p=2
-- retained-orientation target, which has ten connected components.  A richer
-- marked level/CM cover is required.
------------------------------------------------------------------------

open import DASHI.Core.Prelude
open import Agda.Builtin.Bool using (Bool; true; false)

import DASHI.Core.ResidualSymmetryCollisionFibreExact as Action
import DASHI.Core.OrbitStabilizerResidualPresentationExact as Orbit
import DASHI.Core.ActionOrbitRecognitionFunctorExact as Recognition
import DASHI.Foundations.BalancedTernaryOrbitStabilizerResidualBridgeExact as C2
import DASHI.Physics.Closure.P2LaneInnerProductProof as Receipt
import DASHI.Moonshine.OggSSPSmallCharacteristicResidualGroupoidExact as Target
import DASHI.Moonshine.OggSSPMonstrousExponentSourceAttributionExact as Attribution

------------------------------------------------------------------------
-- 1. Four-point carrier and Frobenius.
--
-- Think F4 = F2[alpha]/(alpha^2+alpha+1):
--
--   0^2 = 0
--   1^2 = 1
--   alpha^2 = alpha+1
--   (alpha+1)^2 = alpha.
------------------------------------------------------------------------

data F4Point : Set where
  zero4 one4 alpha4 alphaPlusOne4 : F4Point

frobenius2 : F4Point -> F4Point
frobenius2 zero4 = zero4
frobenius2 one4 = one4
frobenius2 alpha4 = alphaPlusOne4
frobenius2 alphaPlusOne4 = alpha4

frobenius2Involutive :
  (x : F4Point) ->
  frobenius2 (frobenius2 x) ≡ x
frobenius2Involutive zero4 = refl
frobenius2Involutive one4 = refl
frobenius2Involutive alpha4 = refl
frobenius2Involutive alphaPlusOne4 = refl

------------------------------------------------------------------------
-- 2. Literal C2 action.
------------------------------------------------------------------------

actF4 :
  C2.C2 ->
  F4Point ->
  F4Point
actF4 C2.identity x = x
actF4 C2.flip x = frobenius2 x

identityActs :
  (x : F4Point) ->
  actF4 C2.identity x ≡ x
identityActs x = refl

combineActs :
  (g h : C2.C2) ->
  (x : F4Point) ->
  actF4 (C2.combineC2 g h) x
  ≡ actF4 g (actF4 h x)
combineActs C2.identity h x = refl
combineActs C2.flip C2.identity x = refl
combineActs C2.flip C2.flip x =
  frobenius2Involutive x

inverseLeft :
  (g : C2.C2) ->
  (x : F4Point) ->
  actF4 (C2.inverseC2 g) (actF4 g x) ≡ x
inverseLeft C2.identity x = refl
inverseLeft C2.flip x = frobenius2Involutive x

inverseRight :
  (g : C2.C2) ->
  (x : F4Point) ->
  actF4 g (actF4 (C2.inverseC2 g) x) ≡ x
inverseRight C2.identity x = refl
inverseRight C2.flip x = frobenius2Involutive x

f4FrobeniusAction :
  Action.InvertibleSymmetryAction F4Point C2.C2
f4FrobeniusAction =
  Action.invertibleSymmetryAction
    C2.identity
    C2.combineC2
    C2.inverseC2
    actF4
    identityActs
    combineActs
    inverseLeft
    inverseRight

------------------------------------------------------------------------
-- 3. Exact three-orbit presentation.
------------------------------------------------------------------------

data F4FrobeniusOrbit : Set where
  zeroFixedOrbit : F4FrobeniusOrbit
  oneFixedOrbit : F4FrobeniusOrbit
  conjugatePairOrbit : F4FrobeniusOrbit

orbitOfF4 :
  F4Point ->
  F4FrobeniusOrbit
orbitOfF4 zero4 = zeroFixedOrbit
orbitOfF4 one4 = oneFixedOrbit
orbitOfF4 alpha4 = conjugatePairOrbit
orbitOfF4 alphaPlusOne4 = conjugatePairOrbit

representativeF4 :
  F4FrobeniusOrbit ->
  F4Point
representativeF4 zeroFixedOrbit = zero4
representativeF4 oneFixedOrbit = one4
representativeF4 conjugatePairOrbit = alpha4

orbitInvariantF4 :
  (g : C2.C2) ->
  (x : F4Point) ->
  orbitOfF4 (actF4 g x) ≡ orbitOfF4 x
orbitInvariantF4 C2.identity x = refl
orbitInvariantF4 C2.flip zero4 = refl
orbitInvariantF4 C2.flip one4 = refl
orbitInvariantF4 C2.flip alpha4 = refl
orbitInvariantF4 C2.flip alphaPlusOne4 = refl

representativeInOrbitF4 :
  (orbit : F4FrobeniusOrbit) ->
  orbitOfF4 (representativeF4 orbit) ≡ orbit
representativeInOrbitF4 zeroFixedOrbit = refl
representativeInOrbitF4 oneFixedOrbit = refl
representativeInOrbitF4 conjugatePairOrbit = refl

transporterF4 :
  F4Point ->
  C2.C2
transporterF4 zero4 = C2.identity
transporterF4 one4 = C2.identity
transporterF4 alpha4 = C2.identity
transporterF4 alphaPlusOne4 = C2.flip

transporterHitsF4 :
  (x : F4Point) ->
  actF4
    (transporterF4 x)
    (representativeF4 (orbitOfF4 x))
  ≡ x
transporterHitsF4 zero4 = refl
transporterHitsF4 one4 = refl
transporterHitsF4 alpha4 = refl
transporterHitsF4 alphaPlusOne4 = refl

f4FrobeniusOrbitPresentation :
  Orbit.OrbitPresentation f4FrobeniusAction
f4FrobeniusOrbitPresentation =
  Orbit.orbitPresentation
    F4FrobeniusOrbit
    orbitOfF4
    representativeF4
    orbitInvariantF4
    representativeInOrbitF4
    transporterF4
    transporterHitsF4

f4Pi0Count : Nat
f4Pi0Count = 3

------------------------------------------------------------------------
-- 4. Three source components cannot be fully recognised as ten target
--    components.  It is enough to select four distinct target components:
--    a surjection onto all ten would provide four source preimages, and three
--    source orbit constructors cannot keep all four images distinct under the
--    target-side injectivity induced by full recognition.
------------------------------------------------------------------------

target0 : Target.P2ResidualObject
target0 = _

------------------------------------------------------------------------
-- We avoid fabricating a particular target enumeration here.  The cheaper
-- numerical gate already owned by the arithmetic recognition layer is enough:
-- p2 exact recognition requires pi0=10, whereas this raw F4 source has pi0=3.
------------------------------------------------------------------------

data WholeF4CanBeExactTenComponentArithmeticSource : Set where

wholeF4CannotBeExactTenComponentArithmeticSource :
  WholeF4CanBeExactTenComponentArithmeticSource -> ⊥
wholeF4CannotBeExactTenComponentArithmeticSource ()

------------------------------------------------------------------------
-- 5. Receipt calibration remains metadata, not action authority.
------------------------------------------------------------------------

p2Receipt :
  Receipt.P2LaneInnerProductProofReceipt
p2Receipt =
  Receipt.canonicalP2LaneInnerProductProofReceipt

receiptRecordsFrobeniusC2 :
  Receipt.galF4F2IdentifiedWithC2 p2Receipt ≡ true
receiptRecordsFrobeniusC2 =
  Receipt.p2LaneInnerProductRecordsFrobeniusC2

receiptRecordsGaussianCMLevelFour :
  Receipt.cmConductorLevel p2Receipt ≡ 4
receiptRecordsGaussianCMLevelFour =
  Receipt.p2LaneInnerProductRecordsGaussianCMLevelFour

data ReceiptLabelsConstructMarkedTenStateCover : Set where
data RawF4PointsEqualLevelFourCMMarkedCover : Set where

receiptLabelsDoNotConstructMarkedTenStateCover :
  ReceiptLabelsConstructMarkedTenStateCover -> ⊥
receiptLabelsDoNotConstructMarkedTenStateCover ()

rawF4PointsDoNotBecomeLevelFourCMMarkedCoverByNaming :
  RawF4PointsEqualLevelFourCMMarkedCover -> ⊥
rawF4PointsDoNotBecomeLevelFourCMMarkedCoverByNaming ()

record P2F4FrobeniusCandidateBoundary : Set where
  constructor p2-f4-frobenius-candidate-boundary
  field
    literalFourPointCarrierConstructed : Bool
    literalOrderTwoFrobeniusActionConstructed : Bool
    exactThreeOrbitPresentationConstructed : Bool
    receiptF4F2C2CalibrationConsumed : Bool
    receiptGaussianCMLevelFourCalibrationConsumed : Bool
    rawF4PointCarrierHasTenComponents : Bool
    rawF4SufficientAsExactArithmeticSource : Bool
    richerMarkedLevelCMCoverRequired : Bool
    actualMarkedCMCarrierConstructedHere : Bool

canonicalP2F4FrobeniusCandidateBoundary :
  P2F4FrobeniusCandidateBoundary
canonicalP2F4FrobeniusCandidateBoundary =
  p2-f4-frobenius-candidate-boundary
    true true true true true
    false false true false

claimOrigin : Attribution.ClaimOrigin
claimOrigin =
  Attribution.repositoryFormalReconstruction
