module DASHI.Moonshine.OggSSP4A2BIntegralRestrictionRefinementExact where

------------------------------------------------------------------------
-- 4A -> 2B INTEGRAL RESTRICTION REFINEMENT
--
-- EXTERNAL SOURCES
--
-- ATLAS of Finite Group Representations:
--   the Monster power map records 4A under the power-up column of 2B.
--   Equivalently, for g in class 4A, g^2 lies in class 2B.
--
-- Carnahan--Urano, "Monstrous Moonshine for Integral Group Rings":
--   for cyclic subgroups generated by a 4A element, the integral Moonshine
--   module is explicitly decomposed into indecomposable integral group-ring
--   modules and the multiplicities are determined.
--
-- DASHI CONTRIBUTION
--
-- Formalize the exact square-subgroup inclusion
--
--     C2 = <g^2>  -->  C4 = <g>
--
-- and the resulting restriction of any invertible C4 action to C2.
--
-- This gives a canonical SOURCE-NATIVE refinement lane for 2B: one may retain
-- the finer 4A/C4 indecomposable label before forgetting to the square-subgroup
-- 2B action.
--
-- ATTRIBUTION FIREWALL
--
-- Neither ATLAS nor Carnahan--Urano identifies the restricted 4A
-- indecomposable labels with the five characteristic-2 inertia sectors.
-- Neither source proves the 3,3,2,1,1 localized DVR-length law.
------------------------------------------------------------------------

open import DASHI.Core.Prelude
open import Agda.Builtin.Bool using (Bool; true; false)

import DASHI.Core.AttributedSourceCore as Source
import DASHI.Core.ResidualSymmetryCollisionFibreExact as Action
import DASHI.Foundations.BalancedTernaryOrbitStabilizerResidualBridgeExact as C2
import DASHI.Moonshine.OggSSPMonstrousExponentSourceAttributionExact as Attribution

------------------------------------------------------------------------
-- 1. Source attribution.
------------------------------------------------------------------------

atlasMonsterPowerMap : Source.AttributedSource
atlasMonsterPowerMap =
  Source.mkNoDOISource
    "ATLAS of Finite Group Representations"
    "Monster group M: conjugacy classes and power map"
    "ATLAS web database"
    ""
    "https://brauer.maths.qmul.ac.uk/Atlas/v3/spor/M/"
    (Source.namedSourceKind "group-theory database")
    "the Monster conjugacy-class power-up table places 4A under 2B, sourcing the class-power statement that the square of a 4A element lies in 2B; does not provide a Moonshine-module sector localization"
    Source.publicAttribution

carnahanUranoIntegralGroupRings : Source.AttributedSource
carnahanUranoIntegralGroupRings =
  Source.mkDOISource
    "Scott Carnahan and Satoru Urano"
    "Monstrous Moonshine for Integral Group Rings"
    "International Mathematics Research Notices 2024(4), 2748-2789"
    "2024"
    "10.1093/imrn/rnad028"
    "https://doi.org/10.1093/imrn/rnad028"
    Source.academicArticleSource
    "proves the integral-group-ring Moonshine conjecture for cyclic subgroups generated by class 4A and explicitly determines multiplicities in the decomposition of the integral Moonshine module into indecomposable integral group-ring modules; does not identify those indecomposables with DASHI inertia sectors"
    Source.publicAttribution

fourATwoBRestrictionSourceAtlas : Source.AttributedSourceAtlas
fourATwoBRestrictionSourceAtlas =
  Source.mkSourceAtlas
    "4A square-to-2B integral restriction refinement"
    "DASHI.Moonshine.OggSSP4A2BIntegralRestrictionRefinementExact"
    (atlasMonsterPowerMap ∷ carnahanUranoIntegralGroupRings ∷ [])
    "ATLAS owns the class-power relation and Carnahan--Urano own the explicit 4A integral decomposition; DASHI owns the restriction/reconstruction interface and any future five-sector recognition"

------------------------------------------------------------------------
-- 2. Concrete cyclic group of order four.
------------------------------------------------------------------------

data C4 : Set where
  c4e :
    C4
  c4g :
    C4
  c4g2 :
    C4
  c4g3 :
    C4

combineC4 : C4 -> C4 -> C4
combineC4 c4e x = x
combineC4 c4g c4e = c4g
combineC4 c4g c4g = c4g2
combineC4 c4g c4g2 = c4g3
combineC4 c4g c4g3 = c4e
combineC4 c4g2 c4e = c4g2
combineC4 c4g2 c4g = c4g3
combineC4 c4g2 c4g2 = c4e
combineC4 c4g2 c4g3 = c4g
combineC4 c4g3 c4e = c4g3
combineC4 c4g3 c4g = c4e
combineC4 c4g3 c4g2 = c4g
combineC4 c4g3 c4g3 = c4g2

inverseC4 : C4 -> C4
inverseC4 c4e = c4e
inverseC4 c4g = c4g3
inverseC4 c4g2 = c4g2
inverseC4 c4g3 = c4g

------------------------------------------------------------------------
-- 3. Exact square-subgroup inclusion C2 -> C4.
------------------------------------------------------------------------

squareSubgroupEmbedding :
  C2.C2 ->
  C4
squareSubgroupEmbedding C2.identity = c4e
squareSubgroupEmbedding C2.flip = c4g2

squareSubgroupIdentity :
  squareSubgroupEmbedding C2.identity ≡ c4e
squareSubgroupIdentity = refl

squareSubgroupCombine :
  (a b : C2.C2) ->
  squareSubgroupEmbedding (C2.combineC2 a b)
  ≡
  combineC4
    (squareSubgroupEmbedding a)
    (squareSubgroupEmbedding b)
squareSubgroupCombine C2.identity C2.identity = refl
squareSubgroupCombine C2.identity C2.flip = refl
squareSubgroupCombine C2.flip C2.identity = refl
squareSubgroupCombine C2.flip C2.flip = refl

squareSubgroupInverse :
  (a : C2.C2) ->
  squareSubgroupEmbedding (C2.inverseC2 a)
  ≡
  inverseC4 (squareSubgroupEmbedding a)
squareSubgroupInverse C2.identity = refl
squareSubgroupInverse C2.flip = refl

squareGeneratorHasOrderTwo :
  combineC4 c4g2 c4g2 ≡ c4e
squareGeneratorHasOrderTwo = refl

fourAGeneratorSquaresToSquareSubgroupGenerator :
  combineC4 c4g c4g ≡ squareSubgroupEmbedding C2.flip
fourAGeneratorSquaresToSquareSubgroupGenerator = refl

------------------------------------------------------------------------
-- 4. Restriction of any invertible C4 action to the square C2 subgroup.
------------------------------------------------------------------------

restrictC4ActionToSquareC2 :
  {State : Set} ->
  Action.InvertibleSymmetryAction State C4 ->
  Action.InvertibleSymmetryAction State C2.C2
restrictC4ActionToSquareC2 action =
  Action.invertibleSymmetryAction
    C2.identity
    C2.combineC2
    C2.inverseC2
    restrictedAct
    restrictedIdentity
    restrictedCombine
    restrictedInverseLeft
    restrictedInverseRight
  where
    restrictedAct :
      C2.C2 ->
      State ->
      State
    restrictedAct symmetry state =
      Action.act action
        (squareSubgroupEmbedding symmetry)
        state

    restrictedIdentity :
      (state : State) ->
      restrictedAct C2.identity state ≡ state
    restrictedIdentity state =
      Action.identityActs action state

    restrictedCombine :
      (a b : C2.C2) ->
      (state : State) ->
      restrictedAct (C2.combineC2 a b) state
      ≡
      restrictedAct a (restrictedAct b state)
    restrictedCombine a b state =
      trans
        (cong
          (λ symmetry -> Action.act action symmetry state)
          (squareSubgroupCombine a b))
        (Action.combineActs action
          (squareSubgroupEmbedding a)
          (squareSubgroupEmbedding b)
          state)

    restrictedInverseLeft :
      (a : C2.C2) ->
      (state : State) ->
      restrictedAct (C2.inverseC2 a)
        (restrictedAct a state)
      ≡ state
    restrictedInverseLeft a state =
      trans
        (cong
          (λ symmetry ->
            Action.act action symmetry
              (Action.act action
                (squareSubgroupEmbedding a)
                state))
          (squareSubgroupInverse a))
        (Action.inverseLeftActs action
          (squareSubgroupEmbedding a)
          state)

    restrictedInverseRight :
      (a : C2.C2) ->
      (state : State) ->
      restrictedAct a
        (restrictedAct (C2.inverseC2 a) state)
      ≡ state
    restrictedInverseRight a state =
      trans
        (cong
          (λ symmetry ->
            Action.act action
              (squareSubgroupEmbedding a)
              (Action.act action symmetry state))
          (squareSubgroupInverse a))
        (Action.inverseRightActs action
          (squareSubgroupEmbedding a)
          state)

------------------------------------------------------------------------
-- 5. Typed external-source receipt.
------------------------------------------------------------------------

record FourAIntegralDecompositionReceipt : Set where
  constructor four-a-integral-decomposition-receipt
  field
    fourACyclicSubgroupUsed :
      Bool
    fourACyclicSubgroupUsedIsTrue :
      fourACyclicSubgroupUsed ≡ true

    fourASquareLiesInTwoB :
      Bool
    fourASquareLiesInTwoBIsTrue :
      fourASquareLiesInTwoB ≡ true

    integralMoonshineModuleDecomposedIntoIndecomposables :
      Bool
    integralMoonshineModuleDecomposedIntoIndecomposablesIsTrue :
      integralMoonshineModuleDecomposedIntoIndecomposables ≡ true

    indecomposableMultiplicitiesExplicitlyDetermined :
      Bool
    indecomposableMultiplicitiesExplicitlyDeterminedIsTrue :
      indecomposableMultiplicitiesExplicitlyDetermined ≡ true

    sourceIdentifiesRestrictedIndecomposableWithFiveInertiaSectors :
      Bool

    sourceProvesRestrictedSectorDVRLengthsThreeThreeTwoOneOne :
      Bool

canonicalFourAIntegralDecompositionReceipt :
  FourAIntegralDecompositionReceipt
canonicalFourAIntegralDecompositionReceipt =
  four-a-integral-decomposition-receipt
    true refl
    true refl
    true refl
    true refl
    false
    false

------------------------------------------------------------------------
-- 6. The actual new recognition obligation.
--
-- This is intentionally only an interface.  A future inhabitant must exhibit
-- source-native 4A indecomposable data and its restriction to the same 2B
-- source piece before any geometric-sector identification is allowed.
------------------------------------------------------------------------

record FourARestrictedTwoBRefinementAuthority : Set₁ where
  field
    FourAIndecomposableLabel :
      Set

    TwoBSourcePiece :
      Set

    fourALabelOfSourcePiece :
      TwoBSourcePiece ->
      FourAIndecomposableLabel

    labelComesFromCarnahanUranoFourADecomposition :
      TwoBSourcePiece ->
      Bool

    labelComesFromCarnahanUranoFourADecompositionIsTrue :
      (piece : TwoBSourcePiece) ->
      labelComesFromCarnahanUranoFourADecomposition piece ≡ true

    restrictionIsAlongSquareSubgroup :
      Bool
    restrictionIsAlongSquareSubgroupIsTrue :
      restrictionIsAlongSquareSubgroup ≡ true

    restrictedSquareActsAsTwoB :
      Bool
    restrictedSquareActsAsTwoBIsTrue :
      restrictedSquareActsAsTwoB ≡ true

    refinementDefinedWithoutMonsterResidual :
      Bool
    refinementDefinedWithoutMonsterResidualIsTrue :
      refinementDefinedWithoutMonsterResidual ≡ true

    refinementDefinedWithoutBase369Labels :
      Bool
    refinementDefinedWithoutBase369LabelsIsTrue :
      refinementDefinedWithoutBase369Labels ≡ true

open FourARestrictedTwoBRefinementAuthority public

------------------------------------------------------------------------
-- 7. No-promotion firewalls.
------------------------------------------------------------------------

data FourASquareRelationCreatesFiveSectorMap : Set where
data ExplicitFourADecompositionCreatesInertiaRecognition : Set where
data RestrictionFunctorCreatesThreeThreeTwoOneOneLengths : Set where
data T4AHauptmodulCreatesMonsterResidualCorrection : Set where

fourASquareRelationDoesNotCreateFiveSectorMap :
  FourASquareRelationCreatesFiveSectorMap -> ⊥
fourASquareRelationDoesNotCreateFiveSectorMap ()

explicitFourADecompositionDoesNotCreateInertiaRecognition :
  ExplicitFourADecompositionCreatesInertiaRecognition -> ⊥
explicitFourADecompositionDoesNotCreateInertiaRecognition ()

restrictionFunctorDoesNotCreateSectorLengths :
  RestrictionFunctorCreatesThreeThreeTwoOneOneLengths -> ⊥
restrictionFunctorDoesNotCreateSectorLengths ()

t4AHauptmodulDoesNotCreateMonsterResidualCorrection :
  T4AHauptmodulCreatesMonsterResidualCorrection -> ⊥
t4AHauptmodulDoesNotCreateMonsterResidualCorrection ()

data FourARestrictedTwoBRefinementAuthorityInhabited : Set where

fourARestrictedTwoBRefinementStillOpen :
  FourARestrictedTwoBRefinementAuthorityInhabited -> ⊥
fourARestrictedTwoBRefinementStillOpen ()

claimOrigin : Attribution.ClaimOrigin
claimOrigin =
  Attribution.repositoryFormalReconstruction

record FourA2BRestrictionRefinementBoundary : Set where
  constructor four-a2b-restriction-refinement-boundary
  field
    atlasFourASquareToTwoBSourced : Bool
    carnahanUranoFourADecompositionSourced : Bool
    explicitFourAIndecomposableMultiplicitiesSourced : Bool
    exactC2ToC4SquareSubgroupEmbeddingProved : Bool
    genericC4ActionRestrictionToC2Proved : Bool
    canonicalSourceNativeP2RefinementLaneExists : Bool
    restrictedIndecomposableToFiveSectorRecognitionPaid : Bool
    threeThreeTwoOneOneLengthLawPaid : Bool
    monsterResidualUsedToDefineRefinement : Bool
    base369UsedToDefineRefinement : Bool
    attributionFirewallPreserved : Bool

canonicalFourA2BRestrictionRefinementBoundary :
  FourA2BRestrictionRefinementBoundary
canonicalFourA2BRestrictionRefinementBoundary =
  four-a2b-restriction-refinement-boundary
    true true true true true true
    false false false false true
