module DASHI.Moonshine.OggSSPSmallPrimePadicMoonshineScopeCutsetExact where

------------------------------------------------------------------------
-- SMALL-PRIME p-ADIC / INTEGRAL MOONSHINE SCOPE CUTSET
--
-- SOTA EXTERNAL INPUT
--
-- Chen--Marks--Tyler:
--   many monstrous Hauptmoduln satisfy congruences modulo powers of
--   p in {2,3,5,7,11}; the paper relates p-adic annihilation to Monster power
--   maps and gives p-adic moonshine examples for certain centralizers of
--   commuting pA-type pairs.
--
-- Carnahan--Urano:
--   formulate a substantially broader integral-group-ring moonshine
--   conjecture, but in that paper prove the new conjecture for cyclic
--   subgroups generated by class 4A.
--
-- CONSEQUENCE
--
-- These papers strongly source the ROUTE
--
--   integral/graded Monster representation
--     -> p-adic Hauptmodul / q-expansion information,
--
-- but do not supply a theorem for the particular 2B/3B local-centralizer
-- valuation defects 10 and 2 required here.
------------------------------------------------------------------------

open import DASHI.Core.Prelude
open import Agda.Builtin.Bool using (Bool; true; false)

import DASHI.Core.AttributedSourceCore as Source
import DASHI.Moonshine.OggSSPSmallPrimeMonsterLocalCentralizerValuationExact as Local
import DASHI.Moonshine.OggSSPSmallPrimeGeneralizedMoonshineCentralizerBridgeExact as GM
import DASHI.Moonshine.OggSSPMonstrousExponentSourceAttributionExact as Attribution

chenMarksTyler : Source.AttributedSource
chenMarksTyler =
  Source.mkNoDOISource
    "Ryan C. Chen, Samuel Marks, and Matthew Tyler"
    "p-adic Properties of Hauptmoduln with Applications to Moonshine"
    "SIGMA 15 (2019), arXiv:1809.02913"
    "2019"
    "https://arxiv.org/abs/1809.02913"
    Source.academicArticleSource
    "proves broad p-adic annihilation/congruence results for monstrous Hauptmoduln and relates them to Monster power maps and selected centralizer moonshine modules; does not state the 2B/3B local-centralizer defect valuation used by DASHI"
    Source.publicAttribution

carnahanUrano : Source.AttributedSource
carnahanUrano =
  Source.mkNoDOISource
    "Scott Carnahan and Satoru Urano"
    "Monstrous Moonshine for integral group rings"
    "arXiv:2111.09404"
    "2021"
    "https://arxiv.org/abs/2111.09404"
    Source.academicArticleSource
    "formulates an integral-group-ring Hauptmodul conjecture and proves the new conjecture in the paper for cyclic subgroups generated by class 4A; this is route-level precedent, not a proof for 2B/3B"
    Source.publicAttribution

padicMoonshineScopeAtlas : Source.AttributedSourceAtlas
padicMoonshineScopeAtlas =
  Source.mkSourceAtlas
    "small-prime p-adic/integral moonshine scope atlas"
    "DASHI.Moonshine.OggSSPSmallPrimePadicMoonshineScopeCutsetExact"
    (chenMarksTyler ∷ carnahanUrano ∷ [])
    "external sources own p-adic Hauptmodul and integral moonshine frameworks; class-specific 2B/3B valuation recognition remains an open DASHI theorem"

------------------------------------------------------------------------
-- 1. What is genuinely sourced.
------------------------------------------------------------------------

record PadicMoonshineRouteReceipt : Set where
  constructor padic-moonshine-route-receipt
  field
    monstrousHauptmodulPadicCongruencesSourced : Bool
    monsterPowerMapRelationSourced : Bool
    selectedCentralizerPadicMoonshineSourced : Bool
    integralGroupRingHauptmodulConjectureSourced : Bool
    integralConjectureProofFor4ASourced : Bool

canonicalPadicMoonshineRouteReceipt :
  PadicMoonshineRouteReceipt
canonicalPadicMoonshineRouteReceipt =
  padic-moonshine-route-receipt
    true true true true true

------------------------------------------------------------------------
-- 2. What the current papers do not close.
------------------------------------------------------------------------

data ChenMarksTylerProve2BDefectTen : Set where
data ChenMarksTylerProve3BDefectTwo : Set where
data CarnahanUranoProve2B3BIntegralBridge : Set where
data PadicMoonshineScopeInhabitsTwistedTraceValuation : Set where

chenMarksTylerDoNotSupply2BDefectTen :
  ChenMarksTylerProve2BDefectTen -> ⊥
chenMarksTylerDoNotSupply2BDefectTen ()

chenMarksTylerDoNotSupply3BDefectTwo :
  ChenMarksTylerProve3BDefectTwo -> ⊥
chenMarksTylerDoNotSupply3BDefectTwo ()

carnahanUrano4AProofDoesNotPromoteTo2B3B :
  CarnahanUranoProve2B3BIntegralBridge -> ⊥
carnahanUrano4AProofDoesNotPromoteTo2B3B ()

scopeAloneDoesNotInhabitTwistedTraceValuation :
  PadicMoonshineScopeInhabitsTwistedTraceValuation -> ⊥
scopeAloneDoesNotInhabitTwistedTraceValuation ()

------------------------------------------------------------------------
-- 3. Refined external theorem target.
------------------------------------------------------------------------

record ClassSpecificPadicCentralizerValuationAuthority : Set₁ where
  field
    generalizedMoonshineBridge :
      GM.GeneralizedMoonshineCentralizerModularBridge

    p2LocalPadicValuationProved :
      Bool
    p2LocalPadicValuationProvedIsTrue :
      p2LocalPadicValuationProved ≡ true

    p3LocalPadicValuationProved :
      Bool
    p3LocalPadicValuationProvedIsTrue :
      p3LocalPadicValuationProved ≡ true

    p2ValueIsLocalCentralizerDefect :
      Bool
    p2ValueIsLocalCentralizerDefectIsTrue :
      p2ValueIsLocalCentralizerDefect ≡ true

    p3ValueIsLocalCentralizerDefect :
      Bool
    p3ValueIsLocalCentralizerDefectIsTrue :
      p3ValueIsLocalCentralizerDefect ≡ true

    badLevelPAndPSquaredCompatibilityOwned :
      Bool
    badLevelPAndPSquaredCompatibilityOwnedIsTrue :
      badLevelPAndPSquaredCompatibilityOwned ≡ true

    sourceOrProofIndependentOfMonsterTarget :
      Bool
    sourceOrProofIndependentOfMonsterTargetIsTrue :
      sourceOrProofIndependentOfMonsterTarget ≡ true

open ClassSpecificPadicCentralizerValuationAuthority public

data ClassSpecificPadicCentralizerAuthorityInhabited : Set where

classSpecificPadicAuthorityStillOpen :
  ClassSpecificPadicCentralizerAuthorityInhabited -> ⊥
classSpecificPadicAuthorityStillOpen ()

------------------------------------------------------------------------
-- 4. Live boundary.
------------------------------------------------------------------------

claimOrigin : Attribution.ClaimOrigin
claimOrigin =
  Attribution.openRecognitionConjecture

record SmallPrimePadicMoonshineScopeBoundary : Set where
  constructor small-prime-padic-moonshine-scope-boundary
  field
    padicHauptmodulFrameworkSourced : Bool
    groupStructureRelationSourced : Bool
    generalizedCentralizerMoonshineSourced : Bool
    integralMoonshineRouteSourced : Bool
    currentIntegralProofCovers2B3B : Bool
    currentPadicPaperProvesLocalDefectsTenTwo : Bool
    classSpecificAuthoritySpecified : Bool
    classSpecificAuthorityInhabited : Bool
    attributionFirewallPreserved : Bool

canonicalSmallPrimePadicMoonshineScopeBoundary :
  SmallPrimePadicMoonshineScopeBoundary
canonicalSmallPrimePadicMoonshineScopeBoundary =
  small-prime-padic-moonshine-scope-boundary
    true true true true false false true false true
