module DASHI.Moonshine.P11Level44BadPrimeOperatorSeparationExact where

------------------------------------------------------------------------
-- PRIMARY SOURCES / CONTEXT
--
-- Fred Diamond and Jerry Shurman,
-- "A First Course in Modular Forms", Graduate Texts in Mathematics 228,
-- Springer, 2005. DOI: 10.1007/978-0-387-27226-9.
-- For p not dividing the original level, on the p^2-oldspace generated by
-- f, V_p f, V_{p^2} f one has the standard coefficient identities
--
--   U_p f       = a_p f - p V_p f,
--   U_p V_p f   = f,
--   U_p V_p^2 f = V_p f.
--
-- John Voight,
-- "Quaternion Algebras", Graduate Texts in Mathematics 288, Springer, 2021.
-- DOI: 10.1007/978-3-030-56694-4.
-- Brandt / quaternionic Hecke context.
--
-- DASHI CONTRIBUTION
--
-- Compare the ACTUAL algebraic shape of the two tempting bad-prime operators.
--
-- Classical Gamma_0(4) oldspace, for the level-11 newform a_2=-2:
--
--   U2(x1,x2,x4) = (-2 x1 + x2, -2 x1 + x4, 0).
--
-- The repository's internally discovered positive five-state R2 restricts to
-- the marked Old3 image as
--
--   R2(x1,x2,x4) = (-x2-x4, -x1-x4, -x1-x2).
--
-- These are NOT similar candidates for one same-object operator.  U2 has the
-- explicit nonzero kernel vector (1,2,2), while marked R2 has no nonzero
-- rational/integral kernel (indeed its determinant is -2 and its eigenvalues
-- are -2,1,1).
--
-- Hence the existing positive R2 cannot simply be relabelled the analytic U2
-- to close the local Jacquet--Langlands comparison.  The actual source-native
-- 2-adic comparison must keep these operator roles distinct and construct the
-- correct local test-vector / compact-open transport.
------------------------------------------------------------------------

open import DASHI.Core.Prelude
open import Agda.Builtin.List using ([]; _∷_)
open import Data.Integer using (ℤ; +_; -[1+_])
  renaming (_+_ to _+ℤ_; _*_ to _*ℤ_)
import Data.Integer.Tactic.RingSolver as ℤRing

import DASHI.Moonshine.P11FiveStatePositiveHeckeLiftExact as Fine
import DASHI.Moonshine.P11MarkedX2S3HeckeDecompositionExact as S3
import DASHI.Moonshine.P11MarkedLevel44PermutationIntertwinerExact as Old

------------------------------------------------------------------------
-- Integer linearization of the existing internally-discovered fine R2.
------------------------------------------------------------------------

markedR2Action : S3.Int5 → S3.Int5
markedR2Action v = S3.int5
  (S3.b0c v +ℤ S3.b1c v +ℤ S3.b2c v)
  (S3.b0c v +ℤ S3.b1c v +ℤ S3.b2c v)
  (S3.a0c v +ℤ S3.a1c v +ℤ S3.b0c v)
  (S3.a0c v +ℤ S3.a1c v +ℤ S3.b1c v)
  (S3.a0c v +ℤ S3.a1c v +ℤ S3.b2c v)

markedR2OnOld3 : Old.Old3 → Old.Old3
markedR2OnOld3 (Old.old3 x y z) = Old.old3
  ((-[1+ 0 ]) *ℤ y +ℤ (-[1+ 0 ]) *ℤ z)
  ((-[1+ 0 ]) *ℤ x +ℤ (-[1+ 0 ]) *ℤ z)
  ((-[1+ 0 ]) *ℤ x +ℤ (-[1+ 0 ]) *ℤ y)

markedR2PreservesOld3Realization :
  (v : Old.Old3) →
  markedR2Action (Old.realizeOld3 v)
  ≡ Old.realizeOld3 (markedR2OnOld3 v)
markedR2PreservesOld3Realization (Old.old3 x y z) =
  Old.int5Ext _ _
    (ℤRing.solve (x ∷ y ∷ z ∷ []))
    (ℤRing.solve (x ∷ y ∷ z ∷ []))
    (ℤRing.solve (x ∷ y ∷ z ∷ []))
    (ℤRing.solve (x ∷ y ∷ z ∷ []))
    (ℤRing.solve (x ∷ y ∷ z ∷ []))

------------------------------------------------------------------------
-- Exact marked R2 decomposition on trivial and standard deck sectors.
------------------------------------------------------------------------

oldOrbitSum : Old.Old3
oldOrbitSum = Old.old3 (+ 1) (+ 1) (+ 1)

oldStandard1 : Old.Old3
oldStandard1 = Old.old3 (+ 1) (-[1+ 0 ]) (+ 0)

oldStandard2 : Old.Old3
oldStandard2 = Old.old3 (+ 1) (+ 0) (-[1+ 0 ])

markedR2TrivialEigen :
  markedR2OnOld3 oldOrbitSum
  ≡ Old.scaleOld3 (-[1+ 1 ]) oldOrbitSum
markedR2TrivialEigen = refl

markedR2Standard1Eigen :
  markedR2OnOld3 oldStandard1 ≡ Old.scaleOld3 (+ 1) oldStandard1
markedR2Standard1Eigen = refl

markedR2Standard2Eigen :
  markedR2OnOld3 oldStandard2 ≡ Old.scaleOld3 (+ 1) oldStandard2
markedR2Standard2Eigen = refl

------------------------------------------------------------------------
-- Classical U2 on the d=1,2,4 Gamma_0(4) degeneracy coordinates.
-- The source level-11 eigenvalue is a2=-2.
------------------------------------------------------------------------

analyticU2 : Old.Old3 → Old.Old3
analyticU2 (Old.old3 x1 x2 x4) = Old.old3
  ((-[1+ 1 ]) *ℤ x1 +ℤ x2)
  ((-[1+ 1 ]) *ℤ x1 +ℤ x4)
  (+ 0)

analyticU2KernelVector : Old.Old3
analyticU2KernelVector = Old.old3 (+ 1) (+ 2) (+ 2)

analyticU2HasNonzeroKernel :
  analyticU2 analyticU2KernelVector ≡ Old.old3 (+ 0) (+ 0) (+ 0)
analyticU2HasNonzeroKernel = refl

data Impossible : Set where

analyticKernelVectorNonzero :
  analyticU2KernelVector ≡ Old.old3 (+ 0) (+ 0) (+ 0) → Impossible
analyticKernelVectorNonzero ()

------------------------------------------------------------------------
-- marked R2 has trivial integral kernel.
------------------------------------------------------------------------

zeroOld3 : Old.Old3
zeroOld3 = Old.old3 (+ 0) (+ 0) (+ 0)

markedR2KernelTrivial :
  (v : Old.Old3) → markedR2OnOld3 v ≡ zeroOld3 → v ≡ zeroOld3
markedR2KernelTrivial (Old.old3 x y z) equality =
  old3Ext x y z equality
  where
  old3Ext :
    (x y z : ℤ) →
    markedR2OnOld3 (Old.old3 x y z) ≡ zeroOld3 →
    Old.old3 x y z ≡ zeroOld3
  old3Ext x y z refl = refl

------------------------------------------------------------------------
-- No bijective intertwiner can conjugate analytic U2 to marked R2.
-- We only need injectivity plus preservation of zero.
------------------------------------------------------------------------

record InjectiveZeroPreservingIntertwiner : Set where
  field
    map : Old.Old3 → Old.Old3
    mapsZero : map zeroOld3 ≡ zeroOld3
    injective : {u v : Old.Old3} → map u ≡ map v → u ≡ v
    intertwines :
      (v : Old.Old3) →
      map (analyticU2 v) ≡ markedR2OnOld3 (map v)
open InjectiveZeroPreservingIntertwiner public

analyticU2CannotBeConjugatedToMarkedR2 :
  InjectiveZeroPreservingIntertwiner → Impossible
analyticU2CannotBeConjugatedToMarkedR2 C =
  analyticKernelVectorNonzero
    (injective C
      (trans
        (sym (mapsZero C))
        (trans
          (cong (map C) (sym analyticU2HasNonzeroKernel))
          (trans
            (intertwines C analyticU2KernelVector)
            (cong markedR2OnOld3
              (markedR2KernelTrivial
                (map C analyticU2KernelVector)
                (trans
                  (sym (intertwines C analyticU2KernelVector))
                  (trans
                    (cong (map C) analyticU2HasNonzeroKernel)
                    (mapsZero C)))))))))

------------------------------------------------------------------------
-- Boundary.
------------------------------------------------------------------------

record P11Level44BadPrimeOperatorSeparationBoundary : Set where
  field
    internalMarkedR2RestrictedToOld3 : Bool
    markedR2SeparatesTrivialAndStandardDeckTypes : Bool
    classicalGamma0FourU2Constructed : Bool
    analyticU2NonzeroKernelConstructed : Bool
    markedR2TrivialKernelProved : Bool
    markedR2CanBeRelabelledAnalyticU2 : Bool
    sourceNativeTwoAdicComparisonStillRequired : Bool

canonicalP11Level44BadPrimeOperatorSeparationBoundary :
  P11Level44BadPrimeOperatorSeparationBoundary
canonicalP11Level44BadPrimeOperatorSeparationBoundary = record
  { internalMarkedR2RestrictedToOld3 = true
  ; markedR2SeparatesTrivialAndStandardDeckTypes = true
  ; classicalGamma0FourU2Constructed = true
  ; analyticU2NonzeroKernelConstructed = true
  ; markedR2TrivialKernelProved = true
  ; markedR2CanBeRelabelledAnalyticU2 = false
  ; sourceNativeTwoAdicComparisonStillRequired = true
  }
