module DASHI.Mathematics.AlgebraicGeometry.ProjectiveSpaceHodgeReopeningCompilerExact where

------------------------------------------------------------------------
-- PROJECTIVE-SPACE HODGE REOPENING COMPILER
--
-- For CP^n, the standard theorem says each H^(p,p) is one-dimensional and is
-- generated by the p-th power of the hyperplane class.  This module isolates
-- exactly the data needed to turn that theorem into the repository's literal
-- HodgeConjectureAtCodimension:
--
--   h = q * H^p
--   H^p is the cycle class of an algebraic codimension-p cycle
--   ----------------------------------------------------------
--   h has an algebraic cycle representative.
--
-- The compiler does not manufacture the geometric CP^n identification,
-- singular/de Rham comparison, or the hyperplane-power theorem.
------------------------------------------------------------------------

open import Agda.Builtin.Equality using (_≡_; refl)
open import Agda.Builtin.Nat using (Nat)
open import Data.Rational.Base using (ℚ)
open import Relation.Binary.PropositionalEquality using (sym; trans)

import DASHI.Mathematics.AlgebraicGeometry.HodgeDecompositionCycleClassExact as Hodge

record ProjectiveSpaceHyperplanePowerSpanning
    {variety : Hodge.SmoothProjectiveComplexVariety}
    {comparison : Hodge.SingularDeRhamComparison variety}
    {hodge : Hodge.HodgeDecomposition variety comparison}
    (cycleMap : Hodge.CycleClassMap variety comparison hodge)
    (codimension : Nat) : Set₁ where
  field
    hyperplanePowerCycle :
      Hodge.Cycle cycleMap codimension

    coefficientOf :
      Hodge.RationalHodgeClass hodge codimension → ℚ

    everyClassIsHyperplanePower :
      (hodgeClass : Hodge.RationalHodgeClass hodge codimension) →
      Hodge.hodgeClassValue hodgeClass
      ≡ Hodge.scale
          (Hodge.HodgePiece hodge codimension codimension)
          (coefficientOf hodgeClass)
          (Hodge.cycleClass cycleMap codimension hyperplanePowerCycle)

open ProjectiveSpaceHyperplanePowerSpanning public

projectiveSpaceCycleRepresentative :
  ∀ {variety comparison hodge cycleMap codimension} →
  ProjectiveSpaceHyperplanePowerSpanning
    {variety = variety}
    {comparison = comparison}
    {hodge = hodge}
    cycleMap codimension →
  Hodge.RationalHodgeClass hodge codimension →
  Hodge.Cycle cycleMap codimension
projectiveSpaceCycleRepresentative spanning hodgeClass =
  Hodge.scaleCycle _ _
    (coefficientOf spanning hodgeClass)
    (hyperplanePowerCycle spanning)

projectiveSpaceCycleRepresentsClass :
  ∀ {variety comparison hodge cycleMap codimension}
    (spanning :
      ProjectiveSpaceHyperplanePowerSpanning
        {variety = variety}
        {comparison = comparison}
        {hodge = hodge}
        cycleMap codimension)
    (hodgeClass : Hodge.RationalHodgeClass hodge codimension) →
  Hodge.cycleClass cycleMap codimension
    (projectiveSpaceCycleRepresentative spanning hodgeClass)
  ≡ Hodge.hodgeClassValue hodgeClass
projectiveSpaceCycleRepresentsClass
    {hodge = hodge}
    {cycleMap = cycleMap}
    {codimension = codimension}
    spanning hodgeClass =
  trans
    (Hodge.cycleClassHomogeneous cycleMap codimension
      (coefficientOf spanning hodgeClass)
      (hyperplanePowerCycle spanning))
    (sym (everyClassIsHyperplanePower spanning hodgeClass))

projectiveSpaceSpanningGivesHodgeConjecture :
  ∀ {variety comparison hodge cycleMap codimension} →
  ProjectiveSpaceHyperplanePowerSpanning
    {variety = variety}
    {comparison = comparison}
    {hodge = hodge}
    cycleMap codimension →
  Hodge.HodgeConjectureAtCodimension cycleMap codimension
projectiveSpaceSpanningGivesHodgeConjecture spanning = record
  { Hodge.everyRationalHodgeClassHasCycle =
      projectiveSpaceCycleRepresentative spanning
  ; Hodge.cycleRepresentsClass =
      projectiveSpaceCycleRepresentsClass spanning
  }

record ProjectiveSpaceLiteralReopeningBoundary : Set where
  constructor projective-space-literal-reopening-boundary
  field
    hyperplanePowerReopeningCompilerPaid : Agda.Builtin.Bool.Bool
    actualCPnGeometricIdentificationPaid : Agda.Builtin.Bool.Bool
    generalHodgeConjecturePaid : Agda.Builtin.Bool.Bool

canonicalProjectiveSpaceLiteralReopeningBoundary :
  ProjectiveSpaceLiteralReopeningBoundary
canonicalProjectiveSpaceLiteralReopeningBoundary =
  projective-space-literal-reopening-boundary
    Agda.Builtin.Bool.true
    Agda.Builtin.Bool.false
    Agda.Builtin.Bool.false
