module DASHI.Reasoning.Everything where

-- Reasoning domain rollup.

import DASHI.Reasoning.RelationalEverything
import DASHI.Reasoning.TernarySynthesisOrbitWeldEverything
import DASHI.Reasoning.PathologicEverything
import DASHI.Reasoning.AccessBiasFallacySeparationExact
import DASHI.Reasoning.DialecticalOppositionNonExplosionExact
import DASHI.Reasoning.PredicateNormalFormEvidenceAuditExact
import DASHI.Reasoning.EvidenceDesignAdmissibilityExact
import DASHI.Reasoning.ClaimAuditManifestExact
import DASHI.Reasoning.ExperimentalAssertionConeEverything
import DASHI.Reasoning.SpacyDependencyToCandidateLogicalPNFExact
import DASHI.Reasoning.SpacyExecutableSemanticRuleBankExact
import DASHI.Reasoning.SpacyPNF369DialecticBridgeExact
import DASHI.Reasoning.SpacyNegationCounterpositionTernarySeparationExact
import DASHI.Reasoning.SpacyPNF369LogicalQualificationExact
import DASHI.Reasoning.SpacySauerkrautSentenceLogicalTraceExact
import DASHI.Reasoning.SemanticCandidateResidualBidiExact
import DASHI.Reasoning.SemanticConsumerRelativeClosureExact
import DASHI.Reasoning.SemanticEpistemicInterpretationExact
import DASHI.Reasoning.ComparativeInstitutionalMeaningExact
import DASHI.Reasoning.ComparativeInstitutionalDiscriminatorExact
import DASHI.Reasoning.HistoryTimeIndexedConsumerFibreExact
import DASHI.Reasoning.TemporalConsumerIndexedSemanticFibreExact
import DASHI.Reasoning.TemporalConsumerSelectiveReopeningExact
import DASHI.Reasoning.HistoryTimeRelationalReasoningFibreExact
import DASHI.Reasoning.HistoryTimeReasoningFibreTransportExact
import DASHI.Reasoning.HistoryTimeReasoningFibreTransportPathExact
import DASHI.Reasoning.HistoryTimeReasoningFibrePathCompositionExact
import DASHI.Reasoning.HistoryTimeReasoningFibreResidueExact
import DASHI.Reasoning.HistoryTimeIndexedAlgorithmModelExact
import DASHI.Reasoning.QuantumCryptoHistoryIndexedAlgorithmModelExact
import DASHI.Reasoning.PredicateNormalFormLogicalCalculusExact
import DASHI.Reasoning.SensibLawSpacyLogicalImplicationBidiExact
import DASHI.Reasoning.LogicalPromotionExperimentBackpropExact
import DASHI.Reasoning.LogicalConsequenceDerivationPathExact
import DASHI.Reasoning.LogicalConsequenceHistoryResidueExact
import DASHI.Reasoning.HistoryQualifiedImplicationConeExact
import DASHI.Reasoning.HistoryQualifiedPromotionBackpropExact
import DASHI.Reasoning.EvidencePromotionDerivationProtocolExact
import DASHI.Reasoning.SemanticLogicalSelectiveReopeningExact
import DASHI.Reasoning.PNFRevisionSelectiveReopeningExact
import DASHI.Reasoning.AdaptiveSemanticReasoningLoopExact
import DASHI.Reasoning.SelectiveImplicationCertificateReopeningExact
import DASHI.Reasoning.DerivationEdgeInstanceSelectiveReopeningExact
import DASHI.Reasoning.SemanticEpistemicPathReopeningExact
import DASHI.Reasoning.AristotleSelectiveImplicationReopeningExact
import DASHI.Reasoning.ReleasedArtifactProvenanceBidiExact
import DASHI.Reasoning.AristotleMCGSHypergraphExact
import DASHI.Reasoning.AristotleMCGSIntrospectiveSpecimen
import DASHI.Reasoning.AristotleMCGSRecoveredWitness
import DASHI.Reasoning.FolkLawEpistemicAuthorityCaptureExact
import DASHI.Reasoning.EpistemicAuthorityIntrospectiveVisualReceiptExact
import DASHI.Reasoning.FolkLawEpistemicAuthorityBroadExact
import DASHI.Reasoning.EpistemicAuthorityBroadVisualFindingExact

-- Source-bounded metaphor-as-structure / task-relative compression layer.
import DASHI.Reasoning.StructuralMetaphorSourceRegistryExact
import DASHI.Reasoning.StructuralMetaphorTaskCompressionExact
import DASHI.Reasoning.ConsumerRelativeMetaphorTransferFitnessExact
import DASHI.Reasoning.StructuralTransferBreakdownExact
import DASHI.Reasoning.MetaphorTransferResidualExact

-- Relation-representation / dynamic adequacy / realization layer.
import DASHI.Reasoning.RelationRepresentationSourceRegistryExact
import DASHI.Reasoning.RelationRepresentationStudyValidationObligationsExact
import DASHI.Reasoning.RelationRepresentationTOEInferenceHandoffExact
import DASHI.Reasoning.RelationRepresentationExternalReceiptAdmissionExact
import DASHI.Reasoning.ImplementationExperimentProvenanceExact
import DASHI.Reasoning.DASHIgGrokkingEmpiricalBridgeExact
import DASHI.Reasoning.DASHIgGrokkingStage67SpecimenExact
import DASHI.Reasoning.RelationRepresentationAdequacyExact
import DASHI.Reasoning.RelationRepresentationRealizationExact
import DASHI.Reasoning.BidirectionalRelationRepresentationBridgeExact
import DASHI.Reasoning.RelationRepresentationExperimentProtocolExact
import DASHI.Reasoning.RelationRepresentationCandidateDiscriminationExact
import DASHI.Reasoning.RelationRepresentationFrontierProgressGuardExact
import DASHI.Reasoning.RelationRepresentationMechanismSocketExact
import DASHI.Reasoning.FiniteRelationLinearAlgebraProducerExact
import DASHI.Reasoning.FiniteRelationSVDJacobianProducerExact
import DASHI.Reasoning.EigenslurFlourishingRelationBoundaryExact
import DASHI.Reasoning.RelationRepresentationCrossPollinationExact
import DASHI.Reasoning.HumourRelationRepresentationCrossPollinationExact
import DASHI.Reasoning.NeuralSpectralRelationCrossPollinationExact
import DASHI.Reasoning.RelationRepresentationRegression
