module DASHI.Biology.DomainEverything where

-- Biology domain compatibility parent.
-- DASHI.Biology.Everything remains the large historical subject surface;
-- specialized nested and thematic rollups attach here without duplicating
-- their leaves.

import DASHI.Biology.Everything
import DASHI.Biology.Levin.Everything
import DASHI.Biology.WaveAccessPNFEverything
import DASHI.Biology.EmbodiedHyperformalismEverything
import DASHI.Biology.Cannabis.Everything
import DASHI.Biology.AnimalexicEverything
import DASHI.Biology.PointedBulkSporadicTarotEverything
import DASHI.Biology.ThalamocorticalSensoryHistoryExact
import DASHI.Biology.AutisticInformationProcessingLandscapeExact
import DASHI.Biology.NeurotypeProcessingGeometryExact
import DASHI.Biology.ProcessingGeometryActionGateExact
import DASHI.Biology.AuDHDInteractionGeometryExact
import DASHI.Biology.PsilautNetworkResponseGeometryExact
import DASHI.Biology.NeurodivergentSocialEcologySourceRegistryExact
import DASHI.Biology.SocialEcologicalAffordanceConeExact
import DASHI.Biology.TrustedFriendRelationalScaffoldingExact
import DASHI.Biology.TrustedFriendRelationalGateExact
import DASHI.Biology.TrustedFriendEcologyInteractionExact
import DASHI.Biology.NeuroqueerRelationshipEcologyExact
import DASHI.Biology.SolisProjectProvenanceExact
import DASHI.Biology.SolisSystemSensitivityBoundaryExact
import DASHI.Biology.NeurodivergentSocialEcologyCrossPollinationExact

-- Existing thematic Biology aggregates that were previously floating outside
-- the authoritative domain spine.
import DASHI.Biology.TarotEverything
import DASHI.Biology.PsychogeographyEverything
import DASHI.Biology.TrumpPsychogeographyEverything
import DASHI.Biology.AliceBrownEpistemicGovernanceEverything
