module DASHI.Biology.KluverLogPolar5HT2ASourceAtlasExact where

open import DASHI.Core.Prelude
open import Agda.Builtin.String using (String)

import DASHI.Core.AttributedSourceCore as Source

------------------------------------------------------------------------
-- SOURCE ATTRIBUTION
--
-- This atlas follows Docs/SourceAttributionPolicy.md:
--
--   external source claim / datum
--     != DASHI formal reconstruction
--     != DASHI cross-source inference
--     != new DASHI theorem / extension
--     != promotion / external adjudication
--
-- The source rows below pay only the roles named in each
-- formalisationRelationship field.  Citation does not import proof and does
-- not authorize stronger mechanistic or phenomenological claims.
------------------------------------------------------------------------

ermentroutCowan1979 : Source.AttributedSource
ermentroutCowan1979 =
  Source.mkDOISource
    "G. Bard Ermentrout; Jack D. Cowan"
    "A mathematical theory of visual hallucination patterns"
    "Biological Cybernetics 34:137-150"
    "1979"
    "10.1007/BF00336965"
    "https://doi.org/10.1007/BF00336965"
    Source.academicArticleSource
    "Motivates neural-field instability and symmetry-selected visual-pattern families; does not state the finite DASHI witnesses or prove that every hallucination is generated by this mechanism."
    Source.publicAttribution

schwartz1980 : Source.AttributedSource
schwartz1980 =
  Source.mkDOISource
    "Eric L. Schwartz"
    "Computational anatomy and functional architecture of striate cortex: a spatial mapping approach to perceptual coding"
    "Vision Research"
    "1980"
    "10.1016/0042-6989(80)90090-5"
    "https://doi.org/10.1016/0042-6989(80)90090-5"
    Source.academicArticleSource
    "Motivates the complex-log / log-polar retinocortical approximation under which multiplicative radial scale and rotation become cortical translations; does not make the finite DASHI chart an exact human V1 atlas."
    Source.publicAttribution

grusser1995 : Source.AttributedSource
grusser1995 =
  Source.mkDOISource
    "O. J. Grusser"
    "Migraine phosphenes and the retino-cortical magnification factor"
    "Vision Research 35(8):1125-1134"
    "1995"
    "10.1016/0042-6989(94)00187-Q"
    "https://doi.org/10.1016/0042-6989(94)00187-Q"
    Source.academicArticleSource
    "Supports the source-side relation between retinocortical magnification, approximately constant cortical propagation, and nonuniform visual-field aura motion; the finite DASHI step theorem is a new synthetic analogue."
    Source.publicAttribution

bressloffEtAl2001 : Source.AttributedSource
bressloffEtAl2001 =
  Source.mkDOISource
    "Paul C. Bressloff; Jack D. Cowan; Martin Golubitsky; Peter J. Thomas; Matthew C. Wiener"
    "Geometric visual hallucinations, Euclidean symmetry and the functional architecture of striate cortex"
    "Philosophical Transactions of the Royal Society B 356:299-330"
    "2001"
    "10.1098/rstb.2000.0769"
    "https://doi.org/10.1098/rstb.2000.0769"
    Source.academicArticleSource
    "Motivates cortical symmetry/mode families and their retinotopic projection into recurring geometric hallucination classes; does not state the DASHI relation constructors or MDL extensions."
    Source.publicAttribution

hadjikhaniEtAl2001 : Source.AttributedSource
hadjikhaniEtAl2001 =
  Source.mkDOISource
    "Nouchine Hadjikhani; M. Sanchez Del Rio; O. Wu; D. Schwartz; D. Bakker; B. Fischl; K. K. Kwong; F. M. Cutrer; B. R. Rosen; R. B. Tootell; A. G. Sorensen; M. A. Moskowitz"
    "Mechanisms of migraine aura revealed by functional MRI in human visual cortex"
    "Proceedings of the National Academy of Sciences 98(8):4687-4692"
    "2001"
    "10.1073/pnas.071582498"
    "https://doi.org/10.1073/pnas.071582498"
    Source.academicArticleSource
    "Provides human fMRI evidence of a slowly propagating occipital BOLD change congruent with aura retinotopy; it does not prove that psychedelic form constants and migraine aura share one unique mechanism."
    Source.publicAttribution

beliveauEtAl2017 : Source.AttributedSource
beliveauEtAl2017 =
  Source.mkDOISource
    "Vincent Beliveau; Melanie Ganz; Ling Feng; Benedicte Ozenne; Liselotte Hojgaard; Peter M. Fisher; Claus Svarer; Douglas N. Greve; Gitte M. Knudsen"
    "A High-Resolution In Vivo Atlas of the Human Brain's Serotonin System"
    "Journal of Neuroscience 37(1):120-128"
    "2017"
    "10.1523/JNEUROSCI.2830-16.2016"
    "https://doi.org/10.1523/JNEUROSCI.2830-16.2016"
    Source.academicArticleSource
    "Supports a distributed human 5-HT receptor atlas including 5-HT2A; receptor availability is an anatomical observation and does not itself establish psychedelic causal flow or phenomenological meaning."
    Source.publicAttribution

prellerEtAl2017 : Source.AttributedSource
prellerEtAl2017 =
  Source.mkDOISource
    "Katrin H. Preller; Marcus Herdener; Thomas Pokorny; Amanda Planzer; Rainer Kraehenmann; Philipp Stampfli; Matthias E. Liechti; Erich Seifritz; Franz X. Vollenweider"
    "The Fabric of Meaning and Subjective Effects in LSD-Induced States Depend on Serotonin 2A Receptor Activation"
    "Current Biology 27(3):451-457"
    "2017"
    "10.1016/j.cub.2016.12.030"
    "https://doi.org/10.1016/j.cub.2016.12.030"
    Source.academicArticleSource
    "Supports a 5-HT2A-dependent component of LSD-induced subjective effects and altered personal-relevance processing in a ketanserin-blockade paradigm; it does not prove an ACC-specific imperative-attention mechanism."
    Source.publicAttribution

prellerEtAl2018 : Source.AttributedSource
prellerEtAl2018 =
  Source.mkDOISource
    "Katrin H. Preller; Joshua B. Burt; Jie Lisa Ji; Charles H. Schleifer; Brendan D. Adkinson; Philipp Stampfli; Erich Seifritz; Grega Repovs; John H. Krystal; John D. Murray; Franz X. Vollenweider; Alan Anticevic"
    "Changes in global and thalamic brain connectivity in LSD-induced altered states of consciousness are attributable to the 5-HT2A receptor"
    "eLife 7:e35082"
    "2018"
    "10.7554/eLife.35082"
    "https://doi.org/10.7554/eLife.35082"
    Source.academicArticleSource
    "Supports a 5-HT2A-dependent component of LSD-related global/thalamic connectivity changes under ketanserin blockade; it does not make one region or one receptor sufficient for the total experience."
    Source.publicAttribution

hamEtAl2013 : Source.AttributedSource
hamEtAl2013 =
  Source.mkDOISource
    "Timothy Ham; Alex Leff; Xavier de Boissezon; Anna Joffe; David J. Sharp"
    "Cognitive control and the salience network: an investigation of error processing and effective connectivity"
    "Journal of Neuroscience 33(16):7091-7098"
    "2013"
    "10.1523/JNEUROSCI.4692-12.2013"
    "https://doi.org/10.1523/JNEUROSCI.4692-12.2013"
    Source.academicArticleSource
    "Supports dorsal anterior cingulate and bilateral insula as nodes used in a salience-network account; it does not establish that psychedelic salience or entity-like communication originates in dACC."
    Source.publicAttribution

cipolottiEtAl2025 : Source.AttributedSource
cipolottiEtAl2025 =
  Source.mkDOISource
    "Lisa Cipolotti; Joe Mole; James K. Ruffle; Amy Nelson; Robert Gray; Parashkev Nachev"
    "Cognitive control and the anterior cingulate cortex: Necessity and coherence"
    "Cortex 182:87-99"
    "2025"
    "10.1016/j.cortex.2024.11.010"
    "https://doi.org/10.1016/j.cortex.2024.11.010"
    Source.academicArticleSource
    "Provides a recent source-side caution against treating medial frontal/ACC activation as a simple necessary controller across canonical conflict tasks; used here as an anti-overclaim boundary."
    Source.publicAttribution

canonicalKluverLogPolar5HT2ASources : List Source.AttributedSource
canonicalKluverLogPolar5HT2ASources =
  ermentroutCowan1979
  ∷ schwartz1980
  ∷ grusser1995
  ∷ bressloffEtAl2001
  ∷ hadjikhaniEtAl2001
  ∷ beliveauEtAl2017
  ∷ prellerEtAl2017
  ∷ prellerEtAl2018
  ∷ hamEtAl2013
  ∷ cipolottiEtAl2025
  ∷ []

canonicalKluverLogPolar5HT2AAtlas : Source.AttributedSourceAtlas
canonicalKluverLogPolar5HT2AAtlas =
  Source.mkSourceAtlas
    "Kluver/log-polar/5-HT2A source atlas"
    "DASHI.Biology.KluverLogPolar5HT2ASourceAtlasExact"
    canonicalKluverLogPolar5HT2ASources
    "Source-bounded support for neural-field form constants, log-polar retinotopy, migraine propagation geometry, human 5-HT2A mapping, pharmacological blockade, and ACC/salience context. DASHI composition theorems remain repo-native."

canonicalKluverLogPolar5HT2AAtlasIsNonPromoting :
  Source.atlasCreatesAuthority canonicalKluverLogPolar5HT2AAtlas ≡ false
canonicalKluverLogPolar5HT2AAtlasIsNonPromoting =
  Source.atlasCreatesAuthorityIsFalse canonicalKluverLogPolar5HT2AAtlas
