module DASHI.Biology.QuailHistamineMicrobiomeHostBridgeRegression where

import DASHI.Biology.QuailHistamineMicrobiomeHostBridgeExact as Q
import DASHI.Biology.Levin.MicrobiomeHostAppetiteBoundary as Host

hostBoundaryRegression : Host.MicrobiomeHostAppetiteBoundary
hostBoundaryRegression = Q.microbiomeHostBoundary Q.canonicalQuailHistamineMicrobiomeHostBridge

routeRegression : Host.AppetiteSignalRoute
routeRegression = Q.histamineRoute Q.canonicalQuailHistamineMicrobiomeHostBridge

bridgeBoundaryRegression : Q.QuailHistamineMicrobiomeHostBoundary
bridgeBoundaryRegression = Q.canonicalQuailHistamineMicrobiomeHostBoundary
