{-# OPTIONS --safe #-}
module DASHI.Physics.Foundations.BalabanContinuumProducerValidation where

open import DASHI.Physics.YangMills.CompactLieProofLevel
import DASHI.Physics.Foundations.BalabanAllSectorContinuumProducerExact as Producer
import DASHI.Physics.Foundations.CommonActionQFTGRContinuumProducerCompilerExact as Compiler

balabanContinuumProducerCompiler : ProofLevel
balabanContinuumProducerCompiler = Producer.balabanContinuumProducerCompilerLevel

commonMetricContinuumProducerCompiler : ProofLevel
commonMetricContinuumProducerCompiler =
  Compiler.commonActionQFTGRContinuumProducerCompilerLevel
