{-# OPTIONS --safe #-}
module DASHI.Physics.Foundations.CMP119AntigravityLiteralEvaluatorFiniteModeSameObjectExact where

open import Agda.Builtin.Nat using (Nat)

import Real as Bishop

import DASHI.Physics.Foundations.CMP119AntigravityCanonicalBishopSU2ConventionExact as Running
import DASHI.Physics.Foundations.CMP119AntigravityCanonicalBishopRichBrillouinUVEdgeExact as RichNorm
import DASHI.Physics.Foundations.CMP119AntigravityFiniteEllBishopShellNormalizationExact as FiniteEll
import DASHI.Physics.Foundations.CMP119AntigravityFiniteModePlaquetteBetaSameObjectExact as FinitePlaquette
import DASHI.Physics.Foundations.CMP119AntigravityRichBrillouinFiniteModeDecompositionExact as Decomposition
import DASHI.Physics.Foundations.CMP119AntigravityRichBrillouinFiniteModeGaussianProjectionExact as RichFinite
import DASHI.Physics.Foundations.CMP119AntigravityRichRegularLiteralEvaluatorSameObjectExact as ReceiptSame
import DASHI.Physics.Foundations.CMP119AntigravitySourceHistoryBishopUVViewExact as UV
import DASHI.Physics.YangMills.BalabanClayT4ConfiguredBrillouinBoxReceiptFamilyExact as Rich
import DASHI.Physics.YangMills.BalabanClayT4LiteralOneLoopBoxEvaluatorExact as Literal
import DASHI.Physics.YangMills.BalabanClayT4LocalizedPlaquetteCoefficientProducerExact as Plaquette
import DASHI.Physics.YangMills.BalabanYM4FiniteModeBetaLowerRemainderExact as Local
import DASHI.Physics.YangMills.BalabanYM4FiniteModeBetaToSourceTrajectoryExact as FiniteMode
import DASHI.Physics.YangMills.BalabanYM4SourceNormalizedCouplingRecurrenceExact as Flow
open import DASHI.Physics.YangMills.CompactLieProofLevel

------------------------------------------------------------------------
-- LITERAL EVALUATOR -> FINITE MODE SAME-OBJECT PRODUCER
--
-- The older finite-mode ABI left `ell` and `epsilon` abstract.  This producer
-- binds them back to the already-existing physical objects:
--
--   ell     <-> pi^-2 log L              (analytic shell coordinate)
--   epsilon <-> rich regularRemainder    (regular Brillouin matching)
--
-- while separately requiring that the rich configured partition is literally
-- the partition generated by the same Wilson/FP/Haar evaluator.
------------------------------------------------------------------------

record LiteralEvaluatorFiniteModeSameObject
    {trajectory : Flow.SourceNormalizedCouplingTrajectory}
    {Mode Atom : Set}
    {expressions ward scalarData}
    (finiteMode : FiniteMode.FiniteModeBetaTrajectoryData trajectory Mode Atom)
    (oneLoop : Plaquette.OneLoopVacuumPolarizationData Nat)
    (remainder : Plaquette.PlaquetteRemainderData Nat)
    (rich : Rich.LiteralBrillouinIntegralPhysicalData Nat Bishop.ℝ)
    (running : Running.CanonicalBishopSU2RunningInputs Nat) : Set₂ where
  field
    finiteModePlaquette :
      FinitePlaquette.FiniteModePlaquetteBetaSameObject
        finiteMode oneLoop remainder

    evaluatorAt :
      Nat → Literal.LiteralGeneratedBoxEvaluator expressions ward scalarData

    richNormalization :
      RichNorm.CanonicalBishopRichBrillouinUVEdgeNormalization rich running

    richAddIsBishopAdd :
      ∀ left right →
      Bishop._≃_
        (Rich.add rich left right)
        (Bishop._+_ left right)

    partitionSameLiteralEvaluator :
      ∀ step →
      ReceiptSame.RichRegularLiteralEvaluatorSameObject
        rich step (evaluatorAt step)

    finiteEllNormalization :
      ∀ step →
      FiniteEll.FiniteEllBishopShellNormalization
        (FiniteMode.gaussianAt finiteMode step) running step

    regularMatchingSameFiniteEpsilon :
      ∀ step →
      Bishop._≃_
        (Rich.regularRemainder rich step)
        (UV.embed
          (Local.epsilon (FiniteMode.gaussianAt finiteMode step)))

open LiteralEvaluatorFiniteModeSameObject public

decompositionAt :
  ∀ {trajectory Mode Atom expressions ward scalarData finiteMode oneLoop
      remainder rich running}
    (sameObject : LiteralEvaluatorFiniteModeSameObject
      {trajectory = trajectory} {Mode = Mode} {Atom = Atom}
      {expressions = expressions} {ward = ward} {scalarData = scalarData}
      finiteMode oneLoop remainder rich running) →
    step →
  Decomposition.RichBrillouinFiniteModeDecomposition
    (FiniteMode.gaussianAt finiteMode step) rich step
decompositionAt sameObject step =
  Decomposition.fromFiniteEllAndRegularMatching
    (richNormalization sameObject)
    (finiteEllNormalization sameObject step)
    (richAddIsBishopAdd sameObject)
    (regularMatchingSameFiniteEpsilon sameObject step)

asRichBrillouinFiniteModeGaussianSameObject :
  ∀ {trajectory Mode Atom expressions ward scalarData finiteMode oneLoop
      remainder rich running} →
  LiteralEvaluatorFiniteModeSameObject
    {trajectory = trajectory} {Mode = Mode} {Atom = Atom}
    {expressions = expressions} {ward = ward} {scalarData = scalarData}
    finiteMode oneLoop remainder rich running →
  RichFinite.RichBrillouinFiniteModeGaussianSameObject
    finiteMode oneLoop remainder rich
asRichBrillouinFiniteModeGaussianSameObject sameObject = record
  { RichFinite.RichBrillouinFiniteModeGaussianSameObject.finiteModePlaquette =
      finiteModePlaquette sameObject
  ; RichFinite.RichBrillouinFiniteModeGaussianSameObject.decompositionAt =
      decompositionAt sameObject
  }

literalEvaluatorFiniteModeSameObjectCompilerLevel : ProofLevel
literalEvaluatorFiniteModeSameObjectCompilerLevel = machineChecked

literalEvaluatorPartitionIdentificationLevel : ProofLevel
literalEvaluatorPartitionIdentificationLevel = conditional

finiteEllPhysicalLogIdentificationLevel : ProofLevel
finiteEllPhysicalLogIdentificationLevel = conditional

regularMatchingFiniteEpsilonIdentificationLevel : ProofLevel
regularMatchingFiniteEpsilonIdentificationLevel = conditional
