module DASHI.Physics.Foundations.CMP119WarpedVacuumWeakYMPhysicalSameObjectNoGoExact where

------------------------------------------------------------------------
-- DASHI-original same-physical-source obstruction.
--
-- Reuses:
--   * the literal finite action source in DiscreteWarpedEinsteinMatterModel;
--   * the weak-coupling SU(2) E/B active-stress nonnegativity theorem.
--
-- The finite warped model has normalized T=(+1,-1,-1,-1) on its four
-- orthonormal diagonal slots and A=T00+T11+T22+T33=-2.
-- The selected weak-coupling YM stress family has A>=0.
-- These cannot be the same physical source with the same metric, sign,
-- active contraction, and normalization simultaneously.
--
-- This is an honest same-object *exclusion*, not an identification of
-- the finite toy source with the selected renormalized CMP119 measure.
------------------------------------------------------------------------

open import Agda.Builtin.Equality using (_≡_; refl)
open import Data.Empty using (⊥)
open import Data.Rational.Base using (ℚ; 0ℚ; 1ℚ; _+_; _≤_; _<_; -_)
import Data.Rational.Properties as ℚP
open import Relation.Binary.PropositionalEquality using (cong₂; subst; trans)
open import Relation.Nullary.Decidable.Core using (toWitness)

import DASHI.Geometry.FlatLorentzianModel as Flat
import DASHI.Physics.Closure.DiscreteWarpedEinsteinMatterModel as Warped
import DASHI.Physics.Foundations.CMP119AntigravityWeakCouplingTraceEnergyNoGoExact as WeakYM

-- Explicit finite->rational normalization; this is NOT an SI scale map,
-- quantum expectation or a continuum tensor reconstruction.
sourceCoefficientAsRational : Warped.SourceCoefficient → ℚ
sourceCoefficientAsRational Warped.negativeSource = - 1ℚ
sourceCoefficientAsRational Warped.zeroSource = 0ℚ
sourceCoefficientAsRational Warped.positiveSource = 1ℚ

warpedActionTensor : Flat.Axis4 → Flat.Axis4 → ℚ
warpedActionTensor a b =
  sourceCoefficientAsRational (Warped.computedMatterStress a b)

Tensor4 : Set
Tensor4 = Flat.Axis4 → Flat.Axis4 → ℚ

diagonalActive : Tensor4 → ℚ
diagonalActive tensor =
  tensor Flat.timeAxis Flat.timeAxis
  + (tensor Flat.xAxis Flat.xAxis
  + (tensor Flat.yAxis Flat.yAxis
  + tensor Flat.zAxis Flat.zAxis))

warpedActionDiagonal : ℚ
warpedActionDiagonal = diagonalActive warpedActionTensor

warpedActionDiagonalNegative : warpedActionDiagonal < 0ℚ
warpedActionDiagonalNegative =
  toWitness {a? = warpedActionDiagonal ℚP.<? 0ℚ} _

-- By requiring equality on the *whole* selected stress tensor, rather
-- than one aggregate fit, we make all four slots accountable. The
-- induced active observable equality is a theorem.
sameTensorForcesSameActive :
  ∀ (selected : Tensor4) →
  ((a b : Flat.Axis4) → selected a b ≡ warpedActionTensor a b) →
  diagonalActive selected ≡ warpedActionDiagonal
sameTensorForcesSameActive selected same =
  cong₂ _+_
    (same Flat.timeAxis Flat.timeAxis)
    (cong₂ _+_
      (same Flat.xAxis Flat.xAxis)
      (cong₂ _+_
        (same Flat.yAxis Flat.yAxis)
        (same Flat.zAxis Flat.zAxis)))

-- The missing physical identification is made explicit: the selected
-- rational tensor must be calculated from the SAME selected YM source,
-- and its diagonal contraction must have the Lorentzian E/B value.
-- No arbitrary stress matching the geometry is generated by this record.
record WeakYMSelectedTensorRepresentation
    (physical : WeakYM.WeakCouplingYMTraceEnergyData) : Set where
  field
    selectedStressTensor : Tensor4
    selectedActiveIsWeakCouplingYM :
      diagonalActive selectedStressTensor
      ≡ WeakYM.activeStress physical

open WeakYMSelectedTensorRepresentation public

weakYMDoesNotHaveWarpedVacuumActive :
  (physical : WeakYM.WeakCouplingYMTraceEnergyData) →
  WeakYM.activeStress physical ≡ warpedActionDiagonal →
  ⊥
weakYMDoesNotHaveWarpedVacuumActive physical same =
  ℚP.<⇒≱
    warpedActionDiagonalNegative
    (subst (0ℚ ≤_) same (WeakYM.activeStressNonnegative physical))

noFullSelectedPhysicalStressWeldToWarpedVacuum :
  (physical : WeakYM.WeakCouplingYMTraceEnergyData) →
  (representation : WeakYMSelectedTensorRepresentation physical) →
  ((a b : Flat.Axis4) →
    selectedStressTensor representation a b ≡ warpedActionTensor a b) →
  ⊥
noFullSelectedPhysicalStressWeldToWarpedVacuum
    physical representation same =
  weakYMDoesNotHaveWarpedVacuumActive physical
    (trans
      (Relation.Binary.PropositionalEquality.sym
        (selectedActiveIsWeakCouplingYM representation))
      (sameTensorForcesSameActive
        (selectedStressTensor representation) same))

------------------------------------------------------------------------
-- Interpretation:
-- The finite warped action *was chosen* to have vacuum-like stress,
-- whereas the weak YM source theorem controls the physical E/B active
-- contraction. Equality is impossible inside that parameter regime.
-- This does not rule out a different quantum source, strong coupling,
-- spacetime-dependent renormalization, or an independently derived
-- additional stress with a sufficiently negative active contribution.
------------------------------------------------------------------------
