{-# OPTIONS --safe #-}
module DASHI.Physics.Foundations.CMP119CosmologyPreferredSourcePhysicsMaxCut20261004NTest where

import DASHI.Physics.Foundations.CMP119CosmologyPreferredSourcePhysicsMaxCut20261004NExact as N

oldFourOpaqueLeafAccountingRetiredRegression =
  N.oldFourOpaqueLeafAccountingRetired

a2IndependentObservableChoiceEliminatedRegression =
  N.a2IndependentObservableChoiceEliminated

a2PairToObservableSameObjectSemanticsStillOpenRegression =
  N.a2PairToObservableSameObjectSemanticsStillOpen

b1DirectInequalityIsCompilerOutputRegression =
  N.b1DirectInequalityIsCompilerOutput

b1MovesWithLateB2CutoffRegression =
  N.b1MovesWithLateB2Cutoff

b2QuantitativeTailMarginIsCompilerOutputRegression =
  N.b2QuantitativeTailMarginIsCompilerOutput

a1StillRequiresSignedSourceLawRegression =
  N.a1StillRequiresSignedSourceLaw
