{-# OPTIONS --safe #-}
module DASHI.Physics.Foundations.CMP119CosmologyA2LocalCWilsonPresentationCompilerTest where

import DASHI.Physics.Foundations.CMP119CosmologyA2LocalCWilsonPresentationCompilerExact as A2

localCStressEncodingPaysObservableConstructionRegression =
  A2.localCStressEncodingPaysObservableConstruction

publishedWilsonApplicationPaysAdmissibilityRegression =
  A2.publishedWilsonApplicationPaysAdmissibility

noIndependentA2SelectedObservableRegression =
  A2.noIndependentA2SelectedObservable
