{-# OPTIONS --safe #-}
module DASHI.Physics.Foundations.CMP119CosmologyPartitionWeylTraceExact where

------------------------------------------------------------------------
-- FINITE ONE-POINT COSMOLOGICAL SOURCE: WEYL TRACE OF D Z.
--
-- The cosmological source generated by the finite Euclidean theory begins
-- with the first variation of the partition functional, not with the
-- connected derivative of an independently chosen normalized insertion.
--
-- This module integrates the pointwise d=4 Wilson trace cancellation from
-- CMP119CosmologyPartitionStressFirstVariationExact on the SAME finite
-- physical measure.  Consequently the four-diagonal first variation of Z
-- is exactly the weighted non-Wilson/reference-measure Weyl score.
--
-- For a metric-independent product-Haar reference this sharpens further:
--
--   sum_mu D_{h_mumu} Z
--     = integral rho * ( - sum_mu D_{h_mumu} S_nonWilson ).
--
-- Hence the classical d=4 Wilson term cannot manufacture a nonzero
-- one-point Weyl source.  Any finite nonzero trace must be supplied by the
-- selected regular/R/boundary/vacuum metric dependence or by an actual
-- metric-dependent reference measure.  No Lorentzian continuation,
-- renormalized continuum stress, anomaly identification, or acceleration
-- sign is asserted here.
------------------------------------------------------------------------

open import Agda.Builtin.Equality using (_≡_)
open import Data.Rational.Base as ℚ using (ℚ; 0ℚ; _+_; _*_; -_)
import Data.Rational.Tactic.RingSolver as Ring
open import Relation.Binary.PropositionalEquality using (cong; sym; trans)

import DASHI.Physics.Foundations.KernelGeometryEmergenceObligations as K
import DASHI.Physics.Foundations.CMP119CosmologyPartitionStressFirstVariationExact as Source
import DASHI.Physics.Foundations.CMP119RationalFiniteMeasureIntegrationLawsExact as Integral
import DASHI.Physics.YangMills.YangMillsClayPinnedPhysicalCarriersExact as Physical

fourDiagonalPartitionDerivativeSum :
  ∀ {Configuration}
    (measure : Physical.PhysicalFiniteYMMeasure Configuration ℚ) →
  Source.CompleteFiniteMetricVariation Configuration → ℚ
fourDiagonalPartitionDerivativeSum measure d =
  (Source.partitionDerivative measure d K.component00
    + Source.partitionDerivative measure d K.component11)
  +
  (Source.partitionDerivative measure d K.component22
    + Source.partitionDerivative measure d K.component33)

weightedWeylNumerator :
  ∀ {Configuration}
    (measure : Physical.PhysicalFiniteYMMeasure Configuration ℚ) →
  Source.CompleteFiniteMetricVariation Configuration → ℚ
weightedWeylNumerator measure d =
  Physical.haarIntegral measure
    (λ x →
      Physical.density measure x
      * Source.fourDiagonalReferenceMinusSector d x)

partitionWeylTraceIsWeightedResidual :
  ∀ {Configuration}
    (measure : Physical.PhysicalFiniteYMMeasure Configuration ℚ)
    (d : Source.CompleteFiniteMetricVariation Configuration)
    (laws : Integral.RationalFiniteMeasureIntegrationLaws measure) →
  fourDiagonalPartitionDerivativeSum measure d
  ≡ weightedWeylNumerator measure d
partitionWeylTraceIsWeightedResidual measure d laws =
  let
    f00 = λ x →
      Physical.density measure x
      * Source.weightedLogDerivative d K.component00 x
    f11 = λ x →
      Physical.density measure x
      * Source.weightedLogDerivative d K.component11 x
    f22 = λ x →
      Physical.density measure x
      * Source.weightedLogDerivative d K.component22 x
    f33 = λ x →
      Physical.density measure x
      * Source.weightedLogDerivative d K.component33 x
  in
  trans
    (sym (Integral.haarIntegralFourAdd laws f00 f11 f22 f33))
    (Integral.haarIntegralCongruent laws _ _
      (λ x →
        trans
          (Ring.solve-∀
            (Physical.density measure x)
            (Source.weightedLogDerivative d K.component00 x)
            (Source.weightedLogDerivative d K.component11 x)
            (Source.weightedLogDerivative d K.component22 x)
            (Source.weightedLogDerivative d K.component33 x))
          (cong
            (λ value → Physical.density measure x * value)
            (Source.weightedLogDerivativeWeylTrace d x))))

nonWilsonDiagonalTrace :
  ∀ {Configuration} →
  Source.CompleteFiniteMetricVariation Configuration →
  Configuration → ℚ
nonWilsonDiagonalTrace d x =
  (Source.nonWilsonDerivative d K.component00 x
    + Source.nonWilsonDerivative d K.component11 x)
  +
  (Source.nonWilsonDerivative d K.component22 x
    + Source.nonWilsonDerivative d K.component33 x)

fixedHaarResidualIsNegativeNonWilsonTrace :
  ∀ {Configuration}
    (d : Source.CompleteFiniteMetricVariation Configuration) →
  (∀ h x → Source.referenceMeasureLogVariation d h x ≡ 0ℚ) →
  ∀ x →
  Source.fourDiagonalReferenceMinusSector d x
  ≡ - nonWilsonDiagonalTrace d x
fixedHaarResidualIsNegativeNonWilsonTrace d referenceFixed x
  rewrite referenceFixed K.component00 x
        | referenceFixed K.component11 x
        | referenceFixed K.component22 x
        | referenceFixed K.component33 x =
  Ring.solve-∀
    (Source.nonWilsonDerivative d K.component00 x)
    (Source.nonWilsonDerivative d K.component11 x)
    (Source.nonWilsonDerivative d K.component22 x)
    (Source.nonWilsonDerivative d K.component33 x)

fixedHaarPartitionWeylTrace :
  ∀ {Configuration}
    (measure : Physical.PhysicalFiniteYMMeasure Configuration ℚ)
    (d : Source.CompleteFiniteMetricVariation Configuration)
    (laws : Integral.RationalFiniteMeasureIntegrationLaws measure) →
  (∀ h x → Source.referenceMeasureLogVariation d h x ≡ 0ℚ) →
  fourDiagonalPartitionDerivativeSum measure d
  ≡
  Physical.haarIntegral measure
    (λ x →
      Physical.density measure x
      * (- nonWilsonDiagonalTrace d x))
fixedHaarPartitionWeylTrace measure d laws referenceFixed =
  trans
    (partitionWeylTraceIsWeightedResidual measure d laws)
    (Integral.haarIntegralCongruent laws _ _
      (λ x →
        cong
          (λ value → Physical.density measure x * value)
          (fixedHaarResidualIsNegativeNonWilsonTrace
            d referenceFixed x)))

traceSilentCompleteActionForcesZeroPartitionWeylTrace :
  ∀ {Configuration}
    (measure : Physical.PhysicalFiniteYMMeasure Configuration ℚ)
    (d : Source.CompleteFiniteMetricVariation Configuration)
    (laws : Integral.RationalFiniteMeasureIntegrationLaws measure) →
  (∀ h x → Source.referenceMeasureLogVariation d h x ≡ 0ℚ) →
  (∀ x → nonWilsonDiagonalTrace d x ≡ 0ℚ) →
  fourDiagonalPartitionDerivativeSum measure d ≡ 0ℚ
traceSilentCompleteActionForcesZeroPartitionWeylTrace
    measure d laws referenceFixed traceSilent =
  trans
    (fixedHaarPartitionWeylTrace measure d laws referenceFixed)
    (trans
      (Integral.haarIntegralCongruent laws _ _
        (λ x →
          trans
            (cong
              (λ value → Physical.density measure x * (- value))
              (traceSilent x))
            (Ring.solve-∀ (Physical.density measure x))))
      (Integral.haarIntegralZero laws))
