{-# OPTIONS --safe #-}
module DASHI.Physics.Foundations.CMP119AntigravityRichBrillouinFiniteModeDecompositionExact where

open import Agda.Builtin.Nat using (Nat)
open import Relation.Binary.PropositionalEquality using (subst)

import Real as Bishop
import RealProperties as BishopP

import DASHI.Physics.Closure.NSTriadKNMurrayBishopDirectCanonicalCarrier as Carrier
import DASHI.Physics.Foundations.CMP119AntigravitySourceHistoryBishopUVViewExact as UV
import DASHI.Physics.Foundations.CMP119AntigravityCanonicalBishopSU2ConventionExact as Running
import DASHI.Physics.Foundations.CMP119AntigravityCanonicalBishopRichBrillouinUVEdgeExact as RichNorm
import DASHI.Physics.Foundations.CMP119AntigravityFiniteEllBishopShellNormalizationExact as FiniteEll
import DASHI.Physics.YangMills.BalabanClayT4ConfiguredBrillouinBoxReceiptFamilyExact as Rich
import DASHI.Physics.YangMills.BalabanYM4FiniteModeBetaLowerRemainderExact as Local
open import DASHI.Physics.YangMills.CompactLieProofLevel

------------------------------------------------------------------------
-- EXISTING BRILLOUIN SHELL + REGULAR MATCHING -> FINITE-MODE beta_Z
--
-- FiniteGaussianModeEnclosure already stores
--
--   betaZ = (11/12) * ell + epsilon.
--
-- The rich configured carrier already stores
--
--   coefficient = scalarIntegral + regularRemainder.
--
-- Therefore a same-object identification needs only the two physically
-- meaningful component equations below.  The full beta_Z equality is then
-- generated by carrier algebra; it is not an additional source premise.
------------------------------------------------------------------------

record RichBrillouinFiniteModeDecomposition
    {Mode : Set}
    (gaussian : Local.FiniteGaussianModeEnclosure Mode)
    (rich : Rich.LiteralBrillouinIntegralPhysicalData Nat Bishop.ℝ)
    (step : Nat) : Set₁ where
  field
    richAddIsBishopAdd :
      ∀ left right →
      Bishop._≃_
        (Rich.add rich left right)
        (Bishop._+_ left right)

    shellSameFiniteUniversalTerm :
      Bishop._≃_
        (Rich.scalarIntegral rich step)
        (UV.embed
          (Local.oneLoopSU2Factor * Local.ell gaussian))

    regularMatchingSameFiniteEpsilon :
      Bishop._≃_
        (Rich.regularRemainder rich step)
        (UV.embed (Local.epsilon gaussian))

open RichBrillouinFiniteModeDecomposition public

equalityAsBishopSetoid :
  ∀ {left right : Bishop.ℝ} →
  left ≡ right → Bishop._≃_ left right
equalityAsBishopSetoid {left} equality =
  subst (λ selected → Bishop._≃_ left selected) equality BishopP.≃-refl

richCoefficientSameFiniteModeBetaZ :
  ∀ {Mode gaussian rich step} →
  RichBrillouinFiniteModeDecomposition
    {Mode = Mode} gaussian rich step →
  Bishop._≃_
    (Rich.coefficient rich step)
    (UV.embed (Local.betaZ gaussian))
richCoefficientSameFiniteModeBetaZ
    {gaussian = gaussian} {rich = rich} {step = step} dataSet =
  BishopP.≃-trans
    (equalityAsBishopSetoid
      (Rich.coefficientDefinition rich step))
    (BishopP.≃-trans
      (richAddIsBishopAdd dataSet
        (Rich.scalarIntegral rich step)
        (Rich.regularRemainder rich step))
      (BishopP.≃-trans
        (BishopP.+-cong
          (shellSameFiniteUniversalTerm dataSet)
          (regularMatchingSameFiniteEpsilon dataSet))
        (BishopP.≃-trans
          (BishopP.≃-symm
            (Carrier.bishopEmbedAdd
              (Local.oneLoopSU2Factor * Local.ell gaussian)
              (Local.epsilon gaussian)))
          (subst
            (λ selected →
              Bishop._≃_
                (UV.embed
                  (Local.oneLoopSU2Factor * Local.ell gaussian
                    + Local.epsilon gaussian))
                (UV.embed selected))
            (Local.betaZExact gaussian)
            BishopP.≃-refl))))

fromFiniteEllAndRegularMatching :
  ∀ {Mode gaussian rich running step}
    (normalization :
      RichNorm.CanonicalBishopRichBrillouinUVEdgeNormalization rich running)
    (ellNormalization :
      FiniteEll.FiniteEllBishopShellNormalization gaussian running step)
    (richAdd : ∀ left right →
      Bishop._≃_
        (Rich.add rich left right)
        (Bishop._+_ left right))
    (regularMatching :
      Bishop._≃_
        (Rich.regularRemainder rich step)
        (UV.embed (Local.epsilon gaussian))) →
  RichBrillouinFiniteModeDecomposition gaussian rich step
fromFiniteEllAndRegularMatching {step = step} normalization ellNormalization richAdd regularMatching = record
  { RichBrillouinFiniteModeDecomposition.richAddIsBishopAdd = richAdd
  ; RichBrillouinFiniteModeDecomposition.shellSameFiniteUniversalTerm =
      BishopP.≃-trans
        (RichNorm.richScalarIntegralAtEdgeUsesSuccessorCanonicalNode
          normalization step)
        (BishopP.≃-symm
          (FiniteEll.embeddedFiniteUniversalTermIsCanonicalShellFormula
            ellNormalization))
  ; RichBrillouinFiniteModeDecomposition.regularMatchingSameFiniteEpsilon =
      regularMatching
  }
richBrillouinFiniteModeDecompositionCompilerLevel : ProofLevel
richBrillouinFiniteModeDecompositionCompilerLevel = machineChecked

richShellFiniteUniversalSameObjectLevel : ProofLevel
richShellFiniteUniversalSameObjectLevel = conditional

richRegularMatchingFiniteEpsilonSameObjectLevel : ProofLevel
richRegularMatchingFiniteEpsilonSameObjectLevel = conditional
