module DASHI.Finance.TrumpFamilyTradeEvidenceValidation where

import DASHI.Finance.TrumpFamilyTradeSourceAtlasExact as Atlas
import DASHI.Finance.TrumpFamilyTradePrimarySourceExtensionExact as Primary
import DASHI.Finance.TrumpFamilyExternalCounterpartyEvidenceExact as Counterparty
import DASHI.Finance.TrumpFamilyTradePNFBridgeExact as PNF
import DASHI.GameTheory.SourceConditionedMarketInformationExact as Information
import DASHI.Finance.TrumpFamilyTradeGameTheoryBridgeExact as GameBridge
import DASHI.Finance.TrumpFamilyTradeAcquisitionFrontierExact as Acquisition

sourceBoundary : Atlas.TrumpFamilyTradeSourceBoundary
sourceBoundary = Atlas.canonicalTrumpFamilyTradeSourceBoundary

primaryBoundary : Primary.TrumpFamilyPrimarySourceExtensionBoundary
primaryBoundary = Primary.canonicalTrumpFamilyPrimarySourceExtensionBoundary

counterpartyBoundary : Counterparty.TrumpFamilyExternalCounterpartyBoundary
counterpartyBoundary = Counterparty.canonicalTrumpFamilyExternalCounterpartyBoundary

pnfBoundary : PNF.TrumpFamilyTradePNFBoundary
pnfBoundary = PNF.canonicalTrumpFamilyTradePNFBoundary

informationBoundary : Information.SourceConditionedMarketInformationBoundary
informationBoundary = Information.canonicalSourceConditionedMarketInformationBoundary

gameBoundary : GameBridge.TrumpFamilyTradeGameTheoryBoundary
gameBoundary = GameBridge.canonicalTrumpFamilyTradeGameTheoryBoundary

acquisitionBoundary : Acquisition.TrumpFamilyTradeAcquisitionBoundary
acquisitionBoundary = Acquisition.canonicalTrumpFamilyTradeAcquisitionBoundary
