module DASHI.Culture.CohnInstitutionalExpandedCandidateConsumerReuseRegression where

open import DASHI.Core.Prelude
open import Agda.Builtin.Bool using (true; false)

import DASHI.Culture.CohnInstitutionalExpandedCandidateConsumerReuseExact as Reuse

structuralExclusionHasNeighbour :
  Reuse.structuralEpistemicExclusionStatus Reuse.canonicalExpandedConsumerReuse ≡ Reuse.existingNeighbourConsumer
structuralExclusionHasNeighbour = refl

epistemicLabourHasNeighbour :
  Reuse.epistemicLabourStatus Reuse.canonicalExpandedConsumerReuse ≡ Reuse.existingNeighbourConsumer
epistemicLabourHasNeighbour = refl

participationPowerHasNeighbour :
  Reuse.participationPowerStatus Reuse.canonicalExpandedConsumerReuse ≡ Reuse.existingNeighbourConsumer
participationPowerHasNeighbour = refl

internalExclusionHasNeighbour :
  Reuse.internalExclusionStatus Reuse.canonicalExpandedConsumerReuse ≡ Reuse.existingNeighbourConsumer
internalExclusionHasNeighbour = refl

outsiderWithinHasNeighbour :
  Reuse.outsiderWithinStandpointStatus Reuse.canonicalExpandedConsumerReuse ≡ Reuse.existingNeighbourConsumer
outsiderWithinHasNeighbour = refl

epistemicActivismHasExactApplicationOwner :
  Reuse.epistemicActivismStatus Reuse.canonicalExpandedConsumerReuse ≡ Reuse.exactCanonicalOwner
epistemicActivismHasExactApplicationOwner = refl

relationalResearchBurdenHasNeighbour :
  Reuse.relationalResearchBurdenStatus Reuse.canonicalExpandedConsumerReuse ≡ Reuse.existingNeighbourConsumer
relationalResearchBurdenHasNeighbour = refl

governanceHasExactOwner :
  Reuse.governancePermissionStatus Reuse.canonicalExpandedConsumerReuse ≡ Reuse.exactCanonicalOwner
governanceHasExactOwner = refl

sovereigntyHasExactOwner :
  Reuse.sovereigntyStatus Reuse.canonicalExpandedConsumerReuse ≡ Reuse.exactCanonicalOwner
sovereigntyHasExactOwner = refl

neighbourDoesNotCreateIdentity :
  Reuse.neighbouringConsumerDefinitionallyEqualsSourceCoordinate Reuse.canonicalExpandedConsumerReuseBoundary ≡ false
neighbourDoesNotCreateIdentity = refl

genericBurdenDoesNotBecomeEpistemicLabour :
  Reuse.genericBurdenGeometryEqualsEpistemicLabour Reuse.canonicalExpandedConsumerReuseBoundary ≡ false
genericBurdenDoesNotBecomeEpistemicLabour = refl

genericBurdenDoesNotBecomeIndigenousResearchEthics :
  Reuse.genericBurdenGeometryEqualsIndigenousRelationalEthics Reuse.canonicalExpandedConsumerReuseBoundary ≡ false
genericBurdenDoesNotBecomeIndigenousResearchEthics = refl
