module DASHI.Culture.MissingDeceasedTwentyScientistRound72AmyRichardPOAMSCandidateWeldExact where

open import DASHI.Core.Prelude
open import Agda.Builtin.Bool using (Bool; false; true)
open import Agda.Builtin.Nat using (Nat)
open import Agda.Builtin.String using (String)

import DASHI.Core.AttributedSourceCore as Attribution
import DASHI.Culture.MissingDeceasedTwentyScientistRound28AmyNASACandidateWeldExact as R28
import DASHI.Culture.MissingDeceasedTwentyScientistRound29AmyRichardReferentNonFactorabilityExact as R29
import DASHI.Culture.MissingDeceasedTwentyScientistRound30AmyArchivedStatementAcquisitionExact as R30

record AmyReferentCandidateReceipt : Set where
  constructor amy-referent-candidate-receipt
  field
    teamCarrier : String
    nasaCarrier : String
    archivedStatementCarrier : String
    candidatePerson : String
    compatibility : String
    exactIdentityPaid : Bool
    boundary : String

open AmyReferentCandidateReceipt public

hal5TeamSource : Attribution.AttributedSource
hal5TeamSource = Attribution.mkNoDOISource
  "Amy Eskridge / The Institute for Exotic Science"
  "A Historical Perspective on Anti-Gravity Technology"
  "HAL5 December 2018 presentation deck"
  "2018"
  "https://www.hal5.org/PDF/HAL5-Dec2018-Talk-AntiGravity.pdf"
  Attribution.institutionalSource
  "Pays that Richard Eskridge was presented on Amy Eskridge's team surface as Professor Emeritus / co-founder and retired NASA engineer/scientist; does not identify the later NASA-review paper."
  Attribution.publicAttribution

poamsNTRSSource : Attribution.AttributedSource
poamsNTRSSource = Attribution.mkNoDOISource
  "R.H. Eskridge; M.A. Nelson; M.P. Schoenfeld"
  "A Study of the Pope-Osborne Angular Momentum Synthesis Theory (POAMS) Including a Mathematical Reformulation and Validation Experiment"
  "NASA Technical Reports Server; NASA/TM-20205010911; report M-1531"
  "2021"
  "https://ntrs.nasa.gov/citations/20205010911"
  Attribution.governmentSource
  "Pays an exact NASA MSFC technical memorandum authored by R.H. Eskridge, Nelson and Schoenfeld, under SAA8-1519855, acquired by NTRS on 2020-12-01 and later published in 2021; does not state that this is the paper Amy Eskridge referenced in September 2020."
  Attribution.publicAttribution

amyRichardPOAMSCandidate : AmyReferentCandidateReceipt
amyRichardPOAMSCandidate = amy-referent-candidate-receipt
  "HAL5 Dec-2018 team deck naming Richard Eskridge on Amy's team"
  "NASA NTRS 20205010911 / NASA TM M-1531 authored by R.H. Eskridge at MSFC"
  "September 2020 reproduced Amy statement: foundational work generated by a member of our team while a civil servant at NASA MSFC; paper under NASA review for publication"
  "Richard / R.H. Eskridge"
  "Richard is paid as an Amy-team member and retired NASA engineer/scientist; R.H. Eskridge is paid as an MSFC author on a thematically compatible NASA paper whose NTRS acquisition date follows Amy's statement by roughly two months. These predicates materially strengthen Richard/POAMS as a candidate referent."
  false
  "No acquired carrier explicitly equates the unnamed team member with Richard Eskridge or the unnamed paper with NASA/TM-20205010911. Timing and predicate intersection remain compatibility evidence, not referent identity."

richardOnAmyTeamPaid : Bool
richardOnAmyTeamPaid = true

richardNASAAuthorshipPaid : Bool
richardNASAAuthorshipPaid = true

poamsNASAReviewPublicationCarrierPaid : Bool
poamsNASAReviewPublicationCarrierPaid = true

candidateReferentStrengthened : Bool
candidateReferentStrengthened = true

exactUnnamedTeamMemberIdentityPaid : Bool
exactUnnamedTeamMemberIdentityPaid = false

exactSamePaperIdentityPaid : Bool
exactSamePaperIdentityPaid = false

predicateIntersectionStillDoesNotPayReferentIdentity : Bool
predicateIntersectionStillDoesNotPayReferentIdentity = true

temporalCompatibilityDoesNotPaySamePaper : Bool
temporalCompatibilityDoesNotPaySamePaper = true

similarTechnicalThemeDoesNotPaySameObject : Bool
similarTechnicalThemeDoesNotPaySameObject = true

round72H2PaidCount : Nat
round72H2PaidCount = 0

round72H3PaidCount : Nat
round72H3PaidCount = 0

round72Reading : String
round72Reading = "The Richard Eskridge / POAMS hypothesis is materially stronger as a candidate referent than before: HAL5's 2018 team deck places Richard Eskridge on Amy Eskridge's team and identifies him as a retired NASA engineer/scientist; NASA NTRS 20205010911 is an exact MSFC technical memorandum authored by R.H. Eskridge with an NTRS acquisition date of 2020-12-01; Amy's September 2020 statement referred to foundational work created by an unnamed team member while a NASA MSFC civil servant and to an unnamed paper then under NASA publication review. Those coordinates are compatible and jointly narrow the search. They still do not identify Richard as the unnamed member or POAMS as the unnamed paper. Predicate intersection, thematic fit and timing cannot substitute for an identity-bearing bridge."
