module DASHI.Culture.MissingDeceasedTwentyScientistRoundRobinEverything where

-- Focused aggregate for repeated all-scientist Pareto rounds. Each round keeps
-- the scientific denominator fixed at 11 U.S. + 9 Chinese scientists while
-- allowing source-backed promotion, controls and search residuals to evolve.

import DASHI.Culture.MissingDeceasedTwentyScientistRoundRobinProgressExact
import DASHI.Culture.MissingDeceasedTwentyScientistRound2ProgressExact
import DASHI.Culture.MissingDeceasedTwentyScientistRound3ProgressExact
import DASHI.Culture.MissingDeceasedTwentyScientistRound4ProgressExact
import DASHI.Culture.MissingDeceasedTwentyScientistRound5ScienceProgressExact
import DASHI.Culture.MissingDeceasedTwentyScientistRound6ScienceSuccessionExact
import DASHI.Culture.MissingDeceasedTwentyScientistRound7FiniteWitnessProgressExact
import DASHI.Culture.MissingDeceasedTwentyScientistRound8SourceReplayProgressExact
import DASHI.Culture.MissingDeceasedTwentyScientistRound9ReferenceRuntimeProgressExact
import DASHI.Culture.MissingDeceasedTwentyScientistRound10CompositeTraceProgressExact
import DASHI.Culture.MissingDeceasedTwentyScientistRound11SourceReplayParetoExact
import DASHI.Culture.MissingDeceasedTwentyScientistRound12ScienceImplementationProgressExact
import DASHI.Culture.MissingDeceasedTwentyScientistRound13ReferenceKernelProgressExact
import DASHI.Culture.MissingDeceasedTwentyScientistRound14SourceDataReplayProgressExact
import DASHI.Culture.MissingDeceasedTwentyScientistRound15HiddenProducerProgressExact
import DASHI.Culture.MissingDeceasedTwentyScientistRound16PublicProducerProgressExact
import DASHI.Culture.MissingDeceasedTwentyScientistRound17ProducerExecutionProgressExact
import DASHI.Culture.MissingDeceasedTwentyScientistRound18MaterializationProgressExact
import DASHI.Culture.MissingDeceasedTwentyScientistRound19CrossPollinationParetoExact
import DASHI.Culture.MissingDeceasedTwentyScientistScienceCapabilityBidiExact
import DASHI.Culture.MissingDeceasedTwentyScientistScienceFiniteWitnessBidiExact
import DASHI.Culture.MissingDeceasedTwentyScientistScienceSourceReplayBidiExact
import DASHI.Culture.MissingDeceasedTwentyScientistScienceSourceDataReplayBidiExact
import DASHI.Culture.MissingDeceasedTwentyScientistHiddenProducerBidiExact
import DASHI.Culture.MissingDeceasedTwentyScientistPublicProducerBidiExact
import DASHI.Culture.MissingDeceasedTwentyScientistPublicProducerExecutionBidiExact
import DASHI.Culture.MissingDeceasedTwentyScientistMaterializationBidiExact
import DASHI.Culture.MissingDeceasedTwentyScientistExecutionCrossPollinationBidiExact
import DASHI.Culture.MissingDeceasedTwentyScientistScienceExecutionKernelExact
import DASHI.Culture.MissingDeceasedTwentyScientistScienceReferenceKernelBidiExact
import DASHI.Culture.MissingDeceasedTwentyScientistReferenceKernelExecutionBridgeExact
import DASHI.Culture.MissingDeceasedTwentyScientistEmbodiedTechnologyBidiExact
import DASHI.Culture.MissingDeceasedTwentyScientistEmbodiedReferenceRuntimeBidiExact
import DASHI.Culture.MissingDeceasedTwentyScientistCompositeApplicationProofDebtExact
import DASHI.Culture.MissingDeceasedTwentyScientistCompositeReferenceTraceExact
import DASHI.Culture.MissingDeceasedChineseScienceImplementationEverything
import DASHI.Culture.MissingDeceasedTwentyScientistScienceImplementationCoverageExact

-- Round-12 science-only arithmetic/depth tranche.
import DASHI.Physics.Nuclear.LeBlancFSPICNumericEnvelopeExact
import DASHI.Physics.Materials.RezaBurnResistantAlloyCompositionTradeoffExact
import DASHI.Physics.SpaceWeather.ZhangXiaoxinForecastRecallArithmeticExact

-- Round-14 source-data replay tranche.
import DASHI.Physics.ExoticGravity.NingLiYBCOSourceDataReplayExact
import DASHI.Physics.Materials.ZhouGuangyuanAerogelProcessPropertyDataReplayExact
import DASHI.Physics.Planetary.HicksSmallBodyPhotometryDataReplayExact
import DASHI.Biology.JasonThomasAssayDataReplayExact
import DASHI.Control.ZhangDaibingControlDataReplayExact
import DASHI.GameTheory.FengYangheClassificationDataReplayExact

-- Round-15 hidden-producer acquisition tranche.
import DASHI.Physics.Spectroscopy.MaiwaldActionSpectroscopySupportingInfoExact
import DASHI.Physics.SpaceWeather.ZhangXiaoxinForecastAlgorithmProducerDepthExact
import DASHI.Physics.Aerospace.YanHongThermalFullTextProducerDepthExact
import DASHI.Physics.Materials.FangDainingInverseDesignHiddenProducerDebtExact

-- Round-16 public-producer location tranche.
import DASHI.Physics.SpaceWeather.ZhangXiaoxinForecastPublicProducerExact

-- Round-17 producer-execution readiness tranche.
import DASHI.Physics.SpaceWeather.ZhangXiaoxinForecastProducerExecutionReadinessExact

-- Round-18 local-materialization boundary tranche.
import DASHI.Physics.SpaceWeather.ZhangXiaoxinForecastMaterializationExact
