module DASHI.Culture.MissingDeceasedScientificWorkEverything where

-- Focused aggregate for attribution-safe scientific-work reconstruction,
-- source-exact citation, technical-intersection proof search, independent
-- common-selector/visibility analysis, selector-discrimination search,
-- higher-order capability synthesis, disruption-benefit evidence testing,
-- actor benefit/visibility/effect intersection, and matched disruption-impact
-- controls.
-- Kept separate from AmyEskridgeEvidenceEverything because Amy Eskridge is not
-- explicitly named in the 20 April 2026 House Oversight letter formalised here.

import DASHI.Core.ScientificWorkAttributionExact
import DASHI.Core.ScientificSourceCitationExact
import DASHI.Core.TechnicalDependencyHypergraphExact
import DASHI.Core.CommonSelectorVisibilityHyperfabricExact
import DASHI.Core.SelectorDiscriminationSearchExact
import DASHI.Core.CapabilitySynthesisHypergraphExact
import DASHI.Core.DisruptionBenefitHypothesisExact
import DASHI.Core.ActorBenefitVisibilityDisruptionIntersectionExact
import DASHI.Core.CounterfactualDisruptionImpactExact
import DASHI.Culture.MissingDeceasedScientistWorkAttributionExact
import DASHI.Culture.MissingDeceasedScientificWorkCrossPollinationExact
import DASHI.Culture.MissingDeceasedScientificWorkSourceRegistryExact
import DASHI.Culture.MissingDeceasedScientificWorkSourceRegistryExtendedExact
import DASHI.Culture.MissingDeceasedTechnicalDependencyHypergraphExact
import DASHI.Culture.MissingDeceasedTechnicalIntersectionAcquisitionExact
import DASHI.Culture.MissingDeceasedCommonSelectorVisibilityExact
import DASHI.Culture.MissingDeceasedSelectorAcquisitionExact
import DASHI.Culture.MissingDeceasedSelectorDiscriminationFrontierExact
import DASHI.Culture.MissingDeceasedCapabilitySynthesisExact
import DASHI.Culture.MissingDeceasedDisruptionBenefitEvidenceExact
import DASHI.Culture.MissingDeceasedDisruptionBenefitAcquisitionExact
import DASHI.Culture.MissingDeceasedActorIntersectionFrontierExact
import DASHI.Culture.MissingDeceasedCounterfactualDisruptionImpactExact
import DASHI.Culture.HouseOversightScientistRosterScopeExact
