module DASHI.Culture.MissingDeceasedScientificWorkCustodyEverything where

-- Thin continuation aggregate over the canonical memorial-science/investigation
-- surface. This tranche refines the existing critical-knowledge,
-- externalisation-depth and counterfactual-disruption owners with custody,
-- event-time possession, reconstruction-cost, platform redundancy,
-- institutional continuity and winding-up acquisition receipts.

import DASHI.Culture.MissingDeceasedScientificWorkEverything
import DASHI.Core.CustodyCriticalityDisruptionBridgeExact
import DASHI.Core.CapabilityReconstructionCostBidiExact
import DASHI.Core.ApplicationCapabilityCustodyBidiExact
import DASHI.Core.EventTimeOperationalPossessionEvidenceExact
import DASHI.Culture.MissingDeceasedReconstructionCostMatrixExact
import DASHI.Culture.AmyEskridgeCorporateCustodySurfaceExact
import DASHI.Culture.AmyEskridgeInstituteEntityContinuityExact
import DASHI.Culture.AmyEskridgeInstitutePostDeathContinuityExact
import DASHI.Culture.AmyEskridgeHoloChronPostDeathDissolutionFrontierExact
import DASHI.Culture.MaiwaldCrossInstitutionalCarrierContinuityExact
import DASHI.Culture.MaiwaldParallelPlatformRedundancyExact
import DASHI.Culture.MaiwaldMissionSideInstitutionalContinuityExact
import DASHI.Culture.McCaslandPostAcquisitionContinuityFrontierExact
import DASHI.Culture.McCaslandDraper2025InstitutionalContinuityExact
import DASHI.Culture.HicksEventTimeRoleDiscontinuityExact
import DASHI.Culture.MissingDeceasedCustodyEventTimeMatrixExact
