module DASHI.Physics.Moonshine.Reports.WaveRegime where

-- Short-path compatibility layer for the current wave-regime moonshine reports.

open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.Summary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.CoherenceSummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.StabilitySummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.CompletenessSummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.SoundnessSummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.ConsistencySummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.InvarianceSummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.RobustnessSummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.ResilienceSummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.HarmonySummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.BalanceSummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.SymmetrySummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.ContinuitySummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.CompatibilitySummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.ConcordanceSummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.CohesionSummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.EquilibriumSummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.ConvergenceSummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.AlignmentSummary public

