module DASHI.Physics.Closure.NSPairIncidenceKernelProgram where

open import DASHI.Analysis.WeightedKernelSchurTest public
open import DASHI.Analysis.FiniteWeightedKernelSums public
open import DASHI.Physics.Closure.NSIntegerFourierLattice public
open import DASHI.Physics.Closure.NSWall1CanonicalModePacket public
open import DASHI.Physics.Closure.NSWall1ExactEvaluationCarrier public
open import DASHI.Physics.Closure.NSWall1CanonicalPacketEvaluation public
open import DASHI.Physics.Closure.NSWall1CanonicalAmplitudeProfile public
open import DASHI.Physics.Closure.NSWall1CanonicalPolarizations public
open import DASHI.Physics.Closure.NSDivergenceFreePolarizationBasis public
open import DASHI.Physics.Closure.NSPairIncidenceKernel public
open import DASHI.Physics.Closure.NSFourierBiotSavartTriadKernel public
open import DASHI.Physics.Closure.NSWall1FourierShellInstance public
open import DASHI.Physics.Closure.NSWall1PolarizationInstantiation public
open import DASHI.Physics.Closure.NSWall1UniformWeightedSchur public
open import DASHI.Physics.Closure.NSPairIncidenceSchurBridge public
open import DASHI.Physics.Closure.NSWeightedShellTransferBridge public
open import DASHI.Physics.Closure.NSFactorizedSchurFrameGap public
open import DASHI.Physics.Closure.NSCompactGammaOffPacketWall1PairIncidenceBridge public
