{-# OPTIONS --safe #-}
module DASHI.Physics.Closure.NSTriadKNR650PostDerivativeAnalyticWallRound743Exact where

------------------------------------------------------------------------
-- ROUND743 / POST-DERIVATIVE PREFERRED ANALYTIC WALL
--
-- R737-R742 exhaust the literal derivative attack on
--
--   A_N = X_N - 12 Q_{+-,N}.
--
-- What survives:
--
--   W1  cutoff-uniform signed weighted+terminal payment
--
--         W_N(T) + Q_{+-,N}(T) <= B(T).
--
--   W2  equivalently, under the standard R648 physical packet structure,
--
--         integral PacketStrictSurplus_{N,delta}
--           <= integral CombinedResidue_N,
--
--       with delta > 0.
--
-- The R734 augmented-weighted form remains exactly equivalent to W2 and is
-- useful algebraically, but differentiating it does NOT expose an additional
-- input-Laplacian coercive term: the +12W generated by -12 Qdot cancels the
-- W2 right-hand side exactly (R740).
--
-- Therefore the derivative tranche closes representation/plumbing and leaves
-- one genuine signed comparison for W2.  No R406 transport is mandatory.
------------------------------------------------------------------------

open import Agda.Builtin.Bool using (Bool; true; false)
open import Agda.Builtin.Equality using (_≡_; refl)
open import Agda.Builtin.Nat using (Nat; zero; suc)

import DASHI.Physics.Closure.NSTriadKNR650CurrentSharedWeightedWallRound736Exact as R736
import DASHI.Physics.Closure.NSTriadKNR650AugmentedObservableDerivativeRound737Exact as R737
import DASHI.Physics.Closure.NSTriadKNR650AugmentedDerivativeInputLaplacianRound738Exact as R738
import DASHI.Physics.Closure.NSTriadKNR650AugmentedDerivativeCollectedRound739Exact as R739
import DASHI.Physics.Closure.NSTriadKNR650PointwiseW2CancellationRound740Exact as R740
import DASHI.Physics.Closure.NSTriadKNR650PointwiseW2PhysicalPacketCombinedRound741Exact as R741
import DASHI.Physics.Closure.NSTriadKNR650IntegratedW2PhysicalPacketCombinedRound742Exact as R742

data PostDerivativeAnalyticLeaf : Set where
  weightedPlusTerminalPayment : PostDerivativeAnalyticLeaf
  integratedPacketSurplusBelowCombined : PostDerivativeAnalyticLeaf

postDerivativeAnalyticLeafCount : Nat
postDerivativeAnalyticLeafCount = suc (suc zero)

leafClosed : PostDerivativeAnalyticLeaf → Bool
leafClosed weightedPlusTerminalPayment =
  R736.round736WeightedPlusEndpointClosed
leafClosed integratedPacketSurplusBelowCombined =
  R742.round742IntegratedPacketCombinedPaymentClosed

round743ExactlyTwoPreferredAnalyticLeaves : Bool
round743ExactlyTwoPreferredAnalyticLeaves = true

round743LiteralAugmentedDerivativeClosed : Bool
round743LiteralAugmentedDerivativeClosed =
  R737.round737LiteralAugmentedObservableDerivativeClosed

round743GlobalWeightedInputLaplacianSubstitutionClosed : Bool
round743GlobalWeightedInputLaplacianSubstitutionClosed =
  R738.round738GlobalWeightedIsInputLaplacianClosed

round743CollectedDerivativeExact : Bool
round743CollectedDerivativeExact =
  R739.round739AugmentedDerivativeCollectedExactly

round743InputLaplacianSurvivesW2Cancellation : Bool
round743InputLaplacianSurvivesW2Cancellation =
  R740.round740InputLaplacianSurvivesAfterMovingW2RHS

round743PointwiseW2PacketCombinedNormalFormAvailable : Bool
round743PointwiseW2PacketCombinedNormalFormAvailable =
  R741.round741PointwiseW2IsPhysicalPacketBelowCombined

round743IntegratedW2PacketCombinedNormalFormAvailable : Bool
round743IntegratedW2PacketCombinedNormalFormAvailable =
  R742.round742OriginalIntegratedW2IsPacketSurplusBelowCombined

round743PointwiseStrengtheningMandatory : Bool
round743PointwiseStrengtheningMandatory = false

round743R406TransportMandatory : Bool
round743R406TransportMandatory =
  R742.round742R406TransportRequired

round743WeightedPlusTerminalPaymentClosed : Bool
round743WeightedPlusTerminalPaymentClosed =
  R736.round736WeightedPlusEndpointClosed

round743IntegratedPacketCombinedPaymentClosed : Bool
round743IntegratedPacketCombinedPaymentClosed =
  R742.round742IntegratedPacketCombinedPaymentClosed

round743IntroducesEstimate : Bool
round743IntroducesEstimate = false

round743ClayPromotion : Bool
round743ClayPromotion = false

round743ExactlyTwoPreferredAnalyticLeavesIsTrue :
  round743ExactlyTwoPreferredAnalyticLeaves ≡ true
round743ExactlyTwoPreferredAnalyticLeavesIsTrue = refl

round743LiteralAugmentedDerivativeClosedIsTrue :
  round743LiteralAugmentedDerivativeClosed ≡ true
round743LiteralAugmentedDerivativeClosedIsTrue =
  R737.round737LiteralAugmentedObservableDerivativeClosedIsTrue

round743GlobalWeightedInputLaplacianSubstitutionClosedIsTrue :
  round743GlobalWeightedInputLaplacianSubstitutionClosed ≡ true
round743GlobalWeightedInputLaplacianSubstitutionClosedIsTrue =
  R738.round738GlobalWeightedIsInputLaplacianClosedIsTrue

round743CollectedDerivativeExactIsTrue :
  round743CollectedDerivativeExact ≡ true
round743CollectedDerivativeExactIsTrue =
  R739.round739AugmentedDerivativeCollectedExactlyIsTrue

round743InputLaplacianSurvivesW2CancellationIsFalse :
  round743InputLaplacianSurvivesW2Cancellation ≡ false
round743InputLaplacianSurvivesW2CancellationIsFalse =
  R740.round740InputLaplacianSurvivesAfterMovingW2RHSIsFalse

round743PointwiseW2PacketCombinedNormalFormAvailableIsTrue :
  round743PointwiseW2PacketCombinedNormalFormAvailable ≡ true
round743PointwiseW2PacketCombinedNormalFormAvailableIsTrue =
  R741.round741PointwiseW2IsPhysicalPacketBelowCombinedIsTrue

round743IntegratedW2PacketCombinedNormalFormAvailableIsTrue :
  round743IntegratedW2PacketCombinedNormalFormAvailable ≡ true
round743IntegratedW2PacketCombinedNormalFormAvailableIsTrue =
  R742.round742OriginalIntegratedW2IsPacketSurplusBelowCombinedIsTrue

round743PointwiseStrengtheningMandatoryIsFalse :
  round743PointwiseStrengtheningMandatory ≡ false
round743PointwiseStrengtheningMandatoryIsFalse = refl

round743R406TransportMandatoryIsFalse :
  round743R406TransportMandatory ≡ false
round743R406TransportMandatoryIsFalse =
  R742.round742R406TransportRequiredIsFalse

round743WeightedPlusTerminalPaymentClosedIsFalse :
  round743WeightedPlusTerminalPaymentClosed ≡ false
round743WeightedPlusTerminalPaymentClosedIsFalse =
  R736.round736WeightedPlusEndpointClosedIsFalse

round743IntegratedPacketCombinedPaymentClosedIsFalse :
  round743IntegratedPacketCombinedPaymentClosed ≡ false
round743IntegratedPacketCombinedPaymentClosedIsFalse =
  R742.round742IntegratedPacketCombinedPaymentClosedIsFalse

round743IntroducesEstimateIsFalse :
  round743IntroducesEstimate ≡ false
round743IntroducesEstimateIsFalse = refl

round743ClayPromotionIsFalse :
  round743ClayPromotion ≡ false
round743ClayPromotionIsFalse = refl
