module DASHI.Physics.Closure.NSTriadKNR571PairedSecondMomentPublicationAggregate where

-- Single focused check surface for PR #920.
-- Imports the complete publication-facing local splice and its regressions;
-- no additional theorem authority is introduced here.

import DASHI.Physics.Closure.NSTriadKNR571HomochiralRadialIncrementSpecializationExact
import DASHI.Physics.Closure.NSTriadKNR571HomochiralPairedSecondMomentRealizationExact
import DASHI.Physics.Closure.NSTriadKNR571OppositeRound27PairedTaylorExact
import DASHI.Physics.Closure.NSTriadKNLuoPairedSecondOrderAbsoluteMagnitudeBridgeExact
import DASHI.Physics.Closure.NSTriadKNR571CanonicalSecondMomentMagnitudeAdapterExact
import DASHI.Physics.Closure.NSTriadKNR571HomochiralPairedSecondMomentRealizationRegression
import DASHI.Physics.Closure.NSTriadKNR571HomochiralPairedSecondMomentRealizationValidation
import DASHI.Physics.Closure.NSTriadKNR571SecondOrderAbsoluteMagnitudeRegression
import DASHI.Physics.Closure.NSTriadKNR571CanonicalSecondMomentMagnitudeAdapterRegression
