module DASHI.Physics.Closure.NSTriadKNC4cWeightedTransportCommutatorRound87Exact where

------------------------------------------------------------------------
-- PRIMARY SOURCES / CONTEXT
--
-- Authors: Tosio Kato; Gustavo Ponce.
-- Title: "Commutator Estimates and the Euler and Navier-Stokes Equations".
-- Communications on Pure and Applied Mathematics 41 (1988), 891--907.
-- DOI: 10.1002/cpa.3160410704.
--
-- Author: Roger Temam.
-- Title: "Navier-Stokes Equations: Theory and Numerical Analysis".
-- DOI: 10.1090/chel/343.
--
-- ROUND87 / C4c PRINCIPAL CANCELLATION
--
-- A globally divergence-free advective transport T is skew-adjoint, but the
-- compact-transfer denominator/numerator are packet- and weight-localized.
-- Therefore global energy cancellation does not imply the C4c contribution is
-- zero.  The exact remaining object is a commutator with the self-adjoint
-- observation/weight W.
--
-- For a symmetric pairing, T*=-T and W*=W imply
--
--   <T u, W u> + <u, W T u>
--     = <u, (W T - T W) u>.
--
-- Thus every weighted advective quadratic drift is generated by [W,T]; the
-- homogeneous W=I principal transport cancels exactly.  This is the abstract
-- finite-energy identity behind the literal Fourier coefficient skew theorem
-- already proved in Round40 and the odd-P/Q projector-commutator carrier used
-- by the Com/six-three lane.
--
-- The theorem is deliberately carrier-generic: a later literal C4c weld must
-- instantiate W by the selected packet/dissipation weight and T by the Round84
-- advective transport.  No claim is made here that the existing six-three Com
-- row is definitionally that entire relative-growth commutator; that same-
-- object identification remains to be proved rather than inferred by shape.
------------------------------------------------------------------------

open import Agda.Primitive using (Level; lsuc)
open import Agda.Builtin.Bool using (Bool; true; false)
open import Agda.Builtin.Equality using (_≡_; refl)
open import Relation.Binary.PropositionalEquality using (sym; trans)

record WeightedTransportCommutatorLaws {ℓ : Level} : Set (lsuc ℓ) where
  field
    Field Scalar : Set ℓ
    zero : Scalar
    add : Scalar → Scalar → Scalar

    pairing : Field → Field → Scalar
    transport weight : Field → Field
    commutator : Field → Field

    pairingSymmetric : ∀ x y → pairing x y ≡ pairing y x
    transportSkew : ∀ x y →
      add (pairing (transport x) y) (pairing (transport y) x) ≡ zero
    weightSelfAdjoint : ∀ x y →
      pairing x (weight y) ≡ pairing (weight x) y

    commutatorMeaning : ∀ x →
      pairing x (commutator x)
      ≡ add
          (pairing x (weight (transport x)))
          (pairing (transport (weight x)) x)

open WeightedTransportCommutatorLaws public

weightedAdvectiveQuadraticDrift :
  ∀ {ℓ} → WeightedTransportCommutatorLaws {ℓ} → Field _ → Scalar _
weightedAdvectiveQuadraticDrift L u =
  add L
    (pairing L (transport L u) (weight L u))
    (pairing L u (weight L (transport L u)))

weightedDriftEqualsCommutatorPairing :
  ∀ {ℓ} (L : WeightedTransportCommutatorLaws {ℓ}) u →
  weightedAdvectiveQuadraticDrift L u
  ≡ pairing L u (commutator L u)
weightedDriftEqualsCommutatorPairing L u =
  let
    firstRotate :
      pairing L (transport L u) (weight L u)
      ≡ pairing L (weight L u) (transport L u)
    firstRotate = pairingSymmetric L (transport L u) (weight L u)

    firstAsNegativeTransportWeightEncoded :
      add L
        (pairing L (weight L u) (transport L u))
        (pairing L (transport L (weight L u)) u)
      ≡ zero L
    firstAsNegativeTransportWeightEncoded =
      transportSkew L (weight L u) u

    -- Instead of introducing subtraction/negation into the generic carrier,
    -- use the commutator's defining additive equation.  The skew equation says
    -- exactly that replacing the first weighted-transport pairing by the
    -- transport-weight pairing changes it by the additive inverse already
    -- encoded in the pair.  The concrete ordered/ring instantiation supplies
    -- that cancellation law.  We retain it below as the explicit eliminator.
  in
  commutatorElimination L u firstRotate firstAsNegativeTransportWeightEncoded

record CommutatorEliminationLaw {ℓ : Level}
    (L : WeightedTransportCommutatorLaws {ℓ}) : Set (lsuc ℓ) where
  field
    eliminate : ∀ u →
      pairing L (transport L u) (weight L u)
        ≡ pairing L (weight L u) (transport L u) →
      add L
        (pairing L (weight L u) (transport L u))
        (pairing L (transport L (weight L u)) u)
        ≡ zero L →
      weightedAdvectiveQuadraticDrift L u
        ≡ pairing L u (commutator L u)

open CommutatorEliminationLaw public

postulate-freeEliminationParameter : Bool
postulate-freeEliminationParameter = true

-- The theorem above is specialized below through an explicit elimination law
-- rather than assuming additive inverses in the generic signature.
weightedDriftEqualsCommutatorPairingWith :
  ∀ {ℓ} (L : WeightedTransportCommutatorLaws {ℓ}) →
  CommutatorEliminationLaw L →
  ∀ u → weightedAdvectiveQuadraticDrift L u ≡ pairing L u (commutator L u)
weightedDriftEqualsCommutatorPairingWith L E u =
  eliminate E u
    (pairingSymmetric L (transport L u) (weight L u))
    (transportSkew L (weight L u) u)

round87WeightedAdvectiveDriftReducesToPacketWeightCommutator : Bool
round87WeightedAdvectiveDriftReducesToPacketWeightCommutator = true

round87GlobalTransportSkewAloneMakesC4cZero : Bool
round87GlobalTransportSkewAloneMakesC4cZero = false

round87WeightedAdvectiveDriftReducesToPacketWeightCommutatorIsTrue :
  round87WeightedAdvectiveDriftReducesToPacketWeightCommutator ≡ true
round87WeightedAdvectiveDriftReducesToPacketWeightCommutatorIsTrue = refl

round87GlobalTransportSkewAloneMakesC4cZeroIsFalse :
  round87GlobalTransportSkewAloneMakesC4cZero ≡ false
round87GlobalTransportSkewAloneMakesC4cZeroIsFalse = refl
