module DASHI.Physics.Closure.YMActualPolymerActivityDefinitionReceipt where

open import Agda.Primitive using (Setω)
open import Agda.Builtin.Bool using (Bool; false; true)
open import Agda.Builtin.Equality using (_≡_; refl)
open import Agda.Builtin.Nat using (Nat)
open import Agda.Builtin.String using (String)
open import Data.Empty using (⊥)
open import Data.List.Base using (List; _∷_; [])

import DASHI.Physics.Closure.YMKPActivityRatioMarginReceipt as Rho
import DASHI.Physics.Closure.YMKPAbsorptionMarginThresholdReceipt as Margin

------------------------------------------------------------------------
-- Actual YM polymer activity definition frontier.
--
-- This is YM5 in the Paper 3 roadmap.  It records the precise replacement
-- for the toy rho profile: rho must be computed from same-prime Wilson
-- polymer activities z(Gamma) generated by the carrier action, for polymers
-- containing a fixed edge in the p=7 Bruhat-Tits tree.  This file does not
-- provide that analytic activity; it prevents the toy rho from being
-- consumed as a KP theorem.

data YMActualActivityStatus : Set where
  actualPolymerActivityFrontierRecorded :
    YMActualActivityStatus

data YMRhoSource : Set where
  toyDepthProfile :
    YMRhoSource

  actualWilsonPolymerActivity :
    YMRhoSource

data YMCarrierWilsonActivityInput : Set where
  samePrimeP7EdgeRootedWilsonActivity :
    YMCarrierWilsonActivityInput

data YMActualActivityRequiredField : Set where
  fixedRootEdgeE0 :
    YMActualActivityRequiredField

  samePrimePolymerGammaContainingE0 :
    YMActualActivityRequiredField

  carrierWilsonActionOnGamma :
    YMActualActivityRequiredField

  activityZGammaAbsoluteValue :
    YMActualActivityRequiredField

  localKPSumOverGamma :
    YMActualActivityRequiredField

canonicalYMActualActivityRequiredFields :
  List YMActualActivityRequiredField
canonicalYMActualActivityRequiredFields =
  fixedRootEdgeE0
  ∷ samePrimePolymerGammaContainingE0
  ∷ carrierWilsonActionOnGamma
  ∷ activityZGammaAbsoluteValue
  ∷ localKPSumOverGamma
  ∷ []

data YMActualActivityOpenObligation : Set where
  defineCarrierWilsonActionForSamePrimePolymers :
    YMActualActivityOpenObligation

  computeAbsolutePolymerActivities :
    YMActualActivityOpenObligation

  proveLocalKPSumBelowStrictThreshold :
    YMActualActivityOpenObligation

  feedActualRhoIntoBalabanInduction :
    YMActualActivityOpenObligation

canonicalYMActualActivityOpenObligations :
  List YMActualActivityOpenObligation
canonicalYMActualActivityOpenObligations =
  defineCarrierWilsonActionForSamePrimePolymers
  ∷ computeAbsolutePolymerActivities
  ∷ proveLocalKPSumBelowStrictThreshold
  ∷ feedActualRhoIntoBalabanInduction
  ∷ []

data YMActualActivityNonClaim : Set where
  noToyRhoAsActualActivity :
    YMActualActivityNonClaim

  noActualKPMarginProof :
    YMActualActivityNonClaim

  noBalabanTransferProof :
    YMActualActivityNonClaim

  noContinuumYangMillsClaim :
    YMActualActivityNonClaim

  noClayYangMillsPromotion :
    YMActualActivityNonClaim

canonicalYMActualActivityNonClaims :
  List YMActualActivityNonClaim
canonicalYMActualActivityNonClaims =
  noToyRhoAsActualActivity
  ∷ noActualKPMarginProof
  ∷ noBalabanTransferProof
  ∷ noContinuumYangMillsClaim
  ∷ noClayYangMillsPromotion
  ∷ []

data YMActualActivityPromotion : Set where

ymActualActivityPromotionImpossibleHere :
  YMActualActivityPromotion →
  ⊥
ymActualActivityPromotionImpossibleHere ()

p7ActivityPrime :
  Nat
p7ActivityPrime =
  7

actualActivitySummary :
  String
actualActivitySummary =
  "YM5: toy rho(k)=1/(k+2) is not the KP input; actual rho must be computed from p=7 same-prime Wilson polymer activities containing a fixed root edge."

record YMActualPolymerActivityDefinitionReceipt : Setω where
  field
    status :
      YMActualActivityStatus

    statusIsCanonical :
      status ≡ actualPolymerActivityFrontierRecorded

    consumedToyRhoReceipt :
      Rho.YMKPActivityRatioMarginReceipt

    consumedToyRhoMarkedDiagnostic :
      Rho.rhoProfileToyDiagnostic consumedToyRhoReceipt ≡ true

    consumedMarginReceipt :
      Margin.YMKPAbsorptionMarginThresholdReceipt

    consumedMarginDoesNotProveActualRho :
      Margin.actualRhoMarginProved consumedMarginReceipt ≡ false

    rejectedRhoSource :
      YMRhoSource

    rejectedRhoSourceIsToy :
      rejectedRhoSource ≡ toyDepthProfile

    requiredRhoSource :
      YMRhoSource

    requiredRhoSourceIsActualWilson :
      requiredRhoSource ≡ actualWilsonPolymerActivity

    activityInput :
      YMCarrierWilsonActivityInput

    activityInputIsP7EdgeRooted :
      activityInput ≡ samePrimeP7EdgeRootedWilsonActivity

    p7PrimeRecorded :
      Nat

    p7PrimeRecordedIsCanonical :
      p7PrimeRecorded ≡ p7ActivityPrime

    requiredFields :
      List YMActualActivityRequiredField

    requiredFieldsAreCanonical :
      requiredFields ≡ canonicalYMActualActivityRequiredFields

    openObligations :
      List YMActualActivityOpenObligation

    openObligationsAreCanonical :
      openObligations ≡ canonicalYMActualActivityOpenObligations

    toyRhoPromotedAsKPProof :
      Bool

    toyRhoPromotedAsKPProofIsFalse :
      toyRhoPromotedAsKPProof ≡ false

    actualPolymerActivitySupplied :
      Bool

    actualPolymerActivitySuppliedIsFalse :
      actualPolymerActivitySupplied ≡ false

    nonClaims :
      List YMActualActivityNonClaim

    nonClaimsAreCanonical :
      nonClaims ≡ canonicalYMActualActivityNonClaims

    continuumYangMillsPromoted :
      Bool

    continuumYangMillsPromotedIsFalse :
      continuumYangMillsPromoted ≡ false

    clayYangMillsPromoted :
      Bool

    clayYangMillsPromotedIsFalse :
      clayYangMillsPromoted ≡ false

    summary :
      String

    summaryIsCanonical :
      summary ≡ actualActivitySummary

open YMActualPolymerActivityDefinitionReceipt public

canonicalYMActualPolymerActivityDefinitionReceipt :
  YMActualPolymerActivityDefinitionReceipt
canonicalYMActualPolymerActivityDefinitionReceipt =
  record
    { status =
        actualPolymerActivityFrontierRecorded
    ; statusIsCanonical =
        refl
    ; consumedToyRhoReceipt =
        Rho.canonicalYMKPActivityRatioMarginReceipt
    ; consumedToyRhoMarkedDiagnostic =
        refl
    ; consumedMarginReceipt =
        Margin.canonicalYMKPAbsorptionMarginThresholdReceipt
    ; consumedMarginDoesNotProveActualRho =
        refl
    ; rejectedRhoSource =
        toyDepthProfile
    ; rejectedRhoSourceIsToy =
        refl
    ; requiredRhoSource =
        actualWilsonPolymerActivity
    ; requiredRhoSourceIsActualWilson =
        refl
    ; activityInput =
        samePrimeP7EdgeRootedWilsonActivity
    ; activityInputIsP7EdgeRooted =
        refl
    ; p7PrimeRecorded =
        p7ActivityPrime
    ; p7PrimeRecordedIsCanonical =
        refl
    ; requiredFields =
        canonicalYMActualActivityRequiredFields
    ; requiredFieldsAreCanonical =
        refl
    ; openObligations =
        canonicalYMActualActivityOpenObligations
    ; openObligationsAreCanonical =
        refl
    ; toyRhoPromotedAsKPProof =
        false
    ; toyRhoPromotedAsKPProofIsFalse =
        refl
    ; actualPolymerActivitySupplied =
        false
    ; actualPolymerActivitySuppliedIsFalse =
        refl
    ; nonClaims =
        canonicalYMActualActivityNonClaims
    ; nonClaimsAreCanonical =
        refl
    ; continuumYangMillsPromoted =
        false
    ; continuumYangMillsPromotedIsFalse =
        refl
    ; clayYangMillsPromoted =
        false
    ; clayYangMillsPromotedIsFalse =
        refl
    ; summary =
        actualActivitySummary
    ; summaryIsCanonical =
        refl
    }
