(module_name) @module_name
(data_name) @data_name
(record_name) @record_name
(field_name) @field_name
(function_name) @function_name
(typed_binding) @typed_binding
(untyped_binding) @untyped_binding
(qid) @reference
(id) @reference
