module DASHI.Mathematics.Arithmetic.RationalSquareClassBitInvariantExact where

------------------------------------------------------------------------
-- BIT-VALUED INVARIANTS OF Q*/Q*^2
--
-- Since RationalSquareEquivalent is generated by multiplication by a nonzero
-- rational square, an invariant descends to square classes exactly when it is
-- unchanged on that generator.  This module proves the descent once and then
-- compiles two calibrated invariants into the existing finite C2 x C2 Kummer
-- seed on rational two-torsion.
--
-- The intended concrete invariants for the chosen torsion dictionary are:
--   first bit  = sign parity of the first square-class coordinate;
--   second bit = parity of v_2 of the second square-class coordinate.
-- Their actual rational arithmetic proofs remain separate.
------------------------------------------------------------------------

open import Agda.Builtin.Bool using (Bool; false; true)
open import Agda.Builtin.Equality using (_≡_; refl)
open import Data.Rational.Base using (_*_)
open import Relation.Binary.PropositionalEquality using (sym; trans)

import DASHI.Mathematics.Arithmetic.EllipticCurveTwoTorsionAndBadPrimeExact as Torsion
import DASHI.Mathematics.Arithmetic.EllipticCurveFiniteTwoDescentSeedExact as Seed
import DASHI.Mathematics.Arithmetic.RationalSquareClassSetoidExact as Square
import DASHI.Mathematics.Arithmetic.EllipticRationalKummerOpenExact as Kummer
import DASHI.Mathematics.Arithmetic.EllipticRationalTwoTorsionKummerExact as TorsionKummer

record SquareClassBitInvariant : Set₁ where
  field
    classify :
      Square.NonzeroRational →
      Torsion.Bit

    squareGeneratorInvariant :
      ∀ {left right}
        (multiplier : Square.NonzeroRational) →
      Square.value right
      ≡
      (Square.value left * Square.value multiplier)
        * Square.value multiplier →
      classify left ≡ classify right

open SquareClassBitInvariant public

squareEquivalentPreservesInvariant :
  (invariant : SquareClassBitInvariant) →
  ∀ {left right} →
  Square.RationalSquareEquivalent left right →
  classify invariant left ≡ classify invariant right
squareEquivalentPreservesInvariant invariant
    (Square.square-refl value) =
  refl
squareEquivalentPreservesInvariant invariant
    (Square.square-generator multiplier equation) =
  squareGeneratorInvariant invariant multiplier equation
squareEquivalentPreservesInvariant invariant
    (Square.square-sym equivalence) =
  sym
    (squareEquivalentPreservesInvariant
      invariant equivalence)
squareEquivalentPreservesInvariant invariant
    (Square.square-trans firstSecond secondThird) =
  trans
    (squareEquivalentPreservesInvariant
      invariant firstSecond)
    (squareEquivalentPreservesInvariant
      invariant secondThird)

record SquareClassPairBitProjection : Set₁ where
  field
    firstInvariant :
      SquareClassBitInvariant

    secondInvariant :
      SquareClassBitInvariant

open SquareClassPairBitProjection public

projectPair :
  SquareClassPairBitProjection →
  Kummer.RationalSquareClassPairRepresentative →
  Seed.SquareClassPair
projectPair projection pair =
  Seed.squareClassPair
    (classify
      (firstInvariant projection)
      (Kummer.first pair))
    (classify
      (secondInvariant projection)
      (Kummer.second pair))

pairEquivalentPreservesProjection :
  (projection : SquareClassPairBitProjection) →
  ∀ {left right} →
  Kummer.RationalSquareClassPairEquivalent left right →
  projectPair projection left
  ≡ projectPair projection right
pairEquivalentPreservesProjection projection
    (Kummer.pair-equivalent firstEq secondEq)
    with squareEquivalentPreservesInvariant
      (firstInvariant projection)
      firstEq
       | squareEquivalentPreservesInvariant
          (secondInvariant projection)
          secondEq
... | refl | refl = refl

record TorsionInvariantCalibration
    (projection : SquareClassPairBitProjection) : Set where
  field
    infinityExact :
      projectPair projection
        (TorsionKummer.torsionKummerRepresentative
          Torsion.pointAtInfinityCode)
      ≡ Seed.finiteKummerMap
          Torsion.pointAtInfinityCode

    zeroExact :
      projectPair projection
        (TorsionKummer.torsionKummerRepresentative
          Torsion.pointZeroCode)
      ≡ Seed.finiteKummerMap
          Torsion.pointZeroCode

    oneExact :
      projectPair projection
        (TorsionKummer.torsionKummerRepresentative
          Torsion.pointOneCode)
      ≡ Seed.finiteKummerMap
          Torsion.pointOneCode

    minusOneExact :
      projectPair projection
        (TorsionKummer.torsionKummerRepresentative
          Torsion.pointMinusOneCode)
      ≡ Seed.finiteKummerMap
          Torsion.pointMinusOneCode

open TorsionInvariantCalibration public

calibratedArithmeticProjectionRecoversFiniteSeed :
  (projection : SquareClassPairBitProjection) →
  TorsionInvariantCalibration projection →
  (code : Torsion.TwoTorsionCode) →
  projectPair projection
    (TorsionKummer.torsionKummerRepresentative code)
  ≡ Seed.finiteKummerMap code
calibratedArithmeticProjectionRecoversFiniteSeed
    projection calibration
    (Torsion.torsionCode Torsion.bit0 Torsion.bit0) =
  infinityExact calibration
calibratedArithmeticProjectionRecoversFiniteSeed
    projection calibration
    (Torsion.torsionCode Torsion.bit1 Torsion.bit0) =
  zeroExact calibration
calibratedArithmeticProjectionRecoversFiniteSeed
    projection calibration
    (Torsion.torsionCode Torsion.bit0 Torsion.bit1) =
  oneExact calibration
calibratedArithmeticProjectionRecoversFiniteSeed
    projection calibration
    (Torsion.torsionCode Torsion.bit1 Torsion.bit1) =
  minusOneExact calibration

record RationalSquareClassBitInvariantBoundary : Set where
  constructor rational-square-class-bit-invariant-boundary
  field
    generatedRelationInvariantCompilerPaid : Bool
    squareEquivalentPreservesInvariantPaid : Bool
    pairProjectionRespectsSquareClassesPaid : Bool
    torsionCalibrationGivesFiniteSeedPaid : Bool
    concreteSignInvariantPaid : Bool
    concreteV2ParityInvariantPaid : Bool
    concreteSignAndV2InvariantsPaid : Bool
    localSquareClassProjectionPaid : Bool
    selmerGroupPaid : Bool
    bsdRankEqualityPaid : Bool

canonicalRationalSquareClassBitInvariantBoundary :
  RationalSquareClassBitInvariantBoundary
canonicalRationalSquareClassBitInvariantBoundary =
  rational-square-class-bit-invariant-boundary
    true true true true false false false false false false
