module DASHI.Mathematics.Arithmetic.RationalSquareClassSetoidExact where

------------------------------------------------------------------------
-- Q* / Q*^2: LITERAL NONZERO-RATIONAL SQUARE-CLASS RELATION
--
-- This constructs the equivalence relation generated by multiplication by a
-- nonzero rational square.  It is intentionally a setoid surface, not a fake
-- quotient type: the repository's non-cubical quotient authority can consume
-- this relation once an actual quotient carrier/eliminator is supplied.
------------------------------------------------------------------------

open import Agda.Primitive using (lzero)
open import Agda.Builtin.Bool using (Bool; false; true)
open import Agda.Builtin.Equality using (_≡_)
open import Data.Rational.Base as ℚ using (ℚ; _*_; NonZero)

import DASHI.Foundations.QuotientSetoidSurface as Quotient

record NonzeroRational : Set where
  constructor nonzero-rational
  field
    value : ℚ
    valueNonzero : NonZero value

open NonzeroRational public

data RationalSquareEquivalent :
    NonzeroRational → NonzeroRational → Set where

  square-refl :
    ∀ value →
    RationalSquareEquivalent value value

  square-generator :
    ∀ {left right} →
    (multiplier : NonzeroRational) →
    value right
      ≡ (value left * value multiplier) * value multiplier →
    RationalSquareEquivalent left right

  square-sym :
    ∀ {left right} →
    RationalSquareEquivalent left right →
    RationalSquareEquivalent right left

  square-trans :
    ∀ {first second third} →
    RationalSquareEquivalent first second →
    RationalSquareEquivalent second third →
    RationalSquareEquivalent first third

rationalSquareEquivalence :
  Quotient.IsEquivalence RationalSquareEquivalent
rationalSquareEquivalence = record
  { Quotient.refl≈ = square-refl
  ; Quotient.sym≈ = square-sym
  ; Quotient.trans≈ = square-trans
  }

rationalSquareClassSetoid :
  Quotient.SetoidSurface lzero lzero
rationalSquareClassSetoid = record
  { Quotient.Carrier = NonzeroRational
  ; Quotient._≈_ = RationalSquareEquivalent
  ; Quotient.isEquivalence = rationalSquareEquivalence
  }

squareMultiplicationGeneratesEquivalence :
  ∀ {left right}
    (multiplier : NonzeroRational) →
  value right
    ≡ (value left * value multiplier) * value multiplier →
  RationalSquareEquivalent left right
squareMultiplicationGeneratesEquivalence =
  square-generator

record RationalSquareClassBoundary : Set where
  constructor rational-square-class-boundary
  field
    nonzeroRationalCarrierPaid : Bool
    multiplicationBySquareGeneratorPaid : Bool
    generatedEquivalencePaid : Bool
    rationalSquareClassSetoidPaid : Bool
    quotientCarrierConstructed : Bool
    explicitEllipticKummerMapPaid : Bool
    localSquareClassRealizationsPaid : Bool
    bsdRankEqualityPaid : Bool

canonicalRationalSquareClassBoundary :
  RationalSquareClassBoundary
canonicalRationalSquareClassBoundary =
  rational-square-class-boundary
    true true true true false false false false
