module DASHI.Physics.Gravity.PenroseGlobalHorismosContradictionExact where

open import Agda.Builtin.Bool using (Bool; false; true)
open import Agda.Builtin.Equality using (_≡_; refl)
open import Agda.Builtin.String using (String)

import DASHI.Physics.Gravity.NullRaychaudhuriSachsFocusingExact as Focusing
import DASHI.Physics.Gravity.Penrose1965NullGeodesicIncompletenessExact as Penrose

------------------------------------------------------------------------
-- Global causal/topological Penrose contradiction boundary.
--
-- This owner starts where local null focusing stops.  It records the standard
-- proof architecture:
--
--   trapped surface + null convergence + assumed future null completeness
--     -> finite generator focusing
--     -> compact future horismos E+(T)
--
-- while global hyperbolicity plus a noncompact Cauchy hypersurface gives
--     -> E+(T) noncompact.
--
-- The compact/noncompact contradiction discharges the reductio assumption of
-- future null completeness.  The continuum causal theorems themselves remain
-- external-authority targets; this file does not rederive Lorentzian causality.
------------------------------------------------------------------------

data GlobalPenroseObject : Set where
  trappedSurfaceObject : GlobalPenroseObject
  futureHorismosObject : GlobalPenroseObject
  achronalBoundaryObject : GlobalPenroseObject
  cauchyHypersurfaceObject : GlobalPenroseObject
  nullGeneratorFamilyObject : GlobalPenroseObject

data GlobalPenroseProperty : Set where
  compactProperty : GlobalPenroseProperty
  nonCompactProperty : GlobalPenroseProperty
  achronalProperty : GlobalPenroseProperty
  globallyHyperbolicProperty : GlobalPenroseProperty
  futureNullCompleteProperty : GlobalPenroseProperty
  futureNullIncompleteProperty : GlobalPenroseProperty

record PenroseGlobalHorismosBoundary : Set where
  field
    futureHorismosOfTrappedSurface : String

    nullCompletenessPlusFocusingMakesFutureHorismosCompact : Bool
    nullCompletenessPlusFocusingMakesFutureHorismosCompactIsTrue :
      nullCompletenessPlusFocusingMakesFutureHorismosCompact ≡ true

    globalHyperbolicityIdentifiesHorismosWithAchronalBoundary : Bool
    globalHyperbolicityIdentifiesHorismosWithAchronalBoundaryIsTrue :
      globalHyperbolicityIdentifiesHorismosWithAchronalBoundary ≡ true

    nonCompactCauchySurfaceForcesFutureHorismosNonCompact : Bool
    nonCompactCauchySurfaceForcesFutureHorismosNonCompactIsTrue :
      nonCompactCauchySurfaceForcesFutureHorismosNonCompact ≡ true

    compactAndNonCompactHorismosContradiction : Bool
    compactAndNonCompactHorismosContradictionIsTrue :
      compactAndNonCompactHorismosContradiction ≡ true

    globalContradictionForcesNullIncompleteness : Bool
    globalContradictionForcesNullIncompletenessIsTrue :
      globalContradictionForcesNullIncompleteness ≡ true

    globalOwnerInternallyReprovesContinuumCausality : Bool
    globalOwnerInternallyReprovesContinuumCausalityIsFalse :
      globalOwnerInternallyReprovesContinuumCausality ≡ false

open PenroseGlobalHorismosBoundary public

canonicalPenroseGlobalHorismosBoundary : PenroseGlobalHorismosBoundary
canonicalPenroseGlobalHorismosBoundary = record
  { futureHorismosOfTrappedSurface =
      "E+(T) = J+(T) minus I+(T), equivalently the future causal boundary generated by null geodesics from the trapped surface T under the declared global-hyperbolic hypotheses"
  ; nullCompletenessPlusFocusingMakesFutureHorismosCompact = true
  ; nullCompletenessPlusFocusingMakesFutureHorismosCompactIsTrue = refl
  ; globalHyperbolicityIdentifiesHorismosWithAchronalBoundary = true
  ; globalHyperbolicityIdentifiesHorismosWithAchronalBoundaryIsTrue = refl
  ; nonCompactCauchySurfaceForcesFutureHorismosNonCompact = true
  ; nonCompactCauchySurfaceForcesFutureHorismosNonCompactIsTrue = refl
  ; compactAndNonCompactHorismosContradiction = true
  ; compactAndNonCompactHorismosContradictionIsTrue = refl
  ; globalContradictionForcesNullIncompleteness = true
  ; globalContradictionForcesNullIncompletenessIsTrue = refl
  ; globalOwnerInternallyReprovesContinuumCausality = false
  ; globalOwnerInternallyReprovesContinuumCausalityIsFalse = refl
  }

------------------------------------------------------------------------
-- WrongType / global-local separation.
------------------------------------------------------------------------

record PenroseGlobalInterpretationBoundary : Set where
  field
    compactHorismosIsNotSpacetimeSingularity : Bool
    compactHorismosIsNotSpacetimeSingularityIsTrue :
      compactHorismosIsNotSpacetimeSingularity ≡ true

    globalHyperbolicityIsNotMerelyNoClosedTimelikeCurves : Bool
    globalHyperbolicityIsNotMerelyNoClosedTimelikeCurvesIsTrue :
      globalHyperbolicityIsNotMerelyNoClosedTimelikeCurves ≡ true

    nonCompactCauchyIsTopologicalGlobalInputNotLocalCurvature : Bool
    nonCompactCauchyIsTopologicalGlobalInputNotLocalCurvatureIsTrue :
      nonCompactCauchyIsTopologicalGlobalInputNotLocalCurvature ≡ true

    localFocalPointAloneCannotPayHorismosNoncompactness : Bool
    localFocalPointAloneCannotPayHorismosNoncompactnessIsTrue :
      localFocalPointAloneCannotPayHorismosNoncompactness ≡ true

    assumedNullCompletenessIsReductioInputNotEmpiricalClaim : Bool
    assumedNullCompletenessIsReductioInputNotEmpiricalClaimIsTrue :
      assumedNullCompletenessIsReductioInputNotEmpiricalClaim ≡ true

open PenroseGlobalInterpretationBoundary public

canonicalPenroseGlobalInterpretationBoundary :
  PenroseGlobalInterpretationBoundary
canonicalPenroseGlobalInterpretationBoundary = record
  { compactHorismosIsNotSpacetimeSingularity = true
  ; compactHorismosIsNotSpacetimeSingularityIsTrue = refl
  ; globalHyperbolicityIsNotMerelyNoClosedTimelikeCurves = true
  ; globalHyperbolicityIsNotMerelyNoClosedTimelikeCurvesIsTrue = refl
  ; nonCompactCauchyIsTopologicalGlobalInputNotLocalCurvature = true
  ; nonCompactCauchyIsTopologicalGlobalInputNotLocalCurvatureIsTrue = refl
  ; localFocalPointAloneCannotPayHorismosNoncompactness = true
  ; localFocalPointAloneCannotPayHorismosNoncompactnessIsTrue = refl
  ; assumedNullCompletenessIsReductioInputNotEmpiricalClaim = true
  ; assumedNullCompletenessIsReductioInputNotEmpiricalClaimIsTrue = refl
  }

------------------------------------------------------------------------
-- Explicit composition seams.
------------------------------------------------------------------------

localFocusingConsumer : Set
localFocusingConsumer = Focusing.NullOpticalFocusingBoundary

penroseTheoremConsumer : Set
penroseTheoremConsumer = Penrose.Penrose1965TheoremBoundary

globalHorismosOwnerPromotesContinuumGR : Bool
globalHorismosOwnerPromotesContinuumGR = false

globalHorismosOwnerPromotesContinuumGRIsFalse :
  globalHorismosOwnerPromotesContinuumGR ≡ false
globalHorismosOwnerPromotesContinuumGRIsFalse = refl
