module DASHI.Physics.Gravity.PenroseGlobalHorismosContradictionExact where

open import Agda.Builtin.Bool using (Bool; false; true)
open import Agda.Builtin.Equality using (_≡_; refl)
open import Agda.Builtin.String using (String)

import DASHI.Physics.Gravity.CausalFutureHorismosNullGeneratorExact as Causal
import DASHI.Physics.Gravity.NullRaychaudhuriSachsFocusingExact as Focusing
import DASHI.Physics.Gravity.PenroseHorismosCompactnessPaymentExact as Compactness
import DASHI.Physics.Gravity.PenroseGlobalCausalityAuthorityExact as Authority
import DASHI.Physics.Gravity.Penrose1965NullGeodesicIncompletenessExact as Penrose

------------------------------------------------------------------------
-- Global causal/topological Penrose contradiction boundary.
--
-- Causal semantics, compactness payment, and exact modern theorem authority
-- are separate consumers. This owner composes them but does not reprove them.
------------------------------------------------------------------------

data GlobalPenroseObject : Set where
  trappedSurfaceObject : GlobalPenroseObject
  futureHorismosObject : GlobalPenroseObject
  achronalBoundaryObject : GlobalPenroseObject
  cauchyHypersurfaceObject : GlobalPenroseObject
  nullGeneratorFamilyObject : GlobalPenroseObject

data GlobalPenroseProperty : Set where
  compactProperty : GlobalPenroseProperty
  nonCompactProperty : GlobalPenroseProperty
  achronalProperty : GlobalPenroseProperty
  globallyHyperbolicProperty : GlobalPenroseProperty
  futureNullCompleteProperty : GlobalPenroseProperty
  futureNullIncompleteProperty : GlobalPenroseProperty

record PenroseGlobalHorismosBoundary : Set where
  field
    futureHorismosOfTrappedSurface : String
    sameHorismosObjectCarriesBothReductioClaims : Bool
    sameHorismosObjectCarriesBothReductioClaimsIsTrue : sameHorismosObjectCarriesBothReductioClaims ≡ true
    nullCompletenessPlusFocusingMakesFutureHorismosCompact : Bool
    nullCompletenessPlusFocusingMakesFutureHorismosCompactIsTrue : nullCompletenessPlusFocusingMakesFutureHorismosCompact ≡ true
    globalHyperbolicityIdentifiesHorismosWithAchronalBoundary : Bool
    globalHyperbolicityIdentifiesHorismosWithAchronalBoundaryIsTrue : globalHyperbolicityIdentifiesHorismosWithAchronalBoundary ≡ true
    nonCompactCauchySurfaceForcesFutureHorismosNonCompact : Bool
    nonCompactCauchySurfaceForcesFutureHorismosNonCompactIsTrue : nonCompactCauchySurfaceForcesFutureHorismosNonCompact ≡ true
    compactAndNonCompactHorismosContradiction : Bool
    compactAndNonCompactHorismosContradictionIsTrue : compactAndNonCompactHorismosContradiction ≡ true
    globalContradictionForcesNullIncompleteness : Bool
    globalContradictionForcesNullIncompletenessIsTrue : globalContradictionForcesNullIncompleteness ≡ true
    globalOwnerInternallyReprovesContinuumCausality : Bool
    globalOwnerInternallyReprovesContinuumCausalityIsFalse : globalOwnerInternallyReprovesContinuumCausality ≡ false

open PenroseGlobalHorismosBoundary public

canonicalPenroseGlobalHorismosBoundary : PenroseGlobalHorismosBoundary
canonicalPenroseGlobalHorismosBoundary = record
  { futureHorismosOfTrappedSurface =
      "E+(T) = J+(T) minus I+(T), generated by null geodesics from T until conjugate/focal structure moves the generator into I+(T)"
  ; sameHorismosObjectCarriesBothReductioClaims = true
  ; sameHorismosObjectCarriesBothReductioClaimsIsTrue = refl
  ; nullCompletenessPlusFocusingMakesFutureHorismosCompact = true
  ; nullCompletenessPlusFocusingMakesFutureHorismosCompactIsTrue = refl
  ; globalHyperbolicityIdentifiesHorismosWithAchronalBoundary = true
  ; globalHyperbolicityIdentifiesHorismosWithAchronalBoundaryIsTrue = refl
  ; nonCompactCauchySurfaceForcesFutureHorismosNonCompact = true
  ; nonCompactCauchySurfaceForcesFutureHorismosNonCompactIsTrue = refl
  ; compactAndNonCompactHorismosContradiction = true
  ; compactAndNonCompactHorismosContradictionIsTrue = refl
  ; globalContradictionForcesNullIncompleteness = true
  ; globalContradictionForcesNullIncompletenessIsTrue = refl
  ; globalOwnerInternallyReprovesContinuumCausality = false
  ; globalOwnerInternallyReprovesContinuumCausalityIsFalse = refl
  }

record PenroseGlobalInterpretationBoundary : Set where
  field
    compactHorismosIsNotSpacetimeSingularity : Bool
    compactHorismosIsNotSpacetimeSingularityIsTrue : compactHorismosIsNotSpacetimeSingularity ≡ true
    globalHyperbolicityIsNotMerelyNoClosedTimelikeCurves : Bool
    globalHyperbolicityIsNotMerelyNoClosedTimelikeCurvesIsTrue : globalHyperbolicityIsNotMerelyNoClosedTimelikeCurves ≡ true
    nonCompactCauchyIsTopologicalGlobalInputNotLocalCurvature : Bool
    nonCompactCauchyIsTopologicalGlobalInputNotLocalCurvatureIsTrue : nonCompactCauchyIsTopologicalGlobalInputNotLocalCurvature ≡ true
    localFocalPointAloneCannotPayHorismosNoncompactness : Bool
    localFocalPointAloneCannotPayHorismosNoncompactnessIsTrue : localFocalPointAloneCannotPayHorismosNoncompactness ≡ true
    assumedNullCompletenessIsReductioInputNotEmpiricalClaim : Bool
    assumedNullCompletenessIsReductioInputNotEmpiricalClaimIsTrue : assumedNullCompletenessIsReductioInputNotEmpiricalClaim ≡ true

open PenroseGlobalInterpretationBoundary public

canonicalPenroseGlobalInterpretationBoundary : PenroseGlobalInterpretationBoundary
canonicalPenroseGlobalInterpretationBoundary = record
  { compactHorismosIsNotSpacetimeSingularity = true
  ; compactHorismosIsNotSpacetimeSingularityIsTrue = refl
  ; globalHyperbolicityIsNotMerelyNoClosedTimelikeCurves = true
  ; globalHyperbolicityIsNotMerelyNoClosedTimelikeCurvesIsTrue = refl
  ; nonCompactCauchyIsTopologicalGlobalInputNotLocalCurvature = true
  ; nonCompactCauchyIsTopologicalGlobalInputNotLocalCurvatureIsTrue = refl
  ; localFocalPointAloneCannotPayHorismosNoncompactness = true
  ; localFocalPointAloneCannotPayHorismosNoncompactnessIsTrue = refl
  ; assumedNullCompletenessIsReductioInputNotEmpiricalClaim = true
  ; assumedNullCompletenessIsReductioInputNotEmpiricalClaimIsTrue = refl
  }

causalBoundaryConsumer : Set
causalBoundaryConsumer = Causal.CausalFutureHorismosBoundary

localFocusingConsumer : Set
localFocusingConsumer = Focusing.NullOpticalFocusingBoundary

compactnessPaymentConsumer : Set
compactnessPaymentConsumer = Compactness.PenroseHorismosCompactnessBoundary

globalCausalityAuthorityConsumer : Set
globalCausalityAuthorityConsumer = Authority.GlobalCausalityAuthorityReceipt

penroseTheoremConsumer : Set
penroseTheoremConsumer = Penrose.Penrose1965TheoremBoundary

globalHorismosOwnerPromotesContinuumGR : Bool
globalHorismosOwnerPromotesContinuumGR = false

globalHorismosOwnerPromotesContinuumGRIsFalse : globalHorismosOwnerPromotesContinuumGR ≡ false
globalHorismosOwnerPromotesContinuumGRIsFalse = refl
