module DASHI.Education.DigitalESDInstitutionalDurabilityMaintenanceRegression where

open import DASHI.Core.Prelude
import DASHI.Education.DigitalESDInstitutionalDurabilityMaintenanceExact as Durability

institutionalDurabilityBoundary = Durability.canonicalInstitutionalDurabilityBoundary
institutionalDurabilityIntersectionalChallenge = Durability.canonicalDurabilityIntersectionalChallenge
institutionalDurabilitySourceAtlas = Durability.canonicalInstitutionalDurabilitySourceAtlas
launchDoesNotDetermineDurability = Durability.initialLaunchCannotDetermineInstitutionalDurability
