module DASHI.Education.DigitalESDManuscriptMethodologyRegression where

open import Agda.Builtin.Bool using (false; true)
open import Agda.Builtin.Equality using (_≡_; refl)
open import Data.Empty using (⊥)

import DASHI.Education.DigitalESDManuscriptMethodologyExact as Method
import DASHI.Education.DigitalESDPaperTypeRequirementParetoExact as Paper
import DASHI.Education.DigitalESDStructuredSearchExact as Search

paperTypeRegression : Method.currentPaperType ≡ Paper.integrativeConceptualReview
paperTypeRegression = refl

researchQuestionCountRegression : Method.researchQuestionCount ≡ 5
researchQuestionCountRegression = refl

methodRetainsStructuredSearchRegression : Method.MethodologyBoundary.transparentStructuredSearchRequired Method.canonicalMethodologyBoundary ≡ true
methodRetainsStructuredSearchRegression = refl

searchClosureDoesNotEqualSynthesisRegression : Method.SearchClosureEqualsEvidenceSynthesis → ⊥
searchClosureDoesNotEqualSynthesisRegression = Method.searchClosureDoesNotEqualEvidenceSynthesis

primarySourceDoesNotAutoIncludeRegression : Method.PrimarySourceAcquisitionCreatesIncludedStudy → ⊥
primarySourceDoesNotAutoIncludeRegression = Method.primarySourceAcquisitionDoesNotCreateIncludedStudy

unescoRoadmapReceiptRegression : Method.SourceReceipt.observed Method.unescoESD2030RoadmapReceipt ≡ true
unescoRoadmapReceiptRegression = refl

unescoMidtermReceiptRegression : Method.SourceReceipt.observed Method.unescoESD2030MidtermReceipt ≡ true
unescoMidtermReceiptRegression = refl

oecdOutlookReceiptRegression : Method.SourceReceipt.observed Method.oecdDigitalEducationOutlook2026Receipt ≡ true
oecdOutlookReceiptRegression = refl

uneceFifthEvaluationReceiptRegression : Method.SourceReceipt.observed Method.uneceFifthESDEvaluationReceipt ≡ true
uneceFifthEvaluationReceiptRegression = refl

unescoAICommonGoodMinisterialReceiptRegression : Method.SourceReceipt.observed Method.unescoAICommonGoodMinisterialReceipt ≡ true
unescoAICommonGoodMinisterialReceiptRegression = refl

unescoAIConsultationDiscussionReceiptRegression : Method.SourceReceipt.observed Method.unescoAIConsultationDiscussionReceipt ≡ true
unescoAIConsultationDiscussionReceiptRegression = refl

unescoAIProcurementBackgroundReceiptRegression : Method.SourceReceipt.observed Method.unescoAIProcurementBackgroundReceipt ≡ true
unescoAIProcurementBackgroundReceiptRegression = refl

unescoAITCOBackgroundReceiptRegression : Method.SourceReceipt.observed Method.unescoAITCOBackgroundReceipt ≡ true
unescoAITCOBackgroundReceiptRegression = refl

consultationDoesNotEqualAdoptedStatementRegression : Method.ConsultationDiscussionPaperEqualsAdoptedMinisterialStatement → ⊥
consultationDoesNotEqualAdoptedStatementRegression = Method.consultationDiscussionPaperDoesNotEqualAdoptedMinisterialStatement

backgroundPaperDoesNotEqualAdoptedPolicyRegression : Method.ConsultationBackgroundPaperEqualsAdoptedPolicy → ⊥
backgroundPaperDoesNotEqualAdoptedPolicyRegression = Method.consultationBackgroundPaperDoesNotEqualAdoptedPolicy

regionalReportsDoNotCreateDigitalESDEffectRegression : Method.RegionalImplementationReportsCreateDigitalESDEffect → ⊥
regionalReportsDoNotCreateDigitalESDEffectRegression = Method.regionalImplementationReportsDoNotCreateDigitalESDEffect

systemTransformationNotActivityRegression : Method.ActivityLevelDeterminesSystemTransformation → ⊥
systemTransformationNotActivityRegression = Method.activityDoesNotDetermineSystemTransformation

performanceNotLearningRegression : Method.TaskPerformanceDeterminesLearning → ⊥
performanceNotLearningRegression = Method.taskPerformanceDoesNotDetermineLearning

methodsExtractionRetainsScopeRegression : Method.MethodologyBoundary.sourcePopulationTimeScopeRetained Method.canonicalMethodologyBoundary ≡ true
methodsExtractionRetainsScopeRegression = refl

methodsExtractionRetainsSourceRoleRegression : Method.MethodologyBoundary.sourceRoleRetained Method.canonicalMethodologyBoundary ≡ true
methodsExtractionRetainsSourceRoleRegression = refl

paperMethodologyDoesNotPromoteSystematicReviewRegression : Method.MethodologyBoundary.promotesSystematicReview Method.canonicalMethodologyBoundary ≡ false
paperMethodologyDoesNotPromoteSystematicReviewRegression = refl

searchLineageRemainsCanonicalRegression : Search.StructuredSearchLedger.scopusExecutionObserved Search.canonicalStructuredSearchLedger ≡ false
searchLineageRemainsCanonicalRegression = refl
