module DASHI.Education.DigitalESDContributionPositioningRegression where

open import Agda.Builtin.Bool using (true; false)
open import Agda.Builtin.Equality using (_≡_; refl)
open import Data.Empty using (⊥)

import DASHI.Education.DigitalESDContributionPositioningExact as Position

reverseAntecedentPaidRegression :
  Position.ContributionPositionBoundary.reverseSustainabilityAntecedentPaid Position.canonicalContributionPositionBoundary ≡ true
reverseAntecedentPaidRegression = refl

twinTransformationAntecedentPaidRegression :
  Position.ContributionPositionBoundary.twinTransformationAntecedentPaid Position.canonicalContributionPositionBoundary ≡ true
twinTransformationAntecedentPaidRegression = refl

reciprocalIntegrationNotPaidByChughRegression :
  Position.ContributionPositionBoundary.chughPaysReciprocalESDCapacityIntegration Position.canonicalContributionPositionBoundary ≡ false
reciprocalIntegrationNotPaidByChughRegression = refl

boehmePaysTwinTransformationRegression :
  Position.ContributionPositionBoundary.boehmePaysTwinTransformationIntegration Position.canonicalContributionPositionBoundary ≡ true
boehmePaysTwinTransformationRegression = refl

boehmeDoesNotPaySameObjectDisciplineRegression :
  Position.ContributionPositionBoundary.boehmePaysSameObjectPaymentDiscipline Position.canonicalContributionPositionBoundary ≡ false
boehmeDoesNotPaySameObjectDisciplineRegression = refl

participantAuthorityNotPaidByAntecedentsRegression :
  Position.ContributionPositionBoundary.closeAntecedentsPayParticipantAuthorityBoundary Position.canonicalContributionPositionBoundary ≡ false
participantAuthorityNotPaidByAntecedentsRegression = refl

noveltyStillOpenRegression :
  Position.ContributionPositionBoundary.globalNoveltyClaimPaid Position.canonicalContributionPositionBoundary ≡ false
noveltyStillOpenRegression = refl

antecedentDoesNotMakeDuplicateRegression : Position.CloseAntecedentAutomaticallyMakesDuplicate → ⊥
antecedentDoesNotMakeDuplicateRegression = Position.closeAntecedentDoesNotAutomaticallyMakeDuplicate

differenceDoesNotMakeNovelRegression : Position.FormalDifferenceAutomaticallyCreatesPublicationNovelty → ⊥
differenceDoesNotMakeNovelRegression = Position.formalDifferenceDoesNotAutomaticallyCreatePublicationNovelty
