module DASHI.Foundations.RelationalStageTwelveGrothendieckExtensionExact where

------------------------------------------------------------------------
-- NON-DISCRETE RELATIONAL GROTHENDIECK EXTENSION OF STAGE TWELVE
--
-- DASHI CONTRIBUTION
--
-- This owner instantiates the *existing* Stage-12 SmallCategory / Sieve /
-- GrothendieckTopology interfaces with an actual A-B-C relational overlap
-- category.  It therefore strengthens the concrete relational surface without
-- inventing a parallel category-theory API.
--
-- The distinguished global cover is generated by U_AB, U_BC and U_CA.  Its
-- closure contains the A/B/C overlap arrows.  Pullback stability and
-- transitivity are proved in the canonical Stage-12 topology type.
------------------------------------------------------------------------

open import DASHI.Core.Prelude

import DASHI.Foundations.StageTwelveGrothendieckRelationHyperformExact as Stage12

open Stage12.SmallCategory
open Stage12.GrothendieckTopology

data RelObj : Set where
  globalABC : RelObj
  edgeAB edgeBC edgeCA : RelObj
  vertexA vertexB vertexC : RelObj

data RelHom : RelObj → RelObj → Set where
  idR : (U : RelObj) → RelHom U U

  abToGlobal : RelHom edgeAB globalABC
  bcToGlobal : RelHom edgeBC globalABC
  caToGlobal : RelHom edgeCA globalABC

  aToAB : RelHom vertexA edgeAB
  bToAB : RelHom vertexB edgeAB
  bToBC : RelHom vertexB edgeBC
  cToBC : RelHom vertexC edgeBC
  cToCA : RelHom vertexC edgeCA
  aToCA : RelHom vertexA edgeCA

  aToGlobal : RelHom vertexA globalABC
  bToGlobal : RelHom vertexB globalABC
  cToGlobal : RelHom vertexC globalABC

composeRel :
  ∀ {U V W : RelObj} →
  RelHom V W →
  RelHom U V →
  RelHom U W
composeRel (idR _) f = f
composeRel f (idR _) = f
composeRel abToGlobal aToAB = aToGlobal
composeRel abToGlobal bToAB = bToGlobal
composeRel bcToGlobal bToBC = bToGlobal
composeRel bcToGlobal cToBC = cToGlobal
composeRel caToGlobal cToCA = cToGlobal
composeRel caToGlobal aToCA = aToGlobal

composeRelIdLeft :
  ∀ {U V : RelObj} →
  (f : RelHom U V) →
  composeRel (idR V) f ≡ f
composeRelIdLeft f = refl

composeRelIdRight :
  ∀ {U V : RelObj} →
  (f : RelHom U V) →
  composeRel f (idR U) ≡ f
composeRelIdRight f = refl

composeRelAssoc :
  ∀ {U V W X : RelObj} →
  (h : RelHom W X) →
  (g : RelHom V W) →
  (f : RelHom U V) →
  composeRel (composeRel h g) f
  ≡ composeRel h (composeRel g f)
composeRelAssoc (idR _) g f = refl
composeRelAssoc h (idR _) f = refl
composeRelAssoc h g (idR _) = refl

relationalPatchCategory : Stage12.SmallCategory
relationalPatchCategory = record
  { Obj = RelObj
  ; Hom = RelHom
  ; id = idR
  ; _∘_ = composeRel
  ; idLeft = composeRelIdLeft
  ; idRight = composeRelIdRight
  ; assoc = composeRelAssoc
  }

------------------------------------------------------------------------
-- The sieve generated by the three pairwise charts.
------------------------------------------------------------------------

data TriadicMember :
  {V : RelObj} →
  RelHom V globalABC →
  Set where
  memberAB : TriadicMember abToGlobal
  memberBC : TriadicMember bcToGlobal
  memberCA : TriadicMember caToGlobal
  memberA : TriadicMember aToGlobal
  memberB : TriadicMember bToGlobal
  memberC : TriadicMember cToGlobal

triadicMemberClosed :
  {V W : RelObj} →
  (f : RelHom V globalABC) →
  TriadicMember f →
  (g : RelHom W V) →
  TriadicMember (composeRel f g)
triadicMemberClosed abToGlobal memberAB (idR edgeAB) = memberAB
triadicMemberClosed abToGlobal memberAB aToAB = memberA
triadicMemberClosed abToGlobal memberAB bToAB = memberB
triadicMemberClosed bcToGlobal memberBC (idR edgeBC) = memberBC
triadicMemberClosed bcToGlobal memberBC bToBC = memberB
triadicMemberClosed bcToGlobal memberBC cToBC = memberC
triadicMemberClosed caToGlobal memberCA (idR edgeCA) = memberCA
triadicMemberClosed caToGlobal memberCA cToCA = memberC
triadicMemberClosed caToGlobal memberCA aToCA = memberA
triadicMemberClosed aToGlobal memberA (idR vertexA) = memberA
triadicMemberClosed bToGlobal memberB (idR vertexB) = memberB
triadicMemberClosed cToGlobal memberC (idR vertexC) = memberC

triadicRelationalSieve :
  Stage12.Sieve relationalPatchCategory globalABC
triadicRelationalSieve = record
  { Stage12.contains = TriadicMember
  ; Stage12.closed = triadicMemberClosed
  }

------------------------------------------------------------------------
-- Coverage: either maximal, or the distinguished global triadic cover.
------------------------------------------------------------------------

RelIsMaximal :
  {U : RelObj} →
  Stage12.Sieve relationalPatchCategory U →
  Set
RelIsMaximal {U} sieve =
  {V : RelObj} →
  (f : RelHom V U) →
  Stage12.Sieve.contains sieve f

data RelCover :
  {U : RelObj} →
  Stage12.Sieve relationalPatchCategory U →
  Set where
  maximalCover :
    {U : RelObj}
    {sieve : Stage12.Sieve relationalPatchCategory U} →
    RelIsMaximal sieve →
    RelCover sieve

  triadicGlobalCover :
    {sieve : Stage12.Sieve relationalPatchCategory globalABC} →
    Stage12.Sieve.contains sieve abToGlobal →
    Stage12.Sieve.contains sieve bcToGlobal →
    Stage12.Sieve.contains sieve caToGlobal →
    RelCover sieve

pullbackOfMaximalIsMaximal :
  {U V : RelObj} →
  (arrow : RelHom V U) →
  (sieve : Stage12.Sieve relationalPatchCategory U) →
  RelIsMaximal sieve →
  RelIsMaximal (Stage12.pullbackSieve relationalPatchCategory arrow sieve)
pullbackOfMaximalIsMaximal arrow sieve cover g =
  cover (composeRel arrow g)

stableTriadic :
  {V : RelObj} →
  (arrow : RelHom V globalABC) →
  (sieve : Stage12.Sieve relationalPatchCategory globalABC) →
  Stage12.Sieve.contains sieve abToGlobal →
  Stage12.Sieve.contains sieve bcToGlobal →
  Stage12.Sieve.contains sieve caToGlobal →
  RelCover (Stage12.pullbackSieve relationalPatchCategory arrow sieve)
stableTriadic (idR globalABC) sieve hab hbc hca =
  triadicGlobalCover hab hbc hca
stableTriadic abToGlobal sieve hab hbc hca =
  maximalCover proof
  where
    proof : RelIsMaximal
      (Stage12.pullbackSieve relationalPatchCategory abToGlobal sieve)
    proof (idR edgeAB) = hab
    proof aToAB = Stage12.Sieve.closed sieve abToGlobal hab aToAB
    proof bToAB = Stage12.Sieve.closed sieve abToGlobal hab bToAB
stableTriadic bcToGlobal sieve hab hbc hca =
  maximalCover proof
  where
    proof : RelIsMaximal
      (Stage12.pullbackSieve relationalPatchCategory bcToGlobal sieve)
    proof (idR edgeBC) = hbc
    proof bToBC = Stage12.Sieve.closed sieve bcToGlobal hbc bToBC
    proof cToBC = Stage12.Sieve.closed sieve bcToGlobal hbc cToBC
stableTriadic caToGlobal sieve hab hbc hca =
  maximalCover proof
  where
    proof : RelIsMaximal
      (Stage12.pullbackSieve relationalPatchCategory caToGlobal sieve)
    proof (idR edgeCA) = hca
    proof cToCA = Stage12.Sieve.closed sieve caToGlobal hca cToCA
    proof aToCA = Stage12.Sieve.closed sieve caToGlobal hca aToCA
stableTriadic aToGlobal sieve hab hbc hca =
  maximalCover proof
  where
    aMember : Stage12.Sieve.contains sieve aToGlobal
    aMember = Stage12.Sieve.closed sieve abToGlobal hab aToAB

    proof : RelIsMaximal
      (Stage12.pullbackSieve relationalPatchCategory aToGlobal sieve)
    proof (idR vertexA) = aMember
stableTriadic bToGlobal sieve hab hbc hca =
  maximalCover proof
  where
    bMember : Stage12.Sieve.contains sieve bToGlobal
    bMember = Stage12.Sieve.closed sieve abToGlobal hab bToAB

    proof : RelIsMaximal
      (Stage12.pullbackSieve relationalPatchCategory bToGlobal sieve)
    proof (idR vertexB) = bMember
stableTriadic cToGlobal sieve hab hbc hca =
  maximalCover proof
  where
    cMember : Stage12.Sieve.contains sieve cToGlobal
    cMember = Stage12.Sieve.closed sieve bcToGlobal hbc cToBC

    proof : RelIsMaximal
      (Stage12.pullbackSieve relationalPatchCategory cToGlobal sieve)
    proof (idR vertexC) = cMember

identityPullbackCoverToCover :
  {U : RelObj} →
  (target : Stage12.Sieve relationalPatchCategory U) →
  RelCover
    (Stage12.pullbackSieve
      relationalPatchCategory
      (idR U)
      target) →
  RelCover target
identityPullbackCoverToCover target (maximalCover cover) =
  maximalCover cover
identityPullbackCoverToCover target
  (triadicGlobalCover hab hbc hca) =
  triadicGlobalCover hab hbc hca

relationalTriadicTopology :
  Stage12.GrothendieckTopology relationalPatchCategory
relationalTriadicTopology = record
  { Cover = RelCover

  ; maximal =
      λ U → maximalCover (λ f → tt)

  ; stable =
      λ arrow sieve cover →
        stableCover arrow sieve cover

  ; transitive =
      λ sieve sieveCover target localCover →
        transitiveCover sieve sieveCover target localCover
  }
  where
    stableCover :
      {U V : RelObj} →
      (arrow : RelHom V U) →
      (sieve : Stage12.Sieve relationalPatchCategory U) →
      RelCover sieve →
      RelCover
        (Stage12.pullbackSieve relationalPatchCategory arrow sieve)
    stableCover arrow sieve (maximalCover cover) =
      maximalCover (pullbackOfMaximalIsMaximal arrow sieve cover)
    stableCover arrow sieve (triadicGlobalCover hab hbc hca) =
      stableTriadic arrow sieve hab hbc hca

    transitiveCover :
      {U : RelObj} →
      (sieve : Stage12.Sieve relationalPatchCategory U) →
      RelCover sieve →
      (target : Stage12.Sieve relationalPatchCategory U) →
      (({V : RelObj} →
        (f : RelHom V U) →
        Stage12.Sieve.contains sieve f →
        RelCover
          (Stage12.pullbackSieve
            relationalPatchCategory
            f
            target))) →
      RelCover target

    transitiveCover {U} sieve (maximalCover cover) target localCover =
      identityPullbackCoverToCover target
        (localCover (idR U) (cover (idR U)))

    transitiveCover sieve
      (triadicGlobalCover hab hbc hca)
      target localCover
      with localCover abToGlobal hab
         | localCover bcToGlobal hbc
         | localCover caToGlobal hca
    ... | maximalCover abMax
        | maximalCover bcMax
        | maximalCover caMax =
      triadicGlobalCover
        (abMax (idR edgeAB))
        (bcMax (idR edgeBC))
        (caMax (idR edgeCA))

triadicRelationalSieveCovers :
  Stage12.GrothendieckTopology.Cover
    relationalTriadicTopology
    triadicRelationalSieve
triadicRelationalSieveCovers =
  triadicGlobalCover memberAB memberBC memberCA

record RelationalStageTwelveGrothendieckBoundary : Set where
  constructor relational-stage-twelve-grothendieck-boundary
  field
    reusesCanonicalStageTwelveCategoryAPI : Bool
    nonIdentityRelationalArrowsExist : Bool
    threeDyadsGenerateGlobalCover : Bool
    overlapArrowsRetainedBySieveClosure : Bool
    pullbackStabilityPaid : Bool
    transitivityPaid : Bool
    sameAsDiscreteMaximalOnlyConcreteSite : Bool
    analyticModularSiteIdentified : Bool

canonicalRelationalStageTwelveGrothendieckBoundary :
  RelationalStageTwelveGrothendieckBoundary
canonicalRelationalStageTwelveGrothendieckBoundary =
  relational-stage-twelve-grothendieck-boundary
    true true true true true true false false
