module DASHI.Astronomy.LocalGroupNoPromotionExact where

open import DASHI.Core.Prelude

privatePostImpliesScientificAuthority : Bool
privatePostImpliesScientificAuthority = false

privatePostImpliesScientificAuthorityIsFalse :
  privatePostImpliesScientificAuthority ≡ false
privatePostImpliesScientificAuthorityIsFalse = refl

paperCitationImpliesPosterBenchmarkCorrect : Bool
paperCitationImpliesPosterBenchmarkCorrect = false

paperCitationImpliesPosterBenchmarkCorrectIsFalse :
  paperCitationImpliesPosterBenchmarkCorrect ≡ false
paperCitationImpliesPosterBenchmarkCorrectIsFalse = refl

scientificAgreementImpliesModelCompleteness : Bool
scientificAgreementImpliesModelCompleteness = false

scientificAgreementImpliesModelCompletenessIsFalse :
  scientificAgreementImpliesModelCompleteness ≡ false
scientificAgreementImpliesModelCompletenessIsFalse = refl
