module DASHI.Physics.CondensedMatter.Everything where

import DASHI.Physics.CondensedMatter.FlatBandObservableFibreExact
import DASHI.Physics.CondensedMatter.GaoFe5GeTe2FlatBandChargeOrderSourceReplayExact
import DASHI.Physics.CondensedMatter.ThreeFoldBandFoldingExact
import DASHI.Physics.CondensedMatter.FlatBandTwistronicsFe5GeTe2CrossPollinationExact
import DASHI.Physics.CondensedMatter.HexagonalSqrt3R30ReciprocalFoldingExact
import DASHI.Physics.CondensedMatter.GaoFe5GeTe2Sqrt3R30SameObjectWeldExact
import DASHI.Physics.CondensedMatter.ARPESBandFoldingWitnessGateExact
import DASHI.Physics.CondensedMatter.GaoFe5GeTe2FigureReplayExact

-- Co1/4TaSe2 altermagnet / magnetic-crystal lane.
import DASHI.Physics.CondensedMatter.AltermagnetCoQuarterTaSeTwo
import DASHI.Physics.CondensedMatter.AltermagnetCrystalActionBridgeExact
import DASHI.Physics.CondensedMatter.AltermagnetNodalSymmetryExact
import DASHI.Physics.CondensedMatter.CoQuarterTaSeTwoMagneticCellIdentificationExact
import DASHI.Physics.CondensedMatter.CoQuarterTaSeTwoPhysicalSymmetryExact
import DASHI.Physics.CondensedMatter.CoQuarterTaSeTwoBNS194268SameObjectExact
import DASHI.Physics.CondensedMatter.CoQuarterTaSeTwoBlochRepresentationBoundaryExact
import DASHI.Physics.CondensedMatter.CoQuarterTaSeTwoARPESWitnessGateExact
import DASHI.Physics.CondensedMatter.CoQuarterTaSeTwoTwistronicsCrossPollinationExact
import DASHI.Physics.CondensedMatter.CoQuarterTaSeTwoMaxCutStatusExact
