{-# OPTIONS --safe #-}
module DASHI.Physics.YangMills.BalabanSameFamilyCompositeOPEStressCompilerExact where

------------------------------------------------------------------------
-- C: SAME-FAMILY COMPOSITE MARK -> CONTINUUM OPE/STRESS PACKAGE
--
-- The dyadic OPE decay is not a separate physical premise.  It is compiled
-- from the shared composite-mark tail already proved in the RG shell.
------------------------------------------------------------------------

open import Agda.Builtin.Nat using (Nat)
open import Data.Rational.Base using (ℚ)
open import Agda.Builtin.Equality using (_≡_)

open import DASHI.Physics.YangMills.CompactLieProofLevel
import DASHI.Physics.YangMills.BalabanSharedMarkedAnalyticShellExact as Shared
import DASHI.Physics.YangMills.YangMillsSharedMarkedCompositeOPERemainderExact as MarkedOPE
import DASHI.Physics.YangMills.YangMillsContinuumLocalOperatorOPEStressTensorExact as Local

record SameFamilyCompositeOPEStressInputs
    (Scale Volume Root ContinuumFamily CurvaturePolynomial LocalOperator Position
     OPECoefficient StressTensor Hamiltonian : Set) : Set₁ where
  field
    shared : Shared.SharedMarkedAnalyticShellControl Scale Volume Root

    selectedScale : Scale
    selectedVolume : Volume
    selectedRoot : Root
    remaining : Nat → Nat

    continuumFamily : ContinuumFamily

    localOperator : CurvaturePolynomial → LocalOperator
    GaugeInvariant : LocalOperator → Set
    LocalAt : LocalOperator → Position → Set
    curvatureOperatorsGaugeInvariant : ∀ polynomial →
      GaugeInvariant (localOperator polynomial)
    curvatureOperatorsLocal : ∀ polynomial position →
      LocalAt (localOperator polynomial) position

    OPEAdmissible : LocalOperator → LocalOperator → Set
    coefficient :
      LocalOperator → LocalOperator → LocalOperator → Position → OPECoefficient

    physicalRemainder :
      LocalOperator → LocalOperator → Position → Nat → ℚ

    -- SAME-object payment: the physical remainder is exactly the composite-mark
    -- tail generated by the completed RG family.
    physicalRemainderIsCompositeTail :
      ∀ left right position admissible depth →
      physicalRemainder left right position depth
      ≡
      Local.remainderMagnitude
        (MarkedOPE.sharedCompositeAsDyadicOPERemainder
          shared selectedScale selectedVolume selectedRoot remaining)
        depth

    ShortDistanceAFMatching : Set
    shortDistanceAFMatching : ShortDistanceAFMatching

    stressTensor : StressTensor
    Symmetric : StressTensor → Set
    ConservedInCorrelators : StressTensor → Set
    LocalStressTensor : StressTensor → Set
    stressTensorSymmetric : Symmetric stressTensor
    stressTensorConserved : ConservedInCorrelators stressTensor
    stressTensorLocal : LocalStressTensor stressTensor

    reconstructedHamiltonian : Hamiltonian
    SpatialIntegralT00Generates : StressTensor → Hamiltonian → Set
    stressTensorGeneratesHamiltonian :
      SpatialIntegralT00Generates stressTensor reconstructedHamiltonian

open SameFamilyCompositeOPEStressInputs public

compileContinuumLocalOperatorOPEStressTensor :
  ∀ {Scale Volume Root ContinuumFamily CurvaturePolynomial LocalOperator Position
      OPECoefficient StressTensor Hamiltonian} →
  SameFamilyCompositeOPEStressInputs
    Scale Volume Root ContinuumFamily CurvaturePolynomial LocalOperator Position
    OPECoefficient StressTensor Hamiltonian →
  Local.ContinuumLocalOperatorOPEStressTensor
    ContinuumFamily CurvaturePolynomial LocalOperator Position
    OPECoefficient StressTensor Hamiltonian
compileContinuumLocalOperatorOPEStressTensor inputs = record
  { Local.ContinuumLocalOperatorOPEStressTensor.continuumFamily =
      continuumFamily inputs
  ; Local.ContinuumLocalOperatorOPEStressTensor.localOperator =
      localOperator inputs
  ; Local.ContinuumLocalOperatorOPEStressTensor.GaugeInvariant =
      GaugeInvariant inputs
  ; Local.ContinuumLocalOperatorOPEStressTensor.LocalAt =
      LocalAt inputs
  ; Local.ContinuumLocalOperatorOPEStressTensor.curvatureOperatorsGaugeInvariant =
      curvatureOperatorsGaugeInvariant inputs
  ; Local.ContinuumLocalOperatorOPEStressTensor.curvatureOperatorsLocal =
      curvatureOperatorsLocal inputs
  ; Local.ContinuumLocalOperatorOPEStressTensor.OPEAdmissible =
      OPEAdmissible inputs
  ; Local.ContinuumLocalOperatorOPEStressTensor.coefficient =
      coefficient inputs
  ; Local.ContinuumLocalOperatorOPEStressTensor.OPERemainder =
      physicalRemainder inputs
  ; Local.ContinuumLocalOperatorOPEStressTensor.opeRemainderMajorant =
      λ left right position admissible →
        MarkedOPE.sharedCompositeAsDyadicOPERemainder
          (shared inputs)
          (selectedScale inputs)
          (selectedVolume inputs)
          (selectedRoot inputs)
          (remaining inputs)
  ; Local.ContinuumLocalOperatorOPEStressTensor.opeRemainderIsPhysicalRemainder =
      λ left right position admissible depth →
        physicalRemainderIsCompositeTail inputs
          left right position admissible depth
  ; Local.ContinuumLocalOperatorOPEStressTensor.ShortDistanceAFMatching =
      ShortDistanceAFMatching inputs
  ; Local.ContinuumLocalOperatorOPEStressTensor.shortDistanceAFMatching =
      shortDistanceAFMatching inputs
  ; Local.ContinuumLocalOperatorOPEStressTensor.stressTensor =
      stressTensor inputs
  ; Local.ContinuumLocalOperatorOPEStressTensor.Symmetric =
      Symmetric inputs
  ; Local.ContinuumLocalOperatorOPEStressTensor.ConservedInCorrelators =
      ConservedInCorrelators inputs
  ; Local.ContinuumLocalOperatorOPEStressTensor.LocalStressTensor =
      LocalStressTensor inputs
  ; Local.ContinuumLocalOperatorOPEStressTensor.stressTensorSymmetric =
      stressTensorSymmetric inputs
  ; Local.ContinuumLocalOperatorOPEStressTensor.stressTensorConserved =
      stressTensorConserved inputs
  ; Local.ContinuumLocalOperatorOPEStressTensor.stressTensorLocal =
      stressTensorLocal inputs
  ; Local.ContinuumLocalOperatorOPEStressTensor.reconstructedHamiltonian =
      reconstructedHamiltonian inputs
  ; Local.ContinuumLocalOperatorOPEStressTensor.SpatialIntegralT00Generates =
      SpatialIntegralT00Generates inputs
  ; Local.ContinuumLocalOperatorOPEStressTensor.stressTensorGeneratesHamiltonian =
      stressTensorGeneratesHamiltonian inputs
  }

sameFamilyCompositeOPERemainderCompilerLevel : ProofLevel
sameFamilyCompositeOPERemainderCompilerLevel = machineChecked

sameFamilyCompositeOPEStressCompilerLevel : ProofLevel
sameFamilyCompositeOPEStressCompilerLevel = machineChecked

physicalCompositeSameObjectIdentificationLevel : ProofLevel
physicalCompositeSameObjectIdentificationLevel = conditional

physicalLocalStressAFIdentificationLevel : ProofLevel
physicalLocalStressAFIdentificationLevel = conditional
