module DASHI.Physics.YangMills.BalabanCMP116ComparisonVsAbsoluteLocalizationRound386Validation where

import DASHI.Physics.YangMills.BalabanCMP116ComparisonVsAbsoluteLocalizationRound386Exact
import DASHI.Physics.YangMills.BalabanCMP116MinimalDistanceLiteralHessianRound385Exact
import DASHI.Physics.YangMills.BalabanCMP116SharedMarkedAmplitudeDirectRound346Exact
import DASHI.Physics.YangMills.BalabanCMP116CanonicalCommonDomainSourceRound338Exact
