{-# OPTIONS --safe #-}
module DASHI.Physics.YangMills.BalabanHeatDoobSameDensityLogHessianRound103Exact where

------------------------------------------------------------------------
-- ROUND103 BC2: SAME-DENSITY HEAT/DOOB LOG-HESSIAN IDENTITY
--
-- The expectation/covariance operators below are parameterized directly by the
-- Round103 carrier potential.  Hence "same density" is enforced by their types
-- and definitions rather than by opaque `Set` labels.
------------------------------------------------------------------------

open import Agda.Builtin.Equality using (_≡_)

open import DASHI.Foundations.RealAnalysisAxioms using (ℝ; _-ℝ_)
open import DASHI.Physics.YangMills.CompactLieProofLevel
import DASHI.Physics.YangMills.BalabanCMP109116LiteralDifferentiatedCarrierRound103Exact as Carrier
import DASHI.Physics.YangMills.BalabanCMP109116SourceContinuationRound103Exact as Source

record HeatDoobSameDensityCalculus
    (carrier : Carrier.LiteralDifferentiatedEffectiveDensityCarrier) : Set₁ where
  field
    Time : Set

    -- First derivative on the same physical background coordinate used by BC1.
    firstVariation :
      (Source.Background (Carrier.source carrier) → ℝ) →
      Source.Background (Carrier.source carrier) →
      Source.Tangent (Carrier.source carrier) → ℝ

    -- The heat-kernel tilted expectation is defined using the carrier potential
    -- itself.  No alternative Gibbs density can be passed here.
    heatTiltExpectation :
      Time → Source.Background (Carrier.source carrier) →
      (Source.Background (Carrier.source carrier) → ℝ) → ℝ

    heatTiltCovariance :
      Time → Source.Background (Carrier.source carrier) →
      (Source.Background (Carrier.source carrier) → ℝ) →
      (Source.Background (Carrier.source carrier) → ℝ) → ℝ

    -- Evidence that this covariance is the covariance generated by the same
    -- expectation operator, rather than an independently supplied bilinear form.
    covarianceDefinition : ∀ time background f g →
      heatTiltCovariance time background f g
      ≡ heatTiltExpectation time background (λ y → f y *ℝ g y)
          -ℝ (heatTiltExpectation time background f
              *ℝ heatTiltExpectation time background g)

    heatDoobHessian :
      Time → Source.Background (Carrier.source carrier) →
      Source.Tangent (Carrier.source carrier) →
      Source.Tangent (Carrier.source carrier) → ℝ

    -- Standard differentiation theorem for
    -- V_t = -log H_t(exp(-V)), with V literally `Carrier.effectivePotential`.
    logHeatHessianIdentity : ∀ time background u v →
      heatDoobHessian time background u v
      ≡ heatTiltExpectation time background
          (λ y → Carrier.cmp116PhysicalMarkedHessian carrier y u v)
        -ℝ heatTiltCovariance time background
          (λ y → firstVariation (Carrier.effectivePotential carrier) y u)
          (λ y → firstVariation (Carrier.effectivePotential carrier) y v)

open HeatDoobSameDensityCalculus public

carrierGradient :
  ∀ {carrier}
    (dataSet : HeatDoobSameDensityCalculus carrier) →
  Source.Background (Carrier.source carrier) →
  Source.Tangent (Carrier.source carrier) → ℝ
carrierGradient {carrier} dataSet =
  firstVariation dataSet (Carrier.effectivePotential carrier)

conditionalExpectedStaticHessian :
  ∀ {carrier}
    (dataSet : HeatDoobSameDensityCalculus carrier) →
  Time dataSet → Source.Background (Carrier.source carrier) →
  Source.Tangent (Carrier.source carrier) →
  Source.Tangent (Carrier.source carrier) → ℝ
conditionalExpectedStaticHessian {carrier} dataSet time background u v =
  heatTiltExpectation dataSet time background
    (λ y → Carrier.cmp116PhysicalMarkedHessian carrier y u v)

conditionalGradientCovariance :
  ∀ {carrier}
    (dataSet : HeatDoobSameDensityCalculus carrier) →
  Time dataSet → Source.Background (Carrier.source carrier) →
  Source.Tangent (Carrier.source carrier) →
  Source.Tangent (Carrier.source carrier) → ℝ
conditionalGradientCovariance dataSet time background u v =
  heatTiltCovariance dataSet time background
    (λ y → carrierGradient dataSet y u)
    (λ y → carrierGradient dataSet y v)

heatDoobHessianIsStaticMinusCovariance :
  ∀ {carrier}
    (dataSet : HeatDoobSameDensityCalculus carrier) →
  ∀ time background u v →
  heatDoobHessian dataSet time background u v
  ≡ conditionalExpectedStaticHessian dataSet time background u v
      -ℝ conditionalGradientCovariance dataSet time background u v
heatDoobHessianIsStaticMinusCovariance dataSet =
  logHeatHessianIdentity dataSet

sameDensityHeatDoobIdentityWiringLevel : ProofLevel
sameDensityHeatDoobIdentityWiringLevel = machineChecked

heatDoobLogHessianConditionalCovarianceIdentityLevel : ProofLevel
heatDoobLogHessianConditionalCovarianceIdentityLevel = standardImported

-- Remaining physical BC2 leaf: instantiate `heatTiltExpectation` by the compact
-- group heat kernel acting on exp(-V) for this exact finite-cutoff carrier, and
-- instantiate `firstVariation` by the same CMP116 physical source derivative.
literalYMSameDensityHeatDoobIdentificationLevel : ProofLevel
literalYMSameDensityHeatDoobIdentificationLevel = conditional
