{-# OPTIONS --safe #-}
module DASHI.Physics.YangMills.BalabanCMP98Equation119StrongestPhysicalProducerRound160Exact where

------------------------------------------------------------------------
-- ROUND160 A1 BIDI: STRONGEST EQ. (119) PRODUCER
--
-- Tadeusz Bałaban, "Averaging Operations for Lattice Gauge Theories",
-- Commun. Math. Phys. 98 (1985), 17--51. DOI: 10.1007/BF01211042.
--
-- This module composes the least-privilege improvements rather than exposing an
-- older, weaker interface to downstream consumers:
--   R158 fixes the coarse fine-segment length to L=13;
--   R155-R157 construct Y_x from literal path holonomy and inherit principal
--             image admission from the existing physical small-field owner;
--   R159 constructs the full left/right dexp family from one exp/log
--             differential calculus plus adjoint transport.
--
-- Consequently the direct Eq. (119) consumer below accepts no arbitrary Q', no
-- arbitrary path values, no point Y_x values, no log function, no arbitrary LR
-- family and no arbitrary coarse segment length.
------------------------------------------------------------------------

open import Agda.Builtin.Nat using (Nat)

open import DASHI.Physics.YangMills.CompactLieProofLevel
import DASHI.Physics.YangMills.BalabanCMP98MultiscaleAveragingDerivativeRound126Exact as R126
import DASHI.Physics.YangMills.BalabanCMP98Equation119OneStepDerivativeRound146Exact as R146
import DASHI.Physics.YangMills.BalabanCMP98Equation119PhysicalPrincipalImageRound157Exact as R157
import DASHI.Physics.YangMills.BalabanCMP98Equation119CanonicalCoarseSegmentRound158Exact as R158
import DASHI.Physics.YangMills.BalabanCMP98Equation119DifferentialDexpRound159Exact as R159
import DASHI.Physics.YangMills.BalabanClayGate4SU2PrincipalLogBallExact as Log

strongestPhysicalOneStepDerivative :
  ∀ {C n Group group Field CoarseBond FineBond Radius}
    (source : R158.CanonicalL13Equation119Source C n Group group)
    (meaning : Log.PhysicalSU2PrincipalLogMeaning
      Field CoarseBond FineBond
      (R126.Vector (R146.additive C)) Group Radius) →
  R157.CMP98RelativeContourPhysicalBridge
    (R158.asRound152Source source) meaning →
  R159.UniformAdjointDifferentialCalculus
    (R126.Vector (R146.additive C)) →
  R126.OneStepAveragingDerivative (R146.additive C)
strongestPhysicalOneStepDerivative source meaning bridge calculus =
  R157.physicalPrincipalImageOneStepDerivative
    (R158.asRound152Source source)
    meaning
    bridge
    (R159.asUniformLeftRightDexpFamily calculus)

strongestPhysicalMultiscaleDerivative :
  ∀ {C n Group group Field CoarseBond FineBond Radius}
    (source : R158.CanonicalL13Equation119Source C n Group group)
    (meaning : Log.PhysicalSU2PrincipalLogMeaning
      Field CoarseBond FineBond
      (R126.Vector (R146.additive C)) Group Radius) →
  R157.CMP98RelativeContourPhysicalBridge
    (R158.asRound152Source source) meaning →
  R159.UniformAdjointDifferentialCalculus
    (R126.Vector (R146.additive C)) →
  Nat → R126.Operator (R146.additive C)
strongestPhysicalMultiscaleDerivative source meaning bridge calculus =
  R157.physicalPrincipalImageMultiscaleDerivative
    (R158.asRound152Source source)
    meaning
    bridge
    (R159.asUniformLeftRightDexpFamily calculus)

cmp98Equation119StrongestPhysicalProducerRound160Level : ProofLevel
cmp98Equation119StrongestPhysicalProducerRound160Level = machineChecked

-- The remaining literal same-object cut is deliberately small:
--   * select the CMP98 coarse axis/orientation and prove its canonical L=13
--     segment connects the chosen c-/c+ centres;
--   * identify the literal path-holonomy relative element with the existing
--     physical transported-relative object;
--   * identify the physical principal-log/differential/adjoint normalizations
--     with CMP98's printed exp(iY), (1/i)log, g and R conventions.
-- Everything else in Eq. (119) is generated by R146-R160.
literalCMP98StrongestSameObjectCutRound160Level : ProofLevel
literalCMP98StrongestSameObjectCutRound160Level = conditional
