module DASHI.Physics.YangMills.BalabanClayGate4Validation where

-- Existing carriers and exact reusable owners.
import DASHI.Physics.YangMills.BalabanPeriodicTorus4Carrier
import DASHI.Physics.YangMills.BalabanSU2RationalWilsonLargeFieldGapExact
import DASHI.Physics.YangMills.BalabanClayP2BadComponentGeometryExact
import DASHI.Physics.YangMills.BalabanClayP3FiniteConstrainedIntegralExact
import DASHI.Physics.YangMills.BalabanClayT2PeriodicAdjacencyBFSExact
import DASHI.Physics.YangMills.BalabanClayT2TraversalRootedShellExact
import DASHI.Physics.YangMills.BalabanCriticalMapRGCutsetCompletion
import DASHI.Physics.YangMills.BalabanClayT4RunningCouplingConventionBridgeExact

-- Earlier Gate-4 architecture and literal predicate tranche.
import DASHI.Physics.YangMills.BalabanClayLargeFieldVerifiedLiteratureExact
import DASHI.Physics.YangMills.BalabanClayGate4LargeFieldArchaeologyExact
import DASHI.Physics.YangMills.BalabanClayGate4TypedReuseAndFiniteGeometryExact
import DASHI.Physics.YangMills.BalabanClayGate4LiteralWilsonLargeFieldPredicateExact
import DASHI.Physics.YangMills.BalabanClayGate4FiniteEnlargementCollarOwnershipExact
import DASHI.Physics.YangMills.BalabanClayGate4ROperationDecayTargetsExact

-- Literal periodic incidence, holonomy, bad reach and finite geometry.
import DASHI.Physics.YangMills.BalabanClayGate4LiteralPeriodicPlaquetteWitnessExact
import DASHI.Physics.YangMills.BalabanClayGate4LiteralPeriodicPlaquetteHolonomyGaugeExact
import DASHI.Physics.YangMills.BalabanClayGate4PeriodicPhysicalAdjacencyAndBadReachExact
import DASHI.Physics.YangMills.BalabanClayGate4PeriodicReachCollarEnumerationExact

-- Concrete T/R pipelines and proof-bearing analytic reductions.
import DASHI.Physics.YangMills.BalabanClayGate4ComponentClassAndFiniteTOperationExact
import DASHI.Physics.YangMills.BalabanClayGate4TOperationSmallFactorReductionExact
import DASHI.Physics.YangMills.BalabanClayGate4FiniteROperationAndDecayAssemblyExact
import DASHI.Physics.YangMills.BalabanClayGate4CountingAndLocalizationReuseExact

-- Absorption, combined one-step closure, all-scale induction and provenance.
import DASHI.Physics.YangMills.BalabanClayGate4P0GrowthAbsorptionExact
import DASHI.Physics.YangMills.BalabanClayGate4CombinedSmallLargeNormAssemblyExact
import DASHI.Physics.YangMills.BalabanClayGate4CombinedRGUVIterationExact
import DASHI.Physics.YangMills.BalabanClayGate4PrimaryTargetAndAttachmentAuditExact

-- Authoritative proof-level and branch-head verification surfaces.
import DASHI.Physics.YangMills.BalabanClayGate4AndNumericalAuditCompletionLedger
import DASHI.Physics.YangMills.BalabanClayBranchHeadReceiptSurface
