module DASHI.Physics.YangMills.BalabanCutoffBetaLaw where

-- Producer-side surface for the finite-cutoff coupling dynamics.  The
-- existing inverse-square step is deliberately an evaluated recurrence,
-- which is exactly what the budget arithmetic consumes.  This file records
-- the missing fact needed to *produce* that recurrence from Balaban's block
-- transformation: each correction is the value of one fixed cutoff/scale
-- beta law at the generated coupling, rather than an arbitrary sequence.

open import Agda.Builtin.Bool using (false)
open import Agda.Builtin.Equality using (_≡_)
open import Agda.Builtin.String using (String)
open import Data.Nat.Base using (ℕ; suc; _<_)
open import Data.Empty using (⊥)

open import DASHI.Foundations.RealAnalysisAxioms using (ℝ)
open import DASHI.Geometry.Gauge.SUNPrimitives using (clayYangMillsPromoted)
open import DASHI.Physics.YangMills.YMSourceAuthoritySurface using
  ( SourceAuthorityId ; VerificationStatus ; balaban-cmp-109 ; openTarget )
open import DASHI.Physics.YangMills.BalabanEffectiveCouplingTrajectory using
  ( BalabanInverseSquareCouplingStep
  ; coupling
  ; betaCorrection
  )

record BalabanCutoffCouplingDynamics (K : ℕ) : Set₁ where
  field
    step : BalabanInverseSquareCouplingStep

    -- `betaLaw k k<K g` is the source β_{k+1}(g) correction generated by
    -- the actual scale-k Balaban transformation in its inverse-square
    -- coordinate.
    betaLaw : (k : ℕ) → k < K → ℝ → ℝ

    generatedBetaCorrection :
      ∀ k → (k<K : k < K) →
      betaCorrection step (suc k)
        ≡ betaLaw k k<K (coupling step k)

    -- The inverse-square coordinate relation itself remains the explicit
    -- field of `step`; this witness says that it is the source coordinate,
    -- not merely a convenient numerical parametrisation.
    sourceCoordinateMeaning :
      BalabanInverseSquareCouplingStep.inverseSquareCoordinateMeaning step

    sourceAuthorityId : SourceAuthorityId
    theoremLocator : String
    status : VerificationStatus
    noClayPromotion : clayYangMillsPromoted ≡ false

open BalabanCutoffCouplingDynamics public

-- CMP 109 I defines β_{j+1}(g_j) from the fluctuation effective action
-- (1.20)--(1.22).  Its introduction states that the four-dimensional tuned
-- small-coupling result (Theorem 2, pp. 258--260) needs a separate
-- perturbative proof.  Keep this producer unavailable until that exact
-- finite-cutoff estimate is extracted or proved.
actualBalabanCutoffCouplingDynamicsAvailable : Set
actualBalabanCutoffCouplingDynamicsAvailable = ⊥

currentBalabanCutoffBetaLawStatus : VerificationStatus
currentBalabanCutoffBetaLawStatus = openTarget
