module DASHI.Physics.YangMills.BalabanClayLiteralFrontierProducerBundle where

-- One import surface for the literal T2--T5 producer tranche.  The individual
-- modules keep their remaining local analytic hypotheses explicit; this bundle
-- performs no proof-level promotion by import alone.

-- Canonical authors/title/venue/DOI/arXiv/section/relationship metadata and a
-- theorem-disconnected quarantine for unverified completion claims.
import DASHI.Physics.YangMills.BalabanClayLiteralFrontierVerifiedLiteratureExact
import DASHI.Physics.YangMills.BalabanClayConfiguredVerifiedLiteratureExact
import DASHI.Physics.YangMills.BalabanClayLiteralFrontierQuarantinedClaims

-- Bishop constructive reals, concrete series terms, series completeness and
-- explicit transport into the older postulated real socket, followed by the
-- shared interval machinery.
import DASHI.Foundations.BishopConstructiveRealBridgeExact
import DASHI.Foundations.BishopPowerSeriesElementaryBridgeExact
import DASHI.Foundations.BishopElementarySeriesTermsExact
import DASHI.Foundations.RealElementaryFunctionsBishopTransportExact
import DASHI.Foundations.RealElementaryFunctionsAlternatingSeriesExact
import DASHI.Foundations.RealElementaryFunctionsCanonicalInstanceExact
import DASHI.Physics.YangMills.BalabanClayCommonCertifiedTaylorEnclosureExact
import DASHI.Physics.YangMills.BalabanClayCommonTaylorRemainderToEnclosureExact
import DASHI.Physics.YangMills.BalabanClayCommonNegativeLogSincReductionExact
import DASHI.Physics.YangMills.BalabanClayCommonRationalSincCertificateExact
import DASHI.Physics.YangMills.BalabanClayCommonLogSixteenCertificateExact
import DASHI.Physics.YangMills.BalabanClayCommonElementaryRealInhabitantsExact

-- T3: reference coercivity, exact chart singular values, fixed named atom lists
-- and coordinate formulas, periodic bond kernels, Fourier symbols, RG/images
-- and the configured Green gateway.
import DASHI.Physics.YangMills.BalabanClayT3PhysicalUniformFluctuationCoercivityExact
import DASHI.Physics.YangMills.BalabanClayT3LiteralPhysicalCoercivityProducerExact
import DASHI.Physics.YangMills.BalabanClayT3LiteralBackgroundHessianRemaindersExact
import DASHI.Physics.YangMills.BalabanClayT3LiteralSU2ChartIntervalBoundsExact
import DASHI.Physics.YangMills.BalabanClayT3RightJacobianSampleCheckExact
import DASHI.Physics.YangMills.BalabanClayT3LiteralFiveRemainderConstantsExact
import DASHI.Physics.YangMills.BalabanClayT3LiteralCommonRadiusWitnessExact
import DASHI.Physics.YangMills.BalabanClayT3ConfiguredGeometricConstantsExact
import DASHI.Physics.YangMills.BalabanClayT3ConfiguredFiveHessianDominationExact
import DASHI.Physics.YangMills.BalabanClayT3LiteralPointwiseHessianEstimatesExact
import DASHI.Physics.YangMills.BalabanClayT3ConfiguredFiniteAtomListsExact
import DASHI.Physics.YangMills.BalabanClayT3LiteralFixedAtomFormulaInstanceExact
import DASHI.Physics.YangMills.BalabanClayT3ConfiguredCommonRadiusCertificateExact
import DASHI.Physics.YangMills.BalabanClayT3PhysicalGreenCombesThomasExact
import DASHI.Physics.YangMills.BalabanClayT3ConfiguredPhysicalGreenInstanceExact
import DASHI.Physics.YangMills.BalabanClayT3LiteralHessianFourierImageInstanceExact
import DASHI.Physics.YangMills.BalabanClayT3PeriodicTorusGreenCarrierExact
import DASHI.Physics.YangMills.BalabanClayT3PeriodicHessianKernelFormulaExact
import DASHI.Physics.YangMills.BalabanClayT3ConfiguredPhysicalGatewayExact

-- T2: action gain, component losses, Bishop-backed quaternion normalization,
-- rooted encoding, actual periodic adjacency and the certified BFS/DFS boundary.
import DASHI.Physics.YangMills.BalabanClayT2LiteralWilsonSixFactorProducerExact
import DASHI.Physics.YangMills.BalabanClayT2LiteralActivityLossConstantsExact
import DASHI.Physics.YangMills.BalabanClayT2LiteralPhysicalLossWitnessExact
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredActionGainThresholdExact
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredComponentLossBoundsExact
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredModelSpecificLossClosureExact
import DASHI.Physics.YangMills.BalabanClayT2LiteralHaarTraceClassClosureExact
import DASHI.Physics.YangMills.BalabanClayT2QuaternionCubicEnumerationExact
import DASHI.Physics.YangMills.BalabanClayT2GeneratedQuaternionJetExact
import DASHI.Physics.YangMills.BalabanClayT2BishopQuaternionNormalizationExact
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredLossBudgetCertificateExact
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredStrictLossMarginExact
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredRobustOneSixteenthEndpointExact
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredPhysicalLossInstanceExact
import DASHI.Physics.YangMills.BalabanClayT2LiteralEightWayCliqueExact
import DASHI.Physics.YangMills.BalabanClayT2PhysicalRootedPolymerEncodingExact
import DASHI.Physics.YangMills.BalabanClayT2PhysicalPolymerCarrierInstanceExact
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredPhysicalPolymerCarrierExact
import DASHI.Physics.YangMills.BalabanClayT2RepositoryConnectedPolymerExtractionExact
import DASHI.Physics.YangMills.BalabanClayT2RepositoryBreadthFirstTreeInstanceExact
import DASHI.Physics.YangMills.BalabanClayT2PeriodicBlockPolymerCarrierExact
import DASHI.Physics.YangMills.BalabanClayT2PeriodicAdjacencyBFSExact

-- T4: fixed Wilson/ghost/Haar conventions, symbolic diagram expressions, Ward
-- reduction, generated normalized grid and recursive proof-producing evaluator.
import DASHI.Physics.YangMills.BalabanClayT4LocalizedPlaquetteCoefficientProducerExact
import DASHI.Physics.YangMills.BalabanClayT4LiteralVacuumPolarizationIntegralExact
import DASHI.Physics.YangMills.BalabanClayT4LiteralOneLoopCoefficientClosureExact
import DASHI.Physics.YangMills.BalabanClayT4WilsonOneLoopConventionExact
import DASHI.Physics.YangMills.BalabanClayT4LiteralDiagramWardCancellationExact
import DASHI.Physics.YangMills.BalabanClayT4LiteralMomentumDiagramBoxDataExact
import DASHI.Physics.YangMills.BalabanClayT4GeneratedBrillouinGridExact
import DASHI.Physics.YangMills.BalabanClayT4LiteralOneLoopBoxEvaluatorExact
import DASHI.Physics.YangMills.BalabanClayT4Balaban1987TheoremShapeExact
import DASHI.Physics.YangMills.BalabanClayT4Balaban536VacuumPolarizationTargetExact
import DASHI.Physics.YangMills.BalabanClayT4ConfiguredBrillouinIntegralCertificateExact
import DASHI.Physics.YangMills.BalabanClayT4ConfiguredBrillouinBoxReceiptFamilyExact
import DASHI.Physics.YangMills.BalabanClayT4ConfiguredPhysicalOneLoopInstanceExact

-- T5: separate KP and sharper FP criteria, exact marked-activity margins,
-- repository-specific rooted-shell injection, physical cluster/RG/moment and
-- marginal/projective compactness, followed by complete OS Gram transport.
import DASHI.Physics.YangMills.BalabanClayT5ThermodynamicUniformIntegrabilityExact
import DASHI.Physics.YangMills.BalabanClayT5PhysicalMeasureGramContinuityExact
import DASHI.Physics.YangMills.BalabanClayT5QuantitativeTailMomentCompactnessExact
import DASHI.Physics.YangMills.BalabanClayT5ConfiguredGeometricTailExact
import DASHI.Physics.YangMills.BalabanClayT5RootedShellBoundaryTailExact
import DASHI.Physics.YangMills.BalabanClayT5MarkedFernandezProcacciExact
import DASHI.Physics.YangMills.BalabanClayT5PhysicalRootedShellInjectionExact
import DASHI.Physics.YangMills.BalabanClayT5BoundaryContinuumMomentMeasureExact
import DASHI.Physics.YangMills.BalabanClayT5ConfiguredPhysicalTailMomentInstanceExact
import DASHI.Physics.YangMills.BalabanClayT5PhysicalClusterMomentCompactnessExact

-- Exact status split for configured arithmetic, Bishop integration and leaves.
import DASHI.Physics.YangMills.BalabanClayConfiguredFrontierCompletionLedger
import DASHI.Physics.YangMills.BalabanClayBishopFrontierCompletionLedger

-- User-run authoritative typecheck receipt surface.
import DASHI.Physics.YangMills.BalabanClayBranchHeadReceiptSurface
