module DASHI.Physics.YangMills.BalabanClayGate4ParameterizedEffectiveActionExact where

------------------------------------------------------------------------
-- SLOW-PARAMETERIZED EFFECTIVE ACTION GENERATED BY THE PHYSICAL T-OPERATION
--
-- P3's FiniteEffectiveAction uses a coarse-independent Fine -> Scalar weight.
-- The live Gate4 physical density is explicitly slow-dependent, so identifying
-- those carriers directly would be false plumbing.
--
-- This owner defines the exact effective-action object matching the physical
-- Gate4 carrier:
--
--   A_phys(scale,selected,slow)
--     = -log(T_phys(scale,selected,slow) 1)
--
-- and proves by the supplied exp(-log(.)) law that exponentiating that action
-- returns the SAME localized physical T-operation.
------------------------------------------------------------------------

open import Agda.Builtin.Equality using (_≡_)
open import Data.Rational.Base using (ℚ)

open import DASHI.Physics.YangMills.CompactLieProofLevel
import DASHI.Physics.YangMills.BalabanClayGate4CanonicalRationalPhysicalTExact as PhysicalT
import DASHI.Physics.YangMills.BalabanClayGate4ComponentClassAndFiniteTOperationExact as T

record ParameterizedPhysicalEffectiveAction
    {Scale Fine SlowField Component Functional EffectiveAction : Set}
    (construction :
      PhysicalT.CanonicalRationalPhysicalTConstruction
        Scale Fine SlowField Component Functional) : Set₁ where
  field
    negativeLog : ℚ → EffectiveAction
    exponentialOfNegativeAction : EffectiveAction → ℚ

    exponentialNegativeLog : ∀ scalar →
      exponentialOfNegativeAction (negativeLog scalar) ≡ scalar

open ParameterizedPhysicalEffectiveAction public

generatedPhysicalEffectiveAction :
  ∀ {Scale Fine SlowField Component Functional EffectiveAction}
    {construction :
      PhysicalT.CanonicalRationalPhysicalTConstruction
        Scale Fine SlowField Component Functional} →
  ParameterizedPhysicalEffectiveAction
    {EffectiveAction = EffectiveAction} construction →
  (scale : Scale) →
  T.SecondClassComponent
    (T.classData (PhysicalT.canonicalPhysicalTData construction))
    scale →
  SlowField →
  EffectiveAction
generatedPhysicalEffectiveAction {construction = construction}
  dataSet scale selected slow =
  negativeLog dataSet
    (T.localizedTOperation
      (PhysicalT.canonicalPhysicalTData construction)
      scale selected slow
      (T.oneFunctional
        (PhysicalT.canonicalPhysicalTData construction)))

generatedPhysicalEffectiveActionDefinesTOperation :
  ∀ {Scale Fine SlowField Component Functional EffectiveAction}
    {construction :
      PhysicalT.CanonicalRationalPhysicalTConstruction
        Scale Fine SlowField Component Functional}
    (dataSet :
      ParameterizedPhysicalEffectiveAction
        {EffectiveAction = EffectiveAction} construction)
    (scale : Scale)
    (selected :
      T.SecondClassComponent
        (T.classData (PhysicalT.canonicalPhysicalTData construction))
        scale)
    (slow : SlowField) →
  exponentialOfNegativeAction dataSet
    (generatedPhysicalEffectiveAction dataSet scale selected slow)
  ≡
  T.localizedTOperation
    (PhysicalT.canonicalPhysicalTData construction)
    scale selected slow
    (T.oneFunctional
      (PhysicalT.canonicalPhysicalTData construction))
generatedPhysicalEffectiveActionDefinesTOperation
  dataSet scale selected slow =
  exponentialNegativeLog dataSet _

parameterizedPhysicalEffectiveActionCompilerLevel : ProofLevel
parameterizedPhysicalEffectiveActionCompilerLevel = machineChecked

generatedPhysicalEffectiveActionDefinesTOperationLevel : ProofLevel
generatedPhysicalEffectiveActionDefinesTOperationLevel = machineChecked

-- Physical scalar backend leaf: instantiate negativeLog/exp(-.) on the chosen
-- scalar/effective-action carrier.  The theorem above itself is generic.
physicalNegativeLogExponentialBackendLevel : ProofLevel
physicalNegativeLogExponentialBackendLevel = conditional
