module DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119Round214ExponentialFiniteSemanticsValidation where

open import Agda.Builtin.Equality using (_≡_; refl)
open import DASHI.Physics.YangMills.CompactLieProofLevel
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119Round214ExponentialFiniteSemanticsExact as P

path4FiniteCompilerOwned :
  P.path4BetaDrivenCMP119Round214ExponentialFiniteSemanticsCompilerLevel ≡ machineChecked
path4FiniteCompilerOwned = refl

path4ExpectationIntegralCompilerOwned :
  P.path4BetaDrivenCMP119Round214ExponentialExpectationIntegralCompilerLevel ≡ machineChecked
path4ExpectationIntegralCompilerOwned = refl

path4ObservableEvaluationRemainsPhysical :
  P.path4BetaDrivenCMP119Round214ExponentialObservableEvaluationLevel ≡ conditional
path4ObservableEvaluationRemainsPhysical = refl
