{-# OPTIONS --safe #-}
module DASHI.Physics.YangMills.BalabanA2LiteralSameHistoryPrefixSensitivityRound103Exact where

------------------------------------------------------------------------
-- ROUND103 A2: LITERAL SHELL SENSITIVITIES -> CUMULATIVE SAME-HISTORY q
--
-- For two shooting inputs u,v, compare the beta coefficients generated by their
-- two literal CMP109 histories at the same shell.  If
--
--   |beta_j(u)-beta_j(v)| <= q_j |u-v|,
-- then finite triangle inequality gives
--   |B_K(u)-B_K(v)| <= (sum_{j<K} q_j) |u-v|.
--
-- This removes cumulative-prefix Lipschitzness as an independent physical
-- premise.  The remaining source task is shellwise response on the literal
-- generated histories plus the already-developed cutoff-independent q-sum gate.
------------------------------------------------------------------------

open import Agda.Builtin.Equality using (_≡_; refl)
open import Agda.Builtin.Nat using (Nat; zero; suc)
open import Relation.Binary.PropositionalEquality using (cong; sym; trans)

open import DASHI.Foundations.RealAnalysisAxioms using
  ( ℝ; 0ℝ; _+ℝ_; _-ℝ_; _*ℝ_; absℝ; _≤ℝ_
  ; ≤ℝ-refl; +-mono-≤; absZero; absAddSubadditive
  ; *-distribʳ-+; +-identityˡ; subAddDistributes )
open import DASHI.Physics.YangMills.CompactLieProofLevel
import DASHI.Physics.YangMills.BalabanCutoffBetaLaw as BetaLaw
import DASHI.Physics.YangMills.BalabanEffectiveCouplingTrajectory as Trajectory
import DASHI.Physics.YangMills.BalabanBetaPrefixSensitivityToTubeContractionExact as Shoot

sumReal : (Nat → ℝ) → Nat → ℝ
sumReal f zero = 0ℝ
sumReal f (suc n) = sumReal f n +ℝ f n

sumScaleRight :
  (f : Nat → ℝ) (d : ℝ) → ∀ K →
  sumReal (λ j → f j *ℝ d) K ≡ sumReal f K *ℝ d
sumScaleRight f d zero = sym (DASHI.Foundations.RealAnalysisAxioms.mulZeroˡ d)
sumScaleRight f d (suc n) =
  trans
    (cong (_+ℝ (f n *ℝ d)) (sumScaleRight f d n))
    (sym (*-distribʳ-+ (sumReal f n) (f n) d))

record LiteralSameHistoryShellSensitivity (TubePoint : Set) (K : Nat) : Set₁ where
  field
    initialInverseSquare : TubePoint → ℝ
    dynamics : TubePoint → BetaLaw.BalabanCutoffCouplingDynamics K

    shellSensitivity : Nat → ℝ

    -- Only physical shells are consumed.  The generated beta correction is the
    -- exact CMP109 coefficient already wired through `BalabanCutoffBetaLaw`.
    shellLipschitz : ∀ u v j →
      absℝ
        (Trajectory.betaCorrection
            (BetaLaw.step (dynamics u)) (suc j)
          -ℝ Trajectory.betaCorrection
            (BetaLaw.step (dynamics v)) (suc j))
      ≤ℝ shellSensitivity j *ℝ
          absℝ (initialInverseSquare u -ℝ initialInverseSquare v)

open LiteralSameHistoryShellSensitivity public

betaPrefixAt :
  ∀ {TubePoint K} →
  LiteralSameHistoryShellSensitivity TubePoint K → TubePoint → Nat → ℝ
betaPrefixAt dataSet point zero = 0ℝ
betaPrefixAt dataSet point (suc n) =
  betaPrefixAt dataSet point n
    +ℝ Trajectory.betaCorrection
      (BetaLaw.step (dynamics dataSet point)) (suc n)

prefixDifferenceBound :
  ∀ {TubePoint K}
    (dataSet : LiteralSameHistoryShellSensitivity TubePoint K)
    u v n →
  absℝ (betaPrefixAt dataSet u n -ℝ betaPrefixAt dataSet v n)
  ≤ℝ sumReal (shellSensitivity dataSet) n *ℝ
      absℝ (initialInverseSquare dataSet u -ℝ initialInverseSquare dataSet v)
prefixDifferenceBound dataSet u v zero =
  let
    differenceZero = DASHI.Foundations.RealAnalysisAxioms.subSelf 0ℝ
    leftZero = trans (cong absℝ differenceZero) absZero
    rightZero = DASHI.Foundations.RealAnalysisAxioms.mulZeroˡ
      (absℝ (initialInverseSquare dataSet u -ℝ initialInverseSquare dataSet v))
  in
  DASHI.Foundations.RealAnalysisAxioms.≤ℝ-replace-both
    (sym leftZero) (sym rightZero) ≤ℝ-refl
prefixDifferenceBound dataSet u v (suc n) =
  let
    bu = betaPrefixAt dataSet u n
    bv = betaPrefixAt dataSet v n
    eu = Trajectory.betaCorrection
      (BetaLaw.step (dynamics dataSet u)) (suc n)
    ev = Trajectory.betaCorrection
      (BetaLaw.step (dynamics dataSet v)) (suc n)
    distance = absℝ
      (initialInverseSquare dataSet u -ℝ initialInverseSquare dataSet v)

    split = subAddDistributes bu eu bv ev
    triangle = absAddSubadditive (bu -ℝ bv) (eu -ℝ ev)
    ih = prefixDifferenceBound dataSet u v n
    shell = shellLipschitz dataSet u v n
    added = +-mono-≤ ih shell
  in
  DASHI.Foundations.RealAnalysisAxioms.≤ℝ-replace-both
    (cong absℝ split)
    (sym (*-distribʳ-+ (sumReal (shellSensitivity dataSet) n)
      (shellSensitivity dataSet n) distance))
    (DASHI.Foundations.RealAnalysisAxioms.≤ℝ-trans triangle added)

record LiteralSameHistoryShootingData (TubePoint : Set) (K : Nat) : Set₁ where
  field
    shells : LiteralSameHistoryShellSensitivity TubePoint K
    renormalisationMap : TubePoint → TubePoint
    renormalisedInverseSquare : ℝ

    mapHasLiteralPrefixFormula : ∀ u →
      initialInverseSquare shells (renormalisationMap u)
      ≡ renormalisedInverseSquare +ℝ betaPrefixAt shells u K

open LiteralSameHistoryShootingData public

asBetaPrefixShootingMap :
  ∀ {TubePoint K} →
  LiteralSameHistoryShootingData TubePoint K → Shoot.BetaPrefixShootingMap TubePoint
asBetaPrefixShootingMap dataSet = record
  { Shoot.BetaPrefixShootingMap.initialInverseSquare =
      initialInverseSquare (shells dataSet)
  ; Shoot.BetaPrefixShootingMap.renormalisationMap = renormalisationMap dataSet
  ; Shoot.BetaPrefixShootingMap.renormalisedInverseSquare =
      renormalisedInverseSquare dataSet
  ; Shoot.BetaPrefixShootingMap.cumulativeBeta =
      λ u → betaPrefixAt (shells dataSet) u _
  ; Shoot.BetaPrefixShootingMap.mapHasSourceFormula =
      mapHasLiteralPrefixFormula dataSet
  }

literalCumulativePrefixSensitivity :
  ∀ {TubePoint K}
    (dataSet : LiteralSameHistoryShootingData TubePoint K) u v →
  absℝ
    (Shoot.cumulativeBeta (asBetaPrefixShootingMap dataSet) u
      -ℝ Shoot.cumulativeBeta (asBetaPrefixShootingMap dataSet) v)
  ≤ℝ sumReal (shellSensitivity (shells dataSet)) K *ℝ
      absℝ
        (Shoot.initialInverseSquare (asBetaPrefixShootingMap dataSet) u
          -ℝ Shoot.initialInverseSquare (asBetaPrefixShootingMap dataSet) v)
literalCumulativePrefixSensitivity dataSet =
  prefixDifferenceBound (shells dataSet)

a2ShellToCumulativeSensitivityLevel : ProofLevel
a2ShellToCumulativeSensitivityLevel = machineChecked

-- Physical source leaf after this compiler: prove the shellwise `shellLipschitz`
-- coefficients on pairs of literal generated CMP109 histories and instantiate
-- their finite/cutoff-uniform sum by the existing mixed-Cauchy + cubic-drift +
-- irrelevant-response gate.  No independent cumulative-Lipschitz theorem remains.
literalCMP109SameHistoryShellSensitivityLevel : ProofLevel
literalCMP109SameHistoryShellSensitivityLevel = conditional
