module DASHI.Physics.YangMills.BalabanClayLiteralFrontierProducerBundle where

-- One import surface for the literal T2--T5 producer tranche.  The individual
-- modules keep their remaining local analytic hypotheses explicit; this bundle
-- performs no proof-level promotion by import alone.

-- Canonical authors/title/venue/DOI/arXiv/section/relationship metadata and a
-- theorem-disconnected quarantine for unverified completion claims.
import DASHI.Physics.YangMills.BalabanClayLiteralFrontierVerifiedLiteratureExact
import DASHI.Physics.YangMills.BalabanClayConfiguredVerifiedLiteratureExact
import DASHI.Physics.YangMills.BalabanClayLiteralFrontierQuarantinedClaims

-- Shared rational/Taylor interval carriers, generic remainder-to-enclosure and
-- negative-log-sinc reductions, configured coefficients, the elementary-real
-- adapter, the common alternating-series/log/positive-exp-tail authority, and
-- the single canonical extension of DASHI's existing real carrier.
import DASHI.Foundations.RealElementaryFunctionsAlternatingSeriesExact
import DASHI.Foundations.RealElementaryFunctionsCanonicalInstanceExact
import DASHI.Physics.YangMills.BalabanClayCommonCertifiedTaylorEnclosureExact
import DASHI.Physics.YangMills.BalabanClayCommonTaylorRemainderToEnclosureExact
import DASHI.Physics.YangMills.BalabanClayCommonNegativeLogSincReductionExact
import DASHI.Physics.YangMills.BalabanClayCommonRationalSincCertificateExact
import DASHI.Physics.YangMills.BalabanClayCommonLogSixteenCertificateExact
import DASHI.Physics.YangMills.BalabanClayCommonElementaryRealInhabitantsExact

-- T3: reference coercivity, exact chart singular values, fixed finite atom
-- lists for plaquette/transport/chart/gauge/block estimates, configured common
-- radius, actual periodic-torus bond kernels and Fourier/image carriers, and
-- physical Green decay.
import DASHI.Physics.YangMills.BalabanClayT3PhysicalUniformFluctuationCoercivityExact
import DASHI.Physics.YangMills.BalabanClayT3LiteralPhysicalCoercivityProducerExact
import DASHI.Physics.YangMills.BalabanClayT3LiteralBackgroundHessianRemaindersExact
import DASHI.Physics.YangMills.BalabanClayT3LiteralSU2ChartIntervalBoundsExact
import DASHI.Physics.YangMills.BalabanClayT3RightJacobianSampleCheckExact
import DASHI.Physics.YangMills.BalabanClayT3LiteralFiveRemainderConstantsExact
import DASHI.Physics.YangMills.BalabanClayT3LiteralCommonRadiusWitnessExact
import DASHI.Physics.YangMills.BalabanClayT3ConfiguredGeometricConstantsExact
import DASHI.Physics.YangMills.BalabanClayT3ConfiguredFiveHessianDominationExact
import DASHI.Physics.YangMills.BalabanClayT3LiteralPointwiseHessianEstimatesExact
import DASHI.Physics.YangMills.BalabanClayT3ConfiguredFiniteAtomListsExact
import DASHI.Physics.YangMills.BalabanClayT3ConfiguredCommonRadiusCertificateExact
import DASHI.Physics.YangMills.BalabanClayT3PhysicalGreenCombesThomasExact
import DASHI.Physics.YangMills.BalabanClayT3ConfiguredPhysicalGreenInstanceExact
import DASHI.Physics.YangMills.BalabanClayT3LiteralHessianFourierImageInstanceExact
import DASHI.Physics.YangMills.BalabanClayT3PeriodicTorusGreenCarrierExact
import DASHI.Physics.YangMills.BalabanClayT3ConfiguredPhysicalGatewayExact

-- T2: action gain, all five non-action losses, strict one-fifth robustness,
-- literal Haar/trace-class closure, generated four-link quaternion jets,
-- rooted physical encoding, concrete periodic block/list/tree/traversal carrier,
-- breadth-first extraction, patch masks and FP geometry.
import DASHI.Physics.YangMills.BalabanClayT2LiteralWilsonSixFactorProducerExact
import DASHI.Physics.YangMills.BalabanClayT2LiteralActivityLossConstantsExact
import DASHI.Physics.YangMills.BalabanClayT2LiteralPhysicalLossWitnessExact
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredActionGainThresholdExact
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredComponentLossBoundsExact
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredModelSpecificLossClosureExact
import DASHI.Physics.YangMills.BalabanClayT2LiteralHaarTraceClassClosureExact
import DASHI.Physics.YangMills.BalabanClayT2QuaternionCubicEnumerationExact
import DASHI.Physics.YangMills.BalabanClayT2GeneratedQuaternionJetExact
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredLossBudgetCertificateExact
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredStrictLossMarginExact
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredRobustOneSixteenthEndpointExact
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredPhysicalLossInstanceExact
import DASHI.Physics.YangMills.BalabanClayT2LiteralEightWayCliqueExact
import DASHI.Physics.YangMills.BalabanClayT2PhysicalRootedPolymerEncodingExact
import DASHI.Physics.YangMills.BalabanClayT2PhysicalPolymerCarrierInstanceExact
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredPhysicalPolymerCarrierExact
import DASHI.Physics.YangMills.BalabanClayT2RepositoryConnectedPolymerExtractionExact
import DASHI.Physics.YangMills.BalabanClayT2RepositoryBreadthFirstTreeInstanceExact
import DASHI.Physics.YangMills.BalabanClayT2PeriodicBlockPolymerCarrierExact

-- T4: localized projector, literal momentum-space Wilson/ghost/Haar vertices,
-- Ward cancellation, transverse scalar reduction, Balaban targets, generated
-- normalized 4^4 rational grid, and proof-producing Brillouin-box receipts.
import DASHI.Physics.YangMills.BalabanClayT4LocalizedPlaquetteCoefficientProducerExact
import DASHI.Physics.YangMills.BalabanClayT4LiteralVacuumPolarizationIntegralExact
import DASHI.Physics.YangMills.BalabanClayT4LiteralOneLoopCoefficientClosureExact
import DASHI.Physics.YangMills.BalabanClayT4LiteralDiagramWardCancellationExact
import DASHI.Physics.YangMills.BalabanClayT4LiteralMomentumDiagramBoxDataExact
import DASHI.Physics.YangMills.BalabanClayT4GeneratedBrillouinGridExact
import DASHI.Physics.YangMills.BalabanClayT4Balaban1987TheoremShapeExact
import DASHI.Physics.YangMills.BalabanClayT4Balaban536VacuumPolarizationTargetExact
import DASHI.Physics.YangMills.BalabanClayT4ConfiguredBrillouinIntegralCertificateExact
import DASHI.Physics.YangMills.BalabanClayT4ConfiguredBrillouinBoxReceiptFamilyExact
import DASHI.Physics.YangMills.BalabanClayT4ConfiguredPhysicalOneLoopInstanceExact

-- T5: staged thermodynamic/continuum tails, explicit dyadic geometric tails,
-- finite-tail arithmetic, physical boundary/defect/moment/marginal adapters,
-- compactness, projective consistency, uniqueness and complete OS Gram forms.
import DASHI.Physics.YangMills.BalabanClayT5ThermodynamicUniformIntegrabilityExact
import DASHI.Physics.YangMills.BalabanClayT5PhysicalMeasureGramContinuityExact
import DASHI.Physics.YangMills.BalabanClayT5QuantitativeTailMomentCompactnessExact
import DASHI.Physics.YangMills.BalabanClayT5ConfiguredGeometricTailExact
import DASHI.Physics.YangMills.BalabanClayT5RootedShellBoundaryTailExact
import DASHI.Physics.YangMills.BalabanClayT5BoundaryContinuumMomentMeasureExact
import DASHI.Physics.YangMills.BalabanClayT5ConfiguredPhysicalTailMomentInstanceExact

-- Exact status split for the newly configured arithmetic and remaining leaves.
import DASHI.Physics.YangMills.BalabanClayConfiguredFrontierCompletionLedger

-- User-run authoritative typecheck receipt surface.
import DASHI.Physics.YangMills.BalabanClayBranchHeadReceiptSurface
