module DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119Equation171FiniteSemanticsValidation where

open import Agda.Builtin.Equality using (_≡_; refl)
open import DASHI.Physics.YangMills.CompactLieProofLevel
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119Equation171FiniteSemanticsExact as P

path4FiniteCompilerOwned :
  P.path4BetaDrivenCMP119Equation171FiniteSemanticsCompilerLevel ≡ machineChecked
path4FiniteCompilerOwned = refl

path4ExpectationIntegralCompilerOwned :
  P.path4BetaDrivenCMP119Equation171ExpectationIntegralCompilerLevel ≡ machineChecked
path4ExpectationIntegralCompilerOwned = refl

path4ObservableEvaluationRemainsPhysical :
  P.path4BetaDrivenCMP119Equation171ObservableEvaluationLevel ≡ conditional
path4ObservableEvaluationRemainsPhysical = refl
