module DASHI.Physics.YangMills.BalabanClayConstructiveProducerAdvance where

import DASHI.Physics.YangMills.BalabanClayP1PicardBackgroundConstructionExact
import DASHI.Physics.YangMills.BalabanClayT1CommonAnalyticContractionExact
import DASHI.Physics.YangMills.BalabanClayP2BadComponentGeometryExact
import DASHI.Physics.YangMills.BalabanClayT2WilsonActivityFactorProductExact
import DASHI.Physics.YangMills.BalabanClayT2TraversalRootedShellExact
import DASHI.Physics.YangMills.BalabanClayT2ClusterCriterionComparisonExact
import DASHI.Physics.YangMills.BalabanClayT2EightWayFernandezProcacciExact
import DASHI.Physics.YangMills.BalabanClayT2UrsellCauchyExact
import DASHI.Physics.YangMills.BalabanClayP3FiniteConstrainedIntegralExact
import DASHI.Physics.YangMills.BalabanClayP3PrincipalFibreCoordinatesExact
import DASHI.Physics.YangMills.BalabanClayT3CompactHaarLimitExact
import DASHI.Physics.YangMills.BalabanClayT3OperatorSchurComplementExact
import DASHI.Physics.YangMills.BalabanClayT3UniformFluctuationSchurExact
import DASHI.Physics.YangMills.BalabanClayT3PhysicalUniformFluctuationCoercivityExact
import DASHI.Physics.YangMills.BalabanClayT3SchurWardBetaExact
import DASHI.Physics.YangMills.BalabanClayT3WardIdentityLiteratureExact
import DASHI.Physics.YangMills.BalabanClayT4BetaNormalizationConventionExact
import DASHI.Physics.YangMills.BalabanClayT4RunningCouplingConventionBridgeExact
import DASHI.Physics.YangMills.BalabanClayT4SUNWilsonActionConventionExact
import DASHI.Physics.YangMills.BalabanClayT4CanonicalScalarWitnessExact
import DASHI.Physics.YangMills.BalabanClayT5PhysicalMassTransportExact
import DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact
import DASHI.Physics.YangMills.BalabanClayT5OSGramTopologyExact
import DASHI.Physics.YangMills.BalabanClayT5OSGramClosedPropertyExact
import DASHI.Physics.YangMills.BalabanClayLiteratureNormalizationLedger

-- Literal producer tranche.  The bundle contains the new finite proofs,
-- explicit analytic input records, and fail-closed frontier ledger.
import DASHI.Physics.YangMills.BalabanClayLiteralFrontierProducerBundle
import DASHI.Physics.YangMills.BalabanClayLiteralFrontierCompletionLedger

-- Gate-4 large-field archaeology, numerical dependency graph, model-suitability
-- quarantine and mass-gap anti-circularity audit.  These modules reference the
-- existing small-field/RG/numerical owners rather than creating parallel proofs.
import DASHI.Physics.YangMills.BalabanClayLargeFieldVerifiedLiteratureExact
import DASHI.Physics.YangMills.BalabanClayNumericalIngredientDependencyAuditExact
import DASHI.Physics.YangMills.BalabanClayGate4LargeFieldArchaeologyExact
import DASHI.Physics.YangMills.BalabanClayExternalModelAndFailureAuditExact
import DASHI.Physics.YangMills.BalabanClayGate4AndNumericalAuditCompletionLedger
