module DASHI.Physics.YangMills.BalabanClayConfiguredFrontierCompletionLedger where

open import DASHI.Physics.YangMills.CompactLieProofLevel

import DASHI.Physics.YangMills.BalabanClayCommonTaylorRemainderToEnclosureExact as Taylor
import DASHI.Physics.YangMills.BalabanClayCommonNegativeLogSincReductionExact as NegLog
import DASHI.Physics.YangMills.BalabanClayCommonRationalSincCertificateExact as Sinc
import DASHI.Physics.YangMills.BalabanClayCommonLogSixteenCertificateExact as Log16
import DASHI.Physics.YangMills.BalabanClayCommonElementaryRealInhabitantsExact as Elementary
import DASHI.Physics.YangMills.BalabanClayT3RightJacobianSampleCheckExact as Sample
import DASHI.Physics.YangMills.BalabanClayT3ConfiguredGeometricConstantsExact as Geometry
import DASHI.Physics.YangMills.BalabanClayT3ConfiguredFiveHessianDominationExact as Hessian
import DASHI.Physics.YangMills.BalabanClayT3ConfiguredCommonRadiusCertificateExact as Radius
import DASHI.Physics.YangMills.BalabanClayT3PhysicalGreenCombesThomasExact as Green
import DASHI.Physics.YangMills.BalabanClayT3ConfiguredPhysicalGreenInstanceExact as GreenInstance
import DASHI.Physics.YangMills.BalabanClayT3ConfiguredPhysicalGatewayExact as T3Gateway
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredActionGainThresholdExact as Action
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredComponentLossBoundsExact as Components
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredModelSpecificLossClosureExact as ModelLoss
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredLossBudgetCertificateExact as Loss
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredStrictLossMarginExact as Margin
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredRobustOneSixteenthEndpointExact as RobustEndpoint
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredPhysicalLossInstanceExact as LossInstance
import DASHI.Physics.YangMills.BalabanClayT2ConfiguredPhysicalPolymerCarrierExact as Polymer
import DASHI.Physics.YangMills.BalabanClayT2RepositoryConnectedPolymerExtractionExact as PolymerExtraction
import DASHI.Physics.YangMills.BalabanClayT4Balaban1987TheoremShapeExact as BalabanShape
import DASHI.Physics.YangMills.BalabanClayT4Balaban536VacuumPolarizationTargetExact as Balaban536
import DASHI.Physics.YangMills.BalabanClayT4LiteralDiagramWardCancellationExact as Diagrams
import DASHI.Physics.YangMills.BalabanClayT4ConfiguredBrillouinIntegralCertificateExact as OneLoop
import DASHI.Physics.YangMills.BalabanClayT4ConfiguredBrillouinBoxReceiptFamilyExact as BoxReceipts
import DASHI.Physics.YangMills.BalabanClayT4ConfiguredPhysicalOneLoopInstanceExact as PhysicalOneLoop
import DASHI.Physics.YangMills.BalabanClayT5ConfiguredGeometricTailExact as Tail
import DASHI.Physics.YangMills.BalabanClayT5RootedShellBoundaryTailExact as ShellTail

------------------------------------------------------------------------
-- I. Exact configured arithmetic, finite reductions and physical adapters.
------------------------------------------------------------------------

symmetricRemainderReductionLevel = Taylor.symmetricRemainderReductionLevel
alternatingBracketReductionLevel = Taylor.alternatingBracketReductionLevel
negativeLogSincReductionLevel = NegLog.negativeLogSincReductionLevel
configuredRationalCoefficientLevel = Sinc.configuredRationalCoefficientLevel
configuredHornerIdentityLevel = Sinc.configuredHornerIdentityLevel
logSixteenFinitePartialSumArithmeticLevel =
  Log16.logSixteenFinitePartialSumArithmeticLevel
logSixteenMonotoneReductionLevel = Log16.logSixteenMonotoneReductionLevel

configuredSineCosineReductionLevel =
  Elementary.configuredSineCosineReductionLevel
configuredSincDivisionReductionLevel =
  Elementary.configuredSincDivisionReductionLevel
configuredNegativeLogReductionLevel =
  Elementary.configuredNegativeLogReductionLevel
configuredLogSixteenAuthorityAdapterLevel =
  Elementary.configuredLogSixteenAuthorityAdapterLevel

rightJacobianSampleRationalLevel = Sample.rightJacobianSampleRationalLevel
rightJacobianSampleReductionLevel = Sample.rightJacobianSampleReductionLevel
configuredIncidenceDataLevel = Geometry.configuredIncidenceDataLevel
configuredCoefficientArithmeticLevel = Geometry.configuredCoefficientArithmeticLevel
localToGlobalRemainderReductionLevel =
  Hessian.localToGlobalRemainderReductionLevel
fiveConfiguredDominationAdapterLevel =
  Hessian.fiveConfiguredDominationAdapterLevel
configuredCommonRadiusArithmeticLevel = Radius.configuredCommonRadiusArithmeticLevel
configuredFiveRemaindersBelowHalfLevel = Radius.configuredFiveRemaindersBelowHalfLevel
localCombesThomasReductionLevel = Green.localCombesThomasReductionLevel
fourierRGImageAssemblyLevel = Green.fourierRGImageAssemblyLevel
configuredCombesThomasArithmeticLevel =
  GreenInstance.configuredCombesThomasArithmeticLevel
configuredLocalGreenAdapterLevel = GreenInstance.configuredLocalGreenAdapterLevel
configuredFourierRGImageReductionLevel =
  GreenInstance.configuredFourierRGImageReductionLevel
configuredT3LocalToCoerciveGatewayLevel =
  T3Gateway.configuredT3LocalToCoerciveGatewayLevel
configuredT3CoerciveToGreenGatewayLevel =
  T3Gateway.configuredT3CoerciveToGreenGatewayLevel

configuredActionThresholdArithmeticLevel =
  Action.configuredActionThresholdArithmeticLevel
configuredActionGainReductionLevel = Action.configuredActionGainReductionLevel
configuredComponentArithmeticLevel = Components.configuredComponentArithmeticLevel
configuredComponentBudgetReductionLevel =
  Components.configuredComponentBudgetReductionLevel
haarPhysicalReductionLevel = ModelLoss.haarPhysicalReductionLevel
localizedTraceLogReductionLevel = ModelLoss.localizedTraceLogReductionLevel
quaternionPhysicalReductionLevel = ModelLoss.quaternionPhysicalReductionLevel
localizationPatchReductionLevel = ModelLoss.localizationPatchReductionLevel
configuredLossArithmeticLevel = Loss.configuredLossArithmeticLevel
configuredComponentSumReductionLevel = Loss.configuredComponentSumReductionLevel
configuredLogSixteenReductionLevel = Loss.configuredLogSixteenReductionLevel
configuredOneSixteenthAssemblyLevel = Loss.configuredOneSixteenthAssemblyLevel
sharpPartialSumArithmeticLevel = Margin.sharpPartialSumArithmeticLevel
configuredOneFifthRobustnessReductionLevel =
  Margin.configuredOneFifthRobustnessReductionLevel
configuredRobustActivityEndpointLevel =
  RobustEndpoint.configuredRobustActivityEndpointLevel
configuredEmbeddedLossInstanceLevel = LossInstance.configuredEmbeddedLossInstanceLevel

configuredPatchDirectionMaskLevel = Polymer.configuredPatchDirectionMaskLevel
configuredInteriorEightCountLevel = Polymer.configuredInteriorEightCountLevel
configuredCanonicalTraceAdapterLevel = Polymer.configuredCanonicalTraceAdapterLevel
canonicalRootTreeAlgorithmReductionLevel =
  PolymerExtraction.canonicalRootTreeAlgorithmReductionLevel
canonicalDecoderInjectivityLevel =
  PolymerExtraction.canonicalDecoderInjectivityLevel
configuredTraceFamilyAdapterLevel =
  PolymerExtraction.configuredTraceFamilyAdapterLevel

balabanTheorem1ArchitectureLevel = BalabanShape.balabanTheorem1ArchitectureLevel
balabanLocalizationConventionLevel = BalabanShape.balabanLocalizationConventionLevel
balaban031ComparisonReductionLevel = BalabanShape.balaban031ComparisonReductionLevel
balaban536LaurentReductionLevel = Balaban536.balaban536LaurentReductionLevel
balaban537MomentumReductionLevel = Balaban536.balaban537MomentumReductionLevel
balaban541CoefficientExtractionLevel = Balaban536.balaban541CoefficientExtractionLevel
literalVertexReductionLevel = Diagrams.literalVertexReductionLevel
literalDiagramCombinationLevel = Diagrams.literalDiagramCombinationLevel
literalWardCancellationLevel = Diagrams.literalWardCancellationLevel
literalTransverseScalarReductionLevel = Diagrams.literalTransverseScalarReductionLevel
universalColorCoefficientArithmeticLevel = OneLoop.universalColorCoefficientArithmeticLevel
brillouinBoxSummationReductionLevel = OneLoop.brillouinBoxSummationReductionLevel
configuredPlaquetteCoefficientAssemblyLevel =
  OneLoop.configuredPlaquetteCoefficientAssemblyLevel
boxReceiptConstructionLevel = BoxReceipts.boxReceiptConstructionLevel
finiteBoxFamilyAssemblyLevel = BoxReceipts.finiteBoxFamilyAssemblyLevel
configuredIntegralAdapterLevel = BoxReceipts.configuredIntegralAdapterLevel
literalDiagramCoherenceReductionLevel =
  PhysicalOneLoop.literalDiagramCoherenceReductionLevel
configuredBoxToBalabanCoefficientReductionLevel =
  PhysicalOneLoop.configuredBoxToBalabanCoefficientReductionLevel
balaban031EndpointReductionLevel = PhysicalOneLoop.balaban031EndpointReductionLevel

configuredDyadicTailArithmeticLevel = Tail.configuredDyadicTailArithmeticLevel
configuredBoundaryTailReductionLevel = Tail.configuredBoundaryTailReductionLevel
configuredContinuumTailReductionLevel = Tail.configuredContinuumTailReductionLevel
rootedShellTailIdentificationLevel = ShellTail.rootedShellTailIdentificationLevel
rootedShellToBoundaryTailReductionLevel =
  ShellTail.rootedShellToBoundaryTailReductionLevel

------------------------------------------------------------------------
-- II. Remaining primitive analytic and model-specific inhabitants.
------------------------------------------------------------------------

elementaryTaylorLogExpInputsLevel = Elementary.elementaryTaylorLogExpInputsLevel
positiveExponentialTailAndLogInputsLevel =
  Margin.positiveExponentialTailAndLogInputsLevel
literalSampleSineEvaluationInputsLevel = Sample.literalSampleSineEvaluationInputsLevel
literalLocalPointwiseAndIncidenceInputsLevel =
  Hessian.literalLocalPointwiseAndIncidenceInputsLevel
literalLocalHessianGapFourierImageInputsLevel =
  T3Gateway.literalLocalHessianGapFourierImageInputsLevel
literalFiniteRangeGapAndFourierImageInputsLevel =
  GreenInstance.literalFiniteRangeGapAndFourierImageInputsLevel
periodicRandomWalkTransferInputsLevel = Green.periodicRandomWalkTransferInputsLevel
physicalLargeFieldPlaquetteAndBetaInputsLevel =
  Action.physicalLargeFieldPlaquetteAndBetaInputsLevel
literalLinkTraceQuaternionCollarPatchInputsLevel =
  ModelLoss.literalLinkTraceQuaternionCollarPatchInputsLevel
physicalAdditionalLossBelowOneFifthInputsLevel =
  RobustEndpoint.physicalAdditionalLossBelowOneFifthInputsLevel
physicalActionAndComponentInputsLevel =
  LossInstance.physicalActionAndComponentInputsLevel
physicalLossDominationInputsLevel = Loss.physicalLossDominationInputsLevel
repositoryOrderConnectivityAndDecoderInputsLevel =
  PolymerExtraction.repositoryOrderConnectivityAndDecoderInputsLevel
literalWilsonGhostHaarFormulaInputsLevel =
  Diagrams.literalWilsonGhostHaarFormulaInputsLevel
literalDiagramNumeratorDenominatorAndQuadratureInputsLevel =
  BoxReceipts.literalDiagramNumeratorDenominatorAndQuadratureInputsLevel
literalDiagramIntegrandAndQuarticInputsLevel =
  PhysicalOneLoop.literalDiagramIntegrandAndQuarticInputsLevel
literalDiagramToBalabanTargetInputsLevel =
  Balaban536.literalDiagramToBalabanTargetInputsLevel
literalDASHIMainAndQuarticInputsLevel =
  BalabanShape.literalDASHIMainAndQuarticInputsLevel
physicalClusterDiameterInputsLevel = Tail.physicalClusterDiameterInputsLevel
boundaryEscapeInputsLevel = ShellTail.boundaryEscapeInputsLevel
physicalExponentialMomentCompactnessInputsLevel =
  Tail.physicalExponentialMomentCompactnessInputsLevel
