module DASHI.Physics.YangMills.BalabanClayConstructiveProducerSubmissionRound8Advance where

import DASHI.Physics.YangMills.BalabanBishopRatioMonotoneTermsExact
import DASHI.Physics.YangMills.BalabanBishopAlternatingFirstOmittedExact
import DASHI.Physics.YangMills.BalabanP06CanonicalAnimalConstantExact
import DASHI.Physics.YangMills.BalabanP06A1A2A3InfluenceExact
import DASHI.Physics.YangMills.BalabanP11PrefixTailMinimumExact
import DASHI.Physics.YangMills.BalabanStepVCanonicalAnimalMarginExact
import DASHI.Physics.YangMills.BalabanStepVGeometricInfluenceSummationExact
import DASHI.Physics.YangMills.YangMillsSubmissionRound8SourceAudit
import DASHI.Physics.YangMills.YangMillsSubmissionRound8Ledger
import DASHI.Physics.YangMills.YangMillsSubmissionRound8Receipt
import DASHI.Physics.YangMills.YangMillsSubmissionRound8Validation
