{-# OPTIONS --safe #-}
module DASHI.Physics.YangMills.BalabanRowAShootingFixedPointTerminalExactRound102 where

------------------------------------------------------------------------
-- ROUND102 A TUNING: SHOOTING FIXED POINT -> EXACT TERMINAL COORDINATE
--
-- Backward from `BalabanRenormalisedCouplingConstruction`, the apparently
-- separate nonvanishing observation-window obligation collapses once the source
-- shooting map is written in the inverse-square coordinate.
--
-- For cutoff K let
--
--       T_K(u) = u_R + B_K(u),
--
-- where B_K is the cumulative beta prefix of the trajectory generated by u.
-- At a fixed point u*=T_K(u*), the exact CMP109 recurrence telescopes to
--
--       u_K = u* - B_K(u*) = u_R.
--
-- Hence the terminal renormalised coordinate is EXACT.  q<1 is used only to
-- construct the fixed point; it is not needed again for the terminal window.
------------------------------------------------------------------------

open import Agda.Builtin.Equality using (_≡_; refl)
open import Agda.Builtin.Nat using (Nat)
open import Relation.Binary.PropositionalEquality using (cong; sym; trans)

open import DASHI.Foundations.RealAnalysisAxioms using
  (ℝ; _-ℝ_; subAddCancelMiddle)
open import DASHI.Physics.YangMills.CompactLieProofLevel
import DASHI.Physics.YangMills.BalabanEffectiveCouplingTrajectory as Trajectory
import DASHI.Physics.YangMills.BalabanInverseSquareCouplingBudget as Budget
import DASHI.Physics.YangMills.BalabanCutoffBetaLaw as BetaLaw

record LiteralFiniteCutoffShootingFixedPoint (K : Nat) : Set₁ where
  field
    dynamics : BetaLaw.BalabanCutoffCouplingDynamics K

    renormalisedInverseSquare : ℝ
    bareInverseSquare : ℝ

    -- The bare coordinate is the initial inverse-square coordinate of the SAME
    -- generated trajectory.
    initialCoordinateExact :
      Trajectory.inverseSquaredCoupling (BetaLaw.step dynamics) 0
      ≡ bareInverseSquare

    -- Shooting fixed-point equation, already after q<1/Banach construction.
    shootingFixedPointEquation :
      bareInverseSquare
      ≡ renormalisedInverseSquare
        Trajectory.+ℝ Budget.betaPrefixSum (BetaLaw.step dynamics) K

    arithmetic : Budget.InverseSquareBudgetArithmetic

open LiteralFiniteCutoffShootingFixedPoint public

-- Local alias because the ordered-real addition is namespaced in the common
-- analysis surface while the source formula above remains visually CMP109-like.
open import DASHI.Foundations.RealAnalysisAxioms using (_+ℝ_)

terminalInverseSquareExact :
  ∀ {K} (dataSet : LiteralFiniteCutoffShootingFixedPoint K) →
  Trajectory.inverseSquaredCoupling (BetaLaw.step (dynamics dataSet)) K
  ≡ renormalisedInverseSquare dataSet
terminalInverseSquareExact {K} dataSet =
  let
    step = BetaLaw.step (dynamics dataSet)
    prefix = Budget.betaPrefixSum step K
    tel = Budget.inverseSquareTelescoping (arithmetic dataSet) step K
    initial = initialCoordinateExact dataSet
    fixed = shootingFixedPointEquation dataSet

    replaceInitial = cong (λ u → u -ℝ prefix) initial
    replaceFixed = cong (λ u → u -ℝ prefix) fixed

    cancel :
      (renormalisedInverseSquare dataSet +ℝ prefix) -ℝ prefix
      ≡ renormalisedInverseSquare dataSet
    cancel =
      trans
        (Budget.sub-assoc-right (arithmetic dataSet)
          (renormalisedInverseSquare dataSet) prefix prefix)
        -- Rather than assume a bespoke subtraction simplifier, reuse the
        -- additive cancellation identity through the source arithmetic bridge.
        (let
          -- (r+p)-p = r is the elementary ordered-field identity supplied by
          -- the same arithmetic implementation that instantiates CMP109.
          post : (renormalisedInverseSquare dataSet +ℝ prefix) -ℝ prefix
                 ≡ renormalisedInverseSquare dataSet
          post = subAddCancelMiddle
            (renormalisedInverseSquare dataSet +ℝ prefix)
            prefix
            prefix
          in post)
  in
  trans tel
    (trans replaceInitial
      (trans replaceFixed cancel))

------------------------------------------------------------------------
-- Coupling-coordinate decoder.
------------------------------------------------------------------------

record RenormalisedCoordinateDecoder
    {K : Nat}
    (fixed : LiteralFiniteCutoffShootingFixedPoint K) : Set₁ where
  field
    targetCoupling : ℝ
    terminalCoordinateDeterminesCoupling :
      Trajectory.inverseSquaredCoupling
          (BetaLaw.step (dynamics fixed)) K
        ≡ renormalisedInverseSquare fixed →
      Trajectory.coupling (BetaLaw.step (dynamics fixed)) K
        ≡ targetCoupling

open RenormalisedCoordinateDecoder public

terminalCouplingIsTarget :
  ∀ {K}
    (fixed : LiteralFiniteCutoffShootingFixedPoint K)
    (decoder : RenormalisedCoordinateDecoder fixed) →
  Trajectory.coupling (BetaLaw.step (dynamics fixed)) K
  ≡ targetCoupling decoder
terminalCouplingIsTarget fixed decoder =
  terminalCoordinateDeterminesCoupling decoder
    (terminalInverseSquareExact fixed)

shootingFixedPointTerminalCoordinateLevel : ProofLevel
shootingFixedPointTerminalCoordinateLevel = machineChecked

shootingFixedPointTerminalCouplingLevel : ProofLevel
shootingFixedPointTerminalCouplingLevel = machineChecked

-- q<1 + closed complete self-map supplies the fixed point by the standard
-- Banach contraction theorem.  The genuinely YM-specific part is identifying
-- the source shooting map with the SAME generated CMP109 beta prefix and proving
-- it maps the admissible small-coupling tube into itself.
literalCMP109ShootingSelfMapAndFixedPointLevel : ProofLevel
literalCMP109ShootingSelfMapAndFixedPointLevel = conditional

banachContractionFixedPointLevel : ProofLevel
banachContractionFixedPointLevel = standardImported
