{-# OPTIONS --safe #-}
module DASHI.Physics.YangMills.BalabanOSIndexedTransferCoordinateRound331Exact where

------------------------------------------------------------------------
-- ROUND331 / MAKE "SAME HAMILTONIAN" PROOF-RELEVANT
--
-- R311's historical `SameHamiltonianTransferCoordinate` stores an arbitrary
-- Hamiltonian beside an arbitrary transfer-energy/decay-ratio coordinate.  The
-- record name therefore promises more than its fields prove: mere pairing does
-- not establish that the coordinate is the transfer coordinate OF that
-- Hamiltonian.
--
-- The preferred carrier below is indexed by the actual OS reconstruction and
-- retains the missing semantic coordinate as proof-bearing data.  Projection to
-- R311 is compiler-owned; the physical `TransferCoordinateOf` witness remains
-- the one genuine H3 application theorem.
------------------------------------------------------------------------

open import Agda.Builtin.Bool using (Bool; true; false)
open import Agda.Builtin.Equality using (_≡_; refl)

open import DASHI.Physics.YangMills.CompactLieProofLevel
import DASHI.Physics.YangMills.BalabanOSMassGapClosure as OS
import DASHI.Physics.YangMills.BalabanTransferEnergyDecayRatioCoordinateRound302Exact as R302
import DASHI.Physics.YangMills.BalabanPairwiseMassRateFromTransferCoordinateRound311Exact as R311

record OSIndexedTransferCoordinate
    {Observable Point Scalar : Set}
    {system : OS.ContinuumSchwingerSystem Observable Point Scalar}
    (reconstruction : OS.OSReconstructionAuthority Observable Point Scalar system)
    (Energy : Set) : Set₁ where
  field
    coordinate : R302.TransferEnergyDecayRatioCoordinate Energy

    -- Physical semantics, not bookkeeping: the chosen order-reversing decay
    -- coordinate is the transfer/semigroup energy coordinate generated by the
    -- SAME Hamiltonian produced by this OS reconstruction.
    TransferCoordinateOf :
      OS.Hamiltonian reconstruction →
      R302.TransferEnergyDecayRatioCoordinate Energy → Set

    coordinateOfReconstructedHamiltonian :
      TransferCoordinateOf (OS.hamiltonian reconstruction) coordinate

open OSIndexedTransferCoordinate public

------------------------------------------------------------------------
-- The clustering-free version is the direct H2-core/H3 interface.  Its
-- Hamiltonian is definitionally the H2 pre-gap reconstructed Hamiltonian.
-- The actual transfer-semigroup meaning remains proof-bearing physical data.
------------------------------------------------------------------------

record PreGapOSIndexedTransferCoordinate
    {Observable Point Scalar : Set}
    {system : OS.PreGapContinuumSchwingerSystem Observable Point Scalar}
    (reconstruction :
      OS.PreGapOSReconstructionAuthority Observable Point Scalar system)
    (Energy : Set) : Set₁ where
  field
    coordinateCore : R302.TransferEnergyDecayRatioCoordinate Energy

    TransferCoordinateOfCore :
      OS.HamiltonianCore reconstruction →
      R302.TransferEnergyDecayRatioCoordinate Energy → Set

    coordinateOfReconstructedHamiltonianCore :
      TransferCoordinateOfCore
        (OS.hamiltonianCore reconstruction) coordinateCore

open PreGapOSIndexedTransferCoordinate public

preGapAsSameHamiltonianTransferCoordinate :
  ∀ {Observable Point Scalar Energy}
    {system : OS.PreGapContinuumSchwingerSystem Observable Point Scalar}
    (reconstruction :
      OS.PreGapOSReconstructionAuthority Observable Point Scalar system) →
  PreGapOSIndexedTransferCoordinate reconstruction Energy →
  R311.SameHamiltonianTransferCoordinate
    (OS.HamiltonianCore reconstruction) Energy
preGapAsSameHamiltonianTransferCoordinate reconstruction source = record
  { R311.SameHamiltonianTransferCoordinate.reconstructedHamiltonian =
      OS.hamiltonianCore reconstruction
  ; R311.SameHamiltonianTransferCoordinate.coordinate =
      coordinateCore source
  }


asHistoricalSameHamiltonianTransferCoordinate :
  ∀ {Observable Point Scalar Energy}
    {system : OS.ContinuumSchwingerSystem Observable Point Scalar}
    (reconstruction : OS.OSReconstructionAuthority Observable Point Scalar system) →
  OSIndexedTransferCoordinate reconstruction Energy →
  R311.SameHamiltonianTransferCoordinate
    (OS.Hamiltonian reconstruction) Energy
asHistoricalSameHamiltonianTransferCoordinate reconstruction dataSet = record
  { R311.SameHamiltonianTransferCoordinate.reconstructedHamiltonian =
      OS.hamiltonian reconstruction
  ; R311.SameHamiltonianTransferCoordinate.coordinate = coordinate dataSet
  }

record Round331Boundary : Set where
  constructor round331-boundary
  field
    arbitraryHamiltonianCoordinatePairingProvesSameObject : Bool
    arbitraryHamiltonianCoordinatePairingProvesSameObjectIsFalse :
      arbitraryHamiltonianCoordinatePairingProvesSameObject ≡ false

    osHamiltonianSelectedDefinitionally : Bool
    osHamiltonianSelectedDefinitionallyIsTrue :
      osHamiltonianSelectedDefinitionally ≡ true

    transferCoordinateOfWitnessStillPhysical : Bool
    transferCoordinateOfWitnessStillPhysicalIsTrue :
      transferCoordinateOfWitnessStillPhysical ≡ true

    projectionToHistoricalR311CompilerOwned : Bool
    projectionToHistoricalR311CompilerOwnedIsTrue :
      projectionToHistoricalR311CompilerOwned ≡ true

canonicalRound331Boundary : Round331Boundary
canonicalRound331Boundary =
  round331-boundary false refl true refl true refl true refl

round331OSIndexedTransferAdapterLevel : ProofLevel
round331OSIndexedTransferAdapterLevel = machineChecked

-- This is H3 after the representation repair.  No second Hamiltonian equality
-- is required; the theorem is exactly that the selected decay/energy coordinate
-- is generated by the reconstructed transfer semigroup/Hamiltonian.
round331PhysicalTransferCoordinateOfOSHamiltonianLevel : ProofLevel
round331PhysicalTransferCoordinateOfOSHamiltonianLevel = conditional

round331PreGapOSIndexedTransferCompilerLevel : ProofLevel
round331PreGapOSIndexedTransferCompilerLevel = machineChecked

round331PreGapPhysicalSemigroupIdentificationLevel : ProofLevel
round331PreGapPhysicalSemigroupIdentificationLevel = conditional
