module DASHI.Physics.YangMills.BalabanCMP116MinimalDistanceLiteralHessianRound385Validation where

import DASHI.Physics.YangMills.BalabanCMP116MinimalDistanceLiteralHessianRound385Exact
import DASHI.Physics.YangMills.BalabanCMP116MinimalFixedPointDistanceRound384Exact
import DASHI.Physics.YangMills.BalabanCMP116DistanceUpperHessianBidiRound379Exact
import DASHI.Physics.YangMills.BalabanCMP109116LiteralDifferentiatedCarrierRound103Exact
