module DASHI.Physics.YangMills.BalabanCMP116ParametricSubstitutionMarkedSourceRound378Validation where

import DASHI.Physics.YangMills.BalabanCMP116ParametricSubstitutionMarkedSourceRound378Exact
import DASHI.Physics.YangMills.BalabanCMP116CanonicalSubstitutionDistanceAttachmentRound377Exact
import DASHI.Physics.YangMills.BalabanCMP116SubstitutionHessianBidiRound376Exact
import DASHI.Physics.YangMills.BalabanCMP116HessianBidiBridgeRound375Exact
import DASHI.Physics.YangMills.BalabanCMP116PublishedParametricFixedPointRound371Exact
