module DASHI.Physics.YangMills.Everything where

-- Authoritative Yang--Mills lane rollup.
-- Keep leaf modules out of DASHI.Everything; aggregate them here first.

import DASHI.Physics.YangMills.ClayPromotionAuthorityGate
import DASHI.Physics.YangMills.P01P33ProofSurfaces
import DASHI.Physics.YangMills.YMSupportGraphDistance
import DASHI.Physics.YangMills.MassGapSpectralStatement
import DASHI.Physics.YangMills.OSAxiomBundle

-- Step-V / RG surfaces that the closure audit found were previously unwired.
import DASHI.Physics.YangMills.PostulateInventory
import DASHI.Physics.YangMills.BalabanStepVSpatialKPCertificate
import DASHI.Physics.YangMills.BalabanRGStepVLane
import DASHI.Physics.YangMills.O4CovarianceRestorationGate
import DASHI.Physics.YangMills.YMMassGapRoute
import DASHI.Physics.YangMills.BalabanClayGate4LightweightValidation

-- Existing theorem-level high-alpha route consumed by the operator/domain weld.
import DASHI.Physics.YangMills.BalabanCMP98Equation119PositiveBondSelectedCutFederbushRound184Exact
import DASHI.Physics.YangMills.BalabanCMP98SelectedPhysicalUnitCarrierRound187Exact
import DASHI.Physics.YangMills.BalabanCMP98RawUnitPathHomomorphismRound189Exact
import DASHI.Physics.YangMills.BalabanCMP98Equation119CanonicalP4CutRadiusFirewallExact
import DASHI.Physics.YangMills.BalabanCMP98Equation119PointwiseSemanticSelectedCutExact
import DASHI.Physics.YangMills.BalabanCMP98Equation119DisjunctivePhysicalSourceCutExact
import DASHI.Physics.YangMills.BalabanCMP98Path13PerturbationCarrierWeldExact
import DASHI.Physics.YangMills.BalabanCMP98Equation119TwoCarrierSelectedBondExact
import DASHI.Physics.YangMills.BalabanRationalUnitQuaternionRealLieAdjointExact
import DASHI.Physics.YangMills.BalabanCMP98Equation119GeometryRelativeContourExact
import DASHI.Physics.YangMills.BalabanCMP98Path13TwoCarrierSourceFamilyExact
import DASHI.Physics.YangMills.BalabanPath13CanonicalBondCenteredEmbeddingExact
import DASHI.Physics.YangMills.BalabanPath13RadiusSixWalkAgreementExact
import DASHI.Physics.YangMills.BalabanCMP98Path13ReducedFamilyGeometryExact
import DASHI.Physics.YangMills.BalabanCMP98Path13RelativeContourPrincipalImageExact
import DASHI.Physics.YangMills.BalabanPath13RadiusOperatorDefectRouteExact
import DASHI.Physics.YangMills.BalabanPath13RadiusPrincipalImageRouteExact
import DASHI.Physics.YangMills.BalabanPath13SelectedVariationalRadiusExact
import DASHI.Physics.YangMills.BalabanPath13SelectedBackgroundRadiusFibreExact
import DASHI.Physics.YangMills.BalabanPath13SelectedBackgroundOperatorChartExact
import DASHI.Physics.YangMills.BalabanCMP98Path13ReducedTwoCarrierSourceFamilyExact
import DASHI.Physics.YangMills.BalabanCMP98Path13VariationalRadiusSourceFamilyExact
import DASHI.Physics.YangMills.BalabanR208BishopLegacyRingEmbeddingExact
import DASHI.Physics.YangMills.BalabanCMP98Path13BishopBridgeSourceFamilyExact
import DASHI.Physics.YangMills.BalabanCMP98Path13DirectCalculusSourceFamilyExact
import DASHI.Physics.YangMills.BalabanCMP98Path13PreferredDirectCalculusSourceFamilyExact
import DASHI.Physics.YangMills.BalabanCMP98Path13UniformCalculusDecompositionExact
import DASHI.Physics.YangMills.BalabanCMP98Path13SplitCalculusPreferredSourceFamilyExact
import DASHI.Physics.YangMills.BalabanCMP98Path13DexpInversePairExact
import DASHI.Physics.YangMills.BalabanCMP98Path13ReducedAdjointExpFamilyExact
import DASHI.Physics.YangMills.BalabanCMP98Path13MinimalSemanticCalculusExact
import DASHI.Physics.YangMills.BalabanCMP98Path13PreferredMinimalSemanticSourceFamilyExact

-- Source-sign correction: the printed CMP98 Eq. (119) roles are
-- dexpPlus/Jplus/Ad(exp), despite historical compatibility field names.
import DASHI.Physics.YangMills.BalabanCMP98Path13PrintedSemanticOperatorsExact
import DASHI.Physics.YangMills.BalabanCMP98Path13PrintedRoleSourceFamilyExact
import DASHI.Physics.YangMills.BalabanCMP98Path13PrintedOperatorChartWeldExact
import DASHI.Physics.YangMills.BalabanCMP98Path13PreferredPrintedRoleSourceFamilyExact
import DASHI.Physics.YangMills.BalabanPath13Eq119PrintedRoleCorrectionProvenanceExact

-- T3 right-Jacobian cross-pollination into the corrected printed-role path.
import DASHI.Physics.YangMills.BalabanCMP98Path13T3PrintedOperatorAdapterExact
import DASHI.Physics.YangMills.BalabanCMP98Path13T3SelectedPrintedSemanticsExact
import DASHI.Physics.YangMills.BalabanCMP98Path13PreferredT3PrintedRoleSourceFamilyExact
import DASHI.Physics.YangMills.BalabanPath13Eq119T3PrintedRoleProvenanceExact

-- Preferred T3 scalar boundary: Eq. (119) consumes only the rational->legacy
-- ring embedding. Bishop completeness/convergence remains a compatibility
-- producer, not a primitive Path13 source payment.
import DASHI.Physics.YangMills.BalabanCMP98Path13PreferredT3MinimalScalarSourceFamilyExact
import DASHI.Physics.YangMills.BalabanPath13Eq119T3MinimalScalarProvenanceExact

-- Split Path13 physics from R171's source-independent standard representation.
import DASHI.Physics.YangMills.BalabanPath13SplitPhysicalStandardOperatorCutExact
import DASHI.Physics.YangMills.BalabanPath13SplitPhysicalPrincipalImageRouteExact
import DASHI.Physics.YangMills.BalabanCMP98Path13SplitT3SelectedSemanticsExact
import DASHI.Physics.YangMills.BalabanCMP98Path13PreferredSplitPhysicalT3SourceFamilyExact
import DASHI.Physics.YangMills.BalabanPath13Eq119SplitPhysicalStandardProvenanceExact

-- Direct source-theorem specialization to the literal Path13 carrier.
import DASHI.Physics.YangMills.BalabanPath13VariationalSpecializationExact
import DASHI.Physics.YangMills.BalabanPath13VariationalRadiusFromSpecializationExact

-- Align the selected/cut defect algebra with the R171 operator kernel itself.
import DASHI.Physics.YangMills.BalabanR171OperatorKernelGroupDefectAdapterExact
import DASHI.Physics.YangMills.BalabanPath13R171AlignedVariationalRouteExact

-- Least-privilege current source: minimal printed semantics plus direct 74-link
-- cut budget (37/1024 <= selected radius). T3 and 1/24 are compatibility paths.
import DASHI.Physics.YangMills.BalabanPath13DirectRelative74CutExact
import DASHI.Physics.YangMills.BalabanCMP98Path13PreferredR171AlignedPrintedSourceExact

-- Newest canonical status surface for the source-correct preferred route.
import DASHI.Physics.YangMills.BalabanCMP98Path13CurrentPreferredSourceFrontierExact

import DASHI.Physics.YangMills.BalabanPath13Eq119SourceRouteProvenanceExact
import DASHI.Physics.YangMills.BalabanPath13Eq119BishopBridgeProvenanceExact
import DASHI.Physics.YangMills.BalabanPath13Eq119DirectCalculusProvenanceExact
import DASHI.Physics.YangMills.BalabanPath13Eq119SplitCalculusProvenanceExact
import DASHI.Physics.YangMills.BalabanPath13Eq119MinimalSemanticProvenanceExact
import DASHI.Physics.YangMills.BalabanCMP98Equation119RecoveredShortestSourceCutExact
import DASHI.Physics.Closure.YMStrictSelectedHodgeVariationPairing
import DASHI.Physics.YangMills.BalabanVacuumOrthogonalMoscoRecoveryExact
import DASHI.Physics.YangMills.BalabanClayDenseCoreSpectralGapExact
import DASHI.Physics.YangMills.BalabanOSExponentialClusteringImpliesHamiltonianGapExact
import DASHI.Physics.YangMills.BalabanClayHighestAlphaReuseExact
import DASHI.Physics.YangMills.BalabanClayMassGapGatePackageExact

-- Receipt-vs-theorem terminal audit.
import DASHI.Physics.YangMills.BalabanCMP98Equation119ClayTerminalBidiRound186Exact
import DASHI.Physics.YangMills.BalabanCMP98TerminalHamiltonianBidiRound188Exact
import DASHI.Physics.YangMills.BalabanCMP98ClayBoundarySupersessionRound190Exact

-- September 2026 bidirectional Lean/Agda operator-domain cross-pollination.
import DASHI.Physics.YangMills.YMOperatorDomainContinuumSources2026Exact
import DASHI.Physics.YangMills.YMAristotleOperatorReturn2026Exact
import DASHI.Physics.YangMills.YMOperatorDomainContinuumFrontier2026Exact
