{-# OPTIONS --safe #-}
module DASHI.Physics.YangMills.YangMillsPreferredSameHamiltonianTransferRound577Exact where

------------------------------------------------------------------------
-- GOAL-1 B2 / ROUND577:
-- SAME-HAMILTONIAN IS A CONSTRUCTOR FACT; TRANSFER-COORDINATE SEMANTICS IS PHYSICAL
--
-- R331 is the correct proof-relevant carrier:
--
--   reconstruction : OS reconstruction
--   coordinate     : energy <-> decay-ratio coordinate
--   proof          : coordinate is generated by THAT reconstruction's H.
--
-- Projection to the historical R311 pair is compiler-owned and chooses
--
--   reconstructedHamiltonian := OS.hamiltonian reconstruction
--
-- definitionally.  Therefore the remaining B2 theorem is not a Hamiltonian
-- equality.  It is exactly the physical transfer/semigroup calibration of the
-- energy-decay coordinate on the reconstructed H.
------------------------------------------------------------------------

open import Agda.Builtin.Bool using (Bool; false; true)

open import DASHI.Physics.YangMills.CompactLieProofLevel

import DASHI.Physics.YangMills.BalabanOSMassGapClosure as OS
import DASHI.Physics.YangMills.BalabanOSIndexedTransferCoordinateRound331Exact as R331
import DASHI.Physics.YangMills.BalabanPairwiseMassRateFromTransferCoordinateRound311Exact as R311
import DASHI.Physics.YangMills.BalabanTransferEnergyDecayRatioCoordinateRound302Exact as R302

record PreferredSameHamiltonianTransfer
    {Observable Point Scalar : Set}
    {system : OS.ContinuumSchwingerSystem Observable Point Scalar}
    (reconstruction :
      OS.OSReconstructionAuthority Observable Point Scalar system)
    (Energy : Set)
    : Set₁ where
  field
    transfer :
      R331.OSIndexedTransferCoordinate reconstruction Energy

open PreferredSameHamiltonianTransfer public

asHistoricalR311 :
  ∀ {Observable Point Scalar Energy}
    {system : OS.ContinuumSchwingerSystem Observable Point Scalar}
    {reconstruction :
      OS.OSReconstructionAuthority Observable Point Scalar system} →
  PreferredSameHamiltonianTransfer reconstruction Energy →
  R311.SameHamiltonianTransferCoordinate
    (OS.Hamiltonian reconstruction) Energy
asHistoricalR311 {reconstruction = reconstruction} source =
  R331.asHistoricalSameHamiltonianTransferCoordinate
    reconstruction
    (transfer source)

selectedHamiltonianIsReconstructedByConstruction : Bool
selectedHamiltonianIsReconstructedByConstruction = true

postHocHamiltonianEqualityRequired : Bool
postHocHamiltonianEqualityRequired = false

independentMassRateCoordinateRequired : Bool
independentMassRateCoordinateRequired = false

round577SameHamiltonianProjectionCompilerLevel : ProofLevel
round577SameHamiltonianProjectionCompilerLevel =
  R331.round331OSIndexedTransferAdapterLevel

-- This is the genuine B2 physical theorem.
literalRound577TransferCoordinateOfReconstructedHamiltonianLevel : ProofLevel
literalRound577TransferCoordinateOfReconstructedHamiltonianLevel =
  R331.round331PhysicalTransferCoordinateOfOSHamiltonianLevel

-- Positivity of the half-rate candidate after the coordinate is supplied is
-- already compiler-owned by the local energy/rate calculus.
round577CandidateGapPositivityCompilerLevel : ProofLevel
round577CandidateGapPositivityCompilerLevel =
  R302.round302PhysicalTransferEnergyDecayCoordinateLevel
