{-# OPTIONS --safe #-}
module DASHI.Physics.YangMills.YangMillsOSReconstructedTransferCoordinateTheoremExact where

------------------------------------------------------------------------
-- B2 theorem-bearing constructor.
--
-- The Hamiltonian is not an independent argument: it is definitionally the
-- Hamiltonian of the supplied OS reconstruction.  The only physical theorem is
-- that the chosen energy/decay coordinate is generated by that Hamiltonian.
------------------------------------------------------------------------

import DASHI.Physics.YangMills.BalabanOSMassGapClosure as OS
import DASHI.Physics.YangMills.BalabanOSIndexedTransferCoordinateRound331Exact as R331
import DASHI.Physics.YangMills.BalabanTransferEnergyDecayRatioCoordinateRound302Exact as R302
import DASHI.Physics.YangMills.YangMillsPreferredSameHamiltonianTransferRound577Exact as R577

literalOSIndexedTransferCoordinate :
  ∀ {Observable Point Scalar Energy}
    {system : OS.ContinuumSchwingerSystem Observable Point Scalar}
    (reconstruction :
      OS.OSReconstructionAuthority Observable Point Scalar system)
    (coordinate : R302.TransferEnergyDecayRatioCoordinate Energy)
    (TransferCoordinateOf :
      OS.Hamiltonian reconstruction →
      R302.TransferEnergyDecayRatioCoordinate Energy → Set)
    (coordinateOfReconstructedHamiltonian :
      TransferCoordinateOf (OS.hamiltonian reconstruction) coordinate) →
  R331.OSIndexedTransferCoordinate reconstruction Energy
literalOSIndexedTransferCoordinate
    reconstruction coordinate TransferCoordinateOf
    coordinateOfReconstructedHamiltonian = record
  { R331.OSIndexedTransferCoordinate.coordinate = coordinate
  ; R331.OSIndexedTransferCoordinate.TransferCoordinateOf =
      TransferCoordinateOf
  ; R331.OSIndexedTransferCoordinate.coordinateOfReconstructedHamiltonian =
      coordinateOfReconstructedHamiltonian
  }

literalPreferredSameHamiltonianTransfer :
  ∀ {Observable Point Scalar Energy}
    {system : OS.ContinuumSchwingerSystem Observable Point Scalar}
    {reconstruction :
      OS.OSReconstructionAuthority Observable Point Scalar system} →
  R331.OSIndexedTransferCoordinate reconstruction Energy →
  R577.PreferredSameHamiltonianTransfer reconstruction Energy
literalPreferredSameHamiltonianTransfer transfer = record
  { R577.PreferredSameHamiltonianTransfer.transfer = transfer
  }
