module DASHI.Physics.YangMills.YMClayAristotleGapParityEverything where

-- Focused rollup for the post-#987 Aristotle donor reconciliation. This is
-- intentionally separate from the historical global Yang-Mills rollup so the
-- cross-prover authority boundary remains inspectable.

import DASHI.Physics.YangMills.YMClayAristotleDonorAtlasExact
import DASHI.Physics.YangMills.YMClayVacuumSectorSpectralGapParityExact
import DASHI.Physics.YangMills.YMClayLiteralSU2LatticeDonorExact
import DASHI.Physics.YangMills.YMClayVaryingCarrierTransportParityExact
import DASHI.Physics.YangMills.YMClayUniformGapReductionParityExact
import DASHI.Physics.YangMills.YMClayCorrelationCriterionParityExact
import DASHI.Physics.YangMills.YMClayCorrelationCriterionParityValidation
import DASHI.Physics.YangMills.YMClayDenseL2CorrelationBidiParityExact
import DASHI.Physics.YangMills.YMClayDenseL2CorrelationBidiParityValidation
import DASHI.Physics.YangMills.YMClayDenseMarkedSourceF1ProducerExact
import DASHI.Physics.YangMills.YMClayDenseMarkedSourceF1ProducerValidation
import DASHI.Physics.YangMills.YMClayR295MarkedSourceAdapterExact
import DASHI.Physics.YangMills.YMClayR295MarkedSourceAdapterValidation
import DASHI.Physics.YangMills.YMClayF1PhysicalMinCutExact
import DASHI.Physics.YangMills.YMClayF1WilsonR295SameObjectWeldExact
import DASHI.Physics.YangMills.YMClayF1WilsonR295SameObjectWeldValidation
import DASHI.Physics.YangMills.YMClayF1TranslatedPairL2CalibrationExact
import DASHI.Physics.YangMills.YMClayF1TranslatedPairL2CalibrationValidation
import DASHI.Physics.YangMills.YMClayF1PhysicalMinCutValidation
import DASHI.Physics.YangMills.YMClayUrsellTransferMixingBoundaryExact
import DASHI.Physics.YangMills.YMClayUrsellTransferMixingBoundaryValidation
import DASHI.Physics.YangMills.YMClayF1MixingSourceAuditExact
import DASHI.Physics.YangMills.YMClayF1MixingSourceAuditValidation
import DASHI.Physics.YangMills.YMClayCompleteDensityTransferMixingBoundaryExact
import DASHI.Physics.YangMills.YMClayCompleteDensityTransferMixingBoundaryValidation
import DASHI.Physics.YangMills.YMClayCMSDrellYanEmpiricalContactBoundaryExact
import DASHI.Physics.YangMills.YMClayCMSDrellYanEmpiricalContactBoundaryValidation
import DASHI.Physics.YangMills.YMClayDirectSourceOSMassGapFrontierExact
import DASHI.Physics.YangMills.YMClayDirectSourceOSMassGapFrontierValidation
import DASHI.Physics.YangMills.YMClayRouteSSelectedLimitClosureExact
import DASHI.Physics.YangMills.YMClayRouteSSelectedLimitClosureValidation
import DASHI.Physics.YangMills.YMClayRouteSH1DirectSelectedMarkedDecayExact
import DASHI.Physics.YangMills.YMClayRouteSH1DirectSelectedMarkedDecayValidation
import DASHI.Physics.YangMills.YMClayOSLiteralStressRouteParetoExact
import DASHI.Physics.YangMills.YMClayOSLiteralStressRouteParetoValidation
import DASHI.Physics.YangMills.YMClayLevel2SameFamilyStressRecoveryExact
import DASHI.Physics.YangMills.YMClayLevel2SameFamilyStressRecoveryValidation
import DASHI.Physics.YangMills.YMClayLevel2WardRGReuseExact
import DASHI.Physics.YangMills.YMClayLevel2WardRGReuseValidation
import DASHI.Physics.YangMills.YMClayLevel2StressOPEMinCutExact
import DASHI.Physics.YangMills.YMClayLevel2StressOPEMinCutValidation
import DASHI.Physics.YangMills.YMClayLevel2OPECoefficientCoordinateWeldExact
import DASHI.Physics.YangMills.YMClayLevel2OPECoefficientCoordinateWeldValidation
import DASHI.Physics.YangMills.YMClayLevel2CompositeOperatorCoefficientWeldExact
import DASHI.Physics.YangMills.YMClayLevel2CompositeOperatorCoefficientWeldValidation
import DASHI.Physics.YangMills.YMClayLevel2LiteralOPECoefficientScaleAttachmentExact
import DASHI.Physics.YangMills.YMClayLevel2LiteralOPECoefficientScaleAttachmentValidation
import DASHI.Physics.YangMills.YMClayLevel2D2PhysicalMinCutExact
import DASHI.Physics.YangMills.YMClayLevel2D2PhysicalMinCutValidation
import DASHI.Physics.YangMills.YMClayLevel2R129CompositeOperatorAttachmentExact
import DASHI.Physics.YangMills.YMClayLevel2R129CompositeOperatorAttachmentValidation
import DASHI.Physics.YangMills.YMClayLevel2R129LiteralOPECoefficientWeldExact
import DASHI.Physics.YangMills.YMClayLevel2R129LiteralOPECoefficientWeldValidation
import DASHI.Physics.YangMills.YMClayLevel2ContinuumWardTransportExact
import DASHI.Physics.YangMills.YMClayLevel2ContinuumWardTransportValidation
import DASHI.Physics.YangMills.YMClayF3SprintConstructionFrontierExact
import DASHI.Physics.YangMills.YMClayF3SprintConstructionFrontierValidation
import DASHI.Physics.YangMills.YMClayPhysicalStressOSCommonCoreWitnessExact
import DASHI.Physics.YangMills.YMClayPhysicalStressOSCommonCoreWitnessValidation
import DASHI.Physics.YangMills.YMClayF134ContinuumWeldParityExact
import DASHI.Physics.YangMills.YMClayF134TypedCompositionValidation
import DASHI.Physics.YangMills.YMClayPhysicalF34TypedCompositionExact
import DASHI.Physics.YangMills.YMClayPhysicalF34TypedCompositionValidation
import DASHI.Physics.YangMills.YMClayClosedWorldResidualAudit20260917Exact
import DASHI.Physics.YangMills.YMClayFullPhysicalFormalismExact
import DASHI.Physics.YangMills.YMClayFullPhysicalFormalismValidation
import DASHI.Physics.YangMills.YMClayF1CanonicalSourceApplicationExact
import DASHI.Physics.YangMills.YMClayF1CanonicalSourceApplicationValidation
import DASHI.Physics.YangMills.YMClayR387PhysicalMassGapCertificateExact
import DASHI.Physics.YangMills.YMClayOutstandingPhysicalFrontierExact
import DASHI.Physics.YangMills.YMClayCanonicalMassGapConclusionExact
import DASHI.Physics.YangMills.YMClayTrancheProofLevelAuditValidation
import DASHI.Physics.YangMills.YMClayAristotleGapParityValidation

import DASHI.Physics.YangMills.YMClayAristotleRouteSLiteralWilsonDonorExact
import DASHI.Physics.YangMills.YMClayLiteralWilsonRouteSThreeInputBoundaryExact
import DASHI.Physics.YangMills.YMClayLiteralWilsonRouteSThreeInputBoundaryValidation
import DASHI.Physics.YangMills.YMClayLiteralLocalFieldsClosureExact
import DASHI.Physics.YangMills.YMClayLiteralTopDownRouteSClosureExact
import DASHI.Physics.YangMills.YMClayLiteralTopDownRouteSClosureValidation

import DASHI.Physics.YangMills.YMClayLiteralWilsonP1FiniteClusteringExact
import DASHI.Physics.YangMills.YMClayLiteralWilsonP2ExpectationConvergenceExact
import DASHI.Physics.YangMills.YMClayLiteralWilsonP3SameOSCorrelationExact
import DASHI.Physics.YangMills.YMClayLiteralWilsonP123ReductionValidation
import DASHI.Physics.YangMills.YMClayLevel2D2TransportGeneratedRecurrenceExact
import DASHI.Physics.YangMills.YMClayLevel2D2TransportGeneratedRecurrenceValidation

import DASHI.Physics.YangMills.YMClayLevel2D3ConservedWardChargeExact
import DASHI.Physics.YangMills.YMClayLevel2D3ConservedWardChargeValidation

import DASHI.Physics.YangMills.YMClayLiteralWilsonS2CanonicalProductPresentationExact
import DASHI.Physics.YangMills.YMClayLiteralWilsonS2CanonicalProductPresentationValidation
import DASHI.Physics.YangMills.YMClayLiteralWilsonS2SameAlgebraBoundExact
import DASHI.Physics.YangMills.YMClayLiteralWilsonS2SameAlgebraBoundValidation

import DASHI.Physics.YangMills.YMClayLevel2CompositeTransportABIInsufficiencyExact

import DASHI.Physics.YangMills.BalabanSU2RationalWilsonTraceBoundExact
import DASHI.Physics.YangMills.BalabanSU2RationalWilsonTraceBoundValidation
import DASHI.Physics.YangMills.YMClayLevel2D2R129CompositeConvergenceExact

import DASHI.Physics.YangMills.YMClayContinuumConstructionSameObjectBridgeExact
import DASHI.Physics.YangMills.YMClayContinuumConstructionSameObjectBridgeValidation

import DASHI.Physics.YangMills.BalabanYM4FiveChannelCauchyQuotientMajorantExact
import DASHI.Physics.YangMills.BalabanYM4FiveChannelTaylorCauchyClosureExact
import DASHI.Physics.YangMills.BalabanYM4FiveChannelTaylorCauchyClosureValidation

import DASHI.Physics.YangMills.BalabanClayT5ConfiguredDyadicTailSummationExact
import DASHI.Physics.YangMills.BalabanClayT5ConfiguredDyadicTailSummationValidation

import DASHI.Physics.YangMills.BalabanClayT5TypedContinuumDefectCauchyExact
import DASHI.Physics.YangMills.BalabanClayT5TypedContinuumDefectCauchyValidation

import DASHI.Physics.YangMills.BalabanClayT5MarkovToProkhorovTightnessExact
import DASHI.Physics.YangMills.BalabanClayT5MarkovToProkhorovTightnessValidation

import DASHI.Physics.YangMills.BalabanClayT5Path4MarkovProkhorovExact
import DASHI.Physics.YangMills.BalabanClayT5Path4MarkovProkhorovValidation

import DASHI.Physics.YangMills.BalabanFiniteRGProbabilityExpectationSemanticsExact
import DASHI.Physics.YangMills.BalabanFiniteRGProbabilityExpectationSemanticsValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4FiniteProbabilitySemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4FiniteProbabilitySemanticsValidation

import DASHI.Physics.YangMills.YMClayLiteralVocabularyNonPinningExact

import DASHI.Physics.YangMills.BalabanClayGate4ReferenceToFiniteRGProbabilityExact
import DASHI.Physics.YangMills.BalabanClayGate4ReferenceToFiniteRGProbabilityValidation
import DASHI.Physics.YangMills.BalabanClayP3CanonicalRationalConstrainedSumExact
import DASHI.Physics.YangMills.BalabanClayGate4CanonicalRationalPhysicalTExact
import DASHI.Physics.YangMills.BalabanClayGate4CanonicalRationalPhysicalTValidation

import DASHI.Physics.YangMills.BalabanClayGate4CanonicalRationalReferenceAlgebraExact
import DASHI.Physics.YangMills.BalabanClayGate4CanonicalRationalReferenceAlgebraValidation
import DASHI.Physics.YangMills.BalabanClayGate4PreferredRationalReferenceNormalizationExact
import DASHI.Physics.YangMills.BalabanClayGate4PreferredRationalReferenceNormalizationValidation


import DASHI.Physics.YangMills.BalabanFiniteProbabilityPartitionDisintegrationExact
import DASHI.Physics.YangMills.BalabanFiniteProbabilityPartitionDisintegrationValidation
import DASHI.Physics.YangMills.BalabanClayGate4ConstrainedReferenceKernelExact
import DASHI.Physics.YangMills.BalabanClayGate4ConstrainedReferenceKernelValidation
import DASHI.Physics.YangMills.BalabanFiniteConditionalMixtureReopeningExact
import DASHI.Physics.YangMills.BalabanFiniteConditionalMixtureReopeningValidation
import DASHI.Physics.YangMills.BalabanClayGate4ConditionalMixtureReopeningExact
import DASHI.Physics.YangMills.BalabanClayGate4ConditionalMixtureReopeningValidation
import DASHI.Physics.YangMills.BalabanFiniteVolumeConditionalGate4PresentationExact
import DASHI.Physics.YangMills.BalabanFiniteVolumeConditionalGate4PresentationValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4ConditionalGate4FiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4ConditionalGate4FiniteSemanticsValidation
import DASHI.Physics.YangMills.BalabanClayGate4ProbabilitySemanticCorrectionExact

import DASHI.Physics.YangMills.BalabanFinitePositiveWeightNormalizationExact
import DASHI.Physics.YangMills.BalabanFinitePositiveWeightNormalizationValidation
import DASHI.Physics.YangMills.BalabanClayGate4RawSlowDensityToProbabilityExact
import DASHI.Physics.YangMills.BalabanClayGate4RawSlowDensityToProbabilityValidation
import DASHI.Physics.YangMills.BalabanFiniteVolumeRawDensityGate4PresentationExact
import DASHI.Physics.YangMills.BalabanFiniteVolumeRawDensityGate4PresentationValidation
import DASHI.Physics.YangMills.BalabanCMP119FiniteSlowDensityRealizationExact
import DASHI.Physics.YangMills.BalabanCMP119FiniteSlowDensityRealizationValidation
import DASHI.Physics.YangMills.BalabanCMP119FiniteVolumeGate4PresentationExact
import DASHI.Physics.YangMills.BalabanCMP119FiniteVolumeGate4PresentationValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4CMP119FiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4CMP119FiniteSemanticsValidation

import DASHI.Physics.YangMills.BalabanCMP119AssembledFiniteSlowDensityExact
import DASHI.Physics.YangMills.BalabanCMP119AssembledFiniteSlowDensityValidation
import DASHI.Physics.YangMills.BalabanCMP119AssembledFiniteVolumeGate4PresentationExact
import DASHI.Physics.YangMills.BalabanCMP119AssembledFiniteVolumeGate4PresentationValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4CMP119AssembledFiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4CMP119AssembledFiniteSemanticsValidation

import DASHI.Physics.YangMills.BalabanCMP119Gate4ConstrainedMassWeldExact
import DASHI.Physics.YangMills.BalabanCMP119Gate4ConstrainedMassWeldValidation
import DASHI.Physics.YangMills.BalabanCMP119Gate4ConstrainedMassFiniteVolumePresentationExact
import DASHI.Physics.YangMills.BalabanCMP119Gate4ConstrainedMassFiniteVolumePresentationValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4CMP119ConstrainedMassFiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4CMP119ConstrainedMassFiniteSemanticsValidation

import DASHI.Physics.YangMills.BalabanClayGate4CanonicalPhysicalTOperationRationalNonnegativeExact
import DASHI.Physics.YangMills.BalabanClayGate4CanonicalPhysicalTOperationRationalNonnegativeValidation
import DASHI.Physics.YangMills.BalabanCMP119PhysicalTOperationWeldExact
import DASHI.Physics.YangMills.BalabanCMP119PhysicalTOperationWeldValidation
import DASHI.Physics.YangMills.BalabanCMP119PhysicalTOperationFiniteVolumePresentationExact
import DASHI.Physics.YangMills.BalabanCMP119PhysicalTOperationFiniteVolumePresentationValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4CMP119PhysicalTOperationFiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4CMP119PhysicalTOperationFiniteSemanticsValidation

import DASHI.Physics.YangMills.BalabanCMP119FiniteDensityAssemblySemanticsExact
import DASHI.Physics.YangMills.BalabanCMP119FiniteDensityAssemblySemanticsValidation
import DASHI.Physics.YangMills.BalabanCMP119PhysicalTOperationAssemblyRealizationExact
import DASHI.Physics.YangMills.BalabanCMP119PhysicalTOperationAssemblyRealizationValidation
import DASHI.Physics.YangMills.BalabanCMP119SplitPhysicalTOperationFiniteVolumePresentationExact
import DASHI.Physics.YangMills.BalabanCMP119SplitPhysicalTOperationFiniteVolumePresentationValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4CMP119SplitPhysicalTOperationFiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4CMP119SplitPhysicalTOperationFiniteSemanticsValidation

import DASHI.Physics.YangMills.BalabanCMP119Section2FiniteDensityEvaluationExact
import DASHI.Physics.YangMills.BalabanCMP119Section2FiniteDensityEvaluationValidation
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119FiniteDensityEvaluationExact
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119FiniteDensityEvaluationValidation
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119PhysicalTOperationFiniteVolumeExact
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119PhysicalTOperationFiniteVolumeValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119PhysicalTOperationFiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119PhysicalTOperationFiniteSemanticsValidation

import DASHI.Physics.YangMills.BalabanClayGate4ParameterizedEffectiveActionExact
import DASHI.Physics.YangMills.BalabanClayGate4ParameterizedEffectiveActionValidation
import DASHI.Physics.YangMills.BalabanCMP119PhysicalEffectiveActionRealizationExact
import DASHI.Physics.YangMills.BalabanCMP119PhysicalEffectiveActionRealizationValidation
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119GeneratedActionFiniteVolumeExact
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119GeneratedActionFiniteVolumeValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119GeneratedActionFiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119GeneratedActionFiniteSemanticsValidation

import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119Round214ActionEvaluationExact
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119Round214ActionEvaluationValidation
import DASHI.Physics.YangMills.BalabanCMP119Round214BackedPhysicalEffectiveActionExact
import DASHI.Physics.YangMills.BalabanCMP119Round214BackedPhysicalEffectiveActionValidation
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119Round214GeneratedActionFiniteVolumeExact
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119Round214GeneratedActionFiniteVolumeValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119Round214GeneratedActionFiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119Round214GeneratedActionFiniteSemanticsValidation

import DASHI.Physics.YangMills.BalabanCMP119Round214ExponentialPhysicalTBridgeExact
import DASHI.Physics.YangMills.BalabanCMP119Round214ExponentialPhysicalTBridgeValidation
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119Round214ExponentialFiniteVolumeExact
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119Round214ExponentialFiniteVolumeValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119Round214ExponentialFiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119Round214ExponentialFiniteSemanticsValidation

import DASHI.Physics.YangMills.BalabanCMP122Equation171TOperationSemanticsExact
import DASHI.Physics.YangMills.BalabanCMP122Equation171TOperationSemanticsValidation
import DASHI.Physics.YangMills.BalabanCMP119Equation171PhysicalTOperationRealizationExact
import DASHI.Physics.YangMills.BalabanCMP119Equation171PhysicalTOperationRealizationValidation
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119Equation171FiniteVolumeExact
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119Equation171FiniteVolumeValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119Equation171FiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119Equation171FiniteSemanticsValidation

import DASHI.Physics.YangMills.BalabanEmbeddedCanonicalRationalConstrainedFoldExact
import DASHI.Physics.YangMills.BalabanEmbeddedCanonicalRationalConstrainedFoldValidation
import DASHI.Physics.YangMills.BalabanCMP122Equation171FiniteConstrainedRealizationExact
import DASHI.Physics.YangMills.BalabanCMP122Equation171FiniteConstrainedRealizationValidation
import DASHI.Physics.YangMills.BalabanCMP119Equation171FinitePhysicalRealizationExact
import DASHI.Physics.YangMills.BalabanCMP119Equation171FinitePhysicalRealizationValidation
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119Equation171StructuredFiniteVolumeExact
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119Equation171StructuredFiniteVolumeValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119Equation171StructuredFiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119Equation171StructuredFiniteSemanticsValidation
