module DASHI.Physics.YangMills.YMClayAristotleGapParityEverything where

-- Focused rollup for the post-#987 Aristotle donor reconciliation. This is
-- intentionally separate from the historical global Yang-Mills rollup so the
-- cross-prover authority boundary remains inspectable.

import DASHI.Physics.YangMills.YMClayAristotleDonorAtlasExact
import DASHI.Physics.YangMills.YMClayVacuumSectorSpectralGapParityExact
import DASHI.Physics.YangMills.YMClayLiteralSU2LatticeDonorExact
import DASHI.Physics.YangMills.YMClayVaryingCarrierTransportParityExact
import DASHI.Physics.YangMills.YMClayUniformGapReductionParityExact
import DASHI.Physics.YangMills.YMClayCorrelationCriterionParityExact
import DASHI.Physics.YangMills.YMClayCorrelationCriterionParityValidation
import DASHI.Physics.YangMills.YMClayDenseL2CorrelationBidiParityExact
import DASHI.Physics.YangMills.YMClayDenseL2CorrelationBidiParityValidation
import DASHI.Physics.YangMills.YMClayDenseMarkedSourceF1ProducerExact
import DASHI.Physics.YangMills.YMClayDenseMarkedSourceF1ProducerValidation
import DASHI.Physics.YangMills.YMClayR295MarkedSourceAdapterExact
import DASHI.Physics.YangMills.YMClayR295MarkedSourceAdapterValidation
import DASHI.Physics.YangMills.YMClayF1PhysicalMinCutExact
import DASHI.Physics.YangMills.YMClayF1WilsonR295SameObjectWeldExact
import DASHI.Physics.YangMills.YMClayF1WilsonR295SameObjectWeldValidation
import DASHI.Physics.YangMills.YMClayF1TranslatedPairL2CalibrationExact
import DASHI.Physics.YangMills.YMClayF1TranslatedPairL2CalibrationValidation
import DASHI.Physics.YangMills.YMClayF1PhysicalMinCutValidation
import DASHI.Physics.YangMills.YMClayUrsellTransferMixingBoundaryExact
import DASHI.Physics.YangMills.YMClayUrsellTransferMixingBoundaryValidation
import DASHI.Physics.YangMills.YMClayF1MixingSourceAuditExact
import DASHI.Physics.YangMills.YMClayF1MixingSourceAuditValidation
import DASHI.Physics.YangMills.YMClayCompleteDensityTransferMixingBoundaryExact
import DASHI.Physics.YangMills.YMClayCompleteDensityTransferMixingBoundaryValidation
import DASHI.Physics.YangMills.YMClayCMSDrellYanEmpiricalContactBoundaryExact
import DASHI.Physics.YangMills.YMClayCMSDrellYanEmpiricalContactBoundaryValidation
import DASHI.Physics.YangMills.YMClayDirectSourceOSMassGapFrontierExact
import DASHI.Physics.YangMills.YMClayDirectSourceOSMassGapFrontierValidation
import DASHI.Physics.YangMills.YMClayRouteSSelectedLimitClosureExact
import DASHI.Physics.YangMills.YMClayRouteSSelectedLimitClosureValidation
import DASHI.Physics.YangMills.YMClayRouteSH1DirectSelectedMarkedDecayExact
import DASHI.Physics.YangMills.YMClayRouteSH1DirectSelectedMarkedDecayValidation
import DASHI.Physics.YangMills.YMClayOSLiteralStressRouteParetoExact
import DASHI.Physics.YangMills.YMClayOSLiteralStressRouteParetoValidation
import DASHI.Physics.YangMills.YMClayLevel2SameFamilyStressRecoveryExact
import DASHI.Physics.YangMills.YMClayLevel2SameFamilyStressRecoveryValidation
import DASHI.Physics.YangMills.YMClayLevel2WardRGReuseExact
import DASHI.Physics.YangMills.YMClayLevel2WardRGReuseValidation
import DASHI.Physics.YangMills.YMClayLevel2StressOPEMinCutExact
import DASHI.Physics.YangMills.YMClayLevel2StressOPEMinCutValidation
import DASHI.Physics.YangMills.YMClayLevel2OPECoefficientCoordinateWeldExact
import DASHI.Physics.YangMills.YMClayLevel2OPECoefficientCoordinateWeldValidation
import DASHI.Physics.YangMills.YMClayLevel2CompositeOperatorCoefficientWeldExact
import DASHI.Physics.YangMills.YMClayLevel2CompositeOperatorCoefficientWeldValidation
import DASHI.Physics.YangMills.YMClayLevel2LiteralOPECoefficientScaleAttachmentExact
import DASHI.Physics.YangMills.YMClayLevel2LiteralOPECoefficientScaleAttachmentValidation
import DASHI.Physics.YangMills.YMClayLevel2D2PhysicalMinCutExact
import DASHI.Physics.YangMills.YMClayLevel2D2PhysicalMinCutValidation
import DASHI.Physics.YangMills.YMClayLevel2R129CompositeOperatorAttachmentExact
import DASHI.Physics.YangMills.YMClayLevel2R129CompositeOperatorAttachmentValidation
import DASHI.Physics.YangMills.YMClayLevel2R129LiteralOPECoefficientWeldExact
import DASHI.Physics.YangMills.YMClayLevel2R129LiteralOPECoefficientWeldValidation
import DASHI.Physics.YangMills.YMClayLevel2ContinuumWardTransportExact
import DASHI.Physics.YangMills.YMClayLevel2ContinuumWardTransportValidation
import DASHI.Physics.YangMills.YMClayF3SprintConstructionFrontierExact
import DASHI.Physics.YangMills.YMClayF3SprintConstructionFrontierValidation
import DASHI.Physics.YangMills.YMClayPhysicalStressOSCommonCoreWitnessExact
import DASHI.Physics.YangMills.YMClayPhysicalStressOSCommonCoreWitnessValidation
import DASHI.Physics.YangMills.YMClayF134ContinuumWeldParityExact
import DASHI.Physics.YangMills.YMClayF134TypedCompositionValidation
import DASHI.Physics.YangMills.YMClayPhysicalF34TypedCompositionExact
import DASHI.Physics.YangMills.YMClayPhysicalF34TypedCompositionValidation
import DASHI.Physics.YangMills.YMClayClosedWorldResidualAudit20260917Exact
import DASHI.Physics.YangMills.YMClayFullPhysicalFormalismExact
import DASHI.Physics.YangMills.YMClayFullPhysicalFormalismValidation
import DASHI.Physics.YangMills.YMClayF1CanonicalSourceApplicationExact
import DASHI.Physics.YangMills.YMClayF1CanonicalSourceApplicationValidation
import DASHI.Physics.YangMills.YMClayR387PhysicalMassGapCertificateExact
import DASHI.Physics.YangMills.YMClayOutstandingPhysicalFrontierExact
import DASHI.Physics.YangMills.YMClayCanonicalMassGapConclusionExact
import DASHI.Physics.YangMills.YMClayTrancheProofLevelAuditValidation
import DASHI.Physics.YangMills.YMClayAristotleGapParityValidation

import DASHI.Physics.YangMills.YMClayAristotleRouteSLiteralWilsonDonorExact
import DASHI.Physics.YangMills.YMClayLiteralWilsonRouteSThreeInputBoundaryExact
import DASHI.Physics.YangMills.YMClayLiteralWilsonRouteSThreeInputBoundaryValidation
import DASHI.Physics.YangMills.YMClayLiteralLocalFieldsClosureExact
import DASHI.Physics.YangMills.YMClayLiteralTopDownRouteSClosureExact
import DASHI.Physics.YangMills.YMClayLiteralTopDownRouteSClosureValidation

import DASHI.Physics.YangMills.YMClayLiteralWilsonP1FiniteClusteringExact
import DASHI.Physics.YangMills.YMClayLiteralWilsonP2ExpectationConvergenceExact
import DASHI.Physics.YangMills.YMClayLiteralWilsonP3SameOSCorrelationExact
import DASHI.Physics.YangMills.YMClayLiteralWilsonP123ReductionValidation
import DASHI.Physics.YangMills.YMClayLevel2D2TransportGeneratedRecurrenceExact
import DASHI.Physics.YangMills.YMClayLevel2D2TransportGeneratedRecurrenceValidation

import DASHI.Physics.YangMills.YMClayLevel2D3ConservedWardChargeExact
import DASHI.Physics.YangMills.YMClayLevel2D3ConservedWardChargeValidation

import DASHI.Physics.YangMills.YMClayLiteralWilsonS2CanonicalProductPresentationExact
import DASHI.Physics.YangMills.YMClayLiteralWilsonS2CanonicalProductPresentationValidation
import DASHI.Physics.YangMills.YMClayLiteralWilsonS2SameAlgebraBoundExact
import DASHI.Physics.YangMills.YMClayLiteralWilsonS2SameAlgebraBoundValidation

import DASHI.Physics.YangMills.YMClayLevel2CompositeTransportABIInsufficiencyExact

import DASHI.Physics.YangMills.BalabanSU2RationalWilsonTraceBoundExact
import DASHI.Physics.YangMills.BalabanSU2RationalWilsonTraceBoundValidation
import DASHI.Physics.YangMills.YMClayLevel2D2R129CompositeConvergenceExact

import DASHI.Physics.YangMills.YMClayContinuumConstructionSameObjectBridgeExact
import DASHI.Physics.YangMills.YMClayContinuumConstructionSameObjectBridgeValidation

import DASHI.Physics.YangMills.BalabanYM4FiveChannelCauchyQuotientMajorantExact
import DASHI.Physics.YangMills.BalabanYM4FiveChannelTaylorCauchyClosureExact
import DASHI.Physics.YangMills.BalabanYM4FiveChannelTaylorCauchyClosureValidation

import DASHI.Physics.YangMills.BalabanClayT5ConfiguredDyadicTailSummationExact
import DASHI.Physics.YangMills.BalabanClayT5ConfiguredDyadicTailSummationValidation

import DASHI.Physics.YangMills.BalabanClayT5TypedContinuumDefectCauchyExact
import DASHI.Physics.YangMills.BalabanClayT5TypedContinuumDefectCauchyValidation

import DASHI.Physics.YangMills.BalabanClayT5MarkovToProkhorovTightnessExact
import DASHI.Physics.YangMills.BalabanClayT5MarkovToProkhorovTightnessValidation

import DASHI.Physics.YangMills.BalabanClayT5Path4MarkovProkhorovExact
import DASHI.Physics.YangMills.BalabanClayT5Path4MarkovProkhorovValidation

import DASHI.Physics.YangMills.BalabanFiniteRGProbabilityExpectationSemanticsExact
import DASHI.Physics.YangMills.BalabanFiniteRGProbabilityExpectationSemanticsValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4FiniteProbabilitySemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4FiniteProbabilitySemanticsValidation
