module DASHI.Physics.YangMills.YMClayAristotleGapParityEverything where

-- Focused rollup for the post-#987 Aristotle donor reconciliation. This is
-- intentionally separate from the historical global Yang-Mills rollup so the
-- cross-prover authority boundary remains inspectable.

import DASHI.Physics.YangMills.YMClayAristotleDonorAtlasExact
import DASHI.Physics.YangMills.YMClayVacuumSectorSpectralGapParityExact
import DASHI.Physics.YangMills.YMClayLiteralSU2LatticeDonorExact
import DASHI.Physics.YangMills.YMClayVaryingCarrierTransportParityExact
import DASHI.Physics.YangMills.YMClayUniformGapReductionParityExact
import DASHI.Physics.YangMills.YMClayCorrelationCriterionParityExact
import DASHI.Physics.YangMills.YMClayCorrelationCriterionParityValidation
import DASHI.Physics.YangMills.YMClayDenseL2CorrelationBidiParityExact
import DASHI.Physics.YangMills.YMClayDenseL2CorrelationBidiParityValidation
import DASHI.Physics.YangMills.YMClayDenseMarkedSourceF1ProducerExact
import DASHI.Physics.YangMills.YMClayDenseMarkedSourceF1ProducerValidation
import DASHI.Physics.YangMills.YMClayR295MarkedSourceAdapterExact
import DASHI.Physics.YangMills.YMClayR295MarkedSourceAdapterValidation
import DASHI.Physics.YangMills.YMClayF1PhysicalMinCutExact
import DASHI.Physics.YangMills.YMClayF1WilsonR295SameObjectWeldExact
import DASHI.Physics.YangMills.YMClayF1WilsonR295SameObjectWeldValidation
import DASHI.Physics.YangMills.YMClayF1TranslatedPairL2CalibrationExact
import DASHI.Physics.YangMills.YMClayF1TranslatedPairL2CalibrationValidation
import DASHI.Physics.YangMills.YMClayF1PhysicalMinCutValidation
import DASHI.Physics.YangMills.YMClayUrsellTransferMixingBoundaryExact
import DASHI.Physics.YangMills.YMClayUrsellTransferMixingBoundaryValidation
import DASHI.Physics.YangMills.YMClayF1MixingSourceAuditExact
import DASHI.Physics.YangMills.YMClayF1MixingSourceAuditValidation
import DASHI.Physics.YangMills.YMClayCompleteDensityTransferMixingBoundaryExact
import DASHI.Physics.YangMills.YMClayCompleteDensityTransferMixingBoundaryValidation
import DASHI.Physics.YangMills.YMClayCMSDrellYanEmpiricalContactBoundaryExact
import DASHI.Physics.YangMills.YMClayCMSDrellYanEmpiricalContactBoundaryValidation
import DASHI.Physics.YangMills.YMClayDirectSourceOSMassGapFrontierExact
import DASHI.Physics.YangMills.YMClayDirectSourceOSMassGapFrontierValidation
import DASHI.Physics.YangMills.YMClayRouteSSelectedLimitClosureExact
import DASHI.Physics.YangMills.YMClayRouteSSelectedLimitClosureValidation
import DASHI.Physics.YangMills.YMClayRouteSH1DirectSelectedMarkedDecayExact
import DASHI.Physics.YangMills.YMClayRouteSH1DirectSelectedMarkedDecayValidation
import DASHI.Physics.YangMills.YMClayOSLiteralStressRouteParetoExact
import DASHI.Physics.YangMills.YMClayOSLiteralStressRouteParetoValidation
import DASHI.Physics.YangMills.YMClayLevel2SameFamilyStressRecoveryExact
import DASHI.Physics.YangMills.YMClayLevel2SameFamilyStressRecoveryValidation
import DASHI.Physics.YangMills.YMClayLevel2WardRGReuseExact
import DASHI.Physics.YangMills.YMClayLevel2WardRGReuseValidation
import DASHI.Physics.YangMills.YMClayLevel2StressOPEMinCutExact
import DASHI.Physics.YangMills.YMClayLevel2StressOPEMinCutValidation
import DASHI.Physics.YangMills.YMClayLevel2OPECoefficientCoordinateWeldExact
import DASHI.Physics.YangMills.YMClayLevel2OPECoefficientCoordinateWeldValidation
import DASHI.Physics.YangMills.YMClayLevel2CompositeOperatorCoefficientWeldExact
import DASHI.Physics.YangMills.YMClayLevel2CompositeOperatorCoefficientWeldValidation
import DASHI.Physics.YangMills.YMClayLevel2LiteralOPECoefficientScaleAttachmentExact
import DASHI.Physics.YangMills.YMClayLevel2LiteralOPECoefficientScaleAttachmentValidation
import DASHI.Physics.YangMills.YMClayLevel2D2PhysicalMinCutExact
import DASHI.Physics.YangMills.YMClayLevel2D2PhysicalMinCutValidation
import DASHI.Physics.YangMills.YMClayLevel2R129CompositeOperatorAttachmentExact
import DASHI.Physics.YangMills.YMClayLevel2R129CompositeOperatorAttachmentValidation
import DASHI.Physics.YangMills.YMClayLevel2R129LiteralOPECoefficientWeldExact
import DASHI.Physics.YangMills.YMClayLevel2R129LiteralOPECoefficientWeldValidation
import DASHI.Physics.YangMills.YMClayLevel2ContinuumWardTransportExact
import DASHI.Physics.YangMills.YMClayLevel2ContinuumWardTransportValidation
import DASHI.Physics.YangMills.YMClayF3SprintConstructionFrontierExact
import DASHI.Physics.YangMills.YMClayF3SprintConstructionFrontierValidation
import DASHI.Physics.YangMills.YMClayPhysicalStressOSCommonCoreWitnessExact
import DASHI.Physics.YangMills.YMClayPhysicalStressOSCommonCoreWitnessValidation
import DASHI.Physics.YangMills.YMClayF134ContinuumWeldParityExact
import DASHI.Physics.YangMills.YMClayF134TypedCompositionValidation
import DASHI.Physics.YangMills.YMClayPhysicalF34TypedCompositionExact
import DASHI.Physics.YangMills.YMClayPhysicalF34TypedCompositionValidation
import DASHI.Physics.YangMills.YMClayClosedWorldResidualAudit20260917Exact
import DASHI.Physics.YangMills.YMClayFullPhysicalFormalismExact
import DASHI.Physics.YangMills.YMClayFullPhysicalFormalismValidation
import DASHI.Physics.YangMills.YMClayF1CanonicalSourceApplicationExact
import DASHI.Physics.YangMills.YMClayF1CanonicalSourceApplicationValidation
import DASHI.Physics.YangMills.YMClayR387PhysicalMassGapCertificateExact
import DASHI.Physics.YangMills.YMClayOutstandingPhysicalFrontierExact
import DASHI.Physics.YangMills.YMClayCanonicalMassGapConclusionExact
import DASHI.Physics.YangMills.YMClayTrancheProofLevelAuditValidation
import DASHI.Physics.YangMills.YMClayAristotleGapParityValidation

import DASHI.Physics.YangMills.YMClayAristotleRouteSLiteralWilsonDonorExact
import DASHI.Physics.YangMills.YMClayLiteralWilsonRouteSThreeInputBoundaryExact
import DASHI.Physics.YangMills.YMClayLiteralWilsonRouteSThreeInputBoundaryValidation
import DASHI.Physics.YangMills.YMClayLiteralLocalFieldsClosureExact
import DASHI.Physics.YangMills.YMClayLiteralTopDownRouteSClosureExact
import DASHI.Physics.YangMills.YMClayLiteralTopDownRouteSClosureValidation

import DASHI.Physics.YangMills.YMClayLiteralWilsonP1FiniteClusteringExact
import DASHI.Physics.YangMills.YMClayLiteralWilsonP2ExpectationConvergenceExact
import DASHI.Physics.YangMills.YMClayLiteralWilsonP3SameOSCorrelationExact
import DASHI.Physics.YangMills.YMClayLiteralWilsonP123ReductionValidation
import DASHI.Physics.YangMills.YMClayLevel2D2TransportGeneratedRecurrenceExact
import DASHI.Physics.YangMills.YMClayLevel2D2TransportGeneratedRecurrenceValidation

import DASHI.Physics.YangMills.YMClayLevel2D3ConservedWardChargeExact
import DASHI.Physics.YangMills.YMClayLevel2D3ConservedWardChargeValidation

import DASHI.Physics.YangMills.YMClayLiteralWilsonS2CanonicalProductPresentationExact
import DASHI.Physics.YangMills.YMClayLiteralWilsonS2CanonicalProductPresentationValidation
import DASHI.Physics.YangMills.YMClayLiteralWilsonS2SameAlgebraBoundExact
import DASHI.Physics.YangMills.YMClayLiteralWilsonS2SameAlgebraBoundValidation

import DASHI.Physics.YangMills.YMClayLevel2CompositeTransportABIInsufficiencyExact

import DASHI.Physics.YangMills.BalabanSU2RationalWilsonTraceBoundExact
import DASHI.Physics.YangMills.BalabanSU2RationalWilsonTraceBoundValidation
import DASHI.Physics.YangMills.YMClayLevel2D2R129CompositeConvergenceExact

import DASHI.Physics.YangMills.YMClayContinuumConstructionSameObjectBridgeExact
import DASHI.Physics.YangMills.YMClayContinuumConstructionSameObjectBridgeValidation

import DASHI.Physics.YangMills.BalabanYM4FiveChannelCauchyQuotientMajorantExact
import DASHI.Physics.YangMills.BalabanYM4FiveChannelTaylorCauchyClosureExact
import DASHI.Physics.YangMills.BalabanYM4FiveChannelTaylorCauchyClosureValidation

import DASHI.Physics.YangMills.BalabanClayT5ConfiguredDyadicTailSummationExact
import DASHI.Physics.YangMills.BalabanClayT5ConfiguredDyadicTailSummationValidation

import DASHI.Physics.YangMills.BalabanClayT5TypedContinuumDefectCauchyExact
import DASHI.Physics.YangMills.BalabanClayT5TypedContinuumDefectCauchyValidation

import DASHI.Physics.YangMills.BalabanClayT5MarkovToProkhorovTightnessExact
import DASHI.Physics.YangMills.BalabanClayT5MarkovToProkhorovTightnessValidation

import DASHI.Physics.YangMills.BalabanClayT5Path4MarkovProkhorovExact
import DASHI.Physics.YangMills.BalabanClayT5Path4MarkovProkhorovValidation

import DASHI.Physics.YangMills.BalabanFiniteRGProbabilityExpectationSemanticsExact
import DASHI.Physics.YangMills.BalabanFiniteRGProbabilityExpectationSemanticsValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4FiniteProbabilitySemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4FiniteProbabilitySemanticsValidation

import DASHI.Physics.YangMills.YMClayLiteralVocabularyNonPinningExact

import DASHI.Physics.YangMills.BalabanClayGate4ReferenceToFiniteRGProbabilityExact
import DASHI.Physics.YangMills.BalabanClayGate4ReferenceToFiniteRGProbabilityValidation
import DASHI.Physics.YangMills.BalabanClayP3CanonicalRationalConstrainedSumExact
import DASHI.Physics.YangMills.BalabanClayGate4CanonicalRationalPhysicalTExact
import DASHI.Physics.YangMills.BalabanClayGate4CanonicalRationalPhysicalTValidation

import DASHI.Physics.YangMills.BalabanClayGate4CanonicalRationalReferenceAlgebraExact
import DASHI.Physics.YangMills.BalabanClayGate4CanonicalRationalReferenceAlgebraValidation
import DASHI.Physics.YangMills.BalabanClayGate4PreferredRationalReferenceNormalizationExact
import DASHI.Physics.YangMills.BalabanClayGate4PreferredRationalReferenceNormalizationValidation


import DASHI.Physics.YangMills.BalabanFiniteProbabilityPartitionDisintegrationExact
import DASHI.Physics.YangMills.BalabanFiniteProbabilityPartitionDisintegrationValidation
import DASHI.Physics.YangMills.BalabanClayGate4ConstrainedReferenceKernelExact
import DASHI.Physics.YangMills.BalabanClayGate4ConstrainedReferenceKernelValidation
import DASHI.Physics.YangMills.BalabanFiniteConditionalMixtureReopeningExact
import DASHI.Physics.YangMills.BalabanFiniteConditionalMixtureReopeningValidation
import DASHI.Physics.YangMills.BalabanClayGate4ConditionalMixtureReopeningExact
import DASHI.Physics.YangMills.BalabanClayGate4ConditionalMixtureReopeningValidation
import DASHI.Physics.YangMills.BalabanFiniteVolumeConditionalGate4PresentationExact
import DASHI.Physics.YangMills.BalabanFiniteVolumeConditionalGate4PresentationValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4ConditionalGate4FiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4ConditionalGate4FiniteSemanticsValidation
import DASHI.Physics.YangMills.BalabanClayGate4ProbabilitySemanticCorrectionExact

import DASHI.Physics.YangMills.BalabanFinitePositiveWeightNormalizationExact
import DASHI.Physics.YangMills.BalabanFinitePositiveWeightNormalizationValidation
import DASHI.Physics.YangMills.BalabanClayGate4RawSlowDensityToProbabilityExact
import DASHI.Physics.YangMills.BalabanClayGate4RawSlowDensityToProbabilityValidation
import DASHI.Physics.YangMills.BalabanFiniteVolumeRawDensityGate4PresentationExact
import DASHI.Physics.YangMills.BalabanFiniteVolumeRawDensityGate4PresentationValidation
import DASHI.Physics.YangMills.BalabanCMP119FiniteSlowDensityRealizationExact
import DASHI.Physics.YangMills.BalabanCMP119FiniteSlowDensityRealizationValidation
import DASHI.Physics.YangMills.BalabanCMP119FiniteVolumeGate4PresentationExact
import DASHI.Physics.YangMills.BalabanCMP119FiniteVolumeGate4PresentationValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4CMP119FiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4CMP119FiniteSemanticsValidation

import DASHI.Physics.YangMills.BalabanCMP119AssembledFiniteSlowDensityExact
import DASHI.Physics.YangMills.BalabanCMP119AssembledFiniteSlowDensityValidation
import DASHI.Physics.YangMills.BalabanCMP119AssembledFiniteVolumeGate4PresentationExact
import DASHI.Physics.YangMills.BalabanCMP119AssembledFiniteVolumeGate4PresentationValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4CMP119AssembledFiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4CMP119AssembledFiniteSemanticsValidation

import DASHI.Physics.YangMills.BalabanCMP119Gate4ConstrainedMassWeldExact
import DASHI.Physics.YangMills.BalabanCMP119Gate4ConstrainedMassWeldValidation
import DASHI.Physics.YangMills.BalabanCMP119Gate4ConstrainedMassFiniteVolumePresentationExact
import DASHI.Physics.YangMills.BalabanCMP119Gate4ConstrainedMassFiniteVolumePresentationValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4CMP119ConstrainedMassFiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4CMP119ConstrainedMassFiniteSemanticsValidation

import DASHI.Physics.YangMills.BalabanClayGate4CanonicalPhysicalTOperationRationalNonnegativeExact
import DASHI.Physics.YangMills.BalabanClayGate4CanonicalPhysicalTOperationRationalNonnegativeValidation
import DASHI.Physics.YangMills.BalabanCMP119PhysicalTOperationWeldExact
import DASHI.Physics.YangMills.BalabanCMP119PhysicalTOperationWeldValidation
import DASHI.Physics.YangMills.BalabanCMP119PhysicalTOperationFiniteVolumePresentationExact
import DASHI.Physics.YangMills.BalabanCMP119PhysicalTOperationFiniteVolumePresentationValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4CMP119PhysicalTOperationFiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4CMP119PhysicalTOperationFiniteSemanticsValidation

import DASHI.Physics.YangMills.BalabanCMP119FiniteDensityAssemblySemanticsExact
import DASHI.Physics.YangMills.BalabanCMP119FiniteDensityAssemblySemanticsValidation
import DASHI.Physics.YangMills.BalabanCMP119PhysicalTOperationAssemblyRealizationExact
import DASHI.Physics.YangMills.BalabanCMP119PhysicalTOperationAssemblyRealizationValidation
import DASHI.Physics.YangMills.BalabanCMP119SplitPhysicalTOperationFiniteVolumePresentationExact
import DASHI.Physics.YangMills.BalabanCMP119SplitPhysicalTOperationFiniteVolumePresentationValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4CMP119SplitPhysicalTOperationFiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4CMP119SplitPhysicalTOperationFiniteSemanticsValidation

import DASHI.Physics.YangMills.BalabanCMP119Section2FiniteDensityEvaluationExact
import DASHI.Physics.YangMills.BalabanCMP119Section2FiniteDensityEvaluationValidation
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119FiniteDensityEvaluationExact
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119FiniteDensityEvaluationValidation
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119PhysicalTOperationFiniteVolumeExact
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119PhysicalTOperationFiniteVolumeValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119PhysicalTOperationFiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119PhysicalTOperationFiniteSemanticsValidation

import DASHI.Physics.YangMills.BalabanClayGate4ParameterizedEffectiveActionExact
import DASHI.Physics.YangMills.BalabanClayGate4ParameterizedEffectiveActionValidation
import DASHI.Physics.YangMills.BalabanCMP119PhysicalEffectiveActionRealizationExact
import DASHI.Physics.YangMills.BalabanCMP119PhysicalEffectiveActionRealizationValidation
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119GeneratedActionFiniteVolumeExact
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119GeneratedActionFiniteVolumeValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119GeneratedActionFiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119GeneratedActionFiniteSemanticsValidation

import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119Round214ActionEvaluationExact
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119Round214ActionEvaluationValidation
import DASHI.Physics.YangMills.BalabanCMP119Round214BackedPhysicalEffectiveActionExact
import DASHI.Physics.YangMills.BalabanCMP119Round214BackedPhysicalEffectiveActionValidation
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119Round214GeneratedActionFiniteVolumeExact
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119Round214GeneratedActionFiniteVolumeValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119Round214GeneratedActionFiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119Round214GeneratedActionFiniteSemanticsValidation

import DASHI.Physics.YangMills.BalabanCMP119Round214ExponentialPhysicalTBridgeExact
import DASHI.Physics.YangMills.BalabanCMP119Round214ExponentialPhysicalTBridgeValidation
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119Round214ExponentialFiniteVolumeExact
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119Round214ExponentialFiniteVolumeValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119Round214ExponentialFiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119Round214ExponentialFiniteSemanticsValidation

import DASHI.Physics.YangMills.BalabanCMP122Equation171TOperationSemanticsExact
import DASHI.Physics.YangMills.BalabanCMP122Equation171TOperationSemanticsValidation
import DASHI.Physics.YangMills.BalabanCMP119Equation171PhysicalTOperationRealizationExact
import DASHI.Physics.YangMills.BalabanCMP119Equation171PhysicalTOperationRealizationValidation
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119Equation171FiniteVolumeExact
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119Equation171FiniteVolumeValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119Equation171FiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119Equation171FiniteSemanticsValidation

import DASHI.Physics.YangMills.BalabanEmbeddedCanonicalRationalConstrainedFoldExact
import DASHI.Physics.YangMills.BalabanEmbeddedCanonicalRationalConstrainedFoldValidation
import DASHI.Physics.YangMills.BalabanCMP122Equation171FiniteConstrainedRealizationExact
import DASHI.Physics.YangMills.BalabanCMP122Equation171FiniteConstrainedRealizationValidation
import DASHI.Physics.YangMills.BalabanCMP119Equation171FinitePhysicalRealizationExact
import DASHI.Physics.YangMills.BalabanCMP119Equation171FinitePhysicalRealizationValidation
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119Equation171StructuredFiniteVolumeExact
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119Equation171StructuredFiniteVolumeValidation
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119Equation171StructuredFiniteSemanticsExact
import DASHI.Physics.YangMills.BalabanClayT5Path4BetaDrivenCMP119Equation171StructuredFiniteSemanticsValidation

import DASHI.Physics.YangMills.BalabanCMP122Equation171Gate4QuadratureSliceExact
import DASHI.Physics.YangMills.BalabanCMP122Equation171Gate4QuadratureSliceValidation
import DASHI.Physics.YangMills.BalabanCMP122Equation171Gate4RefinementLimitExact
import DASHI.Physics.YangMills.BalabanCMP122Equation171Gate4RefinementLimitValidation
import DASHI.Physics.YangMills.BalabanCMP119Equation171Gate4RefinementSourceLimitExact
import DASHI.Physics.YangMills.BalabanCMP119Equation171Gate4RefinementSourceLimitValidation
import DASHI.Physics.YangMills.BalabanCompactHaarFiniteQuadratureErrorExact
import DASHI.Physics.YangMills.BalabanCompactHaarFiniteQuadratureErrorValidation

import DASHI.Physics.YangMills.BalabanRealSequenceLimitByVanishingErrorExact
import DASHI.Physics.YangMills.BalabanRealSequenceLimitByVanishingErrorValidation
import DASHI.Physics.YangMills.BalabanCMP122Equation171QuantitativeQuadratureLimitExact
import DASHI.Physics.YangMills.BalabanCMP122Equation171QuantitativeQuadratureLimitValidation
import DASHI.Physics.YangMills.BalabanCMP119Equation171QuantitativeSourceLimitExact
import DASHI.Physics.YangMills.BalabanCMP119Equation171QuantitativeSourceLimitValidation
import DASHI.Physics.YangMills.BalabanClayT5QuadratureStagedDiagonalTailExact
import DASHI.Physics.YangMills.BalabanClayT5QuadratureStagedDiagonalTailValidation

import DASHI.Physics.YangMills.BalabanFiniteProductMassExactPartitionExact
import DASHI.Physics.YangMills.BalabanFiniteProductMassExactPartitionValidation
import DASHI.Physics.YangMills.BalabanClayGate4EmbeddedWeightedQuadratureExact
import DASHI.Physics.YangMills.BalabanClayGate4EmbeddedWeightedQuadratureValidation
import DASHI.Physics.YangMills.BalabanCMP122Equation171WeightedGate4QuadratureSliceExact
import DASHI.Physics.YangMills.BalabanCMP122Equation171WeightedGate4QuadratureSliceValidation
import DASHI.Physics.YangMills.BalabanCMP122Equation171WeightedGate4RefinementLimitExact
import DASHI.Physics.YangMills.BalabanCMP122Equation171WeightedGate4RefinementLimitValidation
import DASHI.Physics.YangMills.BalabanCMP119Equation171WeightedGate4SourceLimitExact
import DASHI.Physics.YangMills.BalabanCMP119Equation171WeightedGate4SourceLimitValidation

import DASHI.Physics.YangMills.Balaban1989BetaDrivenFunctionalDensityExact
import DASHI.Physics.YangMills.Balaban1989BetaDrivenFunctionalDensityValidation
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119FunctionalOperatorExact
import DASHI.Physics.YangMills.BalabanBetaDrivenCMP119FunctionalOperatorValidation
import DASHI.Physics.YangMills.BalabanCMP119Equation218FactorizedFunctionalDensityExact
import DASHI.Physics.YangMills.BalabanCMP119Equation218FactorizedFunctionalDensityValidation
import DASHI.Physics.YangMills.BalabanCMP119FactorizedDensityApproximationExact
import DASHI.Physics.YangMills.BalabanCMP119FactorizedDensityApproximationValidation
import DASHI.Physics.YangMills.BalabanCMP119FactorizedDensityConvergenceExact
import DASHI.Physics.YangMills.BalabanCMP119FactorizedDensityConvergenceValidation
import DASHI.Physics.YangMills.BalabanRealVanishingFiniteAlgebraExact
import DASHI.Physics.YangMills.BalabanRealVanishingFiniteAlgebraValidation
import DASHI.Physics.YangMills.BalabanCMP119FactorizedMarkedBudgetVanishesExact
import DASHI.Physics.YangMills.BalabanCMP119FactorizedMarkedBudgetVanishesValidation
import DASHI.Physics.YangMills.BalabanCMP119Equation171WeightedStepApproximationExact
import DASHI.Physics.YangMills.BalabanCMP119Equation171WeightedStepApproximationValidation
import DASHI.Physics.YangMills.BalabanCMP119Equation171WeightedFactorizedConvergenceExact
import DASHI.Physics.YangMills.BalabanCMP119Equation171WeightedFactorizedConvergenceValidation

import DASHI.Physics.YangMills.BalabanCMP119FiniteObservableExpectationConvergenceExact
import DASHI.Physics.YangMills.BalabanCMP119FiniteObservableExpectationConvergenceValidation

import DASHI.Physics.YangMills.YangMillsClayPinnedPhysicalCarriersExact
import DASHI.Physics.YangMills.YangMillsClayPinnedPhysicalCarriersValidation
import DASHI.Physics.YangMills.YangMillsClayPinnedPhysicalConstructionExact
import DASHI.Physics.YangMills.YangMillsClayPinnedPhysicalConstructionValidation
import DASHI.Physics.YangMills.YangMillsClayPinnedPhysicalGapAttachmentExact
import DASHI.Physics.YangMills.YangMillsClayPinnedPhysicalGapAttachmentValidation
import DASHI.Physics.YangMills.YangMillsClayPinnedLiteralCompilerExact
import DASHI.Physics.YangMills.YangMillsClayPinnedLiteralCompilerValidation
import DASHI.Physics.YangMills.YangMillsClayPinnedPhysicalInstanceExact
import DASHI.Physics.YangMills.YangMillsClayPinnedPhysicalInstanceValidation

import DASHI.Physics.YangMills.BalabanCMP116CanonicalPathMarkedReplayRound410Exact
import DASHI.Physics.YangMills.BalabanCMP116CanonicalPathMarkedReplayRound410Validation

import DASHI.Physics.YangMills.BalabanCylinderExpectationLimitMeasureExact
import DASHI.Physics.YangMills.BalabanCylinderExpectationLimitMeasureValidation
import DASHI.Physics.YangMills.BalabanCMP116PublishedSelectedGapProducerExact
import DASHI.Physics.YangMills.BalabanCMP116PublishedSelectedGapProducerValidation
import DASHI.Physics.YangMills.BalabanSameFamilyCompositeOPEStressCompilerExact
import DASHI.Physics.YangMills.BalabanSameFamilyCompositeOPEStressCompilerValidation

import DASHI.Physics.YangMills.YangMillsABCConstructiveCoreExact
import DASHI.Physics.YangMills.YangMillsABCConstructiveCoreValidation


-- Preferred literal real CMP119/CMP116 same-carrier route.
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119ContinuumConstructionExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119OSSystemExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119OSReconstructionExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119CovarianceCarrierExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119RealCovarianceExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119RealTwoJSourceExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119RealCMP116ApplicationExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119RealCMP116ClusteringExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119RealCMP116PhysicalUpperExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119RealCMP116ScaleCalibrationExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119RealCMP116ScaleCalibrationValidation


-- Literal CMP116 differentiated-localization proof producers R411-R414.
import DASHI.Physics.YangMills.BalabanCMP116SelectedSupportConnectionRound411Exact
import DASHI.Physics.YangMills.BalabanCMP116CauchyWeightedDerivativeRound412Exact
import DASHI.Physics.YangMills.BalabanCMP99PathDerivativeSourceReplayRound413Exact
import DASHI.Physics.YangMills.BalabanCMP116ConnectingOuterSumRound414Exact


-- A/B/C literal frontier compilers: concrete OS1, selected R410 source decay, pinned C stress/AF.
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119CylinderEuclideanCovarianceExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119ConcreteOS1SystemExact
import DASHI.Physics.YangMills.BalabanCMP116SelectedMarkedExpansionRound415Exact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119StressCommonCoreExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119ConcreteLocalCExact


-- ABC literal-inhabitant continuation: OS3, R415->physical-scale, Round109 stress same-object.
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119ConcreteOS3SystemExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119RealCMP116MarkedExpansionScaleExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119Round109StressSameObjectExact


-- ABC hard-math continuation: R406->R415, CMP119 compactness, Round109->common core.
import DASHI.Physics.YangMills.BalabanCMP116Round406To415Exact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119SelectedProjectiveCompactnessExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119Round109ToCommonCoreExact


-- ABC open-frontier continuation: source-native B, one-family A, same-family C.
import DASHI.Physics.YangMills.BalabanCMP116Round354To415FixedYExact
import DASHI.Physics.YangMills.BalabanCMP116PreferredR415SourceExact
import DASHI.Physics.YangMills.BalabanCMP116Round406PreferredR415Exact
import DASHI.Physics.YangMills.BalabanCMP116SelectedSupportGraphRound416Exact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119RealCMP116MarkedExpansionUpperExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119RealCMP116MarkedExpansionOrderedUpperExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119WilsonSquareOS2Exact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119ConcreteAExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119ConcreteAProjectiveExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119LiteralAFCoefficientExact
import DASHI.Physics.YangMills.BalabanR144ToCMP119StressInsertionExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119LocalCoreStressExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119Round109ConcreteLocalCExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119MarkedCurvatureCompositeExact

import DASHI.Physics.YangMills.YangMillsFiniteNormalizedExpectationSymmetryExact

import DASHI.Physics.YangMills.YangMillsStressWardPointwiseCoreGeneratorExact


-- ABC literal-inhabitant continuation: source-fed A, integrated B, completed C.
import DASHI.Physics.YangMills.BalabanCMP116LiteralMarkedChargingRound416Exact
import DASHI.Physics.YangMills.BalabanCMP116LiteralMarkedChargingToR415Exact
import DASHI.Physics.YangMills.BalabanCMP116LiteralSelectedExpansionRound418Exact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119StandaloneWilsonSquareExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119WilsonSourceOS2Exact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119FiniteEuclideanSourceExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119BosonicOS3SourceExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119OS05CanonicalLimitExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119ConcreteAFromSourcesExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119PreferredR415ToRealExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119PreferredR415ClusteringExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119R129CompositeHubExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119R129NuclearCompositeExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119R109NuclearStressExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119MicrocausalChargeExact

import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119ConcreteANumeratorExact

import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119UniformProjectiveCompactnessExact

import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119StressPointwiseCommonCoreExact


-- ABC least-privilege refinements: ordered B, support-graph B, pointwise C.
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119PreferredR415OrderedRealExact
import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119PointwiseStressCoreExact
import DASHI.Physics.YangMills.BalabanCMP116Round406SupportGraphGeometryExact

import DASHI.Physics.YangMills.BalabanR144CanonicalMetricTangentAttachmentExact

import DASHI.Physics.YangMills.BalabanCMP116Round406SourceRateSplitAmplitudeRound420Exact
import DASHI.Physics.YangMills.BalabanCMP116Round406ExactR410ReplayRound421Exact
import DASHI.Physics.YangMills.BalabanCMP116Equation126129ToRound406Round422Exact
import DASHI.Physics.YangMills.BalabanCMP116Round406NonemptySelectedFibreRound423Exact
import DASHI.Physics.YangMills.BalabanCMP116Round406SupportGraphPreferredR415Round419Exact

import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119LiteralACompletionRound424Exact

import DASHI.Physics.YangMills.BalabanCMP116LiteralBCompletionRound425Exact

import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119LiteralBRealCompletionRound426Exact

import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119SameCompletedCompositeStressRound427Exact
import DASHI.Physics.YangMills.BalabanR144CanonicalMetricTangentRound428Exact

import DASHI.Physics.YangMills.BalabanCMP116CanonicalFourStageR406Round429Exact

import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119R129PaysContinuumSemanticsRound430Exact

import DASHI.Physics.YangMills.YangMillsFiniteHaarActionNumeratorInvariantRound431Exact

import DASHI.Physics.YangMills.YangMillsClayPinnedCMP119ContinuumFromOSRound432Exact

import DASHI.Physics.YangMills.BalabanR144CanonicalMetricDomainRound433Exact

import DASHI.Physics.YangMills.BalabanCMP116CanonicalTwiceMarkedSupportRound434Exact
\nimport DASHI.Physics.YangMills.BalabanCMP116CanonicalSelectedBSourceRound435Exact\n\nimport DASHI.Physics.YangMills.YangMillsClayPinnedCMP119CanonicalASourceRound436Exact\n\nimport DASHI.Physics.YangMills.YangMillsClayGoal1CanonicalCSourceRound437Exact\n\nimport DASHI.Physics.YangMills.BalabanCMP116CanonicalLiteralRateSourceRound438Exact\n