module DASHI.ComputerScience.RSA260BidiRuntimeKrylovActionBindingValidationExact where

import DASHI.ComputerScience.RSA260BidiRuntimeKrylovActionBindingExact

open DASHI.ComputerScience.RSA260BidiRuntimeKrylovActionBindingExact

_ = canonicalRuntimeKrylovActionBindingBoundary
