module DASHI.ComputerScience.RSA260BidiLeftMinimalIndexProjectionDependenceValidationExact where

import DASHI.ComputerScience.RSA260BidiLeftMinimalIndexProjectionDependenceExact as Projection

projectionDependenceBoundary : Projection.LeftMinimalIndexProjectionBoundary
projectionDependenceBoundary = Projection.canonicalLeftMinimalIndexProjectionBoundary

sameCarrierProjectionCollision : Projection.SameCarrierProjectionDependenceReceipt
sameCarrierProjectionCollision = Projection.currentSameCarrierProjectionDependenceReceipt

firstResidual : Projection.LeftMinimalIndexProjectionResidual
firstResidual = Projection.firstLeftMinimalIndexProjectionResidual
