module DASHI.Base369Ternary27StratifiedFibreEverything where

-- Merged geometric / stratification / spectral substrate.
import DASHI.Foundations.Base369Ternary27HypervoxelFabricGeometryExact
import DASHI.Foundations.Base369Ternary27HypervoxelStratificationExact
import DASHI.Moonshine.Base369Ternary27SpectralSymmetryIrrepBridgeExact
import DASHI.Moonshine.Base369Ternary27CharacterAdjacencyEquivarianceExact
import DASHI.Moonshine.Base369Ternary27SignedSymmetryMonsterIntertwinerExact
import DASHI.Moonshine.Base369Ternary27PathCubeSpectralBandsExact

-- Stratified/fibre/plaquette/holonomy continuation.
import DASHI.Foundations.Base369Ternary27StratifiedAppraisalFibreExact
import DASHI.Foundations.Base369Ternary27StratifiedFibrePlaquetteExact
import DASHI.Foundations.Base369Ternary27StratumStabiliserFibreAdmissibilityExact
import DASHI.Foundations.Base369Ternary27StabiliserOperatorHolonomyExact
import DASHI.Foundations.Base369Ternary27OperatorOrbitQuotientExact
import DASHI.Foundations.Base369Ternary27AdmissibilityPathDynamicsExact
import DASHI.Moonshine.Base369Ternary27StratifiedFibreHolonomyExact

-- BIDI weld to the existing Monster 3B finite Heisenberg and harmonic lanes.
import DASHI.Moonshine.Base369AppraisalFibreHeisenbergCarrierBidiExact
import DASHI.Moonshine.Base369HeisenbergTranslationGridObstructionExact
import DASHI.Moonshine.Base369MonsterFineCarrierEquivarianceAuditExact

-- Periodic C3^9 host versus non-periodic P3^9 observational restriction.
import DASHI.Moonshine.Base369PeriodicTernaryTorusPathRestrictionBidiExact
import DASHI.Moonshine.Base369PeriodicHeisenbergFibreEquivarianceExact

-- Exact decimal/nonary completion, 10 x 3^9 bulk, and structured 53/54 branch.
import DASHI.Moonshine.Base369DecimalCompletionMonsterBulkBidiExact
import DASHI.Moonshine.Base369MonsterTwoComponentCompletionBidiExact

-- Refined 54 carrier: nontrivial zeta pair x ternary-27 = sixfold x nonary-9,
-- with the sixfold factor exactly charted to the Heisenberg coordinate axes.
import DASHI.Moonshine.Base369ZetaHeisenbergFiftyFourCarrierExact
import DASHI.Base369ZetaHeisenbergFiftyFourValidation
import DASHI.Base369MonsterTwoComponentCompletionValidation

-- Consumer-first representation-theoretic frontier: actual M -> MN3B
-- restriction and a now theorem-bearing finite Heisenberg group chain.
import DASHI.Moonshine.Base369Monster3BRepresentationBidiSearchExact
import DASHI.Moonshine.Monster3BFiniteHeisenbergCentralExtensionExact
import DASHI.Moonshine.Monster3BF3AlgebraExact
import DASHI.Moonshine.Monster3BFiniteHeisenbergDotBilinearityExact
import DASHI.Moonshine.Monster3BFiniteHeisenbergCocycleExact
import DASHI.Moonshine.Monster3BFiniteHeisenbergAssociativityExact
import DASHI.Moonshine.Monster3BFiniteHeisenbergInverseExact
import DASHI.Moonshine.Monster3BFiniteHeisenbergGroupLawFrontierExact
import DASHI.Moonshine.Monster3BFiniteHeisenbergNondegeneracyExact
import DASHI.Moonshine.Monster3BFiniteStoneVonNeumannFrontierExact

import DASHI.Base369Ternary27StratifiedFibreHolonomyValidation
