module DASHI.DrugPolicyPsychedelicSemanticEpistemicValidation where

open import DASHI.Core.Prelude

import DASHI.Governance.DrugPolicyPsychedelicSemanticEpistemicEverything

import DASHI.Core.AffectedDependencyClosureExact as Affected
import DASHI.Core.ActionabilityCostedExperimentChoiceExact as Choice
import DASHI.Core.SequentialConsumerExperimentPlannerExact as Sequential
import DASHI.Governance.ContestedDrugCategoryAtlasBidiExact as Atlas
import DASHI.Governance.DrugCategoryMultiChartTranslationGeometryExact as Translation
import DASHI.Governance.DrugCategoryTranslationSelectiveReopeningExact as TranslationReopen
import DASHI.Governance.DrugCategoryTranslationPathResidueExact as PathResidue
import DASHI.Governance.DrugCategoryTranslationEdgeIndexedReopeningExact as EdgeIndexed
import DASHI.Governance.DrugCategoryPartialTranslationPathCategoryExact as PartialPath
import DASHI.Governance.DrugCategoryComposedPathEdgeReopeningExact as ComposedReopen
import DASHI.Governance.DrugCategoryConsumerIndexedTranslationAdmissionExact as ConsumerAdmission
import DASHI.Governance.DrugCategoryConsumerRelativeQuotientInverseExact as QuotientInverse
import DASHI.Governance.DrugCategoryConsumerRelativeInverseCompositionExact as InverseComposition
import DASHI.Governance.DrugCategoryQuotientInverseFailureBackpropExact as InverseFailure
import DASHI.Governance.DrugCategoryExplicitConsumerQuotientExact as ExplicitQuotient
import DASHI.Governance.DrugCategoryClinicalQuotientRelativeFibreExact as RelativeFibre
import DASHI.Governance.DrugCategoryConsumerQuotientRefinementExact as QuotientRefinement
import DASHI.Governance.DrugCategoryCostedQuotientDiscriminatorExact as CostedDiscriminator
import DASHI.Governance.DrugCategoryAdaptiveQuotientExperimentLoopExact as AdaptiveLoop
import DASHI.Governance.DrugGovernanceFiveProbeWorldExact as FiveWorld
import DASHI.Governance.DrugGovernanceFiveProbeOptionConeExact as FiveCone
import DASHI.Governance.DrugGovernanceFiveProbeAdaptivePlannerExact as FivePlanner
import DASHI.Governance.DrugGovernanceFarCrossPollinationCapstoneExact as Far
import DASHI.Governance.DrugCategoryPhilosophyOperatorAtlasExact as Philosophy
import DASHI.Governance.DrugCategoryPhilosophySelectiveReopeningExact as PhilosophyReopen

atlasBoundary : Atlas.ContestedDrugCategoryAtlasBoundary
atlasBoundary = Atlas.canonicalContestedDrugCategoryAtlasBoundary

translationBoundary : Translation.DrugCategoryMultiChartTranslationBoundary
translationBoundary = Translation.canonicalDrugCategoryMultiChartTranslationBoundary

translationReopeningBoundary : TranslationReopen.DrugCategoryTranslationReopeningBoundary
translationReopeningBoundary = TranslationReopen.canonicalDrugCategoryTranslationReopeningBoundary

translationPathBoundary : PathResidue.DrugCategoryTranslationPathResidueBoundary
translationPathBoundary = PathResidue.canonicalDrugCategoryTranslationPathResidueBoundary

edgeIndexedBoundary : EdgeIndexed.DrugCategoryTranslationEdgeIndexedBoundary
edgeIndexedBoundary = EdgeIndexed.canonicalDrugCategoryTranslationEdgeIndexedBoundary

partialTranslationPathBoundary : PartialPath.DrugCategoryPartialTranslationPathBoundary
partialTranslationPathBoundary = PartialPath.canonicalDrugCategoryPartialTranslationPathBoundary

composedPathReopeningBoundary : ComposedReopen.ComposedPathEdgeReopeningBoundary
composedPathReopeningBoundary = ComposedReopen.canonicalComposedPathEdgeReopeningBoundary

consumerAdmissionBoundary : ConsumerAdmission.DrugCategoryConsumerIndexedTranslationBoundary
consumerAdmissionBoundary = ConsumerAdmission.canonicalDrugCategoryConsumerIndexedTranslationBoundary

quotientInverseBoundary : QuotientInverse.DrugCategoryConsumerRelativeQuotientInverseBoundary
quotientInverseBoundary = QuotientInverse.canonicalDrugCategoryConsumerRelativeQuotientInverseBoundary

inverseCompositionBoundary : InverseComposition.ConsumerRelativeInverseCompositionBoundary
inverseCompositionBoundary = InverseComposition.canonicalConsumerRelativeInverseCompositionBoundary

inverseFailureBoundary : InverseFailure.QuotientInverseFailureBackpropBoundary
inverseFailureBoundary = InverseFailure.canonicalQuotientInverseFailureBackpropBoundary

explicitConsumerQuotientBoundary : ExplicitQuotient.DrugCategoryExplicitConsumerQuotientBoundary
explicitConsumerQuotientBoundary = ExplicitQuotient.canonicalDrugCategoryExplicitConsumerQuotientBoundary

relativeFibreBoundary : RelativeFibre.DrugCategoryClinicalQuotientRelativeFibreBoundary
relativeFibreBoundary = RelativeFibre.canonicalDrugCategoryClinicalQuotientRelativeFibreBoundary

quotientRefinementBoundary : QuotientRefinement.DrugCategoryConsumerQuotientRefinementBoundary
quotientRefinementBoundary = QuotientRefinement.canonicalDrugCategoryConsumerQuotientRefinementBoundary

costedDiscriminatorBoundary : CostedDiscriminator.DrugCategoryCostedQuotientDiscriminatorBoundary
costedDiscriminatorBoundary = CostedDiscriminator.canonicalDrugCategoryCostedQuotientDiscriminatorBoundary

adaptiveLoopBoundary : AdaptiveLoop.DrugCategoryAdaptiveQuotientExperimentBoundary
adaptiveLoopBoundary = AdaptiveLoop.canonicalDrugCategoryAdaptiveQuotientExperimentBoundary

fiveWorldBoundary : FiveWorld.FiveProbeWorldBoundary
fiveWorldBoundary = FiveWorld.canonicalFiveProbeWorldBoundary

fiveConeBoundary : FiveCone.FiveProbeOptionConeBoundary
fiveConeBoundary = FiveCone.canonicalFiveProbeOptionConeBoundary

fivePlannerBoundary : FivePlanner.FiveProbeAdaptivePlannerBoundary
fivePlannerBoundary = FivePlanner.canonicalFiveProbeAdaptivePlannerBoundary

farBoundary : Far.DrugGovernanceFarCrossPollinationBoundary
farBoundary = Far.canonicalDrugGovernanceFarCrossPollinationBoundary

philosophyBoundary : Philosophy.DrugCategoryPhilosophyOperatorBoundary
philosophyBoundary = Philosophy.canonicalDrugCategoryPhilosophyOperatorBoundary

philosophyReopeningBoundary : PhilosophyReopen.PhilosophySeededReopeningBoundary
philosophyReopeningBoundary = PhilosophyReopen.canonicalPhilosophySeededReopeningBoundary

stateClinicalRevisionStillReopensClinicalSafety :
  Affected.ReopeningObligation EdgeIndexed.Depends
    (EdgeIndexed.edgeArtifact EdgeIndexed.stateToClinicalEdge)
    (EdgeIndexed.consumerArtifact EdgeIndexed.clinicalSafetyConsequence)
stateClinicalRevisionStillReopensClinicalSafety = EdgeIndexed.stateClinicalRevisionReopensClinicalSafety

stateClinicalRevisionAlsoReopensComposedLivedConsumer :
  Affected.ReopeningObligation ComposedReopen.Depends
    (ComposedReopen.edgeArtifact EdgeIndexed.stateToClinicalEdge)
    (ComposedReopen.consumerCertificate ComposedReopen.livedSubjectMaintained)
stateClinicalRevisionAlsoReopensComposedLivedConsumer =
  ComposedReopen.stateClinicalRevisionReopensLivedSubjectConsumer

clinicalFactPreservedButSubjectNotGloballyPreserved :
  PartialPath.CoordinatePreserved PartialPath.stateClinicalLivedPath Translation.clinicalFactCoordinate
clinicalFactPreservedButSubjectNotGloballyPreserved =
  PartialPath.clinicalFactPreservedAlongStateClinicalLived

clinicalConsumerAdmitsComposedPath :
  ConsumerAdmission.ConsumerPathSafe ConsumerAdmission.clinicalSafetyConsumer PartialPath.stateClinicalLivedPath
clinicalConsumerAdmitsComposedPath = ConsumerAdmission.clinicalSafetyAdmitsStateClinicalLived

clinicalQuotientInverseExistsOnComposedPath :
  QuotientInverse.ConsumerRelativeQuotientInverse
    ConsumerAdmission.clinicalSafetyConsumer PartialPath.stateClinicalLivedPath
clinicalQuotientInverseExistsOnComposedPath =
  QuotientInverse.clinicalQuotientInverseOnStateClinicalLived

clinicalQuotientInverseComposesAcrossPathSegments :
  QuotientInverse.ConsumerRelativeQuotientInverse
    ConsumerAdmission.clinicalSafetyConsumer
    (PartialPath.appendPath InverseComposition.stateClinicalPath InverseComposition.clinicalLivedPath)
clinicalQuotientInverseComposesAcrossPathSegments = InverseComposition.composedClinicalInverse

historyInverseFailureCreatesReconstructionDemand :
  TranslationReopen.ReconstructionDemand Translation.historyResidual
historyInverseFailureCreatesReconstructionDemand = InverseFailure.historyFailureBackpropagates

clinicalObserverDescendsButSubjectObserverDoesNot :
  ExplicitQuotient.DescendsThrough
    ExplicitQuotient.clinicalObserver ExplicitQuotient.clinicalObserver
clinicalObserverDescendsButSubjectObserverDoesNot =
  ExplicitQuotient.clinicalDescendsThroughClinical

clinicalPlusRelativeFineExactlyReopensState :
  (state : ExplicitQuotient.TranslationState) →
  RelativeFibre.reopenClinicalRelative
    (ExplicitQuotient.clinicalObserver state)
    (RelativeFibre.relativeSemantic state)
  ≡ state
clinicalPlusRelativeFineExactlyReopensState =
  RelativeFibre.clinicalPlusRelativeReconstructsState

subjectNonDescentSelectsSubjectRefinement : QuotientRefinement.RefinementCoordinate
subjectNonDescentSelectsSubjectRefinement = QuotientRefinement.canonicalSubjectRefinement

subjectProbeIsDeclaredCheapestResolvingMove :
  Choice.CheapestResolvingMove
    CostedDiscriminator.subjectProblem
    CostedDiscriminator.DeclaredProbeMove
subjectProbeIsDeclaredCheapestResolvingMove = CostedDiscriminator.subjectCheapestResolving

subjectSelectedProbeClosesSubjectConsumer :
  Sequential.SequentialConsumerPlan
    AdaptiveLoop.subjectConsumer
    (AdaptiveLoop.allCompatible tt)
subjectSelectedProbeClosesSubjectConsumer = AdaptiveLoop.subjectOneShotPlan

authorityProbeNowHasLiveSeparator = FiveWorld.authoritySeparates
materialProbeNowHasLiveSeparator = FiveWorld.materialSeparates
sovereigntyProbeNowHasLiveSeparator = FiveWorld.sovereigntySeparates

sovereignExternalisationContractsOptionCone = FiveCone.sovereignToExternalContracts

authoritySelectedProbeClosesAuthorityConsumer :
  Sequential.SequentialConsumerPlan
    FiveWorld.authorityPosition
    (FivePlanner.allCompatible tt)
authoritySelectedProbeClosesAuthorityConsumer = FivePlanner.authorityPlan
