module DASHI.EverythingRelationalTrialecticHyperfabric where

------------------------------------------------------------------------
-- RELATIONAL TRIALECTIC HYPERFABRIC ROLLUP
--
-- This is an aggregate import only.  It does not strengthen any source claim.
-- In particular:
--   * citations do not import proof or authority;
--   * a general relational architecture is not a trauma-causal theorem;
--   * 369/D4/C3/Monster arithmetic is not psychological semantics;
--   * tetralemma/sixfold qualification does not replace the relational carrier;
--   * three dyadic edge states do not determine the triadic face.
------------------------------------------------------------------------

import DASHI.Core.RelationalTrialecticSourceAtlasExact
import DASHI.Core.RelationalTrialecticDisambiguationExact
import DASHI.Core.RelationalSelfStalkExact
import DASHI.Core.RelationalSelfDescentExact
import DASHI.Core.RelationalTransportDescentSheafExact
import DASHI.Core.RelationalTransportGroupoidActionExact
import DASHI.Core.RelationalTransportActionTwoCellExact
import DASHI.Core.IrigarayContactRelationalRechartExact

import DASHI.Reasoning.TrialecticObserverMatrix369Exact
import DASHI.Reasoning.Trialectic369DescentNaturalityExact
import DASHI.Reasoning.ActualFaceHypercubeGluingFromSharedSliceExact
import DASHI.Reasoning.Trialectic369CechCornerStarRecognitionExact
import DASHI.Reasoning.Trialectic369AppraisalSharedX6SliceExact
import DASHI.Core.ActionOrbitRecognitionFunctorExact
import DASHI.Reasoning.TrialecticBraidedTwoEyedCoordinationExact
import DASHI.Reasoning.TrialecticThreeStrandBraidHistoryExact
import DASHI.Core.ProvenancePreservingRecognitionFunctorExact
import DASHI.Reasoning.Trialectic369CechGrothendieckComparisonExact
import DASHI.Reasoning.TrialecticAttachedTwoCellExact
import DASHI.Reasoning.TrialecticDyadicCoverNerveExact
import DASHI.Reasoning.Trialectic369RubikRefinementExact
import DASHI.Reasoning.Trialectic369HypervoxelUltrametricExact
import DASHI.Reasoning.Trialectic369ObserverHeisenbergFactorizationExact
import DASHI.Reasoning.Trialectic369DeclaredRowConsumerExact
import DASHI.Reasoning.Trialectic369SurfaceConsumerRoutingExact
import DASHI.Reasoning.TrialecticBoundaryFaceNonfactorabilityExact
import DASHI.Reasoning.TrialecticProductiveJoinDescentExact
import DASHI.Reasoning.TrialecticThreeCellHyperformSynthesisExact
import DASHI.Reasoning.TrialecticGrothendieckThreeCellDescentExact
import DASHI.Reasoning.TrialecticGrothendieckAttachedTwoCellDescentExact
import DASHI.Reasoning.TrialecticHigherDescentPromotionLedgerExact
import DASHI.Reasoning.TrialecticGrothendieckTransitionCocycleExact
import DASHI.Reasoning.TrialecticGrothendieckTransportCoherenceExact
import DASHI.Reasoning.TrialecticGrothendieckCellPresheafExact
import DASHI.Reasoning.TrialecticThreeCellCarryDepthExact
import DASHI.Reasoning.TrialecticLocalLogicQualificationExact
import DASHI.Reasoning.RelationalPerspectiveSubjectExact
import DASHI.Reasoning.RelationalPerspectiveIntegrationExact

import DASHI.Foundations.RelationalStageTwelveSiteExact
import DASHI.Foundations.RelationalStageTwelveGrothendieckExtensionExact
import DASHI.Foundations.RelationalDepthPresheafExact
import DASHI.Foundations.RelationalDepthBidescentExact
import DASHI.Foundations.TrialecticDepthHyperformExact
import DASHI.Foundations.RelationalObserverNonaryD4DecompositionExact
import DASHI.Foundations.TrialecticD4C3ResidualBoundaryExact
import DASHI.Foundations.TrialecticZeroToThirteenStageBoundaryExact

import DASHI.Cognition.PNF.TrialecticMentalizingCalibrationExact
import DASHI.Cognition.PNF.PerspectiveAllocationExact
import DASHI.Cognition.PNF.IntegrativeComplexityDifferentiationIntegrationExact
import DASHI.Cognition.PNF.RelationalPerspectiveFactorsThroughExact
import DASHI.Cognition.PNF.AdmissibleFactorisationDecisionHyperfabricExact
import DASHI.Cognition.PNF.RelationalSubjectMemoryDecisionHyperfabricExact
import DASHI.Cognition.PNF.TrialecticMemoryLearningHyperfabricExact
import DASHI.Biology.ThreatMentalizingRelationalMonitoringSeparationExact
import DASHI.Biology.ThreatCalibratedSocialPerceptionBoundaryExact
import DASHI.Biology.TraumaRelationalLearningNonpromotionExact
import DASHI.Biology.TriangulationParentificationSourceAtlasExact
import DASHI.Biology.InterparentalThreatRelationalAdaptationSourceAtlasExact
import DASHI.Reasoning.MediatorActionMotiveNonFactorabilityExact
import DASHI.Cognition.PNF.RelationalPerspectiveTrialecticExact
import DASHI.TraumaRelationalPerspectiveHyperfabricExact

-- Explicit donors whose theorem surfaces are reused rather than duplicated.
import DASHI.Core.ArgumentResponseNonGeometricOppositeBidiExact
import DASHI.Algebra.DisagreementFourViewBoundary
import DASHI.Reasoning.LacanSignifierSubjectCore
import DASHI.Core.IrigarayLabialRelationalCarrierExact
import DASHI.Governance.SexedHistoricalProductiveDialecticalFibreJoinExact
import DASHI.Foundations.StageTwelveGrothendieckRelationHyperformExact
import DASHI.Reasoning.TernarySynthesisLogicQualificationExact
import DASHI.Cognition.PNF.MemoryFibre
import DASHI.Cognition.PNF.LearningAlgebra
import DASHI.Cognition.PNF.FibreLearningDynamics
import DASHI.Cognition.PNF.DecisionActionProjectionNonFactorabilityExact
import DASHI.Cognition.PNF.DecisionActionFibreMultiplicityExact
import DASHI.Cognition.PNF.TraumaMemoryHypervoxelBridge
import DASHI.Reasoning.TraumaAttractorBranchRegulationExact

import DASHI.Reasoning.Trialectic369CechAugmentedCornerStarIndexExact

import DASHI.Reasoning.Trialectic369CechModelSameObjectCapstoneExact

import DASHI.Reasoning.Trialectic369DyadicSectionTriadicKernelExact

import DASHI.Reasoning.Trialectic369DyadicKernel4DescentCountExact

import DASHI.Reasoning.Trialectic369DyadicLocalComplementFactorizationExact

import DASHI.Reasoning.Trialectic369DyadicC3LocalComplementSymmetryExact

import DASHI.Reasoning.Trialectic369DyadicPointedRelativeLocalExact

import DASHI.Reasoning.Trialectic369PreRHTernaryLocalDescentCapstoneExact

import DASHI.Reasoning.Trialectic369DyadicLocalNineObserverCandidateExact

import DASHI.Reasoning.Trialectic369T5ComplementPhaseOrbitResidualExact

import DASHI.Reasoning.Trialectic369T5ComplementOggResidualBidiExact

import DASHI.Reasoning.Trialectic369ParticipantCenteredSSPFactorExact

import DASHI.Reasoning.Trialectic369OutgoingResidualSheet9BidiExact

import DASHI.Reasoning.Trialectic369SSP15RecognitionCapstoneExact

import DASHI.Reasoning.Trialectic369OutgoingSheet9ActionRestrictionCompilerExact

import DASHI.Reasoning.Trialectic369IncomingFaceFrickeQuotientSeparationExact

import DASHI.Reasoning.Trialectic369IncomingAnalyticFrickeQuotientRecognitionExact

import DASHI.Reasoning.Trialectic369OutgoingFineFrickeInvariantNoGoExact

import DASHI.Reasoning.Trialectic369OutgoingFrickeModeBlock18Exact

import DASHI.Reasoning.Trialectic369Shortest3BActionSourceBridgeExact

import DASHI.Reasoning.Trialectic369MultiplicityProjectionDescentCompilerExact

import DASHI.Reasoning.Trialectic369OutgoingLinearMultiplicityWrongTypeCorrectionExact

import DASHI.Reasoning.Trialectic369LinearMultiplicityBasisSpecialisationCompilerExact

import DASHI.Reasoning.Trialectic369OutgoingLinearAcquisitionBridgeExact

import DASHI.Reasoning.Trialectic369Selected3BLinearAcquisitionCompletionExact

import DASHI.Reasoning.Trialectic369CanonicalSelected3BLinearCoreExact

import DASHI.Reasoning.Trialectic369Selected3BLinearCoreCompatibilityExact

import DASHI.Reasoning.Trialectic369MultiplicityProjectionPositionIndependenceExact

import DASHI.Reasoning.Trialectic369Selected3BActionViaFaithfulInclusionExact

import DASHI.Reasoning.Trialectic369MonomialMultiplicityBasisSpecialisationExact

import DASHI.Reasoning.Trialectic369Selected3BSourceAndMonomialCapstoneExact

import DASHI.Reasoning.Trialectic369MonomialTenByNineTransportExact

import DASHI.Reasoning.Trialectic369MultiplicityNormalizerTranslationDescentExact

import DASHI.Reasoning.Trialectic369HistoricalMultiplicityAttachmentDescentBidiExact

import DASHI.Reasoning.Trialectic369Selected3BFullGradeActionMaxCutExact

import DASHI.Reasoning.Trialectic369Selected3BConstituentRetractionExact

import DASHI.Reasoning.Trialectic369OrbifoldCoordinateRetractionWrongTypeExact

import DASHI.Reasoning.Trialectic369Selected3BProjectedActionMaxCutExact

import DASHI.Reasoning.Trialectic369SemanticLinearConstituentRetractionCompilerExact

import DASHI.Reasoning.Trialectic369Selected3BSemanticProjectedCompletionExact

import DASHI.Reasoning.Trialectic369Selected3BProjectionChoiceIndependenceExact
