module DASHI.EverythingNonArchimedeanSpectralBidi where

import DASHI.Analysis.NonArchimedeanSpectralOrbitHypervoxelExact
import DASHI.Analysis.AdelicSpectralCrossPollinationBoundaryExact
import DASHI.Analysis.AdelicSpectralClaimStrengthAuditExact
import DASHI.Analysis.NonArchimedeanSpectralBidiObligationExact
import DASHI.Analysis.NonArchimedeanSpectralObligationRoutingExact
import DASHI.Analysis.NonArchimedeanSpectralCrossLaneBidiExact
import DASHI.Analysis.NonArchimedeanSpectralDirectLimitBidiExact
import DASHI.Analysis.NonArchimedeanSpectralSourceTheoremMatrixExact
import DASHI.Analysis.NonArchimedeanTwistedBlockReductionBidiExact
import DASHI.Analysis.NonArchimedeanSpatialCharacterIntertwinerReuseExact
import DASHI.Analysis.NonArchimedeanSpectralExistingMachineryCrossPollinationExact
import DASHI.Analysis.NonArchimedeanDyadicResolutionHyperfabricBidiExact
import DASHI.Analysis.NonArchimedeanSpectralProofSearchPruningBidiExact
import DASHI.Analysis.NonArchimedeanHadamardTwistedSectorBidiExact
import DASHI.Analysis.NonArchimedeanTwistedSpatialPowerCompilerExact

-- Source-exact correction / original spectral frontier.
import DASHI.Analysis.NonArchimedeanSpectralHypothesisSemanticCorrectionExact
import DASHI.Analysis.NonArchimedeanConcreteDFTMonomialWeldBidiExact
import DASHI.Analysis.NonArchimedeanSpectralCircleDependencyRepairExact
import DASHI.Analysis.NonArchimedeanSpectralTowerSourceRepairBidiExact
import DASHI.Analysis.NonArchimedeanDFTSimilaritySpectrumReuseExact
import DASHI.Analysis.NonArchimedeanOddOrbitCoordinateChartBidiExact
import DASHI.Analysis.NonArchimedeanCanonicalOddOrbitProducerBidiExact
import DASHI.Analysis.NonArchimedeanFullCycleSignedCancellationBidiExact
import DASHI.Analysis.NonArchimedeanMonomialTraceSpatialBidiExact

-- Corrected character-basis closure route.  Existing finite DFT theory and
-- matrix faithfulness are reused; the source product DFT is retained only as a
-- unitary artifact, not as the literal odd-character transform.
import DASHI.Analysis.NonArchimedeanCharacterBasisMatrixFaithfulnessReuseExact
import DASHI.Analysis.NonArchimedeanHalfPeriodCharacterClassifierExact
import DASHI.Analysis.NonArchimedeanTauOddCharacterRestrictionBidiExact
import DASHI.Analysis.NonArchimedeanOddCharacterFourierRechartCorrectionExact
import DASHI.Analysis.NonArchimedeanOddCharacterDFTSourceReuseExact
import DASHI.Analysis.NonArchimedeanProductDFTOddCharacterNoGoExact
import DASHI.Analysis.NonArchimedeanBinarySheetTauOddEquivalenceExact
import DASHI.Analysis.NonArchimedeanTwistedTauOddFunctionEquivalenceExact
import DASHI.Analysis.NonArchimedeanTwistedRestrictionIntertwinerExact
import DASHI.Analysis.NonArchimedeanTwistedRestrictionCoreIntertwinerExact
import DASHI.Analysis.NonArchimedeanConcreteMonomialWeldCompilerExact

-- Arithmetic orbit and signed-return closure.  The stronger checked source
-- theorem `three_pow_two_pow` carries an odd coefficient and supplies the extra
-- dyadic bit needed for the orbit-sum phase; explicit +/- i sqrt(2) values are
-- pruned from the critical path.
import DASHI.Analysis.NonArchimedeanOddOrbitDFTRechartCorrectionExact
import DASHI.Analysis.NonArchimedeanOddOrbitEquivalenceCompilerExact
import DASHI.Analysis.NonArchimedeanCanonicalOddOrbitClosureReuseExact
import DASHI.Analysis.NonArchimedeanPowerOrbitSumBidiExact
import DASHI.Analysis.NonArchimedeanThreePowerOddCoefficientReuseExact
import DASHI.Analysis.NonArchimedeanNegativeOrbitConjugationBidiExact
import DASHI.Analysis.NonArchimedeanOneOrbitTraceCancellationExact
import DASHI.Analysis.NonArchimedeanOrbitSumToSignedCancellationExact
import DASHI.Analysis.NonArchimedeanNegativeOrbitWeightPhaseCompilerExact
import DASHI.Analysis.NonArchimedeanOrbitCancellationToMinusTwoExact
import DASHI.Analysis.NonArchimedeanSpectralOriginalGoalCapstoneExact

-- Optional Monster correspondence x-pollination.  These remain downstream
-- comparison fibres and are not prerequisites for the source spectral closure.
import DASHI.Analysis.NonArchimedeanMonster3BDyadicCorrespondenceBidiExact
import DASHI.Analysis.NonArchimedeanMonster3BPhaseBulkHypervoxelExact
import DASHI.Analysis.NonArchimedeanMonster3BActionSeparationExact
import DASHI.Analysis.NonArchimedeanMonster3BResidualFactorizationExact
import DASHI.Analysis.NonArchimedeanMonsterWilsonDyadicReconciliationExact
import DASHI.Analysis.NonArchimedeanMonsterCorrespondencePromotionKernelExact
