module DASHI.EverythingDigitalESDReciprocalBraid where

------------------------------------------------------------------------
-- Thin aggregate for the digital-ESD research-call tranche.
--
-- Import-only by design: the substantive owners retain their own provenance,
-- authority and non-promotion boundaries.
------------------------------------------------------------------------

import DASHI.Education.DigitalInnovationESDSourceAtlas
import DASHI.Education.DigitalInnovationESDTransformationExact
import DASHI.Education.MDPISpecialIssueResearchGovernanceExact
import DASHI.Education.AliceBrownDigitalESDEpistemicGovernanceBridgeExact
import DASHI.Education.DigitalESDReciprocalBraidExact
import DASHI.Education.DigitalESDCrossRoundAttributionBoundaryExact
import DASHI.Education.DigitalESDAcquisitionSnowballParetoExact
import DASHI.Education.DigitalESDAcquisitionSnowballRegression
import DASHI.Education.DigitalESDSourceAttributionCorrectionExact
import DASHI.Education.DigitalESDSourceAttributionCorrectionRegression
import DASHI.Education.DigitalESDICTLifecycleCircularitySnowballExact
import DASHI.Education.DigitalESDICTLifecycleCircularitySnowballRegression
import DASHI.Education.DigitalESDSameObjectAcquisitionSchedulerExact
import DASHI.Education.DigitalESDSameObjectAcquisitionSchedulerRegression
import DASHI.Education.DigitalESDParticipantGovernanceContextTransferExact
import DASHI.Education.DigitalESDParticipantGovernanceContextTransferRegression
import DASHI.Education.DigitalESDEducationSustainabilityLiteratureMapExact
import DASHI.Education.DigitalESDEducationSustainabilityLiteratureMapRegression
import DASHI.Education.DigitalESDCurrentScholarlySnowballExact
import DASHI.Education.DigitalESDCurrentScholarlySnowballRegression
import DASHI.Education.DigitalESDContributionPositioningExact
import DASHI.Education.DigitalESDContributionPositioningRegression
import DASHI.Education.DigitalESDTransferablePedagogicalPrinciplesExact
import DASHI.Education.DigitalESDTransferablePedagogicalPrinciplesRegression
import DASHI.Education.DigitalESDExternalityIncidenceAuditExact
import DASHI.Education.DigitalESDExternalityIncidenceAuditRegression
import DASHI.Education.DigitalESDStudyClaimCeilingExact
import DASHI.Education.DigitalESDStudyClaimCeilingRegression
import DASHI.Education.DigitalESDStudyClaimMethodBridgeExact
import DASHI.Education.DigitalESDStudyClaimPilotExact
import DASHI.Education.DigitalESDStudyClaimPilotRegression
import DASHI.Education.DigitalESDStudyClaimPilotExtensionExact
import DASHI.Education.DigitalESDStudyClaimPilotExtensionRegression
import DASHI.Education.DigitalESDStudyClaimQuantitativePilotExact
import DASHI.Education.DigitalESDStudyClaimQuantitativePilotRegression
import DASHI.Education.DigitalESDStudyAnalysisSetRefinementExact
import DASHI.Education.DigitalESDStudyAnalysisSetRefinementRegression
import DASHI.Education.DigitalESDQuantitativeUncertaintyAcquisitionExact
import DASHI.Education.DigitalESDQuantitativeUncertaintyAcquisitionRegression
import DASHI.Education.DigitalESDRandomizedCausalAcquisitionExact
import DASHI.Education.DigitalESDRandomizedCausalAcquisitionRegression
import DASHI.Education.DigitalESDInstitutionalEvaluationPilotExact
import DASHI.Education.DigitalESDInstitutionalEvaluationPilotRegression
import DASHI.Education.DigitalESDEmpiricalAuthorityFirewallExact
import DASHI.Education.DigitalESDEmpiricalAuthorityFirewallRegression
import DASHI.Education.DigitalESDTransformativePrincipleMatrixExact
import DASHI.Education.DigitalESDTransformativePrincipleMatrixRegression
import DASHI.Education.DigitalESDTransferablePrincipleDerivationMethodExact
import DASHI.Education.DigitalESDTransferablePrincipleDerivationMethodRegression
import DASHI.Education.DigitalESDPaperTypeRequirementParetoExact
import DASHI.Education.DigitalESDPaperTypeRequirementRegression
import DASHI.Education.DigitalESDConsumerRelativeLifecycleExact
import DASHI.Education.DigitalESDConsumerRelativeLifecycleRegression
import DASHI.Education.DigitalESDStructuredSearchExact
import DASHI.Education.DigitalESDManuscriptDependencyPaymentAdapterExact
import DASHI.Education.DigitalESDStructuredSearchRegression
import DASHI.Education.DigitalESDPrimarySourceMethodologyAtlasExact
import DASHI.Education.DigitalESDManuscriptMethodologyExact
import DASHI.Education.DigitalESDManuscriptMethodologyRegression
import DASHI.Education.DigitalESDPreScreenCandidateSourceScopeMatrixExact
import DASHI.Education.DigitalESDPreScreenCandidateSourceScopeMatrixRegression
import DASHI.Education.DigitalESDDatabaseSearchProtocolExact
import DASHI.Education.DigitalESDDatabaseSearchProtocolRegression
import DASHI.Education.DigitalESDDatabaseTranslationSyntaxExact
import DASHI.Education.DigitalESDDatabaseTranslationSyntaxRegression
import DASHI.Education.DigitalESDDatabaseTranslatedQueriesExact
import DASHI.Education.DigitalESDDatabaseTranslatedQueriesRegression
import DASHI.Education.DigitalESDDatabaseExecutionReceiptExact
import DASHI.Education.DigitalESDDatabaseExecutionReceiptRegression
import DASHI.Education.DigitalESDCanonicalOwnerRegression
import DASHI.Education.DigitalInnovationESDRegression
