module DASHI.JInvariantBase369CrossPollinationEverything where

import DASHI.Moonshine.JInvariantSourceAtlasExact
import DASHI.Moonshine.JInvariantImageFractalSourceAtlasExact
import DASHI.Moonshine.JInvariantLambdaOrbitBase369BridgeExact
import DASHI.Moonshine.JInvariantIntrospectiveCrossPollinationExact
import DASHI.Moonshine.JInvariantColourWheelWaveSignedBidiExact
import DASHI.Moonshine.JInvariantColourWheelPolyphaseSpectralBidiExact
import DASHI.Moonshine.JInvariantColourWheelCyclotomicBidiAdvanceExact
import DASHI.Moonshine.JInvariantColourWheelWaveSignedValidation
import DASHI.Moonshine.JInvariantRainbowFullTurnHyperformExact
import DASHI.Moonshine.JInvariantSignedFibreFractalBidiExact
import DASHI.Moonshine.JInvariantOrderThreeOrbitBalancedTernaryBidiExact
import DASHI.Moonshine.JInvariantOrderThreeSeamModularWordExact
import DASHI.Moonshine.JInvariantOrderThreeSeamScaleRecognitionBidiExact
import DASHI.Moonshine.JInvariantFibonacciJCoarseFineVoxelBidiExact
import DASHI.Moonshine.JInvariantJCoarseFineElevenTritChartShiftExact
import DASHI.Moonshine.JInvariantJCoarseFineFrickeBoundaryTransportBidiExact

-- RH relation-pattern reuse: retain full fine residual by default and quotient
-- only under a declared consumer-sufficiency proof.
import DASHI.Moonshine.JInvariantRiemannObserverResidualSufficiencyBidiExact

-- Rendered acquisition is split into image->analytic and analytic->structured
-- stages.  Once the analytic coordinate supplies both a full structured field
-- and a seam-scale recognizer, the same-object compiler immediately emits the
-- local 27 observer, orbit index, orbit scale and modular-word index packet.
import DASHI.Moonshine.JInvariantRenderedAnalyticStructuredAcquisitionBoundaryExact
import DASHI.Moonshine.JInvariantAnalyticStructuredSeamCompilerBidiExact

import DASHI.Moonshine.JInvariantTeslaPolyphaseSeamRefinementBidiExact
import DASHI.Moonshine.GoldenRatioBinaryTernaryFibreConstructionExact
import DASHI.Moonshine.GoldenRatioBalancedTernaryFRACTRANModularPathExact
import DASHI.Moonshine.GoldenRatioBalancedFRACTRANBishopRatioCarrierExact
import DASHI.Moonshine.GoldenRatioBalancedFRACTRANDenominatorGrowthExact

-- Includes exact Bishop phi/psi quadratic factorisation and the remaining
-- reciprocal-square / conjugate-factor analytic producer boundary.
import DASHI.Moonshine.QuadraticSignedApproximationEverything

import DASHI.Moonshine.JInvariantKleinConstructionGluingBidiExact
import DASHI.Moonshine.MonsterGradedSignedFibreBidiExact
import DASHI.Moonshine.JInvariantBase369RoadmapFrontierExact

import DASHI.Foundations.Base369MobiusTransport
import DASHI.Foundations.Base369WaveContinuousSymbolicCodingExact
import DASHI.Foundations.Base369PolyphaseCharacters
import DASHI.Biology.TriadicKernelLiftQuotientExact
import DASHI.Biology.SignedSSPFRACTRANWeaveExact
import DASHI.Foundations.Base369Ternary27HypervoxelFabricGeometryExact
import DASHI.Moonshine.Base369Ternary27SpectralSymmetryIrrepBridgeExact
import DASHI.Moonshine.C3FourierConjugationExact
import DASHI.Moonshine.MonsterC3CyclotomicEvaluationExact
