module DASHI.JInvariantBase369CrossPollinationEverything where

import DASHI.Moonshine.JInvariantSourceAtlasExact
import DASHI.Moonshine.JInvariantImageFractalSourceAtlasExact
import DASHI.Moonshine.JInvariantLambdaOrbitBase369BridgeExact
import DASHI.Moonshine.JInvariantIntrospectiveCrossPollinationExact
import DASHI.Moonshine.JInvariantColourWheelWaveSignedBidiExact
import DASHI.Moonshine.JInvariantColourWheelPolyphaseSpectralBidiExact
import DASHI.Moonshine.JInvariantColourWheelCyclotomicBidiAdvanceExact
import DASHI.Moonshine.JInvariantColourWheelWaveSignedValidation
import DASHI.Moonshine.JInvariantRainbowFullTurnHyperformExact
import DASHI.Moonshine.JInvariantSignedFibreFractalBidiExact
import DASHI.Moonshine.JInvariantOrderThreeOrbitBalancedTernaryBidiExact
import DASHI.Moonshine.JInvariantOrderThreeSeamModularWordExact
import DASHI.Moonshine.JInvariantOrderThreeSeamScaleRecognitionBidiExact
import DASHI.Moonshine.JInvariantFibonacciJCoarseFineVoxelBidiExact
import DASHI.Moonshine.JInvariantJCoarseFineElevenTritChartShiftExact
import DASHI.Moonshine.JInvariantJCoarseFineFrickeBoundaryTransportBidiExact

-- RH relation-pattern reuse: retain full fine residual by default and quotient
-- only under a declared consumer-sufficiency proof.
import DASHI.Moonshine.JInvariantRiemannObserverResidualSufficiencyBidiExact

-- Rendered acquisition is split into image->analytic and analytic->structured
-- stages.  The stricter interval-valued recognizer keeps pixel uncertainty as
-- a fibre and recognises k only after exact orbit containment and uniqueness.
-- The tri-BIDI governance owner cross-pollinates this with the existing RH
-- hidden-residual rule and light-transport side-information firewall at exact
-- certificate-schema strength only: no theorem is transferred between lanes.
-- Once analytic structured/scale producers exist, the same-object compiler
-- emits local 27, k, D_k and the L^kT word packet immediately.
import DASHI.Moonshine.JInvariantRenderedAnalyticStructuredAcquisitionBoundaryExact
import DASHI.Moonshine.JInvariantRenderedIntervalOrbitRecognitionBidiExact
import DASHI.Moonshine.JInvariantRenderedResidualGovernanceTriBidiExact
import DASHI.Moonshine.JInvariantAnalyticStructuredSeamCompilerBidiExact

import DASHI.Moonshine.JInvariantTeslaPolyphaseSeamRefinementBidiExact
import DASHI.Moonshine.GoldenRatioBinaryTernaryFibreConstructionExact
import DASHI.Moonshine.GoldenRatioBalancedTernaryFRACTRANModularPathExact
import DASHI.Moonshine.GoldenRatioBalancedFRACTRANBishopRatioCarrierExact
import DASHI.Moonshine.GoldenRatioBalancedFRACTRANDenominatorGrowthExact

-- Includes exact norm-one, denominator-cleared reciprocal-square, Bishop
-- phi/psi factorisation, Bishop reciprocal-square convergence, and the
-- remaining rational/Bishop/order same-object producer debt.
import DASHI.Moonshine.QuadraticSignedApproximationEverything

import DASHI.Moonshine.JInvariantKleinConstructionGluingBidiExact
import DASHI.Moonshine.MonsterGradedSignedFibreBidiExact
import DASHI.Moonshine.JInvariantBase369RoadmapFrontierExact

import DASHI.Foundations.Base369MobiusTransport
import DASHI.Foundations.Base369WaveContinuousSymbolicCodingExact
import DASHI.Foundations.Base369PolyphaseCharacters
import DASHI.Biology.TriadicKernelLiftQuotientExact
import DASHI.Biology.SignedSSPFRACTRANWeaveExact
import DASHI.Foundations.Base369Ternary27HypervoxelFabricGeometryExact
import DASHI.Moonshine.Base369Ternary27SpectralSymmetryIrrepBridgeExact
import DASHI.Moonshine.C3FourierConjugationExact
import DASHI.Moonshine.MonsterC3CyclotomicEvaluationExact
