module DASHI.JInvariantBase369CrossPollinationEverything where

import DASHI.Moonshine.JInvariantSourceAtlasExact
import DASHI.Moonshine.JInvariantImageFractalSourceAtlasExact
import DASHI.Moonshine.JInvariantLambdaOrbitBase369BridgeExact
import DASHI.Moonshine.JInvariantIntrospectiveCrossPollinationExact
import DASHI.Moonshine.JInvariantColourWheelWaveSignedBidiExact
import DASHI.Moonshine.JInvariantColourWheelPolyphaseSpectralBidiExact
import DASHI.Moonshine.JInvariantColourWheelCyclotomicBidiAdvanceExact
import DASHI.Moonshine.JInvariantColourWheelWaveSignedValidation
import DASHI.Moonshine.JInvariantRainbowFullTurnHyperformExact
import DASHI.Moonshine.JInvariantSignedFibreFractalBidiExact
import DASHI.Moonshine.JInvariantOrderThreeOrbitBalancedTernaryBidiExact
import DASHI.Moonshine.JInvariantOrderThreeSeamModularWordExact
import DASHI.Moonshine.JInvariantOrderThreeSeamScaleRecognitionBidiExact
import DASHI.Moonshine.JInvariantOrderThreeVisibleScaleUniquenessBidiExact
import DASHI.Moonshine.JInvariantOrderThreeScaleGlobalInjectiveExact
import DASHI.Moonshine.JInvariantFibonacciJCoarseFineVoxelBidiExact
import DASHI.Moonshine.JInvariantJCoarseFineElevenTritChartShiftExact
import DASHI.Moonshine.JInvariantJCoarseFineFrickeBoundaryTransportBidiExact
import DASHI.Moonshine.JInvariantAnalyticJCoarseFineFrickeIntertwinerExact

-- RH relation-pattern reuse: retain full fine residual by default and quotient
-- only under a declared consumer-sufficiency proof.
import DASHI.Moonshine.JInvariantRiemannObserverResidualSufficiencyBidiExact

-- Rendered acquisition is split into image->analytic and analytic->structured
-- stages. Pixel uncertainty remains a fibre. Once a calibration determines an
-- exact D_k scale, global injectivity of D_k=k^2+k+1 makes orbit uniqueness
-- compiler-owned for all Nat. The concrete rendered-scale fixture closes the
-- executable protocol without pretending that an external raster has itself
-- been metrologically calibrated in Agda.
import DASHI.Moonshine.JInvariantRenderedAnalyticStructuredAcquisitionBoundaryExact
import DASHI.Moonshine.JInvariantRenderedIntervalOrbitRecognitionBidiExact
import DASHI.Moonshine.JInvariantRenderedVisibleScaleCompilerBidiExact
import DASHI.Moonshine.JInvariantRenderedGlobalScaleCompilerBidiExact
import DASHI.Moonshine.JInvariantRenderedScaleCalibrationFixtureExact
import DASHI.Moonshine.JInvariantRenderedResidualGovernanceTriBidiExact
import DASHI.Moonshine.JInvariantAnalyticStructuredSeamCompilerBidiExact

import DASHI.Moonshine.JInvariantTeslaPolyphaseSeamRefinementBidiExact
import DASHI.Moonshine.GoldenRatioBinaryTernaryFibreConstructionExact
import DASHI.Moonshine.GoldenRatioBalancedTernaryFRACTRANModularPathExact
import DASHI.Moonshine.GoldenRatioBalancedFRACTRANBishopRatioCarrierExact
import DASHI.Moonshine.GoldenRatioBalancedFRACTRANDenominatorGrowthExact

-- Includes the completed source/static Bishop-phi lane: norm-one, rational and
-- Bishop defect welds, reciprocal-square convergence, phi/psi factorisation,
-- uniform conjugate separation and final FRACTRAN Fibonacci ratio convergence.
import DASHI.Moonshine.QuadraticSignedApproximationEverything

import DASHI.Moonshine.JInvariantKleinConstructionGluingBidiExact
import DASHI.Moonshine.MonsterGradedSignedFibreBidiExact
import DASHI.Moonshine.MonsterGraded3BPhaseFibreIntertwinerExact
import DASHI.Moonshine.JInvariantBase369RoadmapFrontierExact

import DASHI.Foundations.Base369MobiusTransport
import DASHI.Foundations.Base369WaveContinuousSymbolicCodingExact
import DASHI.Foundations.Base369PolyphaseCharacters
import DASHI.Biology.TriadicKernelLiftQuotientExact
import DASHI.Biology.SignedSSPFRACTRANWeaveExact
import DASHI.Foundations.Base369Ternary27HypervoxelFabricGeometryExact
import DASHI.Moonshine.Base369Ternary27SpectralSymmetryIrrepBridgeExact
import DASHI.Moonshine.C3FourierConjugationExact
import DASHI.Moonshine.MonsterC3CyclotomicEvaluationExact
