module DASHI.Analysis.CollatzSyracuseAffineCorrectionSwapExact where

------------------------------------------------------------------------
-- ADJACENT FIXED-COUNT CORRECTION SURGERY
--
-- This owner builds on DASHI's independently reconstructed correction cocycle.
-- Michael Sharpe's `msharpe248/collatz` WordSurgery.lean (commit
-- ec8174b567d5cab4960024782210b5f5db02bd3a) is external provenance for the
-- broader correction-replacement route; the elementary adjacent-swap theorem
-- below is a DASHI derivation on the local BinaryWord carrier.
--
-- Moving one odd bit one place to the right changes the exact affine
-- correction by one mixed-radix unit:
--
--   A(prefix ++ 01 ++ suffix)
--     = A(prefix ++ 10 ++ suffix)
--       + 2^(length prefix) * 3^(ones suffix).
--
-- Thus fixed-length/fixed-count word surgery is generated by explicit
-- 2^p 3^ell correction moves.  No claim of global attainability or stopping is
-- made here.
------------------------------------------------------------------------

open import Agda.Builtin.Equality using (_≡_; refl)
open import Agda.Builtin.Nat using (Nat; _+_; _*_)
open import Data.Nat.Solver using (module +-*-Solver)
open +-*-Solver using (solve; _:+_; _:*_; con; _:=_)

import DASHI.Core.BinaryBranchOutcomeEnumerationExact as Binary
import DASHI.NumberTheory.Collatz.SyracuseAffineIterateExact as Affine
import DASHI.Analysis.CollatzSyracuseAffineCorrectionCocycleExact as Cocycle

zeroOne :
  {n : Nat} →
  Binary.BinaryWord n →
  Binary.BinaryWord (2 + n)
zeroOne suffix = Binary.bit0 (Binary.bit1 suffix)

oneZero :
  {n : Nat} →
  Binary.BinaryWord n →
  Binary.BinaryWord (2 + n)
oneZero suffix = Binary.bit1 (Binary.bit0 suffix)

localZeroOneCorrection :
  {n : Nat} →
  (suffix : Binary.BinaryWord n) →
  Affine.affineAdditiveTerm (zeroOne suffix)
  ≡ 2 * Affine.powNat 3 (Affine.parityCount suffix)
      + 4 * Affine.affineAdditiveTerm suffix
localZeroOneCorrection suffix =
  solve 2
    (λ p a →
      con 2 :* (p :+ (con 2 :* a))
      :=
      (con 2 :* p) :+ (con 4 :* a))
    refl

localOneZeroCorrection :
  {n : Nat} →
  (suffix : Binary.BinaryWord n) →
  Affine.affineAdditiveTerm (oneZero suffix)
  ≡ Affine.powNat 3 (Affine.parityCount suffix)
      + 4 * Affine.affineAdditiveTerm suffix
localOneZeroCorrection suffix =
  solve 2
    (λ p a →
      p :+ (con 2 :* (con 2 :* a))
      :=
      p :+ (con 4 :* a))
    refl

localSwap :
  {n : Nat} →
  (suffix : Binary.BinaryWord n) →
  Affine.affineAdditiveTerm (zeroOne suffix)
  ≡ Affine.affineAdditiveTerm (oneZero suffix)
      + Affine.powNat 3 (Affine.parityCount suffix)
localSwap suffix
  rewrite localZeroOneCorrection suffix
        | localOneZeroCorrection suffix =
  solve 2
    (λ p a →
      (con 2 :* p) :+ (con 4 :* a)
      :=
      (p :+ (con 4 :* a)) :+ p)
    refl

------------------------------------------------------------------------
-- Lift the local swap through an arbitrary prefix with the exact cocycle.
------------------------------------------------------------------------

adjacentSwapCorrection :
  {p n : Nat} →
  (prefix : Binary.BinaryWord p) →
  (suffix : Binary.BinaryWord n) →
  Affine.affineAdditiveTerm
    (Cocycle.appendWord prefix (zeroOne suffix))
  ≡
  Affine.affineAdditiveTerm
    (Cocycle.appendWord prefix (oneZero suffix))
  + Affine.powNat 2 p * Affine.powNat 3 (Affine.parityCount suffix)
adjacentSwapCorrection {p} prefix suffix
  rewrite Cocycle.affineCorrectionCocycle prefix (zeroOne suffix)
        | Cocycle.affineCorrectionCocycle prefix (oneZero suffix)
        | localSwap suffix =
  solve 5
    (λ q a r d s →
      (q :* a) :+ (r :* (d :+ s))
      :=
      ((q :* a) :+ (r :* d)) :+ (r :* s))
    refl

record AffineCorrectionSwapBoundary : Set where
  constructor affineCorrectionSwapBoundary
  field
    localSwapOwned : Nat
    arbitraryPrefixLiftOwned : Nat
    exactMixedRadixStepOwned : Nat
    globalCorrectionCoverageOwned : Nat
    universalStoppingOwned : Nat

canonicalAffineCorrectionSwapBoundary : AffineCorrectionSwapBoundary
canonicalAffineCorrectionSwapBoundary =
  affineCorrectionSwapBoundary 1 1 1 0 0
