module DASHI.Interop.SensibLawBrightonS185AuthorityViolationFrontierValidation where

open import DASHI.Core.Prelude
open import Agda.Builtin.Equality using (_≡_; refl)

import DASHI.Law.SensibLawBrightonS185HistoricalAuthoritySourceExact as Historical
import DASHI.Cognition.PNF.SensibLawBrightonS185HistoricalAuthorityWeldExact as Weld
import DASHI.Cognition.PNF.SensibLawBrightonS185ViolationElementFrontierExact as Frontier

open Historical.HistoricalS185SourceVersionBoundary
open Weld.BrightonHistoricalAuthorityWeldBoundary
open Frontier.BrightonS185ViolationElementFrontierBoundary

historicalVersionPinned :
  exactVersionIdentityPinned Historical.canonicalHistoricalS185SourceVersionBoundary ≡ true
historicalVersionPinned = refl

historicalDatePinned :
  exactMatterDatePinned Historical.canonicalHistoricalS185SourceVersionBoundary ≡ true
historicalDatePinned = refl

meetSourceWeldRequired :
  exactMeetAuthoritySourceWeldRequired Weld.canonicalBrightonHistoricalAuthorityWeldBoundary ≡ true
meetSourceWeldRequired = refl

conditionCoordinateExplicit :
  conditionElementExplicit Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ true
conditionCoordinateExplicit = refl

conditionCoordinateSatisfied :
  conditionElementSatisfied Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ true
conditionCoordinateSatisfied = refl

maintenanceFailureCoordinateExplicit :
  maintenanceFailureElementExplicit Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ true
maintenanceFailureCoordinateExplicit = refl

maintenanceFailureStillUnresolved :
  maintenanceFailureDispositionUnresolved Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ true
maintenanceFailureStillUnresolved = refl

conditionAndMaintenanceSeparated :
  conditionAndMaintenanceFailureSeparated Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ true
conditionAndMaintenanceSeparated = refl

repairChronologyStillRequired :
  requiresRepairChronologyForMaintenanceFailure Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ true
repairChronologyStillRequired = refl

conditionBundleDoesNotPayWholeViolation :
  conditionBundlePaysViolation Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ false
conditionBundleDoesNotPayWholeViolation = refl

nonLiveabilityNoticeDoesNotAutoPayMaintenance :
  nonLiveabilityNoticeAutomaticallyPaysMaintenanceFailure Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ false
nonLiveabilityNoticeDoesNotAutoPayMaintenance = refl

qstarsDoesNotPayMaintenance :
  qstarsAdvicePaysMaintenanceFailure Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ false
qstarsDoesNotPayMaintenance = refl

rentOrderDoesNotPayMaintenance :
  rentOrderPaysMaintenanceFailure Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ false
rentOrderDoesNotPayMaintenance = refl

laterExitDoesNotAutoPayJanuaryMaintenance :
  laterExitCarrierAutomaticallyPaysJanuaryMaintenanceFailure Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ false
laterExitDoesNotAutoPayJanuaryMaintenance = refl

conditionSatisfactionDoesNotAutoCreateViolation :
  conditionSatisfactionAutomaticallyCreatesViolation Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ false
conditionSatisfactionDoesNotAutoCreateViolation = refl
