module DASHI.Interop.SensibLawBrightonS185AuthorityViolationFrontierValidation where

open import DASHI.Core.Prelude
open import Agda.Builtin.Equality using (_≡_; refl)

import DASHI.Law.SensibLawBrightonS185HistoricalAuthoritySourceExact as Historical
import DASHI.Cognition.PNF.SensibLawBrightonS185HistoricalAuthorityWeldExact as Weld
import DASHI.Cognition.PNF.SensibLawBrightonS185ViolationElementFrontierExact as Frontier

open Historical.HistoricalS185SourceVersionBoundary
open Weld.BrightonHistoricalAuthorityWeldBoundary
open Frontier.BrightonS185ViolationElementFrontierBoundary

historicalVersionPinned :
  exactVersionIdentityPinned Historical.canonicalHistoricalS185SourceVersionBoundary ≡ true
historicalVersionPinned = refl

historicalDatePinned :
  exactMatterDatePinned Historical.canonicalHistoricalS185SourceVersionBoundary ≡ true
historicalDatePinned = refl

meetSourceWeldRequired :
  exactMeetAuthoritySourceWeldRequired Weld.canonicalBrightonHistoricalAuthorityWeldBoundary ≡ true
meetSourceWeldRequired = refl

conditionCoordinateExplicit :
  conditionElementExplicit Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ true
conditionCoordinateExplicit = refl

conditionCoordinateSatisfied :
  conditionElementSatisfied Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ true
conditionCoordinateSatisfied = refl

outstandingRemediationCoordinateExplicit :
  outstandingRemediationElementExplicit Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ true
outstandingRemediationCoordinateExplicit = refl

outstandingRemediationCoordinateSatisfied :
  outstandingRemediationElementSatisfied Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ true
outstandingRemediationCoordinateSatisfied = refl

statutoryFailureCoordinateExplicit :
  statutoryMaintenanceFailureElementExplicit Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ true
statutoryFailureCoordinateExplicit = refl

statutoryFailureStillUnresolved :
  statutoryMaintenanceFailureDispositionUnresolved Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ true
statutoryFailureStillUnresolved = refl

factsSeparatedFromLegalConclusion :
  factualCoordinatesSeparatedFromLegalConclusion Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ true
factsSeparatedFromLegalConclusion = refl

chronologyPaysOutstandingRemediation :
  Frontier.chronologyPaysOutstandingRemediation Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ true
chronologyPaysOutstandingRemediation = refl

chronologyDoesNotPayStatutoryFailure :
  chronologyPaysStatutoryS185Failure Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ false
chronologyDoesNotPayStatutoryFailure = refl

chronologyDoesNotPayWholeViolation :
  chronologyPaysWholeViolation Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ false
chronologyDoesNotPayWholeViolation = refl

nonLiveabilityNoticeDoesNotAutoPayMaintenance :
  nonLiveabilityNoticeAutomaticallyPaysMaintenanceFailure Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ false
nonLiveabilityNoticeDoesNotAutoPayMaintenance = refl

qstarsDoesNotPayMaintenance :
  qstarsAdvicePaysMaintenanceFailure Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ false
qstarsDoesNotPayMaintenance = refl

rentOrderDoesNotPayMaintenance :
  rentOrderPaysMaintenanceFailure Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ false
rentOrderDoesNotPayMaintenance = refl

laterExitDoesNotAutoPayJanuaryMaintenance :
  laterExitCarrierAutomaticallyPaysJanuaryMaintenanceFailure Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ false
laterExitDoesNotAutoPayJanuaryMaintenance = refl

satisfiedFactsDoNotAutoCreateViolation :
  satisfiedFactsAutomaticallyCreateViolation Frontier.canonicalBrightonS185ViolationElementFrontierBoundary ≡ false
satisfiedFactsDoNotAutoCreateViolation = refl
