module DASHI.Interop.StateIndexedLiveCutParetoCrossPollinationRegression where

open import Agda.Builtin.Bool using (true; false)
open import Agda.Builtin.Equality using (_≡_; refl)

import DASHI.Interop.StateIndexedLiveCutParetoCrossPollinationExact as State
import DASHI.Core.ResidualConditionedExperimentPortfolioExact as Portfolio
import DASHI.Core.AdmissibleConsumerMDLHyperfabricExact as Pareto
import DASHI.Physics.Closure.NSTriadKNCanonicalClayProofSearchRound486Exact as NS486

salienceIsLiveSetIndexedRegression :
  State.salienceIndexedByResidualAndLiveSet State.canonicalStateIndexedLiveCutParetoAdapter ≡ true
salienceIsLiveSetIndexedRegression =
  State.salienceIndexedByResidualAndLiveSetIsTrue State.canonicalStateIndexedLiveCutParetoAdapter

magnitudeGreedyCanMissNarrowingRegression :
  State.magnitudeGreedyMayMissLiveNarrowing State.canonicalStateIndexedLiveCutParetoAdapter ≡ true
magnitudeGreedyCanMissNarrowingRegression =
  State.magnitudeGreedyMayMissLiveNarrowingIsTrue State.canonicalStateIndexedLiveCutParetoAdapter

salienceNoAdmissionRegression :
  State.salienceCreatesCandidateAdmission State.canonicalStateIndexedLiveCutParetoAdapter ≡ false
salienceNoAdmissionRegression =
  State.salienceCreatesCandidateAdmissionIsFalse State.canonicalStateIndexedLiveCutParetoAdapter

residualUpdateChangesSelectionRegression :
  State.residualUpdateMayChangeSelectedExperiment
    State.canonicalStateIndexedLiveCutParetoAdapter ≡ true
residualUpdateChangesSelectionRegression =
  State.residualUpdateMayChangeSelectedExperimentIsTrue State.canonicalStateIndexedLiveCutParetoAdapter

portfolioNoExecutionAuthorityRegression :
  State.portfolioSelectionCreatesExecutionAuthority
    State.canonicalStateIndexedLiveCutParetoAdapter ≡ false
portfolioNoExecutionAuthorityRegression =
  State.portfolioSelectionCreatesExecutionAuthorityIsFalse State.canonicalStateIndexedLiveCutParetoAdapter

terminalConsumerStillRequiredRegression :
  State.terminalConsumerStillRequired State.canonicalStateIndexedLiveCutParetoAdapter ≡ true
terminalConsumerStillRequiredRegression =
  State.terminalConsumerStillRequiredIsTrue State.canonicalStateIndexedLiveCutParetoAdapter

sameGraphCutStateChangeRegression :
  State.sameGraphFactAppendMayChangeReachabilityAndCut
    State.canonicalStateIndexedLiveCutParetoAdapter ≡ true
sameGraphCutStateChangeRegression =
  State.sameGraphFactAppendMayChangeReachabilityAndCutIsTrue State.canonicalStateIndexedLiveCutParetoAdapter

stateIndexedSelectionNoSourceAuthorityRegression :
  State.stateIndexedSelectionDoesNotCreateSourceAuthority
    State.canonicalStateIndexedLiveCutParetoAdapter ≡ true
stateIndexedSelectionNoSourceAuthorityRegression =
  State.stateIndexedSelectionDoesNotCreateSourceAuthorityIsTrue State.canonicalStateIndexedLiveCutParetoAdapter

historicalEvidenceRetainedRegression :
  State.historicalEvidenceMayRemainValidWhileNextStepSalienceChanges
    State.canonicalStateIndexedLiveCutParetoAdapter ≡ true
historicalEvidenceRetainedRegression =
  State.historicalEvidenceMayRemainValidWhileNextStepSalienceChangesIsTrue State.canonicalStateIndexedLiveCutParetoAdapter

initialPortfolioCandidateEligibleRegression :
  Pareto.Eligible
    (State.asStateIndexedMDLProblem
      Portfolio.toyPortfolio Portfolio.chemistryUnresolved
      Portfolio.mechanismConsumer Portfolio.measurementAuthority)
    Portfolio.chemistryProbe
initialPortfolioCandidateEligibleRegression =
  State.portfolioCandidateIsEligible Portfolio.initialChemistryCandidate

laterPortfolioCandidateEligibleRegression :
  Pareto.Eligible
    (State.asStateIndexedMDLProblem
      Portfolio.toyPortfolio Portfolio.chemistryResolvedDownstreamLive
      Portfolio.mechanismConsumer Portfolio.measurementAuthority)
    Portfolio.downstreamProbe
laterPortfolioCandidateEligibleRegression =
  State.portfolioCandidateIsEligible Portfolio.laterDownstreamCandidate

eligibilityNoRouteAdmissionRegression :
  State.stateIndexedEligibilityDoesNotCreateRouteAdmission ≡ true
eligibilityNoRouteAdmissionRegression = State.stateIndexedEligibilityDoesNotCreateRouteAdmissionIsTrue

admittedCandidateEligibilityProjectionRegression :
  ∀ {P residual consumer authority experiment} →
  State.AdmittedStateIndexedCandidate P residual consumer authority experiment →
  Pareto.Eligible (State.asStateIndexedMDLProblem P residual consumer authority) experiment
admittedCandidateEligibilityProjectionRegression = State.admittedStateIndexedCandidateEligible

admittedCandidateNoAutomaticParetoRegression :
  State.admittedCandidateAutomaticallyParetoOptimal ≡ false
admittedCandidateNoAutomaticParetoRegression = State.admittedCandidateAutomaticallyParetoOptimalIsFalse

admittedCandidateNoAutomaticTerminalClosureRegression :
  State.admittedCandidateAutomaticallyClosesTerminalConsumer ≡ false
admittedCandidateNoAutomaticTerminalClosureRegression =
  State.admittedCandidateAutomaticallyClosesTerminalConsumerIsFalse

parentSnowballPaymentStillFailClosedRegression :
  State.parentSnowballPaymentMaySkipDependency ≡ false
parentSnowballPaymentStillFailClosedRegression = State.parentSnowballPaymentMaySkipDependencyIsFalse

currentSalienceNoAuthorityRegression :
  State.currentSalienceAutomaticallyCreatesAuthority State.canonicalStateIndexedLiveCutParetoBoundary ≡ false
currentSalienceNoAuthorityRegression =
  State.currentSalienceAutomaticallyCreatesAuthorityIsFalse State.canonicalStateIndexedLiveCutParetoBoundary

currentCutNoCrossDomainTransferRegression :
  State.currentMinimalCutAutomaticallyTransfersAcrossDomains State.canonicalStateIndexedLiveCutParetoBoundary ≡ false
currentCutNoCrossDomainTransferRegression =
  State.currentMinimalCutAutomaticallyTransfersAcrossDomainsIsFalse State.canonicalStateIndexedLiveCutParetoBoundary

nsCanonicalResidualRegression :
  NS486.firstCanonicalNSResidual NS486.currentCanonicalNSStatus
  ≡ NS486.missingCutoffUniformSignedCompanionBudget
nsCanonicalResidualRegression = State.nsCurrentResidualIsDirectR423Budget

nsCanonicalR423ShortestRegression :
  State.canonicalShortestConsumerIsR423 State.canonicalNSCanonicalCurrentCutParetoAdapter ≡ true
nsCanonicalR423ShortestRegression =
  State.canonicalShortestConsumerIsR423IsTrue State.canonicalNSCanonicalCurrentCutParetoAdapter

nsDirectR423StillOpenRegression :
  State.directR423BudgetPaid State.canonicalNSCanonicalCurrentCutParetoAdapter ≡ false
nsDirectR423StillOpenRegression =
  State.directR423BudgetPaidIsFalse State.canonicalNSCanonicalCurrentCutParetoAdapter

nsCrossOutputNotRequiredRegression :
  State.crossOutputCoherenceRequired State.canonicalNSCanonicalCurrentCutParetoAdapter ≡ false
nsCrossOutputNotRequiredRegression =
  State.crossOutputCoherenceRequiredIsFalse State.canonicalNSCanonicalCurrentCutParetoAdapter

nsR284NotMandatoryRegression :
  State.r284DecompositionMandatory State.canonicalNSCanonicalCurrentCutParetoAdapter ≡ false
nsR284NotMandatoryRegression =
  State.r284DecompositionMandatoryIsFalse State.canonicalNSCanonicalCurrentCutParetoAdapter

nsClayPromotionStillFalseRegression :
  State.clayPromotionPaid State.canonicalNSCanonicalCurrentCutParetoAdapter ≡ false
nsClayPromotionStillFalseRegression =
  State.clayPromotionPaidIsFalse State.canonicalNSCanonicalCurrentCutParetoAdapter

nsRound83CannotOverrideCanonicalCutRegression :
  State.staleRound83SnapshotMayOverrideCanonicalCut State.canonicalNSCanonicalCurrentCutParetoAdapter ≡ false
nsRound83CannotOverrideCanonicalCutRegression =
  State.staleRound83SnapshotMayOverrideCanonicalCutIsFalse State.canonicalNSCanonicalCurrentCutParetoAdapter

nsOptionalProducerCannotSelfPromoteRegression :
  State.optionalProducerMayBecomeMandatoryWithoutFrontierImprovement
    State.canonicalNSCanonicalCurrentCutParetoAdapter ≡ false
nsOptionalProducerCannotSelfPromoteRegression =
  State.optionalProducerMayBecomeMandatoryWithoutFrontierImprovementIsFalse
    State.canonicalNSCanonicalCurrentCutParetoAdapter

crossDomainShapeNoSharedMathematicsRegression :
  State.crossDomainSchedulerShapeProvesSharedMathematics
    State.canonicalNSCanonicalCurrentCutParetoAdapter ≡ false
crossDomainShapeNoSharedMathematicsRegression =
  State.crossDomainSchedulerShapeProvesSharedMathematicsIsFalse
    State.canonicalNSCanonicalCurrentCutParetoAdapter

routeAdmissionRequiredRegression :
  State.routeMayElaborateBeforeAdmission State.canonicalLeastPrivilegeLiveCutAdmissionAdapter ≡ false
routeAdmissionRequiredRegression =
  State.routeMayElaborateBeforeAdmissionIsFalse State.canonicalLeastPrivilegeLiveCutAdmissionAdapter

silentStrengtheningBlockedRegression :
  State.routeMaySilentlyStrengthenHypotheses State.canonicalLeastPrivilegeLiveCutAdmissionAdapter ≡ false
silentStrengtheningBlockedRegression =
  State.routeMaySilentlyStrengthenHypothesesIsFalse State.canonicalLeastPrivilegeLiveCutAdmissionAdapter

localLemmaNoAutomaticFrontierRegression :
  State.localLemmaAutomaticallyMovesProgrammeFrontier
    State.canonicalLeastPrivilegeLiveCutAdmissionAdapter ≡ false
localLemmaNoAutomaticFrontierRegression =
  State.localLemmaAutomaticallyMovesProgrammeFrontierIsFalse State.canonicalLeastPrivilegeLiveCutAdmissionAdapter

lemmaCountNoAuthorityRegression :
  State.lemmaCountIsAuthoritativeProgress State.canonicalLeastPrivilegeLiveCutAdmissionAdapter ≡ false
lemmaCountNoAuthorityRegression =
  State.lemmaCountIsAuthoritativeProgressIsFalse State.canonicalLeastPrivilegeLiveCutAdmissionAdapter

duplicateRouteReuseRegression :
  State.duplicateRouteShouldBeReproved State.canonicalLeastPrivilegeLiveCutAdmissionAdapter ≡ false
duplicateRouteReuseRegression =
  State.duplicateRouteShouldBeReprovedIsFalse State.canonicalLeastPrivilegeLiveCutAdmissionAdapter

liveCutCannotBypassAdmissionRegression :
  State.liveCutSalienceCannotBypassRouteAdmission State.canonicalLeastPrivilegeLiveCutAdmissionAdapter ≡ true
liveCutCannotBypassAdmissionRegression =
  State.liveCutSalienceCannotBypassRouteAdmissionIsTrue State.canonicalLeastPrivilegeLiveCutAdmissionAdapter
