module DASHI.Interop.StateIndexedLiveCutParetoCrossPollinationRegression where

open import Agda.Builtin.Bool using (true; false)
open import Agda.Builtin.Equality using (_≡_; refl)

import DASHI.Interop.StateIndexedLiveCutParetoCrossPollinationExact as State
import DASHI.Core.ResidualConditionedExperimentPortfolioExact as Portfolio
import DASHI.Core.AdmissibleConsumerMDLHyperfabricExact as Pareto

salienceIsLiveSetIndexedRegression :
  State.salienceIndexedByResidualAndLiveSet State.canonicalStateIndexedLiveCutParetoAdapter ≡ true
salienceIsLiveSetIndexedRegression =
  State.salienceIndexedByResidualAndLiveSetIsTrue State.canonicalStateIndexedLiveCutParetoAdapter

magnitudeGreedyCanMissNarrowingRegression :
  State.magnitudeGreedyMayMissLiveNarrowing State.canonicalStateIndexedLiveCutParetoAdapter ≡ true
magnitudeGreedyCanMissNarrowingRegression =
  State.magnitudeGreedyMayMissLiveNarrowingIsTrue State.canonicalStateIndexedLiveCutParetoAdapter

salienceNoAdmissionRegression :
  State.salienceCreatesCandidateAdmission State.canonicalStateIndexedLiveCutParetoAdapter ≡ false
salienceNoAdmissionRegression =
  State.salienceCreatesCandidateAdmissionIsFalse State.canonicalStateIndexedLiveCutParetoAdapter

residualUpdateChangesSelectionRegression :
  State.residualUpdateMayChangeSelectedExperiment
    State.canonicalStateIndexedLiveCutParetoAdapter ≡ true
residualUpdateChangesSelectionRegression =
  State.residualUpdateMayChangeSelectedExperimentIsTrue
    State.canonicalStateIndexedLiveCutParetoAdapter

portfolioNoExecutionAuthorityRegression :
  State.portfolioSelectionCreatesExecutionAuthority
    State.canonicalStateIndexedLiveCutParetoAdapter ≡ false
portfolioNoExecutionAuthorityRegression =
  State.portfolioSelectionCreatesExecutionAuthorityIsFalse
    State.canonicalStateIndexedLiveCutParetoAdapter

terminalConsumerStillRequiredRegression :
  State.terminalConsumerStillRequired State.canonicalStateIndexedLiveCutParetoAdapter ≡ true
terminalConsumerStillRequiredRegression =
  State.terminalConsumerStillRequiredIsTrue State.canonicalStateIndexedLiveCutParetoAdapter

sameGraphCutStateChangeRegression :
  State.sameGraphFactAppendMayChangeReachabilityAndCut
    State.canonicalStateIndexedLiveCutParetoAdapter ≡ true
sameGraphCutStateChangeRegression =
  State.sameGraphFactAppendMayChangeReachabilityAndCutIsTrue
    State.canonicalStateIndexedLiveCutParetoAdapter

stateIndexedSelectionNoSourceAuthorityRegression :
  State.stateIndexedSelectionDoesNotCreateSourceAuthority
    State.canonicalStateIndexedLiveCutParetoAdapter ≡ true
stateIndexedSelectionNoSourceAuthorityRegression =
  State.stateIndexedSelectionDoesNotCreateSourceAuthorityIsTrue
    State.canonicalStateIndexedLiveCutParetoAdapter

historicalEvidenceRetainedRegression :
  State.historicalEvidenceMayRemainValidWhileNextStepSalienceChanges
    State.canonicalStateIndexedLiveCutParetoAdapter ≡ true
historicalEvidenceRetainedRegression =
  State.historicalEvidenceMayRemainValidWhileNextStepSalienceChangesIsTrue
    State.canonicalStateIndexedLiveCutParetoAdapter

initialPortfolioCandidateEligibleRegression :
  Pareto.Eligible
    (State.asStateIndexedMDLProblem
      Portfolio.toyPortfolio
      Portfolio.chemistryUnresolved
      Portfolio.mechanismConsumer
      Portfolio.measurementAuthority)
    Portfolio.chemistryProbe
initialPortfolioCandidateEligibleRegression =
  State.portfolioCandidateIsEligible Portfolio.initialChemistryCandidate

laterPortfolioCandidateEligibleRegression :
  Pareto.Eligible
    (State.asStateIndexedMDLProblem
      Portfolio.toyPortfolio
      Portfolio.chemistryResolvedDownstreamLive
      Portfolio.mechanismConsumer
      Portfolio.measurementAuthority)
    Portfolio.downstreamProbe
laterPortfolioCandidateEligibleRegression =
  State.portfolioCandidateIsEligible Portfolio.laterDownstreamCandidate

eligibilityNoRouteAdmissionRegression :
  State.stateIndexedEligibilityDoesNotCreateRouteAdmission ≡ true
eligibilityNoRouteAdmissionRegression =
  State.stateIndexedEligibilityDoesNotCreateRouteAdmissionIsTrue

parentSnowballPaymentStillFailClosedRegression :
  State.parentSnowballPaymentMaySkipDependency ≡ false
parentSnowballPaymentStillFailClosedRegression =
  State.parentSnowballPaymentMaySkipDependencyIsFalse

currentSalienceNoAuthorityRegression :
  State.currentSalienceAutomaticallyCreatesAuthority
    State.canonicalStateIndexedLiveCutParetoBoundary ≡ false
currentSalienceNoAuthorityRegression =
  State.currentSalienceAutomaticallyCreatesAuthorityIsFalse
    State.canonicalStateIndexedLiveCutParetoBoundary

currentCutNoCrossDomainTransferRegression :
  State.currentMinimalCutAutomaticallyTransfersAcrossDomains
    State.canonicalStateIndexedLiveCutParetoBoundary ≡ false
currentCutNoCrossDomainTransferRegression =
  State.currentMinimalCutAutomaticallyTransfersAcrossDomainsIsFalse
    State.canonicalStateIndexedLiveCutParetoBoundary

nsRelativeGrowthSplitClosedRegression :
  State.relativeGrowthSplitClosed State.canonicalNSCurrentCutParetoAdapter ≡ true
nsRelativeGrowthSplitClosedRegression =
  State.relativeGrowthSplitClosedIsTrue State.canonicalNSCurrentCutParetoAdapter

nsPressureProducerStillOpenRegression :
  State.nonlinearPressureRelativeGrowthEstimatePaid
    State.canonicalNSCurrentCutParetoAdapter ≡ false
nsPressureProducerStillOpenRegression =
  State.nonlinearPressureRelativeGrowthEstimatePaidIsFalse
    State.canonicalNSCurrentCutParetoAdapter

nsCriticalBarrierStillOpenRegression :
  State.criticalRatioBarrierPaid State.canonicalNSCurrentCutParetoAdapter ≡ false
nsCriticalBarrierStillOpenRegression =
  State.criticalRatioBarrierPaidIsFalse State.canonicalNSCurrentCutParetoAdapter

nsClayPromotionStillFalseRegression :
  State.clayPromotionPaid State.canonicalNSCurrentCutParetoAdapter ≡ false
nsClayPromotionStillFalseRegression =
  State.clayPromotionPaidIsFalse State.canonicalNSCurrentCutParetoAdapter

nsClosedAlgebraNotHighestSalienceRegression :
  State.closedAlgebraRemainsHighestSalience State.canonicalNSCurrentCutParetoAdapter ≡ false
nsClosedAlgebraNotHighestSalienceRegression =
  State.closedAlgebraRemainsHighestSalienceIsFalse State.canonicalNSCurrentCutParetoAdapter

nsParetoCannotSkipCurrentCutRegression :
  State.currentNSCutMayBeSkippedByPareto State.canonicalNSCurrentCutParetoAdapter ≡ false
nsParetoCannotSkipCurrentCutRegression =
  State.currentNSCutMayBeSkippedByParetoIsFalse State.canonicalNSCurrentCutParetoAdapter

nsCrossPollinationNoAuthorityRegression :
  State.crossPollinationCreatesNSTheoremAuthority State.canonicalNSCurrentCutParetoAdapter ≡ false
nsCrossPollinationNoAuthorityRegression =
  State.crossPollinationCreatesNSTheoremAuthorityIsFalse State.canonicalNSCurrentCutParetoAdapter

routeAdmissionRequiredRegression :
  State.routeMayElaborateBeforeAdmission
    State.canonicalLeastPrivilegeLiveCutAdmissionAdapter ≡ false
routeAdmissionRequiredRegression =
  State.routeMayElaborateBeforeAdmissionIsFalse
    State.canonicalLeastPrivilegeLiveCutAdmissionAdapter

silentStrengtheningBlockedRegression :
  State.routeMaySilentlyStrengthenHypotheses
    State.canonicalLeastPrivilegeLiveCutAdmissionAdapter ≡ false
silentStrengtheningBlockedRegression =
  State.routeMaySilentlyStrengthenHypothesesIsFalse
    State.canonicalLeastPrivilegeLiveCutAdmissionAdapter

localLemmaNoAutomaticFrontierRegression :
  State.localLemmaAutomaticallyMovesProgrammeFrontier
    State.canonicalLeastPrivilegeLiveCutAdmissionAdapter ≡ false
localLemmaNoAutomaticFrontierRegression =
  State.localLemmaAutomaticallyMovesProgrammeFrontierIsFalse
    State.canonicalLeastPrivilegeLiveCutAdmissionAdapter

lemmaCountNoAuthorityRegression :
  State.lemmaCountIsAuthoritativeProgress
    State.canonicalLeastPrivilegeLiveCutAdmissionAdapter ≡ false
lemmaCountNoAuthorityRegression =
  State.lemmaCountIsAuthoritativeProgressIsFalse
    State.canonicalLeastPrivilegeLiveCutAdmissionAdapter

duplicateRouteReuseRegression :
  State.duplicateRouteShouldBeReproved
    State.canonicalLeastPrivilegeLiveCutAdmissionAdapter ≡ false
duplicateRouteReuseRegression =
  State.duplicateRouteShouldBeReprovedIsFalse
    State.canonicalLeastPrivilegeLiveCutAdmissionAdapter

liveCutCannotBypassAdmissionRegression :
  State.liveCutSalienceCannotBypassRouteAdmission
    State.canonicalLeastPrivilegeLiveCutAdmissionAdapter ≡ true
liveCutCannotBypassAdmissionRegression =
  State.liveCutSalienceCannotBypassRouteAdmissionIsTrue
    State.canonicalLeastPrivilegeLiveCutAdmissionAdapter
