module DASHI.Cognition.Everything where

-- Cognition domain rollup.
-- Specialized PNF / visual-pattern tranche rollups remain independently
-- checkable but are also reachable through this parent.

import DASHI.Cognition.PNF.PNFIRLearningEverything
import DASHI.Cognition.PNF.NumericPNFHyperfabricEverything
import DASHI.Cognition.VisualPatternModeGeometryEverything
import DASHI.Cognition.PNF.SensibLawCountryUniversalLegalAlgebraEverything
import DASHI.Cognition.PNF.SensibLawCountryJuridicalHumanityOperationalRemedyEverything
import DASHI.Cognition.PNF.SensibLawCountryRemedyTerminalValidationCrossPollinationExact
import DASHI.Cognition.PNF.SensibLawCountryClimateRealisedRepairExternalityEverything
import DASHI.Cognition.PNF.SensibLawCountryRelationalIrreversibilitySourceAtlasExact
import DASHI.Cognition.PNF.SensibLawCountryRelationalLossGenocideBoundaryExact
import DASHI.Cognition.PNF.SensibLawIndigenousCustodianshipDutyCrossPollinationExact
import DASHI.Cognition.PNF.SensibLawCountryRelationalIrreversibilityEverything
import DASHI.Cognition.PNF.SensibLawGenocideConventionEnforcementSourceAtlasExact
import DASHI.Cognition.PNF.SensibLawGenocideConventionWrongTypeBidiExact
import DASHI.Cognition.PNF.SensibLawGenocideEnforcementMeansBidiExact
import DASHI.Cognition.PNF.SensibLawCountryGenocideWrongTypeEnforcementEverything
import DASHI.Cognition.PNF.SensibLawCountryRelationalIrreversibilityGenocideEnforcementEverything
import DASHI.Cognition.PNF.SensibLawBillyRemedyActuationTwoEyedPOSIWIDExact
import DASHI.Cognition.PNF.SensibLawCountryJuridicalHumanityRemedyActuationEverything
import DASHI.Cognition.PNF.SensibLawPluralObserverCorrectionApplicationAtlasExact
import DASHI.Cognition.PNF.SensibLawCountryButForRealisedRepairTwoEyedExact
import DASHI.Cognition.PNF.SensibLawCountryJuridicalHumanityButForRemedyEverything
