module DASHI.Cognition.Everything where

-- Cognition domain rollup.
-- Specialized PNF / visual-pattern tranche rollups remain independently
-- checkable but are also reachable through this parent.

import DASHI.Cognition.PNF.PNFIRLearningEverything
import DASHI.Cognition.PNF.NumericPNFHyperfabricEverything
import DASHI.Cognition.VisualPatternModeGeometryEverything
import DASHI.Cognition.PNF.SensibLawCountryUniversalLegalAlgebraEverything
import DASHI.Cognition.PNF.SensibLawCountryJuridicalHumanityOperationalRemedyEverything
import DASHI.Cognition.PNF.SensibLawCountryRemedyTerminalValidationCrossPollinationExact
import DASHI.Cognition.PNF.SensibLawCountryClimateRealisedRepairExternalityEverything
import DASHI.Cognition.PNF.SensibLawCountryRelationalIrreversibilitySourceAtlasExact
import DASHI.Cognition.PNF.SensibLawIndigenousCustodianshipDutyCrossPollinationExact
import DASHI.Cognition.PNF.SensibLawCountryRelationalIrreversibilityEverything
import DASHI.Cognition.PNF.SensibLawGenocideConventionEnforcementSourceAtlasExact
import DASHI.Cognition.PNF.SensibLawGenocideConventionWrongTypeBidiExact
import DASHI.Cognition.PNF.SensibLawGenocideEnforcementMeansBidiExact
import DASHI.Cognition.PNF.SensibLawCountryGenocideWrongTypeEnforcementEverything
import DASHI.Cognition.PNF.SensibLawCountryRelationalIrreversibilityGenocideEnforcementEverything
import DASHI.Cognition.PNF.SensibLawBillyRemedyActuationTwoEyedPOSIWIDExact
import DASHI.Cognition.PNF.SensibLawCountryJuridicalHumanityRemedyActuationEverything
import DASHI.Cognition.PNF.SensibLawPluralObserverCorrectionApplicationAtlasExact
import DASHI.Cognition.PNF.SensibLawCountryButForRealisedRepairTwoEyedExact
import DASHI.Cognition.PNF.SensibLawCountryJuridicalHumanityButForRemedyEverything
import DASHI.Cognition.PNF.SensibLawFiniteRequirementParetoFrontierEverything
import DASHI.Cognition.PNF.SensibLawNegligenceDutyGenericParetoFrontierExact
import DASHI.Cognition.PNF.SensibLawNegligenceDutyParetoProofPromotionExact
import DASHI.Cognition.PNF.SensibLawHerzogUniversalLegalCrossPollinationEverything
import DASHI.Cognition.PNF.SensibLawUniversalLegalAlgebraEverything
import DASHI.Cognition.PNF.SensibLawAttributedSourcePNFCandidateWeldExact
import DASHI.Cognition.PNF.SensibLawWrongTypeDownstreamPrimarySourceDisciplineExact
import DASHI.Cognition.PNF.SensibLawCullenQueryIndexedFactorisationExact
import DASHI.Cognition.PNF.SensibLawCullenSourceCorrectDutyRoutesExact
import DASHI.Cognition.PNF.SensibLawCullenEdelman64WrongTypeSourceRealisationExact
import DASHI.Cognition.PNF.SensibLawCullenDownstreamElementSourceAtlasExact
import DASHI.Cognition.PNF.SensibLawCullenEdelman64SemanticStateCompilerExact
import DASHI.Cognition.PNF.SensibLawCullenResidualAdmissionBidiExact
