module DASHI.Cognition.TeleodynamicsEverything where

import DASHI.Cognition.TeleodynamicsPrincipiaTwoExact
import DASHI.Cognition.TeleodynamicsSourceAtlas
import DASHI.Cognition.TeleodynamicsCognitionBridge
import DASHI.Cognition.TeleodynamicsRegression
