module DASHI.Physics.Chemistry.AtomicPeriodicTable369AdenylateKinaseCitationNeighbourhoodValidation where

import DASHI.Physics.Chemistry.AtomicPeriodicTable369AdenylateKinaseCitationNeighbourhoodExact as Atlas

open Atlas

atlasBoundary = canonicalAdKCitationNeighbourhoodBoundary

li2015Retained = AdKCitationNeighbourhoodBoundary.liLiuJiAnchorRetained atlasBoundary
song2013Retained = AdKCitationNeighbourhoodBoundary.songZhu2013Retained atlasBoundary
formoso2015Retained = AdKCitationNeighbourhoodBoundary.formoso2015Retained atlasBoundary
zheng2018Retained = AdKCitationNeighbourhoodBoundary.zhengCui2018Retained atlasBoundary
wang2020Retained = AdKCitationNeighbourhoodBoundary.wang2020Retained atlasBoundary
lu2022Retained = AdKCitationNeighbourhoodBoundary.lu2022Retained atlasBoundary

citationImportsNumerics = AdKCitationNeighbourhoodBoundary.citationImportsLiNumericCells atlasBoundary
relatedObservableMeansSameObservable = AdKCitationNeighbourhoodBoundary.relatedObservableMeansSameObservable atlasBoundary
laterMechanismOverridesEarlierSource = AdKCitationNeighbourhoodBoundary.laterMechanismOverridesEarlierSource atlasBoundary
qidCreatesCrossPaperIdentity = AdKCitationNeighbourhoodBoundary.qidCreatesCrossPaperIdentity atlasBoundary
