module DASHI.Physics.Chemistry.AtomicPeriodicTable369AdenylateKinaseAcquisitionEverything where

-- Sparse calibration and repository-wide attribution/external-identity envelope.
import DASHI.Physics.Chemistry.AtomicPeriodicTable369AdenylateKinaseSparseCalibrationFibreExact
import DASHI.Physics.Chemistry.AtomicPeriodicTable369AdenylateKinaseCalibrationAttributionEnvelopeExact
import DASHI.Physics.Chemistry.AtomicPeriodicTable369AdenylateKinaseAttributedSparseTransitionKernelExact

-- Structural identity and same-object source manifestation guards.
import DASHI.Physics.Chemistry.AtomicPeriodicTable369AdenylateKinaseStructuralIdentitySnowballExact
import DASHI.Physics.Chemistry.AtomicPeriodicTable369AdenylateKinaseSupportingMaterialManifestationExact
import DASHI.Physics.Chemistry.AtomicPeriodicTable369AdenylateKinaseGuardedCalibrationAcquisitionExact
import DASHI.Physics.Chemistry.AtomicPeriodicTable369AdenylateKinaseMetadynamicsUncertaintyExact
import DASHI.Physics.Chemistry.AtomicPeriodicTable369AdenylateKinaseCalibrationProvenanceGraphExact

-- Newly acquired same-article endpoint third-coordinate values and composed
-- three-CV endpoint pair.  Intermediate-state dLN cells remain unpaid.
import DASHI.Physics.Chemistry.AtomicPeriodicTable369AdenylateKinaseEndpointDLnAcquisitionExact
import DASHI.Physics.Chemistry.AtomicPeriodicTable369AdenylateKinaseSourcePaidThreeCVEndpointExact

-- Cell-level acquisition frontier: 8 named states x four numeric coordinates
-- plus six route-edge Kramers-rate cells.  Each unpaid cell retains a locator,
-- source role and next-payment obligation instead of disappearing into a global
-- "uncalibrated" flag.
import DASHI.Physics.Chemistry.AtomicPeriodicTable369AdenylateKinaseCalibrationPaymentLedgerExact
