module DASHI.Physics.Chemistry.AtomicPeriodicTable369AdenylateKinaseZhengCui2018AcquisitionValidation where

import DASHI.Physics.Chemistry.AtomicPeriodicTable369AdenylateKinaseZhengCui2018AcquisitionExact as ZC

open ZC

boundary = canonicalZhengCui2018AcquisitionBoundary

fiftyMicrosecondsPaid = ZhengCui2018AcquisitionBoundary.approxFiftyMicrosecondSamplingPaid boundary
closedBasinOpenNmpPaid = ZhengCui2018AcquisitionBoundary.closedBasinOpenNmpLidClosedPaid boundary
multipleTimescalesPaid = ZhengCui2018AcquisitionBoundary.multiplePathwaysAndTimescalesPaid boundary
twoForceFieldsPaid = ZhengCui2018AcquisitionBoundary.twoForceFieldRobustnessPaid boundary
localUnfoldingPaid = ZhengCui2018AcquisitionBoundary.noSignificantLocalUnfoldingPaid boundary

importsLiNumerics = ZhengCui2018AcquisitionBoundary.citationImportsLiNumericCells boundary
sameClosedDefinition = ZhengCui2018AcquisitionBoundary.closedLabelEqualsLiClosedState boundary
experimentalKinetics = ZhengCui2018AcquisitionBoundary.simulationTimescaleEqualsExperimentalKinetics boundary
