module DASHI.Physics.Chemistry.AtomicPeriodicTable369AdenylateKinaseNamedIntermediateGeometryConstraintAcquisitionValidation where

open import DASHI.Core.Prelude

import DASHI.Physics.Chemistry.AtomicPeriodicTable369AdenylateKinaseNamedIntermediateGeometryConstraintAcquisitionExact as Acquisition

boundary = Acquisition.canonicalNamedIntermediateGeometryConstraintBoundary

gammaConstraint = Acquisition.gammaGeometryConstraint
deltaConstraint = Acquisition.deltaGeometryConstraint

gammaThetaOneRegionConstraintPaid = Acquisition.gammaThetaOneRegionConstraintPaid
gammaDLnRegionConstraintPaid = Acquisition.gammaDLnRegionConstraintPaid
deltaThetaOneRegionConstraintPaid = Acquisition.deltaThetaOneRegionConstraintPaid
deltaThetaTwoSemiOpenConstraintPaid = Acquisition.deltaThetaTwoSemiOpenConstraintPaid
deltaDLnRegionConstraintPaid = Acquisition.deltaDLnRegionConstraintPaid

namedStateExactThetaStillUnpaid = Acquisition.namedStateExactThetaStillUnpaid
namedStateExactDLnStillUnpaid = Acquisition.namedStateExactDLnStillUnpaid
ledgerCellsRemainUnchanged = Acquisition.ledgerCellsRemainUnchanged
