module DASHI.Governance.BoloBoloPairedGovernanceExperimentRegression where

open import DASHI.Core.Prelude

import DASHI.Governance.BoloBoloPairedGovernanceExperimentExact as Experiment

sameContextPreferred :
  Experiment.sameTargetContextPreferredOverUnqualifiedHistoricalTransfer Experiment.canonicalPairedExperimentBoundary ≡ true
sameContextPreferred = refl

costMappingPredeclared :
  Experiment.costMappingMustBeFrozenBeforeOutcomes Experiment.canonicalPairedExperimentBoundary ≡ true
costMappingPredeclared = refl

flatNestedContrastDirect :
  Experiment.flatVersusNestedContrastIsPrimaryStructuralComparison Experiment.canonicalPairedExperimentBoundary ≡ true
flatNestedContrastDirect = refl

pilotNotLegitimacy :
  Experiment.experimentalCoordinationWinCreatesPoliticalLegitimacy Experiment.canonicalPairedExperimentBoundary ≡ false
pilotNotLegitimacy = refl

pilotNotEcologicalProof :
  Experiment.experimentalCoordinationWinProvesEcologicalViability Experiment.canonicalPairedExperimentBoundary ≡ false
pilotNotEcologicalProof = refl
