module DASHI.Governance.InstitutionalExtraordinaryClaimReparationValidationExact where

open import DASHI.Core.Prelude

import DASHI.Core.DiscriminatorSynthesisExact as Discriminator
import DASHI.Core.ActiveObligationEvidenceFibreExact as Active
import DASHI.Core.ProofSearchLeastPrivilegeAdmissionExact as ProofSearch
import DASHI.Governance.DrugGovernanceMultiAxisReparativeFibreExact as Fibre
import DASHI.Governance.DrugGovernanceMultiAxisRepairPlannerExact as Planner
import DASHI.Governance.MenWhoStareAtGoatsEvidenceLayerExact as Goats
import DASHI.Governance.MenWhoStareAtGoatsReparativeAuditExact as GoatsRepair
import DASHI.Governance.InstitutionalAnomalousAlteredStateProgramAtlasExact as Atlas
import DASHI.Governance.AnomalousConsciousnessResearchEvidenceContinuumExact as Continuum
import DASHI.Governance.PhenomenonEvidenceFibreOverTimeExact as Temporal
import DASHI.Governance.AnomalousPhenomenonTemporalEvidenceTrajectoriesExact as Trajectory
import DASHI.Governance.PhenomenonEvidenceLadderProjectionOverTimeExact as Ladder
import DASHI.Governance.AnomalousResearchPriorityFromTemporalFibreExact as Priority
import DASHI.Governance.AnomalousConsumerIndexedObligationFibreExact as Obligation
import DASHI.Governance.AnomalousTemporalProofSearchExperimentAdmissionExact as Admission

repairBoundary : Fibre.DrugGovernanceMultiAxisReparativeBoundary
repairBoundary = Fibre.canonicalDrugGovernanceMultiAxisReparativeBoundary
plannerBoundary : Planner.MultiAxisRepairPlannerBoundary
plannerBoundary = Planner.canonicalMultiAxisRepairPlannerBoundary
goatsBoundary : Goats.MenWhoStareAtGoatsEvidenceBoundary
goatsBoundary = Goats.canonicalMenWhoStareAtGoatsEvidenceBoundary
goatsRepairBoundary : GoatsRepair.MenWhoStareAtGoatsReparativeAuditBoundary
goatsRepairBoundary = GoatsRepair.canonicalMenWhoStareAtGoatsReparativeAuditBoundary
atlasBoundary : Atlas.InstitutionalAnomalousAlteredStateAtlasBoundary
atlasBoundary = Atlas.canonicalInstitutionalAnomalousAlteredStateAtlasBoundary
continuumBoundary : Continuum.AnomalousConsciousnessResearchBoundary
continuumBoundary = Continuum.canonicalAnomalousConsciousnessResearchBoundary
temporalBoundary : Temporal.PhenomenonEvidenceFibreOverTimeBoundary
temporalBoundary = Temporal.canonicalPhenomenonEvidenceFibreOverTimeBoundary
trajectoryBoundary : Trajectory.AnomalousPhenomenonTemporalEvidenceBoundary
trajectoryBoundary = Trajectory.canonicalAnomalousPhenomenonTemporalEvidenceBoundary
ladderBoundary : Ladder.PhenomenonEvidenceLadderProjectionBoundary
ladderBoundary = Ladder.canonicalPhenomenonEvidenceLadderProjectionBoundary
priorityBoundary : Priority.AnomalousResearchPriorityTemporalBoundary
priorityBoundary = Priority.canonicalAnomalousResearchPriorityTemporalBoundary
obligationBoundary : Obligation.AnomalousConsumerIndexedObligationBoundary
obligationBoundary = Obligation.canonicalAnomalousConsumerIndexedObligationBoundary
admissionBoundary : Admission.AnomalousTemporalProofSearchAdmissionBoundary
admissionBoundary = Admission.canonicalAnomalousTemporalProofSearchAdmissionBoundary

materialRepairProbeReallySeparates :
  Discriminator.BundleSeparates (Planner.probeFor Planner.materialRepairConsumer)
    Fibre.acknowledgementOnly Fibre.materialBenefitOnly
materialRepairProbeReallySeparates = Planner.materialProbeSeparatesAcknowledgementFromMaterialRepair

sovereigntyProbeReallySeparates :
  Discriminator.BundleSeparates (Planner.probeFor Planner.sovereigntyRepairConsumer)
    Fibre.authorityReformWithoutSovereignty Fibre.fullSyntheticRepair
sovereigntyProbeReallySeparates = Planner.sovereigntyProbeSeparatesAuthorityReformFromFullRepair

goatClaimStillDemandsIndependentEvidence : Goats.EvidenceDemand Goats.goatKillingByStaringClaim
goatClaimStillDemandsIndependentEvidence = Goats.canonicalGoatClaimDemand

programmeHistorySelectsTruthConsumer :
  GoatsRepair.residualProbe GoatsRepair.programmeHistoryResidual ≡ Planner.truthHistoryConsumer
programmeHistorySelectsTruthConsumer = GoatsRepair.historyResidualSelectsTruthProbe

stargateStillDemandsOperationalEvaluation : Atlas.AtlasDemand Atlas.operationalUtilityConsumer
stargateStillDemandsOperationalEvaluation = Atlas.stargateUtilityDemand

psychedelicTherapeuticUseStillNeedsClinicalEvidence : Atlas.AtlasDemand Atlas.therapeuticConsumer
psychedelicTherapeuticUseStillNeedsClinicalEvidence = Atlas.psychedelicTherapeuticDemand

bemHighRigourReplicationStrictlyRefinesFibre :
  Temporal.StrictFibreRefinement
    Trajectory.temporalSystem
    Trajectory.bemInitial2011
    Trajectory.transparentPsi2025
bemHighRigourReplicationStrictlyRefinesFibre =
  Trajectory.bemReplicationStrictlyRemovesRobustOriginalEffect

presentimentUpdateNeedNotShrinkFibre :
  Temporal.FibreUnchanged
    Trajectory.temporalSystem
    Trajectory.presentimentMeta2012
    Trajectory.presentimentUpdate2018
presentimentUpdateNeedNotShrinkFibre =
  Trajectory.presentimentUpdateLeavesCoreInterpretationFibreOpen

psilocybinMetaEvidenceStrictlyRefinesFibre :
  Temporal.StrictFibreRefinement
    Trajectory.temporalSystem
    Trajectory.psilocybinEarlyModernTrials
    Trajectory.psilocybinMeta2025_2026
psilocybinMetaEvidenceStrictlyRefinesFibre =
  Trajectory.psilocybinMetaEvidenceRemovesPureNoEffectInterpretation

sameCoarsePsilocybinLabelHidesReplicationChange :
  Ladder.standingAt Trajectory.psilocybinEarlyModernTrials Temporal.independentReplication
  ≡ Ladder.standingAt Trajectory.psilocybinMeta2025_2026 Temporal.independentReplication → ⊥
sameCoarsePsilocybinLabelHidesReplicationChange =
  Ladder.psilocybinReplicationCoordinateChanged

bemResearchQuestionChangesWithHistory :
  Priority.bemQuestion Priority.bemEarlyResearch
  ≡ Priority.bemQuestion Priority.bemCurrentResearch → ⊥
bemResearchQuestionChangesWithHistory = Priority.bemQuestionChanged

psilocybinCurrentPriorityTargetsControl :
  Priority.unresolvedCoordinate Priority.psilocybinCurrentMove ≡ Temporal.controlStrength
psilocybinCurrentPriorityTargetsControl = refl

ndeCurrentPriorityTargetsMechanism :
  Priority.unresolvedCoordinate Priority.ndeCurrentMove ≡ Temporal.mechanismDiscrimination
ndeCurrentPriorityTargetsMechanism = refl

ndePhenomenologyCanCloseWhileMechanismRemainsOpen :
  Active.ResolvedFor
    Obligation.obligationFamily
    Trajectory.awareII2023
    Obligation.phenomenologyConsumer
ndePhenomenologyCanCloseWhileMechanismRemainsOpen = Obligation.ndePhenomenologyResolved

ndeMechanismStillBlocked :
  Active.ResolvedFor
    Obligation.obligationFamily
    Trajectory.awareII2023
    Obligation.mechanismConsumer → ⊥
ndeMechanismStillBlocked = Obligation.ndeMechanismNotResolved

presentimentExperimentRouteAdmitted : ProofSearch.RouteAdmission
presentimentExperimentRouteAdmitted = Admission.proofSearchAdmission Admission.presentimentRoute

psilocybinExperimentTargetsControlAxis :
  Admission.targetAxis Admission.psilocybinRoute ≡ Temporal.controlStrength
psilocybinExperimentTargetsControlAxis = refl

ndeMechanismExperimentTargetsMechanismAxis :
  Admission.targetAxis Admission.ndeMechanismRoute ≡ Temporal.mechanismDiscrimination
ndeMechanismExperimentTargetsMechanismAxis = refl

bemRepeatAfterTransparentPsiIsRejected :
  Admission.rejectedDisposition Admission.repeatBemOriginalAfterTransparentPsi
  ≡ ProofSearch.rejected ProofSearch.consumerMismatch
bemRepeatAfterTransparentPsiIsRejected = refl
