module DASHI.Governance.IRISDenaMaxCutEverything where

import DASHI.Governance.IRISDenaAustralianCommandStatementReceiptExact
import DASHI.Governance.IRISDenaSenateEstimatesDutyNarrowingExact
import DASHI.Governance.IRISDenaPublicRecordCeilingAndFOIExact
import DASHI.Governance.IRISDenaHansardCorrectionAwareEvidenceExact
import DASHI.Governance.AUKUSOnboardConductSovereigntyBoundaryExact
import DASHI.Governance.AUKUSEmbeddedAuthorityCommandNoncollapseExact
import DASHI.Governance.IRISDenaMinisterialBriefingFOIBoundaryExact
import DASHI.Governance.IRISDenaSameObjectAcquisitionMaxCutExact
import DASHI.Governance.IRISDenaIranContraOpacityNonanalogyExact
import DASHI.Governance.OriginalThreadParetoMaxCut20261008Exact
