#!/usr/bin/env python3
"""Exact rational Albert derivation/triality decomposition diagnostic.

Starting from the explicit H_3(O_Q) Jordan product, this script verifies:

* Der(J) generated by inner derivations has dimension 52;
* the subalgebra fixing the three diagonal primitive idempotents has dimension 28;
* that 28-dimensional subspace is closed under brackets and perfect;
* a complementary 24-dimensional space is the direct sum of three canonical
  eight-dimensional blocks;
* the 28-dimensional frame algebra preserves each eight-dimensional block;
* the actual Albert coordinate S3 acts by conjugation on derivations and cycles/
  swaps those three blocks exactly.

This is an exact SymPy/Q diagnostic.  It establishes the native
52 = 28 + 8 + 8 + 8 triality anatomy but does not by itself classify the Lie
algebras as F4 and D4.
"""
from fractions import Fraction as F
import sympy as sp


def qmul(a,b):
    w,x,y,z=a; W,X,Y,Z=b
    return (w*W-x*X-y*Y-z*Z,
            w*X+x*W+y*Z-z*Y,
            w*Y-x*Z+y*W+z*X,
            w*Z+x*Y-y*X+z*W)
def qconj(a): return (a[0],-a[1],-a[2],-a[3])
def qadd(a,b): return tuple(x+y for x,y in zip(a,b))
def qneg(a): return tuple(-x for x in a)
def omul(o,p):
    a,b=o; c,d=p
    return (qadd(qmul(a,c),qneg(qmul(qconj(d),b))),
            qadd(qmul(d,a),qmul(b,qconj(c))))
def oadd(x,y): return qadd(x[0],y[0]),qadd(x[1],y[1])
def oscale(s,x): return tuple(s*a for a in x[0]),tuple(s*a for a in x[1])
def oconj(x): return qconj(x[0]),qneg(x[1])
def flat(x): return x[0]+x[1]
def real(x): return x[0][0]
def inner(x,y): return real(omul(x,oconj(y)))

def jordan(X,Y):
    a,b,c,x,y,z=X; d,e,f,u,v,w=Y
    d0=a*d+inner(z,w)+inner(y,v)
    d1=b*e+inner(z,w)+inner(x,u)
    d2=c*f+inner(y,v)+inner(x,u)
    ox=oscale(F(1,2),oadd(oadd(oadd(omul(oconj(z),oconj(v)),oscale(b,u)),oscale(f,x)),
                              oadd(oadd(omul(oconj(w),oconj(y)),oscale(e,x)),oscale(c,u))))
    oy=oscale(F(1,2),oadd(oadd(oadd(oscale(d,y),omul(oconj(x),oconj(w))),oscale(c,v)),
                              oadd(oadd(oscale(a,v),omul(oconj(u),oconj(z))),oscale(f,y))))
    oz=oscale(F(1,2),oadd(oadd(oadd(oscale(a,w),oscale(e,z)),omul(oconj(y),oconj(u))),
                              oadd(oadd(oscale(d,z),oscale(b,w)),omul(oconj(v),oconj(x)))))
    return d0,d1,d2,ox,oy,oz

def alb(v):
    o=lambda a:(tuple(F(x) for x in a[:4]),tuple(F(x) for x in a[4:]))
    return F(v[0]),F(v[1]),F(v[2]),o(v[3:11]),o(v[11:19]),o(v[19:27])
def vec(X): return [X[0],X[1],X[2],*flat(X[3]),*flat(X[4]),*flat(X[5])]
def smat(q): return sp.Rational(q.numerator,q.denominator)
def flatten(M): return sp.Matrix(M).reshape(729,1)
def span_rank(ms): return sp.Matrix.hstack(*map(flatten,ms)).rank() if ms else 0

E=[]
for i in range(27):
    v=[F(0)]*27; v[i]=F(1); E.append(alb(v))
L=[]
for i in range(27):
    cols=[vec(jordan(E[i],E[j])) for j in range(27)]
    L.append(sp.Matrix([[smat(cols[c][r]) for c in range(27)] for r in range(27)]))

pairs=[]; deriv=[]
for i in range(27):
    for j in range(i+1,27):
        pairs.append((i,j)); deriv.append(L[i]*L[j]-L[j]*L[i])
span=sp.Matrix.hstack(*map(flatten,deriv))
_,piv=span.rref()
basis=[deriv[i] for i in piv]
assert len(basis)==52

# Frame stabilizer: annihilate all three diagonal primitive idempotents.
constraint_cols=[]
for T in basis:
    block=[]
    for i in range(3): block.extend(list(T[:,i]))
    constraint_cols.append(sp.Matrix(block))
constraints=sp.Matrix.hstack(*constraint_cols)
null=constraints.nullspace()
frame=[sum((v[i]*basis[i] for i in range(52)),sp.zeros(27)) for v in null]
assert len(frame)==28
frame_comm=[frame[i]*frame[j]-frame[j]*frame[i]
            for i in range(28) for j in range(i+1,28)]
assert span_rank(frame)==28
assert span_rank(frame+frame_comm)==28
assert span_rank(frame_comm)==28

pair_index={p:i for i,p in enumerate(pairs)}
# Three canonical 8D complement blocks in the pivot geometry.
V0=[deriv[pair_index[(0,j)]] for j in range(11,19)]
V1=[deriv[pair_index[(0,j)]] for j in range(19,27)]
V2=[deriv[pair_index[(1,j)]] for j in range(3,11)]
for V in (V0,V1,V2): assert span_rank(V)==8
assert span_rank(frame+V0+V1+V2)==52
for V in (V0,V1,V2):
    fv=[f*v-v*f for f in frame for v in V]
    assert span_rank(V+fv)==8

# Signed permutation matrices for the actual Albert coordinate S3.
def perm_matrix(p):
    M=sp.zeros(27)
    for old,x in enumerate(p):
        s=1 if x>0 else -1; new=abs(x)-1; M[new,old]=s
    return M
# cycle: (a,b,c;x,y,z)->(c,a,b;z,x,y)
C=list(range(1,28))
for old,new in ((0,1),(1,2),(2,0)): C[old]=new+1
for oldslot,newslot in ((0,1),(1,2),(2,0)):
    for j in range(8): C[3+8*oldslot+j]=3+8*newslot+j+1
# swap: (a,b,c;x,y,z)->(a,c,b;conj x,conj z,conj y)
S=list(range(1,28)); S[0]=1; S[1]=3; S[2]=2
sgn=[1]+[-1]*7
for j in range(8):
    S[3+j]=sgn[j]*(3+j+1)
    S[11+j]=sgn[j]*(19+j+1)
    S[19+j]=sgn[j]*(11+j+1)
PC,PS=perm_matrix(C),perm_matrix(S)
def conjspace(P,V):
    Pinv=P.inv(); return [P*T*Pinv for T in V]
assert span_rank(frame+conjspace(PC,frame))==28
assert span_rank(frame+conjspace(PS,frame))==28
# C: V0->V1->V2->V0
assert span_rank(V1+conjspace(PC,V0))==8
assert span_rank(V2+conjspace(PC,V1))==8
assert span_rank(V0+conjspace(PC,V2))==8
# S: V0<->V1, V2 fixed
assert span_rank(V1+conjspace(PS,V0))==8
assert span_rank(V0+conjspace(PS,V1))==8
assert span_rank(V2+conjspace(PS,V2))==8

print('Der(J) dimension: 52')
print('diagonal-frame stabilizer dimension: 28')
print('complement dimensions: 8 + 8 + 8')
print('frame algebra closed/perfect: yes')
print('frame preserves each 8D module: yes')
print('Albert S3 triality on modules: C=(012), S=(01)')
