#!/usr/bin/env python3
"""Generate a concise, source-derived map of the DASHI Agda module graph."""
from __future__ import annotations
import argparse, collections, re
from pathlib import Path

MODULE=re.compile(r"^module\s+([\w.]+)\s+where",re.M)
IMPORT=re.compile(r"^(?:open\s+)?import\s+([\w.]+)",re.M)

def main():
 p=argparse.ArgumentParser();p.add_argument("--root",type=Path,default=Path("."));p.add_argument("--output",type=Path,default=Path("Docs/ProjectMap.md"));a=p.parse_args()
 files=sorted((a.root/"DASHI").rglob("*.agda")); rows=[]; inbound=collections.Counter(); lanes=collections.defaultdict(list)
 for f in files:
  text=f.read_text(encoding="utf8",errors="replace"); m=MODULE.search(text); name=m.group(1) if m else str(f.relative_to(a.root)).replace("/", ".")[:-5]
  imports=IMPORT.findall(text); [inbound.update([x]) for x in imports]; lane=name.split(".")[1] if name.startswith("DASHI.") and len(name.split("."))>1 else "root"
  lanes[lane].append((name,imports))
 a.output.parent.mkdir(parents=True,exist_ok=True)
 with a.output.open("w",encoding="utf8") as out:
  out.write("# DASHI project map\n\n> Generated by `scripts/build_project_map.py`; do not edit manually.\n\n")
  out.write(f"This map covers **{len(rows) or len(files):,}** Agda source modules under `DASHI/`. It is navigation and dependency metadata, not a proof-status claim.\n\n")
  out.write("## Start here\n\n- [Repository orientation](RepositoryLongformREADME.md)\n- [Source attribution policy](SourceAttributionPolicy.md)\n- `DASHI/Everything.agda` and lane-level `Everything.agda` aggregates\n\n## Lanes\n\n| Lane | Modules | Aggregate entrypoints |\n| --- | ---: | --- |\n")
  for lane,mods in sorted(lanes.items(),key=lambda x:(-len(x[1]),x[0])):
   aggregates=[n for n,_ in mods if n.endswith(".Everything")]
   shown=", ".join(f"`{n}`" for n in aggregates[:3])
   agg=(shown + (f" (+{len(aggregates)-3} more)" if len(aggregates)>3 else "")) or "—"
   out.write(f"| `{lane}` | {len(mods):,} | {agg} |\n")
  out.write("\n## Most imported DASHI modules\n\n| Module | Direct importers |\n| --- | ---: |\n")
  for name,count in inbound.most_common(30):
   if name.startswith("DASHI."): out.write(f"| `{name}` | {count:,} |\n")
  out.write("\n## How to refresh\n\n```bash\npython scripts/build_project_map.py\n```\n")
if __name__=="__main__":main()
