#!/usr/bin/env bash
set -euo pipefail
ROOT="${DASHI_REPO_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
OWNER="$ROOT/DASHI/Wikimedia/IbrahimMonster3BMathlibCyclotomicFieldScalarExtensionExact.agda"
[[ -f "$OWNER" ]] || { echo "missing owner: $OWNER" >&2; exit 1; }
required=(
  "record MathlibCyclotomicFieldCoordinate"
  "Mathlib/NumberTheory/Cyclotomic/Basic.lean"
  "Mathlib/NumberTheory/NumberField/Cyclotomic/Basic.lean"
  "Mathlib/RingTheory/Polynomial/Cyclotomic/Basic.lean"
  "CyclotomicField 3 ℚ"
  "AlgebraicClosure (CyclotomicField 3 ℚ)"
  "integralPowerBasisOfPrimePow"
  "integralPowerBasisOfPrimePow_gen"
  "integralPowerBasisOfPrimePow_dim"
  "Polynomial.cyclotomic_three"
  "PowerBasis.basis_eq_pow"
  "record LeanPhi3PowerBasisCoordinateReceipt"
  "compilePairTransportFromLeanPhi3Receipt"
  "phiThreeRelationPaysMultiplicationFormula"
  "record LeanPhi3PowerBasisExecutionCandidate"
  "chboishabba/dashi_lean4"
  "leanprover/lean4:v4.28.0"
  "mathlib v4.28.0"
  "agent/monster3b-phi3-power-basis"
  "c8ad5e4cab226d75c1fee2d7c4811e7336c27014"
  "Synthesis/Monster3BPhi3PowerBasis.lean"
  "Synthesis/Monster3BPhi3PowerBasisRegression.lean"
  "chboishabba/dashi_lean4#3"
  "leanWrapperSourceWritten = true"
  "leanWrapperKernelReceiptObserved = false"
  "agdaTransportReceiptObserved = false"
  "leanSourceDoesNotCreateKernelReceipt"
  "draftPullRequestDoesNotCreateLeanReceipt"
  "phiThreeIsTwo"
  "record DashiCyclotomic3ToMathlibCyclotomicFieldTransport"
  "dashiPairPresentationIsCyclotomicField"
  "algebraicClosureTargetIsAlgClosed"
  "pairPresentationDoesNotFollowFromDimensionTwo"
  "A005052"
)
for needle in "${required[@]}"; do
  grep -Fq "$needle" "$OWNER" || { echo "missing mathlib cyclotomic scalar extension marker: $needle" >&2; exit 1; }
done
echo "monster 3B mathlib cyclotomic scalar extension check: ok"
