#!/usr/bin/env bash
set -euo pipefail

root="${1:-.}"
files=(
  "DASHI/Biology/KluverLogPolar5HT2ASourceAtlasExact.agda"
  "DASHI/Biology/Psychedelic5HT2AAttentionBoundaryExact.agda"
  "DASHI/Cognition/LogPolarKluverDerivationExact.agda"
  "DASHI/Cognition/Kluver5HT2ACrossPollinationExact.agda"
  "DASHI/Cognition/KluverLogPolar5HT2AEverything.agda"
  "DASHI/Biology/Kluver5HT2ACrossScaleHyperfibreExact.agda"
  "DASHI/Biology/Kluver5HT2AMolecularProteinInstantiationExact.agda"
  "DASHI/Biology/FiveHT2ASignalingDialecticExact.agda"
  "DASHI/Biology/FiveHT2AProtocolIndexedSignalTransportExact.agda"
  "DASHI/Biology/FiveHT2AVisualCortexBioelectricBridgeExact.agda"
  "DASHI/Cognition/FiveHT2AVisualModeObservationBridgeExact.agda"
  "DASHI/Cognition/AnalyticLogPolarSpiralCompilerExact.agda"
  "DASHI/Biology/IonicMimicrySourceAtlasExact.agda"
  "DASHI/Biology/IonicMimicryGeometryExact.agda"
  "DASHI/Biology/TargetRelativeRecognitionFibreExact.agda"
  "DASHI/Biology/FiveHT2ACalciumIdentityGeometryBoundaryExact.agda"
  "DASHI/Biology/TargetIndexedRecognitionGeometryExact.agda"
  "DASHI/Biology/TargetIndexedRecognitionAdmissibleRegionExact.agda"
  "DASHI/Biology/TargetIndexedRecognitionEmpiricalCalibrationExact.agda"
  "DASHI/Biology/ContextIndexedRecognitionGeometryExact.agda"
  "DASHI/Biology/FiveHT2ARecognitionStateSpaceExact.agda"
  "DASHI/Biology/TargetRecognitionFibrationExact.agda"
  "DASHI/Biology/FiveHT2ARecognitionResidualProjectionExact.agda"
  "DASHI/Biology/FiveHT2AProjectionTowerExact.agda"
)

for relative in "${files[@]}"; do
  file="$root/$relative"
  test -f "$file"
  if grep -nE '^[[:space:]]*postulate([[:space:]]|$)|\{!!\}|TODO|FIXME|--allow-unsolved-metas' "$file"; then
    echo "forbidden hole, postulate, placeholder, or unsafe option in $relative" >&2
    exit 1
  fi
done

atlas="$root/DASHI/Biology/KluverLogPolar5HT2ASourceAtlasExact.agda"
grep -Fq 'Docs/SourceAttributionPolicy.md' "$atlas"
grep -Fq '10.1007/BF00336965' "$atlas"
grep -Fq '10.1016/0042-6989(80)90090-5' "$atlas"
grep -Fq '10.1016/0042-6989(94)00187-Q' "$atlas"
grep -Fq '10.1098/rstb.2000.0769' "$atlas"
grep -Fq '10.1073/pnas.071582498' "$atlas"
grep -Fq 'pubmed.ncbi.nlm.nih.gov/10688105' "$atlas"
grep -Fq '10.1523/JNEUROSCI.2830-16.2016' "$atlas"
grep -Fq '10.1016/j.cub.2016.12.030' "$atlas"
grep -Fq '10.7554/eLife.35082' "$atlas"
grep -Fq '10.1523/JNEUROSCI.4692-12.2013' "$atlas"
grep -Fq '10.1016/j.cortex.2024.11.010' "$atlas"
grep -Fq '10.1038/s41467-024-51861-1' "$atlas"
grep -Fq '10.1038/s42003-025-09492-9' "$atlas"
grep -Fq '10.1016/j.neubiorev.2026.106649' "$atlas"

boundary="$root/DASHI/Biology/Psychedelic5HT2AAttentionBoundaryExact.agda"
grep -Fq 'imperativeLookAtThisMechanismEstablishedIsFalse' "$boundary"
grep -Fq 'telepathicEntitySignalEstablishedIsFalse' "$boundary"
grep -Fq 'anteriorCingulate5HT2ABindingSourceBoundIsTrue' "$boundary"

cross="$root/DASHI/Cognition/Kluver5HT2ACrossPollinationExact.agda"
grep -Fq 'geometryAndPharmacologyAreSeparateEvidenceLayersIsTrue' "$cross"
grep -Fq 'jointMechanismEmpiricallyClosedIsFalse' "$cross"
grep -Fq 'feltImportanceProvesExternalAgencyIsFalse' "$cross"

hyperfibre="$root/DASHI/Biology/Kluver5HT2ACrossScaleHyperfibreExact.agda"
grep -Fq 'NeurochemicalAtomicChemistryBridge' "$hyperfibre"
grep -Fq 'NeurochemicalProteinTargetBridge' "$hyperfibre"
grep -Fq 'NeurochemicalTransmissionBridge' "$hyperfibre"
grep -Fq 'NeurochemicalBrainCarrierBridge' "$hyperfibre"
grep -Fq 'ProteinConformationAttractor' "$hyperfibre"
grep -Fq 'AtomicPeriodicTable369ChemistryHyperfibreBridgeExact' "$hyperfibre"
grep -Fq 'receptorToCorticalModeTransferIsQuantitativelyClosedIsFalse' "$hyperfibre"
grep -Fq 'visualPhenomenologyIsRecoveredFromMolecularStateIsFalse' "$hyperfibre"

molecular="$root/DASHI/Biology/Kluver5HT2AMolecularProteinInstantiationExact.agda"
grep -Fq 'PubChem CID 5202' "$molecular"
grep -Fq 'PubChem CID 5761' "$molecular"
grep -Fq 'PubChem CID 3822' "$molecular"
grep -Fq 'PDB 9AS4' "$molecular"
grep -Fq 'wacker5HT2BNeighborEvidence' "$molecular"
grep -Fq 'assayBoundAffinityStillMissingIsTrue' "$molecular"
grep -Fq 'receptorStateToKluverModeTransferStillMissingIsTrue' "$molecular"
grep -Fq 'ketanserinIdentityAloneDoesNotProveSelective5HT2ABlockade' "$molecular"

signaling="$root/DASHI/Biology/FiveHT2ASignalingDialecticExact.agda"
grep -Fq 'wallachGqHTR' "$signaling"
grep -Fq 'xuGiHallucinogenicAssay' "$signaling"
grep -Fq 'universalGqOnlyMechanismBlocked' "$signaling"
grep -Fq 'universalGiOnlyMechanismBlocked' "$signaling"
grep -Fq 'humanPhenomenologyMechanismClosedIsFalse' "$signaling"

transport="$root/DASHI/Biology/FiveHT2AProtocolIndexedSignalTransportExact.agda"
grep -Fq 'protocolIdentityPreservedIsTrue' "$transport"
grep -Fq 'signalingModulatorCanChangeOutputAtFixedInput' "$transport"
grep -Fq 'quantitativeBiophysicalCalibrationPresentIsFalse' "$transport"
grep -Fq 'receptorSignalDeterminesBrainStateIsFalse' "$transport"

v1="$root/DASHI/Biology/FiveHT2AVisualCortexBioelectricBridgeExact.agda"
grep -Fq 'chemicalCoordinateCanChangeNetworkState' "$v1"
grep -Fq 'quantitativeVoltageCurrentTransferClosedIsFalse' "$v1"
grep -Fq 'mouseV1DoesNotDetermineHumanHallucination' "$v1"

mode="$root/DASHI/Cognition/FiveHT2AVisualModeObservationBridgeExact.agda"
grep -Fq 'temporalDoesNotDetermineSpatial' "$mode"
grep -Fq 'gainDoesNotDetermineForm' "$mode"
grep -Fq 'spatialFieldProtocolPresentIsFalse' "$mode"

spiral="$root/DASHI/Cognition/AnalyticLogPolarSpiralCompilerExact.agda"
grep -Fq 'logRadiusEqualityImpliesExponentialRadius' "$spiral"
grep -Fq 'analyticSpiralPointHasExponentialRadius' "$spiral"
grep -Fq 'affineConstantPhaseRearrangementProvedFromCurrentMinimalRealSpineIsFalse' "$spiral"
grep -Fq 'empiricalV1SpatialModeIdentifiedAsAffineLogPolarPhaseIsFalse' "$spiral"

ionic="$root/DASHI/Biology/IonicMimicryGeometryExact.agda"
grep -Fq 'sameChargeDoesNotMeanSameAction' "$ionic"
grep -Fq 'rigidityChangesOutcome' "$ionic"
grep -Fq 'substitutionDoesNotMeanChemicalIdentity' "$ionic"

recognition="$root/DASHI/Biology/TargetRelativeRecognitionFibreExact.agda"
grep -Fq 'canonicalPbCaRecognitionFibre' "$recognition"
grep -Fq 'canonicalSerotoninLSDRecognitionFibre' "$recognition"
grep -Fq 'recognitionDoesNotMeanSameSignaling' "$recognition"

calcium="$root/DASHI/Biology/FiveHT2ACalciumIdentityGeometryBoundaryExact.agda"
grep -Fq 'calciumSignalIsNotJustConcentration' "$calcium"
grep -Fq 'leadMimicryIsNotPsychedelicMechanism' "$calcium"
grep -Fq 'reporterIntensityDoesNotDetermineBindingGeometry' "$calcium"

geometry="$root/DASHI/Biology/TargetIndexedRecognitionGeometryExact.agda"
grep -Fq 'canonicalSamePairDifferentTargetWitness' "$geometry"
grep -Fq 'targetAScoreIsZero' "$geometry"
grep -Fq 'targetBScoreIsSix' "$geometry"
grep -Fq 'targetBRejectsPair' "$geometry"
grep -Fq 'canonicalAnisotropicRecognitionWitness' "$geometry"
grep -Fq 'arbitraryWeightsDoNotBecomeAffinity' "$geometry"

region="$root/DASHI/Biology/TargetIndexedRecognitionAdmissibleRegionExact.agda"
grep -Fq 'canonicalSamePairDifferentRegionWitness' "$region"
grep -Fq 'scalarScoreAcceptsCanonicalPair' "$region"
grep -Fq 'hardRegionRejectsCanonicalPair' "$region"
grep -Fq 'scalarAcceptanceDoesNotImplyHardGateAcceptance' "$region"

calibration="$root/DASHI/Biology/TargetIndexedRecognitionEmpiricalCalibrationExact.agda"
grep -Fq 'pbCaCoordinationMeasurement' "$calibration"
grep -Fq 'lsdFiveHT2AConformationMeasurement' "$calibration"
grep -Fq 'everyWeightedCoordinateHasMeasurementIsFalse' "$calibration"
grep -Fq 'heldOutValidationPassedIsFalse' "$calibration"
grep -Fq 'noEmpiricalPromotionFromCurrentCalibration' "$calibration"

context="$root/DASHI/Biology/ContextIndexedRecognitionGeometryExact.agda"
grep -Fq 'canonicalSameTargetDifferentContextWitness' "$context"
grep -Fq 'canonicalPairAdmittedInContext0' "$context"
grep -Fq 'canonicalPairRejectedInContext1' "$context"
grep -Fq 'nominalTargetDoesNotFixGeometry' "$context"
grep -Fq 'proteinConformationNotErased' "$context"

statespace="$root/DASHI/Biology/FiveHT2ARecognitionStateSpaceExact.agda"
grep -Fq 'canonicalContextDependentRecognitionWitness' "$statespace"
grep -Fq 'sameLigandAcrossFixtureStates' "$statespace"
grep -Fq 'state0Admitted' "$statespace"
grep -Fq 'state1Rejected' "$statespace"
grep -Fq 'moleculeIdentityIsNotFullState' "$statespace"

fibration="$root/DASHI/Biology/TargetRecognitionFibrationExact.agda"
grep -Fq 'canonicalRecognitionSplitLift' "$fibration"
grep -Fq 'canonicalRecognitionObservationNaturality' "$fibration"
grep -Fq 'canonicalAdmissionChangesAcrossContext' "$fibration"
grep -Fq 'fullGrothendieckEquivalenceClaimedIsFalse' "$fibration"

residual="$root/DASHI/Biology/FiveHT2ARecognitionResidualProjectionExact.agda"
grep -Fq 'publicLigandCollision' "$residual"
grep -Fq 'recognitionRecoverableProjection' "$residual"
grep -Fq 'recognitionCodeSeparating' "$residual"
grep -Fq 'publicProjectionIsNotInjective' "$residual"

tower="$root/DASHI/Biology/FiveHT2AProjectionTowerExact.agda"
grep -Fq 'recognitionStatesCollapseAtSignaling' "$tower"
grep -Fq 'recognitionPerceptComposition' "$tower"
grep -Fq 'signalingProjectionNotFaithful' "$tower"
grep -Fq 'perceptDoesNotDetermineLigand' "$tower"

echo 'Kluver/log-polar/5-HT2A attribution and boundary static contract: OK'
