#!/usr/bin/env python3
"""Check simple alpha normalizations from CM j-value differences.

The calculation is intentionally narrow: it tests explicit arithmetic
normalizations of the three supplied CM j-values against the current carrier
alpha diagnostics.  A numerical near-hit is recorded as a heuristic match only;
it is not a derivation of alpha from modular geometry.
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal, getcontext
from fractions import Fraction
from pathlib import Path


getcontext().prec = 50

REPO_ROOT = Path(__file__).resolve().parents[1]
REPORT_PATH = REPO_ROOT / "Docs" / "AlphaFromJNumericalCheck.md"

ALPHA_TARGETS = {
    "alpha1": Decimal("0.041240"),
    "alpha2": Decimal("0.085720"),
}
MATCH_TOLERANCE = Decimal("0.001000")

J_VALUES = {
    "j(i)": 1728,
    "j(rho)": 0,
    "j((1+i*sqrt(7))/2)": -3375,
}


@dataclass(frozen=True)
class Difference:
    label: str
    left: str
    right: str
    signed: int
    absolute: int


@dataclass(frozen=True)
class NormalizationResult:
    name: str
    source: str
    exact: str
    decimal: Decimal
    target_name: str
    target: Decimal
    abs_error: Decimal
    match: bool


def dec(frac: Fraction) -> Decimal:
    return Decimal(frac.numerator) / Decimal(frac.denominator)


def fmt_decimal(value: Decimal, digits: int = 12) -> str:
    quant = Decimal(1).scaleb(-digits)
    return str(value.quantize(quant))


def cm_differences() -> list[Difference]:
    labels = list(J_VALUES)
    out: list[Difference] = []
    for i, left in enumerate(labels):
        for right in labels[i + 1 :]:
            signed = J_VALUES[left] - J_VALUES[right]
            out.append(
                Difference(
                    label=f"{left} - {right}",
                    left=left,
                    right=right,
                    signed=signed,
                    absolute=abs(signed),
                )
            )
    return out


def normalization_fractions(diff: Difference) -> list[tuple[str, Fraction]]:
    d = diff.absolute
    return [
        ("1/|Delta j|", Fraction(1, d)),
        ("72/|Delta j|", Fraction(72, d)),
        ("144/|Delta j|", Fraction(144, d)),
        ("|Delta j|/1728^2", Fraction(d, 1728 * 1728)),
        ("|Delta j|/3375^2", Fraction(d, 3375 * 3375)),
        ("|Delta j|/5103^2", Fraction(d, 5103 * 5103)),
    ]


def sqrt_normalization(diff: Difference) -> tuple[str, Decimal, str]:
    d = Decimal(diff.absolute)
    value = Decimal(1) / d.sqrt()
    return ("1/sqrt(|Delta j|)", value, f"1/sqrt({diff.absolute})")


def compare(name: str, source: str, exact: str, value: Decimal) -> list[NormalizationResult]:
    rows: list[NormalizationResult] = []
    for target_name, target in ALPHA_TARGETS.items():
        abs_error = abs(value - target)
        rows.append(
            NormalizationResult(
                name=name,
                source=source,
                exact=exact,
                decimal=value,
                target_name=target_name,
                target=target,
                abs_error=abs_error,
                match=abs_error <= MATCH_TOLERANCE,
            )
        )
    return rows


def all_results(differences: list[Difference]) -> list[NormalizationResult]:
    rows: list[NormalizationResult] = []
    for diff in differences:
        for name, frac in normalization_fractions(diff):
            rows.extend(compare(name, diff.label, f"{frac.numerator}/{frac.denominator}", dec(frac)))
        sqrt_name, sqrt_value, sqrt_exact = sqrt_normalization(diff)
        rows.extend(compare(sqrt_name, diff.label, sqrt_exact, sqrt_value))
    return rows


def markdown_report(differences: list[Difference], rows: list[NormalizationResult]) -> str:
    any_alpha1 = any(row.target_name == "alpha1" and row.match for row in rows)
    any_alpha2 = any(row.target_name == "alpha2" and row.match for row in rows)
    both_targets = any_alpha1 and any_alpha2
    lines = [
        "# Alpha From CM j-Values Numerical Check",
        "",
        "Status: generated by `scripts/check_alpha_from_j_values.py`; numerical check only; non-promoting.",
        "",
        "## Inputs",
        "",
        "| CM point | j-value |",
        "|---|---:|",
    ]
    for label, value in J_VALUES.items():
        lines.append(f"| `{label}` | `{value}` |")

    lines.extend(
        [
            "",
            "Targets:",
            "",
            f"- `alpha1 = {ALPHA_TARGETS['alpha1']}`",
            f"- `alpha2 = {ALPHA_TARGETS['alpha2']}`",
            f"- match tolerance: `{MATCH_TOLERANCE}` absolute error",
            "",
            "## Exact Differences",
            "",
            "| Difference | signed | absolute |",
            "|---|---:|---:|",
        ]
    )
    for diff in differences:
        lines.append(f"| `{diff.label}` | `{diff.signed}` | `{diff.absolute}` |")

    lines.extend(
        [
            "",
            "## Normalization Tests",
            "",
            "| Source | normalization | exact | decimal | target | abs error | match |",
            "|---|---|---:|---:|---:|---:|---|",
        ]
    )
    for row in rows:
        lines.append(
            "| "
            f"`{row.source}` | `{row.name}` | `{row.exact}` | "
            f"`{fmt_decimal(row.decimal)}` | `{row.target_name}={row.target}` | "
            f"`{fmt_decimal(row.abs_error)}` | `{str(row.match).lower()}` |"
        )

    lines.extend(
        [
            "",
            "## Conclusion",
            "",
            f"- alpha1 heuristic match found: `{str(any_alpha1).lower()}`",
            f"- alpha2 heuristic match found: `{str(any_alpha2).lower()}`",
            f"- simultaneous alpha1/alpha2 derivation found: `{str(both_targets).lower()}`",
            "",
            "The only near-hit in this tested family is the simple modular-weight normalization "
            "`72 / |j(i)-j(rho)| = 1/24 = 0.041666666667`, which is within the configured "
            "absolute tolerance of the alpha1 diagnostic.  No tested normalization gives alpha2 "
            "within tolerance, and the alpha1 near-hit is not a formal bridge from modular "
            "geometry to the carrier alpha diagnostics.",
            "",
            "Therefore this check does not justify promoting an alpha derivation from CM j-values.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    differences = cm_differences()
    rows = all_results(differences)
    report = markdown_report(differences, rows)
    REPORT_PATH.write_text(report, encoding="utf-8")

    print("CM j-value differences:")
    for diff in differences:
        print(f"  {diff.label}: signed={diff.signed}, absolute={diff.absolute}")
    print(f"targets: alpha1={ALPHA_TARGETS['alpha1']}, alpha2={ALPHA_TARGETS['alpha2']}")
    print(f"tolerance: {MATCH_TOLERANCE}")
    for row in rows:
        if row.match:
            print(
                "match: "
                f"target={row.target_name}, source={row.source}, "
                f"normalization={row.name}, exact={row.exact}, "
                f"decimal={fmt_decimal(row.decimal)}, "
                f"abs_error={fmt_decimal(row.abs_error)}"
            )
    print(f"report: {REPORT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
