#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
OWNER="DASHI/Biology/BioacousticMultimodalLagFactorisationExact.agda"
test -f "$OWNER"
grep -q "data MultimodalQuery" "$OWNER"
grep -q "heartRateLeadsTempo" "$OWNER"
grep -q "pressurePredictsSPLGivenPitch" "$OWNER"
grep -q "danceAddsEnergeticLoadGivenSong" "$OWNER"
grep -q "acousticallySimilarDifferentPhysiology" "$OWNER"
grep -q "record LaggedConsumerRequest" "$OWNER"
grep -q "sameEpisodeRequired" "$OWNER"
grep -q "controlCoordinatesRetained" "$OWNER"
grep -q "acousticOnlyHeartRateLagDefect" "$OWNER"
grep -q "acousticOnlyDanceEnergyDefect" "$OWNER"
grep -q "acousticOnlyCannotAnswerHeartRateLag" "$OWNER"
grep -q "acousticOnlyCannotAnswerDanceEnergy" "$OWNER"
grep -q "lagAssociationDoesNotCreateCausality" "$OWNER"
grep -q "oneQueryAdequacyDoesNotPromoteAllQueries" "$OWNER"
echo "bioacoustic multimodal lag/factorisation static contract passed"
