#!/usr/bin/env bash
set -euo pipefail
root="${1:-.}"
owner="$root/DASHI/Culture/MissingDeceasedTwentyScientistRound15ObjectLinkProgressExact.agda"
agg="$root/DASHI/Culture/MissingDeceasedCommonObjectProgrammeEverything.agda"

test -f "$owner"
grep -q 'round15ScientificCohortCount = 20' "$owner"
grep -q 'round15EveryScientistTouched = true' "$owner"
grep -q 'round15LiteralCommonProgrammePromotionCount = 0' "$owner"
grep -q 'round15InstitutionalAdjacencyDoesNotPayObjectLink = false' "$owner"
grep -q 'Nuno F. G. Loureiro' "$owner"
grep -q 'Joshua Kyle LeBlanc' "$owner"
grep -q 'Frank W. Maiwald' "$owner"
grep -q 'Monica Jacinto / Monica Reza' "$owner"
grep -q 'Carl J. Grillmair' "$owner"
grep -q 'Michael David Hicks' "$owner"
grep -q 'William Neil McCasland' "$owner"
grep -q 'Anthony Chavez' "$owner"
grep -q 'Jason R. Thomas' "$owner"
grep -q 'Amy Eskridge' "$owner"
grep -q 'Ning Li' "$owner"
grep -q 'Chen Shuming' "$owner"
grep -q 'Feng Yanghe' "$owner"
grep -q 'Zhou Guangyuan' "$owner"
grep -q 'Liu Donghao' "$owner"
grep -q 'Zhang Xiaoxin' "$owner"
grep -q 'Zhang Daibing' "$owner"
grep -q 'Li Minyong' "$owner"
grep -q 'Fang Daining' "$owner"
grep -q 'Yan Hong' "$owner"
grep -q 'MissingDeceasedTwentyScientistRound15ObjectLinkProgressExact' "$agg"

echo 'Round-15 object-link progress static contract: OK'
