#!/usr/bin/env python3
import argparse
import importlib.util
from pathlib import Path

HERE = Path(__file__).resolve().parent
SPEC = importlib.util.spec_from_file_location(
    'recognition', HERE / 'j369_kernel_field_recognition.py')
R = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(R)


def tf(x):
    return 'true' if x else 'false'


def render():
    summary = R.recognition_summary()
    fields = summary['fields']
    frontier = summary['full_signed_weave_frontier']
    lines = [
        'module DASHI.Moonshine.Generated.OggSSPMaxCutRuntimeGenerated where',
        '',
        '-- GENERATED by scripts/j369_maxcut_runtime_receipt.py; do not hand-edit.',
        '-- Runtime/exhaustive finite receipts only; semantic promotion stays source-gated.',
        '',
        'open import Agda.Builtin.Bool using (Bool; true; false)',
        '',
        'heisenbergTranslationIntertwinesF3Addition : Bool',
        'heisenbergTranslationIntertwinesF3Addition = ' + tf(summary['existing_heisenberg_translation_intertwines_f3_addition']),
        '',
    ]
    for d in ('4', '5', '6'):
        f = fields[d]
        lines += [
            f'k{d}CoordinateSwapPreservesAddNeg : Bool',
            f'k{d}CoordinateSwapPreservesAddNeg = {tf(f["coordinate_swap_preserves_addition_and_negation"])}',
            f'k{d}CoordinateSwapChangesChosenMultiplication : Bool',
            f'k{d}CoordinateSwapChangesChosenMultiplication = {tf(f["coordinate_swap_changes_chosen_multiplication"])}',
            '',
        ]
    lines += [
        'totalSignedProgramCounterMachinePaid : Bool',
        'totalSignedProgramCounterMachinePaid = ' + tf(frontier['canonical_total_program_counter_machine_paid']),
        'machineToRichSignedStateProjectionPaid : Bool',
        'machineToRichSignedStateProjectionPaid = ' + tf(frontier['machine_to_rich_signed_state_projection_paid']),
        'fullRichSignedTransitionGraphClaimed : Bool',
        'fullRichSignedTransitionGraphClaimed = ' + tf(frontier['full_rich_signed_transition_graph_claimed']),
        '',
    ]
    return '\n'.join(lines)


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--output', type=Path, required=True)
    args = p.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render())


if __name__ == '__main__':
    main()
