#!/usr/bin/env python3
import argparse
import importlib.util
from pathlib import Path

HERE = Path(__file__).resolve().parent
SPEC = importlib.util.spec_from_file_location(
    'recognition', HERE / 'j369_kernel_field_recognition.py')
R = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(R)


def tf(x):
    return 'true' if x else 'false'


def render():
    summary = R.recognition_summary()
    fields = summary['fields']
    frontier = summary['full_signed_weave_frontier']
    lines = [
        'module DASHI.Moonshine.Generated.OggSSPMaxCutRuntimeGenerated where',
        '',
        '-- GENERATED by scripts/j369_maxcut_runtime_receipt.py; do not hand-edit.',
        '-- Runtime/exhaustive finite receipts only; semantic promotion stays source-gated.',
        '',
        'open import Agda.Builtin.Bool using (Bool; true; false)',
        '',
        'heisenbergTranslationIntertwinesF3Addition : Bool',
        'heisenbergTranslationIntertwinesF3Addition = ' + tf(summary['existing_heisenberg_translation_intertwines_f3_addition']),
        'heisenbergCoordinateSwapPreservesDot6Exhaustive : Bool',
        'heisenbergCoordinateSwapPreservesDot6Exhaustive = ' + tf(summary['heisenberg_coordinate_swap_preserves_dot6_exhaustive']),
        'canonicalSignedCoreReplayVerified : Bool',
        'canonicalSignedCoreReplayVerified = ' + tf(summary['canonical_signed_core_replay_verified']),
        '',
    ]
    for d in ('4', '5', '6'):
        f = fields[d]
        lines += [
            f'k{d}CoordinateSwapPreservesAddNeg : Bool',
            f'k{d}CoordinateSwapPreservesAddNeg = {tf(f["coordinate_swap_preserves_addition_and_negation"])}',
            f'k{d}CoordinateSwapChangesChosenMultiplication : Bool',
            f'k{d}CoordinateSwapChangesChosenMultiplication = {tf(f["coordinate_swap_changes_chosen_multiplication"])}',
            '',
        ]
    lines += [
        'totalSignedProgramCounterMachinePaid : Bool',
        'totalSignedProgramCounterMachinePaid = ' + tf(frontier['canonical_total_program_counter_machine_paid']),
        'executedTraceRetainsPrimeIdentity : Bool',
        'executedTraceRetainsPrimeIdentity = ' + tf(frontier['executed_trace_retains_prime_identity']),
        'arbitraryProgramValuationReplayPaid : Bool',
        'arbitraryProgramValuationReplayPaid = ' + tf(frontier['arbitrary_program_valuation_replay_paid']),
        'arbitraryProgramInvariantUnitReplayPaid : Bool',
        'arbitraryProgramInvariantUnitReplayPaid = ' + tf(frontier['arbitrary_program_invariant_unit_replay_paid']),
        'genericProgramLengthDynamicsPaid : Bool',
        'genericProgramLengthDynamicsPaid = ' + tf(frontier['generic_program_length_dynamics_paid']),
        'genericExecutionLengthDynamicsPaid : Bool',
        'genericExecutionLengthDynamicsPaid = ' + tf(frontier['generic_execution_length_dynamics_paid']),
        'genericNormalFormLengthDynamicsPaid : Bool',
        'genericNormalFormLengthDynamicsPaid = ' + tf(frontier['generic_normal_form_length_dynamics_paid']),
        'richMachineCompilerGivenResidualMetadataPaid : Bool',
        'richMachineCompilerGivenResidualMetadataPaid = ' + tf(frontier['rich_machine_compiler_given_residual_metadata_paid']),
        'canonicalVirtualRichProjectionPaid : Bool',
        'canonicalVirtualRichProjectionPaid = ' + tf(frontier['canonical_virtual_rich_projection_paid']),
        'canonicalGeometryRichProjectionPaid : Bool',
        'canonicalGeometryRichProjectionPaid = ' + tf(frontier['canonical_geometry_rich_projection_paid']),
        'addressDynamicsRecovered : Bool',
        'addressDynamicsRecovered = ' + tf(frontier['address_dynamics_recovered']),
        'zeroResidualDynamicsRecovered : Bool',
        'zeroResidualDynamicsRecovered = ' + tf(frontier['zero_residual_dynamics_recovered']),
        'residualWitnessLengthDynamicsRecovered : Bool',
        'residualWitnessLengthDynamicsRecovered = ' + tf(frontier['residual_witness_length_dynamics_recovered']),
        '',
        '-- Compatibility receipt: an unconditional arbitrary rich projection is still unpaid.',
        'machineToRichSignedStateProjectionPaid : Bool',
        'machineToRichSignedStateProjectionPaid = false',
        'fullRichSignedTransitionGraphClaimed : Bool',
        'fullRichSignedTransitionGraphClaimed = ' + tf(frontier['full_rich_signed_transition_graph_claimed']),
        '',
    ]
    return '\n'.join(lines)


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--output', type=Path, required=True)
    args = p.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render())


if __name__ == '__main__':
    main()
