#!/usr/bin/env python3
"""Generate a self-contained animated DASHI operator-transport hyperfabric SVG."""
from pathlib import Path
from dataclasses import dataclass

@dataclass(frozen=True)
class N: id:str; label:str; layer:int; stage:int; bundle:int; note:str
@dataclass(frozen=True)
class E: id:str; a:str; b:str; op:str; colour:str; begin:float; dur:float

W,H=1800,980
nodes=[
N('c14','C-14',0,0,3,'isotope carrier'),N('n14','N-14',0,3,3,'post-decay state'),
N('cat','C atom',1,0,3,'electronic carrier'),N('exc','C*',1,2,3,'excited state'),N('line','spectral line',1,5,3,'observable'),
N('co2','CO₂',2,1,6,'chemical carrier'),N('glu','glucose',2,4,6,'stored chemistry'),
N('evt','collision event',3,0,9,'physical process'),N('hit','tracker hits',3,2,9,'detector response'),N('reco','reco track',3,4,9,'reconstruction'),N('bin','HEPData bin',3,6,9,'empirical contact'),
N('leaf','leaf uptake',4,3,6,'biological transport'),N('bone','bone collagen',4,6,6,'biological state'),N('res','residual',5,7,9,'loose fibre / mismatch')]
edges=[
E('dec','c14','n14','β⁻ decay','#4CD1FF',0,10),E('iso','c14','co2','isotope enters chemistry','#9AD0FF',.8,8),
E('ex','cat','exc','excitation','#B46CFF',.4,7.5),E('em','exc','line','radiative emission','#B46CFF',1.8,7),
E('pho','co2','glu','photosynthesis / refinement','#53E3A6',1.2,9),E('up','co2','leaf','uptake','#FF7AA2',1.6,7),
E('met','leaf','bone','metabolic transport','#FF7AA2',2.5,8),E('dh','evt','hit','detector response','#F9C74F',.1,6.5),
E('hr','hit','reco','reconstruction','#F9C74F',.8,6.5),E('rb','reco','bin','binning / collapse','#F9C74F',1.4,6),
E('lb','line','bin','spectral contact','#9AD0FF',2,7.5),E('gb','glu','bone','biosynthetic storage','#53E3A6',2.3,7),
E('br','bin','res','systematic residual','#FF6B6B',3,6.5)]
L=['Nuclear','Electronic','Chemical','Empirical','Biological','Residual']; B={3:'#4CD1FF',6:'#B46CFF',9:'#F9C74F'}
def xy(n): return 90+n.stage*190,98+n.layer*130+(12 if n.bundle==9 else -12 if n.bundle==3 else 0)
def esc(s): return s.replace('&','&amp;').replace('<','&lt;').replace('>','&gt;')
def rr(x,y,w,h,r=14): return f'M{x+r},{y}H{x+w-r}Q{x+w},{y} {x+w},{y+r}V{y+h-r}Q{x+w},{y+h} {x+w-r},{y+h}H{x+r}Q{x},{y+h} {x},{y+h-r}V{y+r}Q{x},{y} {x+r},{y}Z'
def curve(a,b,i):
 x1,y1=xy(a);x2,y2=xy(b);sx,sy=x1+132,y1+26;tx,ty=x2,y2+26;d=tx-sx;lift=((i%4)-1.5)*16;c=max(35,min(120,abs(d)*.14));sg=1 if ty>sy else -1
 if abs(ty-sy)<20: c=0
 return f'M{sx},{sy}C{sx+d*.33},{sy+sg*c+lift} {sx+d*.66},{ty-sg*c+lift} {tx},{ty}'
def generate():
 m={n.id:n for n in nodes}; out=[f'''<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="{W}" height="{H}" viewBox="0 0 {W} {H}"><defs><linearGradient id="bg"><stop stop-color="#071426"/><stop offset="1" stop-color="#0A1630"/></linearGradient><pattern id="g" width="28" height="28" patternUnits="userSpaceOnUse"><path d="M28 0H0V28" fill="none" stroke="#143053" opacity=".4"/></pattern><filter id="glow"><feGaussianBlur stdDeviation="5" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter><marker id="a" markerWidth="10" markerHeight="10" refX="9" refY="5" orient="auto"><path d="M0 0L10 5 0 10z" fill="#CFEBFF"/></marker><style>text{{font-family:Inter,Arial,sans-serif}}.t{{fill:#EAF3FF;font-weight:700}}.s{{fill:#94B6D6}}.band{{fill:#10294855;stroke:#1F4D7D}}.th{{fill:none;stroke-linecap:round;stroke-dasharray:12 10;animation:d 12s linear infinite}}.n{{fill:#0C203B;stroke:#2B6DA7;stroke-width:1.6}}@keyframes d{{to{{stroke-dashoffset:-44}}}}@keyframes b{{50%{{opacity:.7}}}}.alive{{animation:b 5s ease-in-out infinite}}</style></defs><rect width="100%" height="100%" fill="url(#bg)"/><rect width="100%" height="100%" fill="url(#g)" opacity=".22"/><text x="72" y="58" class="t" font-size="40">DASHI HYPERFABRIC · OPERATOR TRANSPORT OVER TIME</text><text x="72" y="86" class="s" font-size="17">Topology is generated by operator transport: strands refine, collapse, cross layers, and fray into residual.</text>''']
 for i,l in enumerate(L):
  y=80+i*130;out+= [f'<path class="band" d="{rr(54,y,1692,84,18)}"/>',f'<text x="74" y="{y+28}" class="t" font-size="16" letter-spacing="2">{l}</text>']
 for b in (3,6,9):
  ps=[xy(n) for n in nodes if n.bundle==b];minx=min(x for x,y in ps)-34;maxx=max(x+132 for x,y in ps)+34;miny=min(y for x,y in ps)-24;maxy=max(y+52 for x,y in ps)+24
  out += [f'<path d="{rr(minx,miny,maxx-minx,maxy-miny,26)}" fill="none" stroke="{B[b]}" opacity=".25" stroke-width="2" stroke-dasharray="10 8"/>',f'<text x="{minx+18}" y="{miny-6}" class="s" font-size="12">{b}-bundle · shared ultrametric prefix neighbourhood</text>']
 for i,e in enumerate(edges): out.append(f'<path id="{e.id}" d="{curve(m[e.a],m[e.b],i)}" fill="none" stroke="none"/>')
 for i,e in enumerate(edges):
  d=curve(m[e.a],m[e.b],i);a,b=m[e.a],m[e.b];x1,y1=xy(a);x2,y2=xy(b);mx=(x1+x2+132)/2;my=(y1+y2+52)/2-10-(i%2)*12
  out += [f'<path d="{d}" class="th" stroke="{e.colour}" stroke-width="3.6" marker-end="url(#a)"/>',f'<text x="{mx}" y="{my}" class="t" font-size="11">{esc(e.op)}</text>']
  for k in range(2):
   begin=e.begin+k*e.dur/2.2;r=4.5 if k==0 else 3.2;o=1 if k==0 else .65
   out.append(f'<circle r="{r}" fill="{e.colour}" opacity="{o}" filter="url(#glow)"><animate attributeName="opacity" values="0;{o};{o};0" dur="{e.dur}s" begin="{begin}s" repeatCount="indefinite"/><animateMotion dur="{e.dur}s" begin="{begin}s" repeatCount="indefinite"><mpath href="#{e.id}" xlink:href="#{e.id}"/></animateMotion></circle>')
 for n in nodes:
  x,y=xy(n);out += [f'<g class="alive"><path class="n" d="{rr(x,y,132,52)}"/><rect x="{x+8}" y="{y+9}" width="5" height="34" rx="2" fill="{B[n.bundle]}"/><text x="{x+18}" y="{y+23}" class="t" font-size="15">{esc(n.label)}</text><text x="{x+18}" y="{y+39}" class="s" font-size="11">{esc(n.note)} · addr {n.bundle}</text></g>']
 out += [f'<path d="{rr(1235,32,500,176,18)}" fill="#0B1C33" stroke="#27537D"/><text x="1257" y="62" class="t" font-size="14">Visual grammar (operator-driven)</text>', '<text x="1259" y="88" class="s" font-size="12">strand = carrier lineage · split = refinement · merge = collapse</text><text x="1259" y="110" class="s" font-size="12">bundle = shared 3/6/9 prefix · loose fibre = residual</text><text x="1259" y="132" class="s" font-size="12">layers = distinct but stitched operator families</text>',f'<text x="72" y="956" class="s" font-size="12">Generated by scripts/materialize_dashi_hyperfabric.py · self-contained animated SVG prototype.</text></svg>']
 return '\n'.join(out)
if __name__=='__main__':
 out=Path('artifacts/dashi-hyperfabric-transport.svg');out.parent.mkdir(parents=True,exist_ok=True);out.write_text(generate(),encoding='utf-8');print(f'wrote {out}')
