module DASHI.Physics.Plasma.ToroidalGeodesicMagnetGeometrySearchExact where

open import DASHI.Core.Prelude
open import Agda.Builtin.String using (String)

import DASHI.Physics.Plasma.ToroidalConstantMagnitudeGeodesic3DEquilibriumExact as Geodesic
import DASHI.Physics.Plasma.TriadicPhaseConjugationControlExact as Phase
import DASHI.Physics.Plasma.TriadicPhaseFourierProjectorExact as Projector

------------------------------------------------------------------------
-- NUMERICAL 3-D MAGNET-GEOMETRY SEARCH OWNER
--
-- Candidate surfaces are shaped toroidal embeddings r(theta,zeta). A tangent
-- surface field is generated by a stream function chi so that the surface
-- divergence constraint is structural.  Search variables include C3-compatible
-- shape and stream harmonics.  The objective minimizes:
--
--   * variation of |B|,
--   * surface-tangential/geodesic curvature of field lines,
--   * numerical divergence residual,
--   * optional engineering regularization.
--
-- The C_(3^n) Fourier projector and C3 inversion/conjugation action are search
-- structure only.  Numerical optimization does not prove an exact 3-D MHD
-- equilibrium or a realizable external coil set.
------------------------------------------------------------------------

record ToroidalGeodesicGeometrySearchCandidate : Set₁ where
  constructor toroidal-geodesic-geometry-search-candidate
  field
    SurfaceParameter : Set
    StreamParameter : Set
    ObjectiveValue : Set

    toroidalEmbeddingReceipt : Set
    c3CompatibleShapeReceipt : Set
    streamFunctionTangentFieldReceipt : Set
    structuralSurfaceDivergenceReceipt : Set

    magneticMagnitudeVariationReceipt : Set
    geodesicCurvatureResidualReceipt : Set
    finiteAspectRatioReceipt : Set
    closedFieldLineOrTransformReceipt : Set

    phaseConjugation : Phase.TriadicConjugationControlReceipt
    phaseProjector : Projector.CyclicFourierProjectorReceipt

    numericalSolverReceipt : Set
    threeDimensionalPlotReceipt : Set
    candidateReference : String

open ToroidalGeodesicGeometrySearchCandidate public

record ToroidalGeodesicGeometryAcceptance
    (candidate : ToroidalGeodesicGeometrySearchCandidate) : Set₁ where
  constructor toroidal-geodesic-geometry-acceptance
  field
    nearConstantMagneticMagnitudeReceipt : Set
    geodesicResidualWithinBudgetReceipt : Set
    divergenceResidualWithinBudgetReceipt : Set
    zeroBounceBudgetReceipt : Set
    forceBalanceContinuationReceipt : Set
    coilInverseProblemReceipt : Set
    fullGuidingCentreOrbitReceipt : Set
    acceptanceReference : String

open ToroidalGeodesicGeometryAcceptance public

record ToroidalGeodesicSearchBoundary : Set where
  constructor toroidal-geodesic-search-boundary
  field
    numericalMinimumIsExactIsodynamicToroidalField : Bool
    numericalMinimumIsExactIsodynamicToroidalFieldIsFalse :
      numericalMinimumIsExactIsodynamicToroidalField ≡ false

    streamFunctionSurfaceDivergenceReplacesGlobalDivBProof : Bool
    streamFunctionSurfaceDivergenceReplacesGlobalDivBProofIsFalse :
      streamFunctionSurfaceDivergenceReplacesGlobalDivBProof ≡ false

    fieldLinePlotIsCoilGeometry : Bool
    fieldLinePlotIsCoilGeometryIsFalse :
      fieldLinePlotIsCoilGeometry ≡ false

    routeCSearchMayExposeNoGoOrTradeoff : Bool
    routeCSearchMayExposeNoGoOrTradeoffIsTrue :
      routeCSearchMayExposeNoGoOrTradeoff ≡ true

canonicalToroidalGeodesicSearchBoundary : ToroidalGeodesicSearchBoundary
canonicalToroidalGeodesicSearchBoundary =
  toroidal-geodesic-search-boundary
    false refl
    false refl
    false refl
    true refl

solverReference : String
solverReference =
  "scripts/toroidal_routeC_geometry_solver.py -- shaped torus + divergence-free tangent stream field + C3 harmonic search; produces 3-D field-line visualization and residual diagnostics."
