module DASHI.Algebra.Quantum.ShorFreeAmplitudePowModOracleExact where

open import DASHI.Core.Prelude
open import Relation.Binary.PropositionalEquality using (_≡_; refl)

import DASHI.Foundations.Base369Nat as B369
import DASHI.Algebra.Quantum.FiniteQuantumRegister as Finite
import DASHI.Algebra.Quantum.ShorReversiblePowModOracleExact as Graph
import DASHI.Algebra.Quantum.ShorAmplitudeExecutionPrefixExact as Prefix

------------------------------------------------------------------------
-- FREE SUPERPOSITION LIFT OF THE EXACT Q1 powMod GRAPH INVOLUTION
--
-- This owner closes one representation-level gap without pretending to have
-- analytic complex amplitudes.  `FreeAmplitude` is the free finite expression
-- syntax generated by basis kets, formal zero, formal binary superposition and
-- formal scalar-labelled weighting.  No quotient by vector-space laws, norm,
-- Born probability, complex phase or physical Hilbert semantics is claimed.
--
-- The useful theorem is structural: any involution on basis states lifts to an
-- involution on this superposition syntax.  Specialising that lift to Q1's
-- `powModGraphStep` yields an actual inhabitant of the existing
-- `ShorAmplitudeOracleWeld` and proves exact basis-state intertwining.
------------------------------------------------------------------------

data FreeAmplitude (GraphState : Set) : Set where
  zeroKet : FreeAmplitude GraphState
  basisKet : GraphState → FreeAmplitude GraphState
  weightKet : Nat → FreeAmplitude GraphState → FreeAmplitude GraphState
  superpose : FreeAmplitude GraphState → FreeAmplitude GraphState → FreeAmplitude GraphState

mapAmplitudeBasis :
  ∀ {A B : Set} →
  (A → B) →
  FreeAmplitude A →
  FreeAmplitude B
mapAmplitudeBasis f zeroKet = zeroKet
mapAmplitudeBasis f (basisKet x) = basisKet (f x)
mapAmplitudeBasis f (weightKet n ψ) =
  weightKet n (mapAmplitudeBasis f ψ)
mapAmplitudeBasis f (superpose ψ φ) =
  superpose (mapAmplitudeBasis f ψ) (mapAmplitudeBasis f φ)

mapAmplitudeBasisInvolutive :
  ∀ {A : Set} →
  (f : A → A) →
  (fInvolutive : ∀ x → f (f x) ≡ x) →
  (ψ : FreeAmplitude A) →
  mapAmplitudeBasis f (mapAmplitudeBasis f ψ) ≡ ψ
mapAmplitudeBasisInvolutive f involutive zeroKet = refl
mapAmplitudeBasisInvolutive f involutive (basisKet x)
  rewrite involutive x = refl
mapAmplitudeBasisInvolutive f involutive (weightKet n ψ)
  rewrite mapAmplitudeBasisInvolutive f involutive ψ = refl
mapAmplitudeBasisInvolutive f involutive (superpose ψ φ)
  rewrite mapAmplitudeBasisInvolutive f involutive ψ
        | mapAmplitudeBasisInvolutive f involutive φ = refl

record TaggedAmplitude (Basis GraphState : Set) : Set where
  constructor taggedAmplitude
  field
    classicalTag : Basis
    amplitudeSyntax : FreeAmplitude GraphState

open TaggedAmplitude public

graphBasis :
  ∀ {B : Finite.FiniteBasis}
    {base modulus : Nat}
    {modulusNonZero : B369.NonZero modulus} →
  Graph.PowModGraphState B base modulus modulusNonZero →
  Finite.Basis B
graphBasis (Graph.clean b) = b
graphBasis (Graph.loaded b value exact) = b

freeAmplitudeRegister :
  (B : Finite.FiniteBasis) →
  (base modulus : Nat) →
  (modulusNonZero : B369.NonZero modulus) →
  Finite.FiniteQuantumRegister B
freeAmplitudeRegister B base modulus modulusNonZero = record
  { State = TaggedAmplitude
      (Finite.Basis B)
      (Graph.PowModGraphState B base modulus modulusNonZero)
  ; prepare = λ b → taggedAmplitude b (basisKet (Graph.clean b))
  ; observe = classicalTag
  ; observePrepared = λ b → refl
  }

embedGraphBasis :
  (B : Finite.FiniteBasis) →
  (base modulus : Nat) →
  (modulusNonZero : B369.NonZero modulus) →
  Graph.PowModGraphState B base modulus modulusNonZero →
  Finite.State (freeAmplitudeRegister B base modulus modulusNonZero)
embedGraphBasis B base modulus modulusNonZero g =
  taggedAmplitude (graphBasis g) (basisKet g)

freeAmplitudeOracleStep :
  ∀ {B : Finite.FiniteBasis}
    {base modulus : Nat}
    {modulusNonZero : B369.NonZero modulus} →
  Finite.State (freeAmplitudeRegister B base modulus modulusNonZero) →
  Finite.State (freeAmplitudeRegister B base modulus modulusNonZero)
freeAmplitudeOracleStep (taggedAmplitude tag ψ) =
  taggedAmplitude tag
    (mapAmplitudeBasis Graph.powModGraphStep ψ)

freeAmplitudeOracleStepInvolutive :
  ∀ {B : Finite.FiniteBasis}
    {base modulus : Nat}
    {modulusNonZero : B369.NonZero modulus} →
  (ψ : Finite.State (freeAmplitudeRegister B base modulus modulusNonZero)) →
  freeAmplitudeOracleStep (freeAmplitudeOracleStep ψ) ≡ ψ
freeAmplitudeOracleStepInvolutive (taggedAmplitude tag ψ)
  rewrite mapAmplitudeBasisInvolutive
    Graph.powModGraphStep
    Graph.powModGraphStepInvolutive
    ψ = refl

freeAmplitudeOracleCircuit :
  (B : Finite.FiniteBasis) →
  (base modulus : Nat) →
  (modulusNonZero : B369.NonZero modulus) →
  Finite.ReversibleCircuit
    (freeAmplitudeRegister B base modulus modulusNonZero)
freeAmplitudeOracleCircuit B base modulus modulusNonZero = record
  { run = freeAmplitudeOracleStep
  ; reversible = record
      { inv = freeAmplitudeOracleStep
      ; left = freeAmplitudeOracleStepInvolutive
      ; right = freeAmplitudeOracleStepInvolutive
      }
  }

freeAmplitudeCleanEmbedsAsPrepared :
  (B : Finite.FiniteBasis) →
  (base modulus : Nat) →
  (modulusNonZero : B369.NonZero modulus) →
  (b : Finite.Basis B) →
  embedGraphBasis B base modulus modulusNonZero (Graph.clean b)
  ≡ Finite.prepare
      (freeAmplitudeRegister B base modulus modulusNonZero)
      b
freeAmplitudeCleanEmbedsAsPrepared B base modulus modulusNonZero b = refl

freeAmplitudeOracleIntertwines :
  (B : Finite.FiniteBasis) →
  (base modulus : Nat) →
  (modulusNonZero : B369.NonZero modulus) →
  (g : Graph.PowModGraphState B base modulus modulusNonZero) →
  Finite.run
    (freeAmplitudeOracleCircuit B base modulus modulusNonZero)
    (embedGraphBasis B base modulus modulusNonZero g)
  ≡ embedGraphBasis B base modulus modulusNonZero
      (Graph.powModGraphStep g)
freeAmplitudeOracleIntertwines B base modulus modulusNonZero (Graph.clean b) = refl
freeAmplitudeOracleIntertwines B base modulus modulusNonZero
  (Graph.loaded b value exact) = refl

freeAmplitudeOracleWeld :
  (B : Finite.FiniteBasis) →
  (base modulus : Nat) →
  (modulusNonZero : B369.NonZero modulus) →
  Prefix.ShorAmplitudeOracleWeld
    B base modulus modulusNonZero
    (freeAmplitudeRegister B base modulus modulusNonZero)
freeAmplitudeOracleWeld B base modulus modulusNonZero = record
  { embedGraphState = embedGraphBasis B base modulus modulusNonZero
  ; amplitudeOracle = freeAmplitudeOracleCircuit B base modulus modulusNonZero
  ; cleanEmbedsAsPrepared =
      freeAmplitudeCleanEmbedsAsPrepared B base modulus modulusNonZero
  ; oracleIntertwinesGraph =
      freeAmplitudeOracleIntertwines B base modulus modulusNonZero
  }

------------------------------------------------------------------------
-- Authority boundary.
------------------------------------------------------------------------

record FreeAmplitudePowModBoundary : Set where
  constructor freeAmplitudePowModBoundary
  field
    freeSuperpositionSyntaxConstructed : Bool
    q1GraphInvolutionLiftedStructurally : Bool
    amplitudeOracleWeldInhabited : Bool
    complexAmplitudeSemanticsClaimed : Bool
    vectorSpaceQuotientClaimed : Bool
    normalizationClaimed : Bool
    bornMeasurementClaimed : Bool
    cyclicQFTActionClaimed : Bool

canonicalFreeAmplitudePowModBoundary : FreeAmplitudePowModBoundary
canonicalFreeAmplitudePowModBoundary =
  freeAmplitudePowModBoundary
    true true true false false false false false
