module DASHI.Wikimedia.IbrahimMonster3BActualVOASelected3BCompositionExact where

open import DASHI.Core.Prelude
open import Agda.Primitive using (Setω)
open import Agda.Builtin.Bool using (Bool; false; true)
open import Agda.Builtin.String using (String)
open import Data.Empty using (⊥)

import DASHI.Core.AttributedSourceCore as Attribution
import DASHI.Core.SnowballAttributionProvenanceInvariantExact as Snowball
import DASHI.Moonshine.GradedVertexOperatorAlgebraBoundary as GVOA
import DASHI.Moonshine.MonsterGradedVOABridgeExact as Legacy
import DASHI.Moonshine.MonsterGradedVOALiteralActionSameObjectBidiExact as LiteralWeld
import DASHI.Moonshine.MonsterGradedVOASelected3BSameElementBidiExact as Selected
import DASHI.Moonshine.Base369Monster3BVOAActionPhaseAdapterBidiExact as Phase
import DASHI.Wikimedia.IbrahimMonster3BActualLinearMultiplicityAcquisitionExact as Acquisition
import DASHI.Wikimedia.IbrahimMonster3BLinearZetaSectorRestrictionExact as LinearZeta

------------------------------------------------------------------------
-- ACTUAL LITERAL VOA -> SELECTED 3B SAME-OBJECT COMPOSITION
--
-- The repo already owns the strongest first half of this seam in
-- `MonsterGradedVOASelected3BSameElementBidiExact`: its phase source must use
-- the exact literal MoonshineVOABridge already welded to the graded trace
-- authority, and its recognized source carries ActualZetaSectorRecognition on
-- the literal zeta eigensector generated by that same selected element.
--
-- Therefore this owner does NOT recreate a second bridge-equality interface.
-- It reuses `Selected3BRecognizedSameElementSource` and pays only the two
-- remaining cross-owner identity obligations:
--
--   * its welded literal VOA object is the acquisition's literalSameObjectWeld;
--   * compiling that recognized source through singleActionProducerFromVOA
--     gives exactly the single-action producer carried by linearZetaProducer.
--
-- This is identity/routing structure only.  It does not manufacture a
-- recognized source, action linearity, a normalizer-to-Monster embedding,
-- matrices, or a 12+78 intertwiner.
------------------------------------------------------------------------

------------------------------------------------------------------------
-- 1. Attribution / source roles.
------------------------------------------------------------------------

barracloughWilson : Attribution.AttributedSource
barracloughWilson = Attribution.mkDOISource
  "R. W. Barraclough; R. A. Wilson"
  "The Character Table of a Maximal Subgroup of the Monster"
  "LMS Journal of Computation and Mathematics 10, 161-175"
  "2007"
  "10.1112/S1461157000001352"
  "https://doi.org/10.1112/S1461157000001352"
  Attribution.academicArticleSource
  "primary representation-theoretic source for the 3B normalizer and inertia-character route; not authority for a repository same-object equality"
  Attribution.publicAttribution

borcherds : Attribution.AttributedSource
borcherds = Attribution.mkDOISource
  "Richard E. Borcherds"
  "Monstrous moonshine and monstrous Lie superalgebras"
  "Inventiones Mathematicae 109, 405-444"
  "1992"
  "10.1007/BF01232032"
  "https://doi.org/10.1007/BF01232032"
  Attribution.academicArticleSource
  "primary moonshine/VOA representation context; not authority for the repository's selected-3B same-object compiler equality"
  Attribution.publicAttribution

barracloughWilsonAttribution =
  Snowball.canonicalSourceRoleSnowballReceipt barracloughWilson
borcherdsAttribution =
  Snowball.canonicalSourceRoleSnowballReceipt borcherds

------------------------------------------------------------------------
-- 2. Reuse the existing recognized same-element package.
------------------------------------------------------------------------

recognizedActionSourceFromSameElement :
  ∀ {Monster K}
    (source : Selected.Selected3BRecognizedSameElementSource Monster K) →
  Phase.ActualMonster3BVOARecognizedActionSource
    Monster K
    (GVOA.group
      (Legacy.voaAction
        (LiteralWeld.gradedAuthority
          (Selected.weld (Selected.selectedSource source)))))
recognizedActionSourceFromSameElement source = record
  { phaseSource = Selected.phaseSource (Selected.selectedSource source)
  ; recognition = Selected.recognition source
  }

------------------------------------------------------------------------
-- 3. Typed composition into the actual linear-multiplicity acquisition.
------------------------------------------------------------------------

record ActualVOASelected3BComposition
    {Monster K : Set}
    (acquisition :
      Acquisition.ActualLinearMultiplicityAcquisition {Monster} {K}) : Setω where
  field
    recognizedSameElementSource :
      Selected.Selected3BRecognizedSameElementSource Monster K

    selectedWeldIsAcquisitionWeld :
      Selected.weld (Selected.selectedSource recognizedSameElementSource)
      ≡ Acquisition.literalSameObjectWeld acquisition

    compiledSingleActionProducerIsAcquisitionProducer :
      Phase.singleActionProducerFromVOA
        (recognizedActionSourceFromSameElement recognizedSameElementSource)
      ≡ LinearZeta.singleActionProducer
          (Acquisition.linearZetaProducer acquisition)

open ActualVOASelected3BComposition public

------------------------------------------------------------------------
-- 4. WrongType / non-promotion firewalls.
------------------------------------------------------------------------

data RecognizedSourceCreatesLinearity : Set where
data BridgeEqualityCreatesActionIntertwiner : Set where
data ProducerEqualityCreatesNormalizerEmbedding : Set where
data CharacterAuthorityCreatesRecognizedSource : Set where
data QidCreatesComposition : Set where
data DeweyCreatesComposition : Set where
data OeisCreatesComposition : Set where

recognizedSourceDoesNotCreateLinearity :
  RecognizedSourceCreatesLinearity → ⊥
recognizedSourceDoesNotCreateLinearity ()

bridgeEqualityDoesNotCreateActionIntertwiner :
  BridgeEqualityCreatesActionIntertwiner → ⊥
bridgeEqualityDoesNotCreateActionIntertwiner ()

producerEqualityDoesNotCreateNormalizerEmbedding :
  ProducerEqualityCreatesNormalizerEmbedding → ⊥
producerEqualityDoesNotCreateNormalizerEmbedding ()

characterAuthorityDoesNotCreateRecognizedSource :
  CharacterAuthorityCreatesRecognizedSource → ⊥
characterAuthorityDoesNotCreateRecognizedSource ()

qidDoesNotCreateComposition : QidCreatesComposition → ⊥
qidDoesNotCreateComposition ()

deweyDoesNotCreateComposition : DeweyCreatesComposition → ⊥
deweyDoesNotCreateComposition ()

oeisDoesNotCreateComposition : OeisCreatesComposition → ⊥
oeisDoesNotCreateComposition ()

------------------------------------------------------------------------
-- 5. DOI / QID / Dewey / OEIS remain descriptive coordinates only.
------------------------------------------------------------------------

record ActualVOASelected3BExternalCoordinates : Set where
  constructor actual-voa-selected3b-external-coordinates
  field
    groupRepresentationQid : String
    representationCharacterQid : String
    finiteGroupQid : String
    groupRepresentationDewey : String
    finiteGroupDewey : String
    oeisCoordinate : String
    oeisHasCompositionAuthority : Bool
open ActualVOASelected3BExternalCoordinates public

canonicalActualVOASelected3BExternalCoordinates :
  ActualVOASelected3BExternalCoordinates
canonicalActualVOASelected3BExternalCoordinates =
  actual-voa-selected3b-external-coordinates
    "Q1055807"
    "Q600043"
    "Q1057968"
    "512.22"
    "512.23"
    "A005052 remains numerical provenance for 90 = 10*3^2 only; it has no same-object, selected-3B, action, matrix, or intertwiner authority"
    false

------------------------------------------------------------------------
-- 6. Pareto frontier.
------------------------------------------------------------------------

record ActualVOASelected3BCompositionFrontier : Set where
  constructor actual-voa-selected3b-composition-frontier
  field
    literalCharacterActionWeldAlreadyOwned : Bool
    selectedSameElementBridgeWeldAlreadyOwned : Bool
    recognizedZetaSectorPackageAlreadyTyped : Bool
    selected3BLinearProducerAlreadyNamed : Bool
    selectedWeldAcquisitionEqualityRequired : Bool
    sameCompiledSingleActionProducerEqualityRequired : Bool
    recognizedSourceInhabitedHere : Bool
    normalizerMonsterActionWeldPaidHere : Bool
    twelveSeventyEightIntertwinerPaidHere : Bool
    nextResidual : String
open ActualVOASelected3BCompositionFrontier public

currentActualVOASelected3BCompositionFrontier :
  ActualVOASelected3BCompositionFrontier
currentActualVOASelected3BCompositionFrontier =
  actual-voa-selected3b-composition-frontier
    true true true true true true
    false false false
    "locate or construct a Selected3BRecognizedSameElementSource whose weld is literally the acquisition literalSameObjectWeld. The existing same-element owner already forces its phase source onto that literal bridge and carries ActualZetaSectorRecognition. Then prove singleActionProducerFromVOA for that recognized source equals the producer inside linearZetaProducer. After those two identity payments, the next theorem-bearing leaf is the existing Selected3BNormalizerMonsterActionWeld: supply normalizerToMonster and prove the transported 196883 Monster action equals the selected normalizer action. DOI/QID/Dewey/OEIS and character values cannot create any of these receipts."
