module DASHI.Mathematics.Algebra.RationalAlbertKnownGeneratorFamilyExact where

------------------------------------------------------------------------
-- KNOWN SAME-CARRIER ALBERT AUTOMORPHISM GENERATOR FAMILY
--
-- Cross-pollinates the three independently developed automorphism lanes on
-- the literal RationalAlbert carrier:
--   * S3 coordinate cycle/transposition;
--   * two diagonal lifts of explicit signed-basis octonion automorphisms;
--   * one non-diagonal Moufang triality automorphism.
--
-- Every selected map now has an explicit two-sided inverse and preserves the
-- SAME Jordan product and cubic norm.  The remaining F4 theorem is therefore
-- no longer "find nontrivial automorphisms"; it is a generation/type-
-- recognition theorem for the subgroup generated by these maps and, more
-- generally, the full Spin(8) triality family.
------------------------------------------------------------------------

open import Agda.Builtin.Bool using (Bool; true; false)
open import Agda.Builtin.Equality using (_≡_; refl)
open import Agda.Builtin.Nat using (Nat)

import DASHI.Mathematics.Algebra.RationalAlbertHermitianCubicExact as A
import DASHI.Mathematics.Algebra.RationalAlbertJordanProductExact as J
import DASHI.Mathematics.Algebra.RationalAlbertJordanLawsExact as Laws
import DASHI.Mathematics.Algebra.RationalAlbertS3AutomorphismExact as S3
import DASHI.Mathematics.Algebra.RationalAlbertS3AutomorphismLawsExact as S3Laws
import DASHI.Mathematics.Algebra.RationalOctonionSignedBasisAutomorphismExact as G2F
import DASHI.Mathematics.Algebra.RationalAlbertSignedBasisG2SubgroupExact as G2
import DASHI.Mathematics.Algebra.RationalAlbertMoufangTrialityAutomorphismExact as T

data KnownAlbertGenerator : Set where
  coordinateCycle coordinateSwap : KnownAlbertGenerator
  signedBasisA signedBasisB : KnownAlbertGenerator
  selectedMoufangTriality : KnownAlbertGenerator

knownGeneratorCount : Nat
knownGeneratorCount = 5

act : KnownAlbertGenerator → A.RationalAlbert → A.RationalAlbert
act coordinateCycle = S3.cycleA
act coordinateSwap = S3.swapA
act signedBasisA = G2.liftA
act signedBasisB = G2.liftB
act selectedMoufangTriality = T.trialityA

inverseAct : KnownAlbertGenerator → A.RationalAlbert → A.RationalAlbert
inverseAct coordinateCycle = S3.cycleSquared
inverseAct coordinateSwap = S3.swapA
inverseAct signedBasisA = G2.liftA
inverseAct signedBasisB = λ x → G2.liftB (G2.liftB x)
inverseAct selectedMoufangTriality = T.trialityInverseA

inverseLeft : (g : KnownAlbertGenerator) → (x : A.RationalAlbert) →
  inverseAct g (act g x) ≡ x
inverseLeft coordinateCycle x = S3.cycleCubedIdentity x
inverseLeft coordinateSwap x = S3.swapSquaredIdentity x
inverseLeft signedBasisA (A.albert a b c x y z) =
  Laws.albertExt refl refl refl
    (G2F.autoASquaredIdentity x)
    (G2F.autoASquaredIdentity y)
    (G2F.autoASquaredIdentity z)
inverseLeft signedBasisB (A.albert a b c x y z) =
  Laws.albertExt refl refl refl
    (G2F.autoBCubedIdentity x)
    (G2F.autoBCubedIdentity y)
    (G2F.autoBCubedIdentity z)
inverseLeft selectedMoufangTriality = T.trialityInverseLeft

inverseRight : (g : KnownAlbertGenerator) → (x : A.RationalAlbert) →
  act g (inverseAct g x) ≡ x
inverseRight coordinateCycle x = S3.cycleCubedIdentity x
inverseRight coordinateSwap x = S3.swapSquaredIdentity x
inverseRight signedBasisA (A.albert a b c x y z) =
  Laws.albertExt refl refl refl
    (G2F.autoASquaredIdentity x)
    (G2F.autoASquaredIdentity y)
    (G2F.autoASquaredIdentity z)
inverseRight signedBasisB (A.albert a b c x y z) =
  Laws.albertExt refl refl refl
    (G2F.autoBCubedIdentity x)
    (G2F.autoBCubedIdentity y)
    (G2F.autoBCubedIdentity z)
inverseRight selectedMoufangTriality = T.trialityInverseRight

PreservesJordan : KnownAlbertGenerator → Set
PreservesJordan g =
  (x y : A.RationalAlbert) →
    act g (J.jordanProduct x y)
    ≡ J.jordanProduct (act g x) (act g y)

PreservesCubic : KnownAlbertGenerator → Set
PreservesCubic g =
  (x : A.RationalAlbert) → A.cubicNorm (act g x) ≡ A.cubicNorm x

knownGeneratorPreservesJordan : (g : KnownAlbertGenerator) → PreservesJordan g
knownGeneratorPreservesJordan coordinateCycle = S3Laws.cyclePreservesProduct
knownGeneratorPreservesJordan coordinateSwap = S3Laws.swapPreservesProduct
knownGeneratorPreservesJordan signedBasisA = G2.liftAPreservesProduct
knownGeneratorPreservesJordan signedBasisB = G2.liftBPreservesProduct
knownGeneratorPreservesJordan selectedMoufangTriality = T.trialityPreservesProduct

knownGeneratorPreservesCubic : (g : KnownAlbertGenerator) → PreservesCubic g
knownGeneratorPreservesCubic coordinateCycle = S3Laws.cyclePreservesCubic
knownGeneratorPreservesCubic coordinateSwap = S3Laws.swapPreservesCubic
knownGeneratorPreservesCubic signedBasisA = G2.liftAPreservesCubic
knownGeneratorPreservesCubic signedBasisB = G2.liftBPreservesCubic
knownGeneratorPreservesCubic selectedMoufangTriality = T.trialityPreservesCubic

------------------------------------------------------------------------
-- Exact next recognition seam.
--
-- This is intentionally stronger than a carrier/order receipt: it requires a
-- literal group, a literal action on the same Albert carrier, exact agreement
-- with all five already-owned generator maps, and inhabited generation/type
-- recognition receipts.
------------------------------------------------------------------------

record F4GenerationReceipt : Set₁ where
  field
    GeneratedGroup : Set
    identityG : GeneratedGroup
    multiplyG : GeneratedGroup → GeneratedGroup → GeneratedGroup
    inverseG : GeneratedGroup → GeneratedGroup

    associativityG : (a b c : GeneratedGroup) →
      multiplyG (multiplyG a b) c ≡ multiplyG a (multiplyG b c)
    leftIdentityG : (a : GeneratedGroup) → multiplyG identityG a ≡ a
    rightIdentityG : (a : GeneratedGroup) → multiplyG a identityG ≡ a
    leftInverseG : (a : GeneratedGroup) → multiplyG (inverseG a) a ≡ identityG
    rightInverseG : (a : GeneratedGroup) → multiplyG a (inverseG a) ≡ identityG

    actionG : GeneratedGroup → A.RationalAlbert → A.RationalAlbert
    actionIdentity : (x : A.RationalAlbert) → actionG identityG x ≡ x
    actionMultiply : (g h : GeneratedGroup) → (x : A.RationalAlbert) →
      actionG (multiplyG g h) x ≡ actionG g (actionG h x)

    containsKnownGenerator : KnownAlbertGenerator → GeneratedGroup
    knownGeneratorActionAgrees : (g : KnownAlbertGenerator) →
      (x : A.RationalAlbert) →
      actionG (containsKnownGenerator g) x ≡ act g x

    GeneratedByKnownAndTrialityProperty : Set
    generatedByKnownAndTriality : GeneratedByKnownAndTrialityProperty

    EveryGeneratedElementPreservesJordanProperty : Set
    everyGeneratedElementPreservesJordan :
      EveryGeneratedElementPreservesJordanProperty
    EveryGeneratedElementPreservesCubicProperty : Set
    everyGeneratedElementPreservesCubic :
      EveryGeneratedElementPreservesCubicProperty

    FullSpin8TrialityContainedProperty : Set
    fullSpin8TrialityContained : FullSpin8TrialityContainedProperty
    F4RootDatumRecognitionProperty : Set
    f4RootDatumRecognition : F4RootDatumRecognitionProperty
    EveryAlbertAutomorphismGeneratedProperty : Set
    everyAlbertAutomorphismGenerated : EveryAlbertAutomorphismGeneratedProperty

open F4GenerationReceipt public

record KnownGeneratorBoundary : Set where
  constructor known-generator-boundary
  field
    knownGeneratorCountRecorded : Nat
    allKnownGeneratorsBijective : Bool
    allKnownGeneratorsProductPreserving : Bool
    allKnownGeneratorsCubicPreserving : Bool
    diagonalSignedBasisSubgroupOrder : Nat
    nonDiagonalTrialityGeneratorPaid : Bool
    fullSpin8TrialityFamilyPaid : Bool
    f4GenerationRecognitionPaid : Bool

open KnownGeneratorBoundary public

canonicalKnownGeneratorBoundary : KnownGeneratorBoundary
canonicalKnownGeneratorBoundary =
  known-generator-boundary
    5 true true true 1344 true false false
