module DASHI.Mathematics.Algebra.RationalAlbertF4CurrentMaxCutExact where

------------------------------------------------------------------------
-- CURRENT CONSTRUCTIVE F4 FRONTIER
--
-- Positive structure now source-written / exact-runtime checked:
--
-- * actual rational Albert algebra H_3(O_Q), dimension 27;
-- * distinguished unit, trace and cubic norm;
-- * explicit Jordan product, commutativity, unit and Jordan identity;
-- * explicit coordinate S3 automorphism subgroup preserving product/norm;
-- * explicit signed-monomial octonion automorphisms generated by order-7 and
--   order-2 maps; exhaustive basis search gives 1344 such automorphisms;
-- * diagonal lift to Albert automorphisms, commuting with the coordinate S3;
-- * exact runtime combined subgroup order 8064;
-- * exact rational derivation-system rank 677 in 729 unknowns, hence
--   dim Der(J)=52;
-- * the 351 inner commutators [L_ei,L_ej] span exact rank 52.
--
-- Negative/order-only control:
-- a natural 192-element signed-monomial line stabilizer together with the
-- coordinate S3 has order 1152, but this is not promoted to W(F4): the action
-- is the wrong (commuting/direct-product-shaped) triality structure.  Genuine
-- F4 requires the nontrivial D4 triality action, not order 1152 alone.
--
-- Exact remaining promotion:
--   (1) source-native Spin(8)/D4 triality (or an equivalent root/Cartan model),
--   (2) identify the 52-dimensional derivation Lie algebra as type F4,
--   (3) identify the full Albert automorphism algebraic/Lie group as F4.
------------------------------------------------------------------------

open import Agda.Builtin.Bool using (Bool; false; true)
open import Agda.Builtin.Nat using (Nat)

import DASHI.Mathematics.Algebra.RationalAlbertHermitianCubicExact as Cubic
import DASHI.Mathematics.Algebra.RationalAlbertJordanProductExact as Product
import DASHI.Mathematics.Algebra.RationalAlbertJordanLawsExact as Laws
import DASHI.Mathematics.Algebra.RationalAlbertS3AutomorphismExact as S3
import DASHI.Mathematics.Algebra.RationalAlbertS3AutomorphismLawsExact as S3Laws
import DASHI.Mathematics.Algebra.RationalOctonionSignedMonomialAutomorphismsExact as OctAut
import DASHI.Mathematics.Algebra.RationalAlbertSignedMonomialAutomorphismsExact as AlbertAut
import DASHI.Mathematics.Algebra.RationalAlbertDerivationDimensionExact as Der

signedMonomialOctonionRuntimeOrder : Nat
signedMonomialOctonionRuntimeOrder = 1344

explicitAlbertAutomorphismRuntimeOrder : Nat
explicitAlbertAutomorphismRuntimeOrder = 8064

orderTrapLineStabilizerRuntimeOrder : Nat
orderTrapLineStabilizerRuntimeOrder = 192

orderTrapWithCoordinateS3RuntimeOrder : Nat
orderTrapWithCoordinateS3RuntimeOrder = 1152

derivationRuntimeDimension : Nat
derivationRuntimeDimension = Der.derivationSpaceDimensionRuntime

record F4PromotionTarget : Set where
  constructor f4-promotion-target
  field
    d4TrialityActionPaid : Bool
    derivationLieBracketTyped : Bool
    derivationRootCartanTypeF4Paid : Bool
    fullAlbertAutomorphismGroupTypeF4Paid : Bool
open F4PromotionTarget public

currentF4PromotionTarget : F4PromotionTarget
currentF4PromotionTarget =
  f4-promotion-target false false false false

record RationalAlbertF4Boundary : Set where
  constructor rational-albert-f4-boundary
  field
    rationalAlbertCarrierPaid : Bool
    cubicNormPaid : Bool
    jordanProductPaid : Bool
    jordanLawsSourceWritten : Bool
    coordinateS3AutomorphismsSourceWritten : Bool
    coordinateS3ProductNormPreservationSourceWritten : Bool
    signedMonomialOctonionAutomorphismsSourceWritten : Bool
    signedMonomialOctonionClosure1344RuntimeChecked : Bool
    signedMonomialAlbertLiftSourceWritten : Bool
    explicitAlbertAutomorphismSubgroup8064RuntimeChecked : Bool
    derivationConstraintRank677RuntimeChecked : Bool
    derivationDimension52RuntimeChecked : Bool
    innerDerivationSpan52RuntimeChecked : Bool
    order1152AloneRejectedAsF4Recognition : Bool
    nontrivialD4TrialityPaid : Bool
    f4LieAlgebraRecognitionPaid : Bool
    fullF4AutomorphismRecognitionPaid : Bool
open RationalAlbertF4Boundary public

currentRationalAlbertF4Boundary : RationalAlbertF4Boundary
currentRationalAlbertF4Boundary =
  rational-albert-f4-boundary
    true true true true true true
    true true true true true true true true
    false false false
