module DASHI.Mathematics.Algebra.RationalAlbertF4CurrentMaxCutExact where

------------------------------------------------------------------------
-- CURRENT RATIONAL ALBERT / F4 MAX-CUT
--
-- Paid/source-written in this branch:
--
-- * exact rational octonions with multiplication, conjugation, norm,
--   alternativity/flexibility and explicit nonassociativity;
-- * rational Albert carrier H_3(O_Q) with 27 coordinates, identity, trace and
--   cubic determinant/norm;
-- * explicit symmetrised Jordan product;
-- * source-written commutativity, unit and Jordan-identity proofs;
-- * explicit S3 coordinate automorphism subgroup preserving product/norm;
-- * literal standard octonion derivation operator D(a,b);
-- * exact companion computation: 21 imaginary-basis D(e_i,e_j) span rank 14;
-- * exact signed-basis octonion automorphism group of order 1344 generated by
--   explicit order-7 and order-4 maps;
-- * literal Albert inner derivations [L_X,L_Y];
-- * exact companion computation: 351 basis-pair inner derivations span rank 52
--   and satisfy the derivation law on the full 27-coordinate basis;
-- * exact negative trace form rank 52 / positive LDL pivots, center zero, and
--   a regular centralizer of dimension 4 (last rank numerically diagnosed).
--
-- Companion Lean independently owns the standard F4 root datum: 48 roots,
-- rank 4, standard Cartan/Coxeter action and Weyl-order diagnostic 1152.
--
-- The remaining theorem is NOT another cardinality match.  It is the explicit
-- classification/same-Lie-algebra bridge between the concrete rational Albert
-- derivation algebra and the appropriate rational/real form of Lie type F4,
-- followed by the corresponding algebraic-group automorphism recognition.
------------------------------------------------------------------------

open import Agda.Builtin.Bool using (Bool; false; true)
open import Agda.Builtin.Nat using (Nat)

import DASHI.Mathematics.Algebra.RationalAlbertHermitianCubicExact as Cubic
import DASHI.Mathematics.Algebra.RationalAlbertJordanProductExact as Product
import DASHI.Mathematics.Algebra.RationalAlbertJordanLawsExact as Laws
import DASHI.Mathematics.Algebra.RationalAlbertS3AutomorphismExact as S3
import DASHI.Mathematics.Algebra.RationalAlbertS3AutomorphismLawsExact as S3Laws
import DASHI.Mathematics.Algebra.RationalOctonionG2DerivationExact as G2
import DASHI.Mathematics.Algebra.RationalAlbertF4DerivationExact as F4D

record F4CrossKernelReceipt : Set where
  constructor f4-cross-kernel-receipt
  field
    f4RootCount : Nat
    f4Rank : Nat
    f4WeylOrderDiagnostic : Nat
    albertDerivationRank : Nat
    octonionDerivationRank : Nat
    regularCentralizerDimension : Nat
    centerDimension : Nat
    negativeTraceFormPositive : Bool
open F4CrossKernelReceipt public

canonicalF4CrossKernelReceipt : F4CrossKernelReceipt
canonicalF4CrossKernelReceipt =
  f4-cross-kernel-receipt 48 4 1152 52 14 4 0 true

record CurrentF4Boundary : Set where
  constructor current-f4-boundary
  field
    rationalAlbertCarrierPaid : Bool
    cubicNormPaid : Bool
    jordanProductPaid : Bool
    jordanIdentitySourceWritten : Bool
    explicitS3AutomorphismSubgroupPaid : Bool
    standardOctonionDerivationOperatorPaid : Bool
    exactG2Rank14DiagnosticPaid : Bool
    signedBasisAutomorphism1344DiagnosticPaid : Bool
    literalAlbertInnerDerivationOperatorPaid : Bool
    exactAlbertDerivationRank52DiagnosticPaid : Bool
    exactTraceFormCompactnessDiagnosticsPaid : Bool
    independentF4Root48LeanReceiptPaid : Bool
    independentF4Rank4LeanReceiptPaid : Bool
    sameLieAlgebraF4ClassificationPaid : Bool
    rationalFormClassificationPaid : Bool
    fullF4AutomorphismGroupPaid : Bool
open CurrentF4Boundary public

currentF4Boundary : CurrentF4Boundary
currentF4Boundary =
  current-f4-boundary
    true true true true true
    true true true true true true
    true true
    false false false
