module DASHI.Mathematics.Algebra.RationalAlbertKnownGeneratorFamilyExact where

------------------------------------------------------------------------
-- KNOWN SAME-CARRIER ALBERT GENERATOR FAMILY
--
-- Cross-pollinates the three independently developed automorphism lanes on
-- the literal RationalAlbert carrier:
--   * S3 coordinate cycle/transposition;
--   * two diagonal lifts of explicit signed-basis octonion automorphisms;
--   * one non-diagonal Moufang triality transformation.
--
-- Every generator is proved to preserve the SAME Jordan product and cubic
-- norm.  The remaining F4 theorem is therefore no longer "find nontrivial
-- automorphisms"; it is a generation/type-recognition theorem for the group
-- generated by these and/or the full Spin(8) triality family.
------------------------------------------------------------------------

open import Agda.Builtin.Bool using (Bool; true; false)
open import Agda.Builtin.Equality using (_≡_)
open import Agda.Builtin.Nat using (Nat)

import DASHI.Mathematics.Algebra.RationalAlbertHermitianCubicExact as A
import DASHI.Mathematics.Algebra.RationalAlbertJordanProductExact as J
import DASHI.Mathematics.Algebra.RationalAlbertS3AutomorphismExact as S3
import DASHI.Mathematics.Algebra.RationalAlbertS3AutomorphismLawsExact as S3Laws
import DASHI.Mathematics.Algebra.RationalAlbertSignedBasisG2SubgroupExact as G2
import DASHI.Mathematics.Algebra.RationalAlbertMoufangTrialityAutomorphismExact as T

data KnownAlbertGenerator : Set where
  coordinateCycle coordinateSwap : KnownAlbertGenerator
  signedBasisA signedBasisB : KnownAlbertGenerator
  selectedMoufangTriality : KnownAlbertGenerator

knownGeneratorCount : Nat
knownGeneratorCount = 5

act : KnownAlbertGenerator → A.RationalAlbert → A.RationalAlbert
act coordinateCycle = S3.cycleA
act coordinateSwap = S3.swapA
act signedBasisA = G2.liftA
act signedBasisB = G2.liftB
act selectedMoufangTriality = T.trialityA

PreservesJordan : KnownAlbertGenerator → Set
PreservesJordan g =
  (x y : A.RationalAlbert) →
    act g (J.jordanProduct x y)
    ≡ J.jordanProduct (act g x) (act g y)

PreservesCubic : KnownAlbertGenerator → Set
PreservesCubic g =
  (x : A.RationalAlbert) → A.cubicNorm (act g x) ≡ A.cubicNorm x

knownGeneratorPreservesJordan : (g : KnownAlbertGenerator) → PreservesJordan g
knownGeneratorPreservesJordan coordinateCycle = S3Laws.cyclePreservesProduct
knownGeneratorPreservesJordan coordinateSwap = S3Laws.swapPreservesProduct
knownGeneratorPreservesJordan signedBasisA = G2.liftAPreservesProduct
knownGeneratorPreservesJordan signedBasisB = G2.liftBPreservesProduct
knownGeneratorPreservesJordan selectedMoufangTriality = T.trialityPreservesProduct

knownGeneratorPreservesCubic : (g : KnownAlbertGenerator) → PreservesCubic g
knownGeneratorPreservesCubic coordinateCycle = S3Laws.cyclePreservesCubic
knownGeneratorPreservesCubic coordinateSwap = S3Laws.swapPreservesCubic
knownGeneratorPreservesCubic signedBasisA = G2.liftAPreservesCubic
knownGeneratorPreservesCubic signedBasisB = G2.liftBPreservesCubic
knownGeneratorPreservesCubic selectedMoufangTriality = T.trialityPreservesCubic

------------------------------------------------------------------------
-- Exact next recognition seam.
------------------------------------------------------------------------

record F4GenerationReceipt : Set₁ where
  field
    GeneratedGroup : Set
    containsKnownGenerator : KnownAlbertGenerator → GeneratedGroup
    everyGeneratedElementActsOnAlbert : GeneratedGroup → A.RationalAlbert → A.RationalAlbert
    everyGeneratedElementPreservesJordan : Set
    everyGeneratedElementPreservesCubic : Set
    fullSpin8TrialityContained : Set
    f4RootDatumRecognition : Set
    everyAlbertAutomorphismGenerated : Set

open F4GenerationReceipt public

record KnownGeneratorBoundary : Set where
  constructor known-generator-boundary
  field
    knownGeneratorCountRecorded : Nat
    allKnownGeneratorsProductPreserving : Bool
    allKnownGeneratorsCubicPreserving : Bool
    diagonalSignedBasisSubgroupOrder : Nat
    nonDiagonalTrialityGeneratorPaid : Bool
    fullSpin8TrialityFamilyPaid : Bool
    f4GenerationRecognitionPaid : Bool

open KnownGeneratorBoundary public

canonicalKnownGeneratorBoundary : KnownGeneratorBoundary
canonicalKnownGeneratorBoundary =
  known-generator-boundary
    5 true true 1344 true false false
