module DASHI.Mathematics.Algebra.RationalAlbertAutomorphismClosureExact where

------------------------------------------------------------------------
-- PROOF-BEARING CLOSURE OF THE KNOWN ALBERT AUTOMORPHISMS
--
-- The previous tranche owns five explicit automorphisms on the SAME rational
-- Albert carrier.  This owner removes closure plumbing from the F4 frontier:
-- identity, composition and inversion preserve bijectivity, Jordan product and
-- cubic norm, and arbitrary generator words compile to an actual
-- `AlbertAutomorphism` receipt.
--
-- This is still the subgroup generated by the known maps.  It does not prove
-- that the generated subgroup is all of F4 or identify its root datum.
------------------------------------------------------------------------

open import Agda.Builtin.Equality using (_≡_; refl)
open import Relation.Binary.PropositionalEquality using (cong; sym; trans)

import DASHI.Mathematics.Algebra.RationalAlbertHermitianCubicExact as A
import DASHI.Mathematics.Algebra.RationalAlbertJordanProductExact as J
import DASHI.Mathematics.Algebra.RationalAlbertKnownGeneratorFamilyExact as G

record AlbertAutomorphism : Set where
  field
    forward backward : A.RationalAlbert → A.RationalAlbert
    backwardForward : (x : A.RationalAlbert) → backward (forward x) ≡ x
    forwardBackward : (x : A.RationalAlbert) → forward (backward x) ≡ x
    preservesJordan : (x y : A.RationalAlbert) →
      forward (J.jordanProduct x y)
      ≡ J.jordanProduct (forward x) (forward y)
    preservesCubic : (x : A.RationalAlbert) →
      A.cubicNorm (forward x) ≡ A.cubicNorm x

open AlbertAutomorphism public

identityAutomorphism : AlbertAutomorphism
identityAutomorphism = record
  { forward = λ x → x
  ; backward = λ x → x
  ; backwardForward = λ x → refl
  ; forwardBackward = λ x → refl
  ; preservesJordan = λ x y → refl
  ; preservesCubic = λ x → refl
  }

composeAutomorphism : AlbertAutomorphism → AlbertAutomorphism → AlbertAutomorphism
composeAutomorphism first second = record
  { forward = λ x → forward first (forward second x)
  ; backward = λ x → backward second (backward first x)
  ; backwardForward = λ x →
      trans
        (cong (backward second) (backwardForward first (forward second x)))
        (backwardForward second x)
  ; forwardBackward = λ x →
      trans
        (cong (forward first) (forwardBackward second (backward first x)))
        (forwardBackward first x)
  ; preservesJordan = λ x y →
      trans
        (cong (forward first) (preservesJordan second x y))
        (preservesJordan first (forward second x) (forward second y))
  ; preservesCubic = λ x →
      trans
        (preservesCubic first (forward second x))
        (preservesCubic second x)
  }

forwardInjective :
  (automorphism : AlbertAutomorphism) →
  {x y : A.RationalAlbert} →
  forward automorphism x ≡ forward automorphism y → x ≡ y
forwardInjective automorphism {x} {y} equality =
  trans
    (sym (backwardForward automorphism x))
    (trans
      (cong (backward automorphism) equality)
      (backwardForward automorphism y))

backwardPreservesJordan :
  (automorphism : AlbertAutomorphism) →
  (x y : A.RationalAlbert) →
  backward automorphism (J.jordanProduct x y)
  ≡ J.jordanProduct (backward automorphism x) (backward automorphism y)
backwardPreservesJordan automorphism x y =
  forwardInjective automorphism equality
  where
    equality :
      forward automorphism
        (backward automorphism (J.jordanProduct x y))
      ≡ forward automorphism
        (J.jordanProduct (backward automorphism x) (backward automorphism y))
    equality
      rewrite forwardBackward automorphism (J.jordanProduct x y)
            | preservesJordan automorphism
                (backward automorphism x) (backward automorphism y)
            | forwardBackward automorphism x
            | forwardBackward automorphism y
      = refl

backwardPreservesCubic :
  (automorphism : AlbertAutomorphism) →
  (x : A.RationalAlbert) →
  A.cubicNorm (backward automorphism x) ≡ A.cubicNorm x
backwardPreservesCubic automorphism x =
  trans
    (sym (preservesCubic automorphism (backward automorphism x)))
    (cong A.cubicNorm (forwardBackward automorphism x))

inverseAutomorphism : AlbertAutomorphism → AlbertAutomorphism
inverseAutomorphism automorphism = record
  { forward = backward automorphism
  ; backward = forward automorphism
  ; backwardForward = forwardBackward automorphism
  ; forwardBackward = backwardForward automorphism
  ; preservesJordan = backwardPreservesJordan automorphism
  ; preservesCubic = backwardPreservesCubic automorphism
  }

knownAutomorphism : G.KnownAlbertGenerator → AlbertAutomorphism
knownAutomorphism generator = record
  { forward = G.act generator
  ; backward = G.inverseAct generator
  ; backwardForward = G.inverseLeft generator
  ; forwardBackward = G.inverseRight generator
  ; preservesJordan = G.knownGeneratorPreservesJordan generator
  ; preservesCubic = G.knownGeneratorPreservesCubic generator
  }

------------------------------------------------------------------------
-- Free expression syntax for the actually generated same-carrier action.
------------------------------------------------------------------------

data AutomorphismWord : Set where
  identityWord : AutomorphismWord
  generatorWord : G.KnownAlbertGenerator → AutomorphismWord
  composeWord : AutomorphismWord → AutomorphismWord → AutomorphismWord
  inverseWord : AutomorphismWord → AutomorphismWord

compileWord : AutomorphismWord → AlbertAutomorphism
compileWord identityWord = identityAutomorphism
compileWord (generatorWord generator) = knownAutomorphism generator
compileWord (composeWord left right) =
  composeAutomorphism (compileWord left) (compileWord right)
compileWord (inverseWord word) = inverseAutomorphism (compileWord word)
