module DASHI.Core.InstitutionalNormProductionEverything where

import DASHI.Core.InstitutionalNormProductionExact
import DASHI.Core.InstitutionalNormProductionRegression
import DASHI.Core.FragmentationCompositionExact
import DASHI.Core.FragmentationCompositionRegression
import DASHI.Core.ObserverSituatedReasonablenessExact
import DASHI.Core.ObserverSituatedReasonablenessRegression

import DASHI.Core.GenderedNormApprovalIndependenceExact
import DASHI.Core.GenderedNormApprovalSourceExact
import DASHI.Core.GenderedNormApprovalRegression

import DASHI.Core.GenderedApprovalObjectiveRechartExact
import DASHI.Core.GenderedApprovalObjectiveRechartRegression
