module DASHI.Core.PluralEpistemicRevisionBackpropagationEverything where

import DASHI.Core.ExperimentalOutcomeOrientationBackpropagationBidiExact
import DASHI.Core.OrientationCompassExperimentalInterpretationBidiExact
import DASHI.Core.ArgumentResponseNonGeometricOppositeBidiExact
import DASHI.Core.DependencySensitiveClosureReopeningBidiExact
import DASHI.Core.DependencyGraphResultBackpropagationBidiExact
import DASHI.Core.SequentialOutcomeBackpropagationBidiExact

import DASHI.Core.DiagnosisFibreSalienceSchedulerBidiExact
import DASHI.Core.DiagnosisExperimentPortfolioBidiExact
import DASHI.Core.DependencyWeightedDiagnosisSchedulerBidiExact
import DASHI.Core.SequentialDiagnosisDebugLoopBidiExact
import DASHI.Core.ArgumentDiagnosisDebuggingBidiExact
import DASHI.Governance.GovernanceDiagnosisRepairSchedulerBidiExact
import DASHI.Core.RuntimeDiagnosisRepairSchedulerBidiExact
import DASHI.Cognition.PNF.SensibLawDiagnosisRepairSchedulerBidiExact
import DASHI.Biology.DrosophilaDiagnosisRepairSchedulerBidiExact

import DASHI.Core.TemporalDiagnosisProvenanceHistoryBidiExact
import DASHI.Core.TemporalDiagnosisFibreProjectionBidiExact
import DASHI.Core.TemporalDiagnosisHotColdProjectionBidiExact
import DASHI.Core.TemporalDiagnosisSalienceRecalibrationBidiExact
import DASHI.Core.SequentialTemporalDiagnosisRevisionLoopBidiExact
import DASHI.Core.ArgumentTemporalDiagnosisHistoryBidiExact
import DASHI.Core.RuntimeTemporalDiagnosisHistoryBidiExact
import DASHI.Governance.GovernanceTemporalDiagnosisHistoryBidiExact
import DASHI.Cognition.PNF.SensibLawTemporalDiagnosisHistoryBidiExact
import DASHI.Biology.DrosophilaTemporalDiagnosisHistoryBidiExact

import DASHI.Core.TemporalDiagnosisDependencyLineageBidiExact
import DASHI.Core.IncrementalDiagnosisTruthMaintenanceBidiExact

-- Selective invalidation + N-dimensional recursive-Pareto compatibility.
-- Recompute classification precedes ranking.  The current bridge materialises
-- only four residual-relevant semantic axes (consequence, diagnostic residual,
-- authority, recompute cost), keeps 3^9=19683 as visualisation cardinality
-- rather than Pareto dimension, and carries A_(n+1)=9^(A_n) symbolically so
-- tetrational representational capacity never becomes a brute-force search
-- obligation.  Canonical #770 owner paths are intentionally not duplicated
-- while that PR remains on separate ancestry.
import DASHI.Core.SelectiveInvalidationParetoFrontierBidiExact

import DASHI.Biology.AliceBrownDiagnosisRepairSchedulerBidiExact
import DASHI.Biology.AliceBrownTemporalDiagnosisDependencyLineageBidiExact
import DASHI.Biology.AliceBrownSelectiveInvalidationParetoBidiExact
import DASHI.Culture.JohnAnthonyBrownDiagnosisRepairSchedulerBidiExact
import DASHI.Culture.JohnAnthonyBrownTemporalDiagnosisDependencyLineageBidiExact
import DASHI.Culture.JohnAnthonyBrownSelectiveInvalidationParetoBidiExact
