module DASHI.Core.TechnicalDependencyHypergraphExact where

------------------------------------------------------------------------
-- SOURCE-TYPED TECHNICAL DEPENDENCY HYPERGRAPH
--
-- Purpose: distinguish genuine technical/programmatic intersections from
-- weak adjacency generated by common employer, common institutional family,
-- or repeated media narrative.
------------------------------------------------------------------------

open import DASHI.Core.Prelude
open import Agda.Builtin.String using (String)

------------------------------------------------------------------------
-- Node and edge types.
------------------------------------------------------------------------

data TechnicalNodeKind : Set where
  personNode
  technologyNode
  programmeNode
  institutionNode
  fundingOrContractNode
  publicationOrPatentNode
  facilityNode
  : TechnicalNodeKind

record TechnicalNode : Set where
  constructor technical-node
  field
    nodeKind : TechnicalNodeKind
    nodeLabel : String

open TechnicalNode public

data TechnicalEdgeKind : Set where
  workedOn
  authoredOrInvented
  ledOrDirected
  programmeUsesTechnology
  programmeHostedAtFacility
  institutionRunsProgramme
  programmeFundedBy
  sameInstitutionOnly
  sameInstitutionalFamilyOnly
  mediaAssociatedOnly
  reportedRelationshipOnly
  domainSimilarityOnly
  : TechnicalEdgeKind

data EdgeStrength : Set where
  primaryTechnicalReceipt
  primaryRoleReceipt
  officialProgrammeReceipt
  boundedSecondaryReceipt
  mediaNarrativeReceipt
  unresolvedReceipt
  : EdgeStrength

record TechnicalHyperedge : Set where
  constructor technical-hyperedge
  field
    endpoints : List TechnicalNode
    edgeKind : TechnicalEdgeKind
    edgeStrength : EdgeStrength
    provenanceReference : String
    boundedReading : String

open TechnicalHyperedge public

------------------------------------------------------------------------
-- Quotient policy.
--
-- Institution/media edges may be useful provenance, but they cannot by
-- themselves establish a surviving technical connection.
------------------------------------------------------------------------

data QuotientDisposition : Set where
  survivesTechnicalQuotient
  erasedAsInstitutionOnly
  erasedAsMediaOnly
  erasedAsReportedRelationshipOnly
  retainedAsUnresolvedCandidate
  : QuotientDisposition

quotientDisposition : TechnicalHyperedge → QuotientDisposition
quotientDisposition edge with edgeKind edge
... | sameInstitutionOnly = erasedAsInstitutionOnly
... | sameInstitutionalFamilyOnly = erasedAsInstitutionOnly
... | mediaAssociatedOnly = erasedAsMediaOnly
... | reportedRelationshipOnly = erasedAsReportedRelationshipOnly
... | domainSimilarityOnly = retainedAsUnresolvedCandidate
... | workedOn = survivesTechnicalQuotient
... | authoredOrInvented = survivesTechnicalQuotient
... | ledOrDirected = survivesTechnicalQuotient
... | programmeUsesTechnology = survivesTechnicalQuotient
... | programmeHostedAtFacility = survivesTechnicalQuotient
... | institutionRunsProgramme = survivesTechnicalQuotient
... | programmeFundedBy = survivesTechnicalQuotient

record TechnicalDependencyBoundary : Set where
  constructor technical-dependency-boundary
  field
    sameInstitutionEstablishesTechnicalDependency : Bool
    sameInstitutionEstablishesTechnicalDependencyIsFalse :
      sameInstitutionEstablishesTechnicalDependency ≡ false

    sameMediaClusterEstablishesTechnicalDependency : Bool
    sameMediaClusterEstablishesTechnicalDependencyIsFalse :
      sameMediaClusterEstablishesTechnicalDependency ≡ false

    domainSimilarityEstablishesSharedProgramme : Bool
    domainSimilarityEstablishesSharedProgrammeIsFalse :
      domainSimilarityEstablishesSharedProgramme ≡ false

    primaryPersonWorkReceiptSurvivesQuotient : Bool
    primaryPersonWorkReceiptSurvivesQuotientIsTrue :
      primaryPersonWorkReceiptSurvivesQuotient ≡ true

    programmeTechnologyReceiptSurvivesQuotient : Bool
    programmeTechnologyReceiptSurvivesQuotientIsTrue :
      programmeTechnologyReceiptSurvivesQuotient ≡ true

    sharedTechnicalDomainImpliesSharedAdversary : Bool
    sharedTechnicalDomainImpliesSharedAdversaryIsFalse :
      sharedTechnicalDomainImpliesSharedAdversary ≡ false

canonicalTechnicalDependencyBoundary : TechnicalDependencyBoundary
canonicalTechnicalDependencyBoundary =
  technical-dependency-boundary
    false refl
    false refl
    false refl
    true refl
    true refl
    false refl

------------------------------------------------------------------------
-- A surviving intersection needs a shared non-erased technical/program node,
-- not merely a weak institutional/media bridge.
------------------------------------------------------------------------

record SurvivingTechnicalIntersection : Set₁ where
  constructor surviving-technical-intersection
  field
    leftEdge : TechnicalHyperedge
    rightEdge : TechnicalHyperedge
    sharedTechnicalObject : TechnicalNode
    leftSurvives : quotientDisposition leftEdge ≡ survivesTechnicalQuotient
    rightSurvives : quotientDisposition rightEdge ≡ survivesTechnicalQuotient
    intersectionReference : String

open SurvivingTechnicalIntersection public

record CandidateDomainAdjacency : Set₁ where
  constructor candidate-domain-adjacency
  field
    leftObject : TechnicalNode
    rightObject : TechnicalNode
    commonDomain : String
    currentStatus : String
    discriminatorNeeded : String

open CandidateDomainAdjacency public
